CAENPLLConfig: wxSpinCtrlDbl Class Reference
wxSpinCtrlDbl Class Reference
#include <spinctld.h>
Public Types
enum formatType { lf_fmt, le_fmt, lg_fmt }
Public Member Functions
wxSpinCtrlDbl ()
wxSpinCtrlDbl (wxWindow &parent, wxWindowID id, const wxString &value=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxSize(95,-1), long style=0, double min=0.0, double max=100.0, double initial=0.0, double increment=1.0, int digits=wxSPINCTRLDBL_AUTODIGITS, const wxString &name=_T("wxSpinCtrlDbl"))
wxSpinCtrlDbl (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &value=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxSize(95,-1), long style=0, int min=0, int max=100, int initial=0, const wxString &name=_T("wxSpinCtrlDbl"))
bool Create (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &value=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxSize(100,-1), long style=0, double min=0.0, double max=100.0, double initial=0.0, double increment=1.0, int digits=wxSPINCTRLDBL_AUTODIGITS, const wxString &name=_T("wxSpinCtrlDbl"))
virtual ~wxSpinCtrlDbl ()
virtual void SetValue (double value)
void SetValue (double value, double min, double max, double increment, int digits=wxSPINCTRLDBL_AUTODIGITS, formatType fmt=lg_fmt)
virtual void SetValue (const wxString &text, bool force)
void SetRange (double min_val, double max_val)
void SetIncrement (double increment)
void SetIncrement (double increment, int digits, formatType fmt=lg_fmt)
void SetDigits (int digits=wxSPINCTRLDBL_AUTODIGITS, formatType fmt=lg_fmt)
void SetFormat (const wxString &format)
virtual void SetDefaultValue ()
void SetDefaultValue (double default_value)
void SetSnapToTicks (bool forceTicks)
double GetValue () const
double GetMin () const
double GetMax () const
virtual bool HasRange () const
virtual bool InRange (double value) const
double GetIncrement () const
int GetDigits () const
wxString GetFormat () const
double GetDefaultValue () const
bool GetSnapToTicks () const
bool IsDefaultValue () const
virtual bool SetFont (const wxFont &font)
wxFont GetFont () const
virtual bool SetBackgroundColour (const wxColour &colour)
wxColour GetBackgroundColour () const
virtual bool SetForegroundColour (const wxColour &colour)
wxColour GetForegroundColour () const
wxTextCtrl * GetTextCtrl ()
void SetToolTip (const wxString &tip)
virtual void SetHelpText (const wxString &helpText)
Protected Member Functions
void OnSpinUp (wxSpinEvent &event)
void OnSpinDown (wxSpinEvent &event)
void OnTextEnter (wxCommandEvent &event)
void OnText (wxCommandEvent &event)
void OnChar (wxKeyEvent &event)
virtual void SyncSpinToText (bool send_event=true, bool force_valid=true)
void DoSendEvent ()
virtual void DoSetSize (int x, int y, int width, int height, int sizeFlags=wxSIZE_AUTO)
virtual wxSize DoGetBestSize () const
void OnFocus (wxFocusEvent &event)
void OnKillFocus (wxFocusEvent &event)
Protected Attributes
wxSpinButton * m_spinButton
wxSpinCtrlDblTextCtrl * m_textCtrl
double m_min
double m_max
double m_value
double m_default_value
double m_increment
int m_digits
bool m_snap_ticks
wxString m_textFormat
Private Member Functions
void Init ()
Friends
class wxSpinCtrlDblTextCtrl
Detailed Description
Definition at line 57 of file spinctld.h.
Member Enumeration Documentation
enum wxSpinCtrlDbl::formatType
Enumerator:
lf_fmt
le_fmt
lg_fmt
Definition at line 109 of file spinctld.h.
Constructor & Destructor Documentation
wxSpinCtrlDbl::wxSpinCtrlDbl () [inline]
Definition at line 60 of file spinctld.h.
wxSpinCtrlDbl::wxSpinCtrlDbl (wxWindow & parent, wxWindowID id, const wxString & value = wxEmptyString, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxSize(95,-1), long style = 0, double min = 0.0, double max = 100.0, double initial = 0.0, double increment = 1.0, int digits = wxSPINCTRLDBL_AUTODIGITS, const wxString & name = _T("wxSpinCtrlDbl")) [inline]
Definition at line 63 of file spinctld.h.
wxSpinCtrlDbl::wxSpinCtrlDbl (wxWindow * parent, wxWindowID id = wxID_ANY, const wxString & value = wxEmptyString, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxSize(95,-1), long style = 0, int min = 0, int max = 100, int initial = 0, const wxString & name = _T("wxSpinCtrlDbl")) [inline]
Definition at line 79 of file spinctld.h.
wxSpinCtrlDbl::~wxSpinCtrlDbl () [virtual]
Definition at line 209 of file spinctld.cpp.
References wxSpinCtrlDblTextCtrl::m_parent, m_spinButton, and m_textCtrl.
Member Function Documentation
bool wxSpinCtrlDbl::Create (wxWindow * parent, wxWindowID id = wxID_ANY, const wxString & value = wxEmptyString, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxSize(100,-1), long style = 0, double min = 0.0, double max = 100.0, double initial = 0.0, double increment = 1.0, int digits = wxSPINCTRLDBL_AUTODIGITS, const wxString & name = _T("wxSpinCtrlDbl"))
Definition at line 137 of file spinctld.cpp.
References DoGetBestSize(), DoSetSize(), m_default_value, m_increment, m_max, m_min, m_spinButton, m_textCtrl, m_textFormat, m_value, SetBackgroundColour(), SetDigits(), SetForegroundColour(), and wxSpinCtrlDblTextCtrl.
wxSize wxSpinCtrlDbl::DoGetBestSize () const [protected, virtual]
Definition at line 257 of file spinctld.cpp.
References s_spinctrl_bestSize(), and wxSPINCTRLDBL_SPIN_HEIGHT.
Referenced by Create(), and DoSetSize().
void wxSpinCtrlDbl::DoSendEvent () [protected]
Definition at line 274 of file spinctld.cpp.
References m_textCtrl, and m_value.
Referenced by OnChar(), and SyncSpinToText().
void wxSpinCtrlDbl::DoSetSize (int x, int y, int width, int height, int sizeFlags = wxSIZE_AUTO) [protected, virtual]
Definition at line 227 of file spinctld.cpp.
References DoGetBestSize(), m_spinButton, m_textCtrl, wxSPINCTRLDBL_SPIN_HEIGHT, and wxSPINCTRLDBL_SPIN_WIDTH.
Referenced by Create().
wxColour wxSpinCtrlDbl::GetBackgroundColour () const
Definition at line 608 of file spinctld.cpp.
References m_textCtrl.
double wxSpinCtrlDbl::GetDefaultValue () const [inline]
Definition at line 152 of file spinctld.h.
int wxSpinCtrlDbl::GetDigits () const [inline]
Definition at line 150 of file spinctld.h.
wxFont wxSpinCtrlDbl::GetFont () const
Definition at line 594 of file spinctld.cpp.
References m_textCtrl.
wxColour wxSpinCtrlDbl::GetForegroundColour () const
Definition at line 622 of file spinctld.cpp.
References m_textCtrl.
wxString wxSpinCtrlDbl::GetFormat () const [inline]
Definition at line 151 of file spinctld.h.
double wxSpinCtrlDbl::GetIncrement () const [inline]
Definition at line 149 of file spinctld.h.
double wxSpinCtrlDbl::GetMax () const [inline]
Definition at line 146 of file spinctld.h.
Referenced by SyncSpinToText().
double wxSpinCtrlDbl::GetMin () const [inline]
Definition at line 145 of file spinctld.h.
Referenced by SyncSpinToText().
bool wxSpinCtrlDbl::GetSnapToTicks () const [inline]
Definition at line 153 of file spinctld.h.
wxTextCtrl* wxSpinCtrlDbl::GetTextCtrl () [inline]
Definition at line 167 of file spinctld.h.
References wxTextCtrl.
double wxSpinCtrlDbl::GetValue () const [inline]
Definition at line 144 of file spinctld.h.
Referenced by MainFrame::GetControls(), MainFrame::OnCloseWindow(), SyncSpinToText(), and MainFrame::UpdateOutput().
virtual bool wxSpinCtrlDbl::HasRange () const [inline, virtual]
Definition at line 147 of file spinctld.h.
Referenced by SetRange(), and SyncSpinToText().
void wxSpinCtrlDbl::Init () [private]
Definition at line 124 of file spinctld.cpp.
References wxSPINCTRLDBL_AUTODIGITS.
virtual bool wxSpinCtrlDbl::InRange (double value) const [inline, virtual]
Definition at line 148 of file spinctld.h.
Referenced by SetDefaultValue(), SetValue(), and SyncSpinToText().
bool wxSpinCtrlDbl::IsDefaultValue () const [inline]
Definition at line 155 of file spinctld.h.
void wxSpinCtrlDbl::OnChar (wxKeyEvent & event) [protected]
Definition at line 321 of file spinctld.cpp.
References DoSendEvent(), m_increment, m_textCtrl, m_value, SetDefaultValue(), SetValue(), and SyncSpinToText().
Referenced by wxSpinCtrlDblTextCtrl::OnChar().
void wxSpinCtrlDbl::OnFocus (wxFocusEvent & event) [protected]
Definition at line 543 of file spinctld.cpp.
References m_textCtrl.
void wxSpinCtrlDbl::OnKillFocus (wxFocusEvent & event) [protected]
Definition at line 551 of file spinctld.cpp.
References SyncSpinToText().
void wxSpinCtrlDbl::OnSpinDown (wxSpinEvent & event) [protected]
void wxSpinCtrlDbl::OnSpinUp (wxSpinEvent & event) [protected]
void wxSpinCtrlDbl::OnText (wxCommandEvent & event) [protected]
Definition at line 315 of file spinctld.cpp.
void wxSpinCtrlDbl::OnTextEnter (wxCommandEvent & event) [protected]
Definition at line 309 of file spinctld.cpp.
References SyncSpinToText().
bool wxSpinCtrlDbl::SetBackgroundColour (const wxColour & colour) [virtual]
Definition at line 600 of file spinctld.cpp.
References m_textCtrl.
Referenced by Create().
void wxSpinCtrlDbl::SetDefaultValue (double default_value)
Definition at line 525 of file spinctld.cpp.
References InRange(), m_default_value, and SetDefaultValue().
virtual void wxSpinCtrlDbl::SetDefaultValue () [inline, virtual]
Definition at line 135 of file spinctld.h.
Referenced by OnChar(), and SetDefaultValue().
void wxSpinCtrlDbl::SetDigits (int digits = wxSPINCTRLDBL_AUTODIGITS, formatType fmt = lg_fmt)
Definition at line 449 of file spinctld.cpp.
References le_fmt, lf_fmt, lg_fmt, m_digits, m_increment, m_textFormat, m_value, SetValue(), and wxSPINCTRLDBL_AUTODIGITS.
Referenced by Create().
bool wxSpinCtrlDbl::SetFont (const wxFont & font) [virtual]
Definition at line 589 of file spinctld.cpp.
References m_textCtrl.
Referenced by MainFrame::CreateControls().
bool wxSpinCtrlDbl::SetForegroundColour (const wxColour & colour) [virtual]
Definition at line 614 of file spinctld.cpp.
References m_textCtrl.
Referenced by Create().
void wxSpinCtrlDbl::SetFormat (const wxString & format)
Definition at line 516 of file spinctld.cpp.
References m_textFormat, m_value, and SetValue().
void wxSpinCtrlDbl::SetHelpText (const wxString & helpText) [virtual]
Definition at line 635 of file spinctld.cpp.
References m_spinButton, and m_textCtrl.
Referenced by MainFrame::CreateControls().
void wxSpinCtrlDbl::SetIncrement (double increment, int digits, formatType fmt = lg_fmt) [inline]
Definition at line 126 of file spinctld.h.
References SetIncrement().
Referenced by SetIncrement().
void wxSpinCtrlDbl::SetIncrement (double increment)
Definition at line 443 of file spinctld.cpp.
References m_increment, m_value, and SetValue().
void wxSpinCtrlDbl::SetRange (double min_val, double max_val)
Definition at line 428 of file spinctld.cpp.
References HasRange(), m_max, m_min, m_value, and SetValue().
void wxSpinCtrlDbl::SetSnapToTicks (bool forceTicks)
Definition at line 534 of file spinctld.cpp.
References m_snap_ticks, m_value, and SetValue().
void wxSpinCtrlDbl::SetToolTip (const wxString & tip)
Definition at line 628 of file spinctld.cpp.
References m_spinButton, and m_textCtrl.
Referenced by MainFrame::CreateControls().
void wxSpinCtrlDbl::SetValue (const wxString & text, bool force) [virtual]
Definition at line 414 of file spinctld.cpp.
References m_textCtrl, and SetValue().
void wxSpinCtrlDbl::SetValue (double value, double min, double max, double increment, int digits = wxSPINCTRLDBL_AUTODIGITS, formatType fmt = lg_fmt) [inline]
Definition at line 117 of file spinctld.h.
References SetValue().
Referenced by SetValue().
void wxSpinCtrlDbl::SetValue (double value) [virtual]
Definition at line 385 of file spinctld.cpp.
References InRange(), m_default_value, m_increment, m_snap_ticks, m_textCtrl, m_textFormat, m_value, and wxFinite.
Referenced by OnChar(), MainFrame::SetControls(), SetDigits(), SetFormat(), SetIncrement(), SetRange(), SetSnapToTicks(), SetValue(), SyncSpinToText(), and MainFrame::UpdateControls().
void wxSpinCtrlDbl::SyncSpinToText (bool send_event = true, bool force_valid = true) [protected, virtual]
Definition at line 557 of file spinctld.cpp.
References DoSendEvent(), GetMax(), GetMin(), GetValue(), HasRange(), InRange(), m_textCtrl, m_value, and SetValue().
Referenced by OnChar(), OnKillFocus(), wxSpinCtrlDblTextCtrl::OnKillFocus(), and OnTextEnter().
Friends And Related Function Documentation
friend class wxSpinCtrlDblTextCtrl [friend]
Definition at line 207 of file spinctld.h.
Referenced by Create().
Member Data Documentation
double wxSpinCtrlDbl::m_default_value [protected]
Definition at line 200 of file spinctld.h.
Referenced by Create(), SetDefaultValue(), and SetValue().
int wxSpinCtrlDbl::m_digits [protected]
Definition at line 202 of file spinctld.h.
Referenced by SetDigits().
double wxSpinCtrlDbl::m_increment [protected]
Definition at line 201 of file spinctld.h.
Referenced by Create(), OnChar(), SetDigits(), SetIncrement(), and SetValue().
double wxSpinCtrlDbl::m_max [protected]
Definition at line 198 of file spinctld.h.
Referenced by Create(), and SetRange().
double wxSpinCtrlDbl::m_min [protected]
Definition at line 197 of file spinctld.h.
Referenced by Create(), and SetRange().
bool wxSpinCtrlDbl::m_snap_ticks [protected]
Definition at line 203 of file spinctld.h.
Referenced by SetSnapToTicks(), and SetValue().
wxSpinButton* wxSpinCtrlDbl::m_spinButton [protected]
Definition at line 194 of file spinctld.h.
Referenced by Create(), DoSetSize(), SetHelpText(), SetToolTip(), and ~wxSpinCtrlDbl().
wxSpinCtrlDblTextCtrl* wxSpinCtrlDbl::m_textCtrl [protected]
Definition at line 195 of file spinctld.h.
Referenced by Create(), DoSendEvent(), DoSetSize(), GetBackgroundColour(), GetFont(), GetForegroundColour(), OnChar(), OnFocus(), SetBackgroundColour(), SetFont(), SetForegroundColour(), SetHelpText(), SetToolTip(), SetValue(), SyncSpinToText(), ~wxSpinCtrlDbl(), and wxSpinCtrlDblTextCtrl::~wxSpinCtrlDblTextCtrl().
wxString wxSpinCtrlDbl::m_textFormat [protected]
Definition at line 204 of file spinctld.h.
Referenced by Create(), SetDigits(), SetFormat(), and SetValue().
double wxSpinCtrlDbl::m_value [protected]
Definition at line 199 of file spinctld.h.
Referenced by Create(), DoSendEvent(), OnChar(), SetDigits(), SetFormat(), SetIncrement(), SetRange(), SetSnapToTicks(), SetValue(), and SyncSpinToText().
The documentation for this class was generated from the following files:
spinctld.h
spinctld.cpp