CAENPLLConfig: Trash Class Reference
Trash Class Reference
#include <trash.h>
Public Member Functions
Trash ()
Constructors.
Trash (wxWindow *parent, wxWindowID id=SYMBOL_TRASH_IDNAME, const wxString &caption=SYMBOL_TRASH_TITLE, const wxPoint &pos=SYMBOL_TRASH_POSITION, const wxSize &size=SYMBOL_TRASH_SIZE, long style=SYMBOL_TRASH_STYLE)
bool Create (wxWindow *parent, wxWindowID id=SYMBOL_TRASH_IDNAME, const wxString &caption=SYMBOL_TRASH_TITLE, const wxPoint &pos=SYMBOL_TRASH_POSITION, const wxSize &size=SYMBOL_TRASH_SIZE, long style=SYMBOL_TRASH_STYLE)
Creation.
void CreateControls ()
Creates the controls and sizers.
wxBitmap GetBitmapResource (const wxString &name)
Retrieves bitmap resources.
wxIcon GetIconResource (const wxString &name)
Retrieves icon resources.
Static Public Member Functions
static bool ShowToolTips ()
Should we show tooltips?
Public Attributes
wxChoice * m_grid_line_type_control
Detailed Description
Trash class declaration
Definition at line 69 of file trash.h.
Constructor & Destructor Documentation
Trash::Trash ()
Constructors.
Trash type definition
Trash event table definition
Trash constructors
Definition at line 58 of file trash.cpp.
Trash::Trash (wxWindow * parent, wxWindowID id = SYMBOL_TRASH_IDNAME, const wxString & caption = SYMBOL_TRASH_TITLE, const wxPoint & pos = SYMBOL_TRASH_POSITION, const wxSize & size = SYMBOL_TRASH_SIZE, long style = SYMBOL_TRASH_STYLE)
Definition at line 62 of file trash.cpp.
References Create().
Member Function Documentation
bool Trash::Create (wxWindow * parent, wxWindowID id = SYMBOL_TRASH_IDNAME, const wxString & caption = SYMBOL_TRASH_TITLE, const wxPoint & pos = SYMBOL_TRASH_POSITION, const wxSize & size = SYMBOL_TRASH_SIZE, long style = SYMBOL_TRASH_STYLE)
Creation.
Trash creator
Definition at line 71 of file trash.cpp.
References CreateControls(), and m_grid_line_type_control.
Referenced by Trash().
void Trash::CreateControls ()
Creates the controls and sizers.
Control creation for Trash
Definition at line 91 of file trash.cpp.
References ID_BUTTON1, ID_CHECKBOX1, ID_GRID_LINE_TYPE_CHOICE, ID_PANEL, ID_PANEL3, ID_SPINCTRL1, ID_TEXTCTRL1, m_grid_line_type_control, and wxTextCtrl.
Referenced by Create().
wxBitmap Trash::GetBitmapResource (const wxString & name)
Retrieves bitmap resources.
Get bitmap resources
Definition at line 172 of file trash.cpp.
wxIcon Trash::GetIconResource (const wxString & name)
Retrieves icon resources.
Get icon resources
Definition at line 185 of file trash.cpp.
bool Trash::ShowToolTips () [static]
Should we show tooltips?
Should we show tooltips?
Definition at line 163 of file trash.cpp.
Member Data Documentation
wxChoice* Trash::m_grid_line_type_control
Definition at line 102 of file trash.h.
Referenced by Create(), and CreateControls().
The documentation for this class was generated from the following files:
trash.h
trash.cpp