CAENPLLConfig: ConfigDoc Class Reference
ConfigDoc Class Reference
#include <config_doc.h>
Public Member Functions
ConfigDoc (void)
~ConfigDoc (void)
bool Load (const wxString &filename)
bool Save (const wxString &filename)
bool Save ()
bool IsDirty ()
void SetDirty (bool value)
CVT_V17XX_TYPES GetBoardType ()
double GetInputClock () const
bool GetPLLMode () const
bool GetClockOutEnable () const
int GetClockOutDelay () const
bool GetClockOutDelayEnable () const
int GetClockOutDivider () const
int GetADCDivider () const
UINT32 GetBoardBaseAddress () const
int GetVCXOFreq () const
void SetBoardType (CVT_V17XX_TYPES value)
void SetInputClock (double value)
void SetPLLMode (bool value)
void SetClockOutEnable (bool value)
void SetClockOutDelay (int value)
void SetClockOutDelayEnable (bool value)
void SetClockOutDivider (int value)
void SetADCDivider (int value)
void SetBoardBaseAddress (UINT32 value)
void SetVCXOFreq (int value)
const wxString & GetFilename ()
Protected Attributes
CVT_V17XX_TYPES m_board_type
double m_input_clock
bool m_PLL_mode
bool m_clock_out_enable
int m_clock_out_delay
int m_clock_out_divider
int m_adc_divider
bool m_clock_out_delay_enable
UINT32 m_board_base_address
int m_vcxo_freq
wxString m_filename
bool m_is_dirty
Detailed Description
Definition at line 28 of file config_doc.h.
Constructor & Destructor Documentation
ConfigDoc::ConfigDoc (void)
Definition at line 31 of file config_doc.cpp.
ConfigDoc::~ConfigDoc (void)
Definition at line 42 of file config_doc.cpp.
Member Function Documentation
int ConfigDoc::GetADCDivider () const [inline]
Definition at line 52 of file config_doc.h.
References m_adc_divider.
Referenced by GenericBoard::MakeDownloadFile(), and MainFrame::SetControls().
UINT32 ConfigDoc::GetBoardBaseAddress () const [inline]
Definition at line 53 of file config_doc.h.
References m_board_base_address.
Referenced by MainFrame::SetControls().
CVT_V17XX_TYPES ConfigDoc::GetBoardType () [inline]
Definition at line 45 of file config_doc.h.
References m_board_type.
Referenced by MainFrame::SetControls().
int ConfigDoc::GetClockOutDelay () const [inline]
Definition at line 49 of file config_doc.h.
References m_clock_out_delay.
Referenced by GenericBoard::MakeDownloadFile(), and MainFrame::SetControls().
bool ConfigDoc::GetClockOutDelayEnable () const [inline]
Definition at line 50 of file config_doc.h.
References m_clock_out_delay_enable.
Referenced by GenericBoard::MakeDownloadFile(), and MainFrame::SetControls().
int ConfigDoc::GetClockOutDivider () const [inline]
Definition at line 51 of file config_doc.h.
References m_clock_out_divider.
Referenced by GenericBoard::MakeDownloadFile(), and MainFrame::SetControls().
bool ConfigDoc::GetClockOutEnable () const [inline]
Definition at line 48 of file config_doc.h.
References m_clock_out_enable.
Referenced by GenericBoard::MakeDownloadFile(), and MainFrame::SetControls().
const wxString& ConfigDoc::GetFilename () [inline]
Definition at line 128 of file config_doc.h.
References m_filename.
Referenced by MainFrame::DoLoadConfig(), MainFrame::DoSaveConfig(), MainFrame::DownloadFile(), and MainFrame::MakeDownloadFile().
double ConfigDoc::GetInputClock () const [inline]
Definition at line 46 of file config_doc.h.
References m_input_clock.
Referenced by GenericBoard::MakeDownloadFile(), and MainFrame::SetControls().
bool ConfigDoc::GetPLLMode () const [inline]
Definition at line 47 of file config_doc.h.
References m_PLL_mode.
Referenced by GenericBoard::MakeDownloadFile(), and MainFrame::SetControls().
int ConfigDoc::GetVCXOFreq () const [inline]
Definition at line 54 of file config_doc.h.
References m_vcxo_freq.
Referenced by GenericBoard::MakeDownloadFile(), and MainFrame::SetControls().
bool ConfigDoc::IsDirty () [inline]
Definition at line 39 of file config_doc.h.
References m_is_dirty.
Referenced by MainFrame::OnCloseWindow(), and MainFrame::OnOpenToolClick().
bool ConfigDoc::Load (const wxString & filename)
Load data
Definition at line 49 of file config_doc.cpp.
References m_adc_divider, m_board_base_address, m_board_type, m_clock_out_delay, m_clock_out_delay_enable, m_clock_out_divider, m_clock_out_enable, m_filename, m_input_clock, m_is_dirty, m_PLL_mode, and m_vcxo_freq.
Referenced by MainFrame::DoLoadConfig().
bool ConfigDoc::Save (void)
Definition at line 166 of file config_doc.cpp.
References m_filename.
bool ConfigDoc::Save (const wxString & filename)
save data
Definition at line 173 of file config_doc.cpp.
References m_adc_divider, m_board_base_address, m_board_type, m_clock_out_delay, m_clock_out_delay_enable, m_clock_out_divider, m_clock_out_enable, m_input_clock, m_is_dirty, m_PLL_mode, and m_vcxo_freq.
Referenced by MainFrame::DoSaveConfig().
void ConfigDoc::SetADCDivider (int value) [inline]
Definition at line 106 of file config_doc.h.
References m_adc_divider, and m_is_dirty.
Referenced by MainFrame::GetControls().
void ConfigDoc::SetBoardBaseAddress (UINT32 value) [inline]
Definition at line 113 of file config_doc.h.
References m_board_base_address, and m_is_dirty.
Referenced by MainFrame::GetControls().
void ConfigDoc::SetBoardType (CVT_V17XX_TYPES value) [inline]
Definition at line 56 of file config_doc.h.
References m_board_type, and m_is_dirty.
Referenced by MainFrame::GetControls().
void ConfigDoc::SetClockOutDelay (int value) [inline]
Definition at line 85 of file config_doc.h.
References m_clock_out_delay, and m_is_dirty.
Referenced by MainFrame::GetControls().
void ConfigDoc::SetClockOutDelayEnable (bool value) [inline]
Definition at line 92 of file config_doc.h.
References m_clock_out_delay_enable, and m_is_dirty.
Referenced by MainFrame::GetControls().
void ConfigDoc::SetClockOutDivider (int value) [inline]
Definition at line 99 of file config_doc.h.
References m_clock_out_divider, and m_is_dirty.
Referenced by MainFrame::GetControls().
void ConfigDoc::SetClockOutEnable (bool value) [inline]
Definition at line 78 of file config_doc.h.
References m_clock_out_enable, and m_is_dirty.
Referenced by MainFrame::GetControls().
void ConfigDoc::SetDirty (bool value) [inline]
Definition at line 40 of file config_doc.h.
References m_is_dirty.
Referenced by MainFrame::SetDirty().
void ConfigDoc::SetInputClock (double value) [inline]
Definition at line 64 of file config_doc.h.
References m_input_clock, and m_is_dirty.
Referenced by MainFrame::GetControls().
void ConfigDoc::SetPLLMode (bool value) [inline]
Definition at line 71 of file config_doc.h.
References m_is_dirty, and m_PLL_mode.
Referenced by MainFrame::GetControls().
void ConfigDoc::SetVCXOFreq (int value) [inline]
Definition at line 120 of file config_doc.h.
References m_is_dirty, and m_vcxo_freq.
Referenced by MainFrame::GetControls().
Member Data Documentation
int ConfigDoc::m_adc_divider [protected]
Definition at line 137 of file config_doc.h.
Referenced by GetADCDivider(), Load(), Save(), and SetADCDivider().
UINT32 ConfigDoc::m_board_base_address [protected]
Definition at line 139 of file config_doc.h.
Referenced by GetBoardBaseAddress(), Load(), Save(), and SetBoardBaseAddress().
CVT_V17XX_TYPES ConfigDoc::m_board_type [protected]
Definition at line 131 of file config_doc.h.
Referenced by GetBoardType(), Load(), Save(), and SetBoardType().
int ConfigDoc::m_clock_out_delay [protected]
Definition at line 135 of file config_doc.h.
Referenced by GetClockOutDelay(), Load(), Save(), and SetClockOutDelay().
bool ConfigDoc::m_clock_out_delay_enable [protected]
Definition at line 138 of file config_doc.h.
Referenced by GetClockOutDelayEnable(), Load(), Save(), and SetClockOutDelayEnable().
int ConfigDoc::m_clock_out_divider [protected]
Definition at line 136 of file config_doc.h.
Referenced by GetClockOutDivider(), Load(), Save(), and SetClockOutDivider().
bool ConfigDoc::m_clock_out_enable [protected]
Definition at line 134 of file config_doc.h.
Referenced by GetClockOutEnable(), Load(), Save(), and SetClockOutEnable().
wxString ConfigDoc::m_filename [protected]
Definition at line 142 of file config_doc.h.
Referenced by GetFilename(), Load(), and Save().
double ConfigDoc::m_input_clock [protected]
Definition at line 132 of file config_doc.h.
Referenced by GetInputClock(), Load(), Save(), and SetInputClock().
bool ConfigDoc::m_is_dirty [protected]
Definition at line 144 of file config_doc.h.
Referenced by IsDirty(), Load(), Save(), SetADCDivider(), SetBoardBaseAddress(), SetBoardType(), SetClockOutDelay(), SetClockOutDelayEnable(), SetClockOutDivider(), SetClockOutEnable(), SetDirty(), SetInputClock(), SetPLLMode(), and SetVCXOFreq().
bool ConfigDoc::m_PLL_mode [protected]
Definition at line 133 of file config_doc.h.
Referenced by GetPLLMode(), Load(), Save(), and SetPLLMode().
int ConfigDoc::m_vcxo_freq [protected]
Definition at line 140 of file config_doc.h.
Referenced by GetVCXOFreq(), Load(), Save(), and SetVCXOFreq().
The documentation for this class was generated from the following files:
config_doc.h
config_doc.cpp