CAENPLLConfig: VMEWrapper Class Reference
VMEWrapper Class Reference
A wrapper for the VME library APIs.
#include <vme_wrapper.h>
Public Member Functions
VMEWrapper (void)
~VMEWrapper (void)
bool Init (const InputData &input_data)
Connection initialization.
bool End (void)
End of connection.
bool ClearBitmaskReg (UINT32 reg_offset, UINT32 reg_value)
Clear register bitmask.
bool SetBitmaskReg (UINT32 reg_offset, UINT32 reg_value)
Set register bitmask.
bool WriteReg (UINT32 reg_offset, UINT32 reg_value)
Write register value.
bool ReadReg (UINT32 reg_offset, UINT32 &reg_value)
Read register value.
Protected Attributes
Handle m_handle
InputData m_input_data
Detailed Description
A wrapper for the VME library APIs.
This is the VME library wrapper, used by the application to perform VME comunications. You can change the implementation of each method (and keep the external public interface) to comply with your specific VME library APIs
Definition at line 70 of file vme_wrapper.h.
Constructor & Destructor Documentation
VMEWrapper::VMEWrapper (void)
Definition at line 34 of file vme_wrapper.cpp.
References CAEN_VME_INVALID_HANDLE, m_handle, m_input_data, and Handle::m_vme_handle.
VMEWrapper::~VMEWrapper (void)
Definition at line 41 of file vme_wrapper.cpp.
References End().
Member Function Documentation
bool VMEWrapper::ClearBitmaskReg (UINT32 reg_offset, UINT32 reg_value)
Clear register bitmask.
This method clears the bits setted in the reg_value parameter. The clear is perfomed by a read and write operation using the WriteReg and ReadReg wrapper methods. You can reimplement this if your VME library provides a native API.
Parameters:
reg_offset The offset (relative to the board base address) offset of the affected register
reg_value The bitmask applied
Returns:
true if the operation completed successfully
Definition at line 112 of file vme_wrapper.cpp.
References ReadReg(), and WriteReg().
Referenced by GenericBoard::WriteFlashPage().
bool VMEWrapper::End (void)
End of connection.
This method is called once for closing the VME connecion: it have to get release all the resources allocated by the VME library. The connection handle must be invalidated and no more available for further comunications.
Returns:
true if VME connection closing was succesfully completed
Definition at line 93 of file vme_wrapper.cpp.
References CAEN_VME_INVALID_HANDLE, InputData::m_board_type, m_handle, m_input_data, and Handle::m_vme_handle.
Referenced by GenericBoard::PLLUpgrade(), and ~VMEWrapper().
bool VMEWrapper::Init (const InputData & input_data)
Connection initialization.
This method is called once for each VME connection session : it have to perform all the specific initialization tasks required by your VME library, in order to get a valid connection handle.
Parameters:
input_data The input data structure passed
Returns:
true if VME connection opening was succesfully completed
Definition at line 45 of file vme_wrapper.cpp.
References InputData::m_board_type, m_input_data, InputData::m_vme_board_num, and InputData::m_vme_link.
Referenced by GenericBoard::PLLUpgrade(), and GenericBoard::ReadVCXOType().
bool VMEWrapper::ReadReg (UINT32 reg_offset, UINT32 & reg_value)
Read register value.
This method reads the register value and stores it into the reg_value parameter. You must reimplement this using your VME library APIs.
Parameters:
reg_offset The offset (relative to the board base address) offset of the affected register
reg_value The register value read
Returns:
true if the operation completed successfully
Definition at line 151 of file vme_wrapper.cpp.
References CAEN_VME_INVALID_HANDLE, m_handle, and Handle::m_vme_handle.
Referenced by ClearBitmaskReg(), GenericBoard::ReadVCXOType(), and SetBitmaskReg().
bool VMEWrapper::SetBitmaskReg (UINT32 reg_offset, UINT32 reg_value)
Set register bitmask.
This method sets the bits setted in the reg_value parameter. The set is perfomed by a read and write operation using the WriteReg and ReadReg wrapper methods. You can reimplement this if your VME library provides a native API.
Parameters:
reg_offset The offset (relative to the board base address) offset of the affected register
reg_value The bitmask applied
Returns:
true if the operation completed successfully
Definition at line 122 of file vme_wrapper.cpp.
References ReadReg(), and WriteReg().
Referenced by GenericBoard::WriteFlashPage().
bool VMEWrapper::WriteReg (UINT32 reg_offset, UINT32 reg_value)
Write register value.
This method writes the value stored into the reg_value parameter. You must reimplement this using your VME library APIs.
Parameters:
reg_offset The offset (relative to the board base address) offset of the affected register
reg_value The register value written
Returns:
true if the operation completed successfully
Definition at line 132 of file vme_wrapper.cpp.
References CAEN_VME_INVALID_HANDLE, m_handle, and Handle::m_vme_handle.
Referenced by ClearBitmaskReg(), GenericBoard::PLLUpgrade(), SetBitmaskReg(), and GenericBoard::WriteFlashPage().
Member Data Documentation
Handle VMEWrapper::m_handle [protected]
Definition at line 133 of file vme_wrapper.h.
Referenced by End(), ReadReg(), VMEWrapper(), and WriteReg().
InputData VMEWrapper::m_input_data [protected]
Definition at line 134 of file vme_wrapper.h.
Referenced by End(), Init(), and VMEWrapper().
The documentation for this class was generated from the following files:
vme_wrapper.h
vme_wrapper.cpp