CAENPLLConfig: wxHyperlinkEvent Class Reference
wxHyperlinkEvent Class Reference
#include <hyperlinkctrl.h>
Public Member Functions
wxHyperlinkEvent (WXTYPE eventType=wxEVT_COMMAND_LINK_RCLICKED, int id=0)
virtual wxEvent * Clone () const
void SetPosition (const wxPoint &pos)
wxPoint GetPosition (void)
Private Attributes
wxPoint m_pos
Detailed Description
Definition at line 60 of file hyperlinkctrl.h.
Constructor & Destructor Documentation
wxHyperlinkEvent::wxHyperlinkEvent (WXTYPE eventType = wxEVT_COMMAND_LINK_RCLICKED, int id = 0) [inline]
Definition at line 63 of file hyperlinkctrl.h.
Referenced by Clone().
Member Function Documentation
virtual wxEvent* wxHyperlinkEvent::Clone () const [inline, virtual]
Definition at line 65 of file hyperlinkctrl.h.
References wxHyperlinkEvent().
wxPoint wxHyperlinkEvent::GetPosition (void) [inline]
Definition at line 68 of file hyperlinkctrl.h.
void wxHyperlinkEvent::SetPosition (const wxPoint & pos) [inline]
Definition at line 67 of file hyperlinkctrl.h.
References m_pos.
Referenced by wxHyperlinkCtrl::OnMouseEvent().
Member Data Documentation
wxPoint wxHyperlinkEvent::m_pos [private]
Definition at line 68 of file hyperlinkctrl.h.
Referenced by SetPosition().
The documentation for this class was generated from the following file:
hyperlinkctrl.h