#-*- mode: org; coding: utf-8;
#+TITLE: Codes from CAEN

  All codes are from CAEN[fn:1]. If the sub-dir doesn't contain CopyRight info,
  please refer to file:CAEN_License_Agreement.txt.

[fn:1] http://www.caen.it/

* Software Info

* Installation
  + *Notes*: You may encounter "Permission error" while executing ~make
    install~. This can be fixed by creating directory manually. You can first
    create dirs needed manually.
    #+BEGIN_EXAMPLE
    sudo mkdir -p  /etc/CAENPLLConfig /etc/CAENScope /etc/wavedump /etc/cvUpgrade
    sudo chown das /etc/CAENPLLConfig /etc/CAENScope /etc/wavedump /etc/cvUpgrade
    #+END_EXAMPLE

** CAENVMElib
   1. Install libCAENVME.so.* to your desired directory, (e.g. /opt/DAQ/lib)
      : ./inst-dynlib.sh /opt/DAQ/lib
   2. Copy headers to your DAQ directory (e.g. /opt/DAQ/include)
      : cp -vp CAEN*.h /opt/DAQ/include/
   3. (Optional) Use libCAENVME.so with MIDAS/PSI *mvmestd.h*,
      1) Build and install *inbmvme\_v2718/1718.{a,so}*. Default install dir is
         */opt/DAQ/*.
	 : make && make install
      2) When you link your MIDAS FE codes with *libmvme\_a2818*, you should add
         extra link option *-lmvme\_a2818* to your makefile.

** DigitizerSDK
   In order to install the SDK to our default DAQ dir (*/opt/DAQ*), the
   *Makefile* in ~DigitizerSDK/src~ has been modified. Installation is simple as
   : make && make install

** PLLConfig

   1. Package needed in Debian lenny: *libwxgtk2.8-dev*
      : sudo aptitude install libwxgtk2.8-dev
   2. Configuration
      #+BEGIN_EXAMPLE
      ./configure --prefix=/opt/DAQ  \
               CFLAGS="-I/opt/DAQ/include" \
               CXXFLAGS="-I/opt/DAQ/include" \
               LDFLAGS="-L/opt/DAQ/lib"
      #+END_EXAMPLE
   3. Make and install
   4. After installation, the ~src/images~ dir should be copied to
      ~/etc/CAENPLLConfig/~:
      : cp -rvp src/images /etc/CAENPLLConfig/

** CAENCOMMLIBRARY
   + http://www.caen.it/nuclear/swproduct.php?mod=CAENCOMMLIBRARY
   + Use the ~inst-dynlib.sh~ script to install:
     : ./inst-dynlib.sh /opt/DAQ

** Optional packages

*** Scope
    Compiling of this package needs *libwxgtk-dev*. Follow the same procedure of
    *PLLConfig* as above.

*** WaveDump
    This packages need *gnuplot*. In debian, you may install it with the following
    command ~sudo aptitude install gnuplot~.

    1. Configure it
       #+BEGIN_EXAMPLE
       ./configure --prefix=/opt/DAQ CFLAGS="-I/opt/DAQ/include" \
                  CPPFLAGS="-I/opt/DAQ/include" LDFLAGS="-L/opt/DAQ/lib"
       #+END_EXAMPLE
    2. Make and make install
       : make && make install

*** cvUpgrade
    It needs *CAENComm* installed. Other steps are similar with *Scope* and
    *PLLConfig*.


