CAENScope: BoardWorkerThread Class Reference
BoardWorkerThread Class Reference
#include <boardworkerthread.h>
Public Member Functions
BoardWorkerThread (GenericBoard *parent)
~BoardWorkerThread (void)
ExitCode Entry (void)
Protected Attributes
GenericBoard * m_parent
wxDateTime m_next_sw_trigger
Detailed Description
Definition at line 29 of file boardworkerthread.h.
Constructor & Destructor Documentation
BoardWorkerThread::BoardWorkerThread (GenericBoard * parent)
Definition at line 41 of file boardworkerthread.cpp.
References m_parent.
BoardWorkerThread::~BoardWorkerThread (void)
Definition at line 46 of file boardworkerthread.cpp.
Member Function Documentation
wxThread::ExitCode BoardWorkerThread::Entry (void)
Definition at line 50 of file boardworkerthread.cpp.
References BOARD_WORKER_THREAD_ID, g_main_frame, GenericBoard::m_channel_array, GenericBoard::m_is_recording, AppSettings::m_max_log_X, m_next_sw_trigger, GenericBoard::m_p_app_settings, m_parent, GenericBoard::m_record_max_buffers, GenericBoard::m_record_use_max_buffers, AppSettings::m_trigger_msk, GenericBoard::m_virtual_channel_array, GenericBoard::ReadBoardData(), PhysicalBoardChannel::ReadSamplesCache(), GenericBoardChannel::RecordSamples(), SCOPE_NUM_PANELS, GenericBoard::ScopeRefresh, AppSettings::SW_AUTO_TRIGGER_MSK, GenericBoard::UpdateSamplesReadyLed, and GenericBoard::WriteSoftwareTrigger().
Member Data Documentation
wxDateTime BoardWorkerThread::m_next_sw_trigger [protected]
Definition at line 37 of file boardworkerthread.h.
Referenced by Entry().
GenericBoard* BoardWorkerThread::m_parent [protected]
Definition at line 36 of file boardworkerthread.h.
Referenced by BoardWorkerThread(), and Entry().
The documentation for this class was generated from the following files:
boardworkerthread.h
boardworkerthread.cpp