CAENScope: MainFrame Class Reference
MainFrame Class Reference
#include <mainframe.h>
Public Member Functions
MainFrame ()
Constructors.
MainFrame (wxWindow *parent, wxWindowID id=SYMBOL_MAINFRAME_IDNAME, const wxString &caption=SYMBOL_MAINFRAME_TITLE, const wxPoint &pos=SYMBOL_MAINFRAME_POSITION, const wxSize &size=SYMBOL_MAINFRAME_SIZE, long style=SYMBOL_MAINFRAME_STYLE)
virtual ~MainFrame ()
bool Create (wxWindow *parent, wxWindowID id=SYMBOL_MAINFRAME_IDNAME, const wxString &caption=SYMBOL_MAINFRAME_TITLE, const wxPoint &pos=SYMBOL_MAINFRAME_POSITION, const wxSize &size=SYMBOL_MAINFRAME_SIZE, long style=SYMBOL_MAINFRAME_STYLE)
void CreateControls ()
Creates the controls and sizers.
void OnCloseWindow (wxCloseEvent &event)
wxEVT_CLOSE_WINDOW event handler for ID_MAIN_FRAME
void OnSize (wxSizeEvent &event)
wxEVT_SIZE event handler for ID_MAIN_FRAME
void OnBottomWindowSashDragged (wxSashEvent &event)
wxEVT_SASH_DRAGGED event handler for ID_SASHLAYOUTWINDOW2
void OnCommonRunTogglebuttonClick (wxCommandEvent &event)
wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_COMMON_RUN_TOGGLEBUTTON
void OnFrontPanelNimTogglebuttonClick (wxCommandEvent &event)
wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_FRONT_PANEL_NIM_TOGGLEBUTTON
void OnSizeXChoiceSelected (wxCommandEvent &event)
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_SIZE_X_CHOICE
void OnMainDacResetButtonClick (wxCommandEvent &event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_MAIN_DAC_RESET_BUTTON
void OnMainDacOffsetSpinbuttonUpdated (wxSpinEvent &event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_MAIN_DAC_OFFSET_SPINBUTTON
void OnTriggerExtTogglebuttonClick (wxCommandEvent &event)
wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_TRIGGER_EXT_TOGGLEBUTTON
void OnTriggerAutoTogglebuttonClick (wxCommandEvent &event)
wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_TRIGGER_AUTO_TOGGLEBUTTON
void OnTriggerForceButtonClick (wxCommandEvent &event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_TRIGGER_FORCE_BUTTON
void OnTriggerPostSpinctrlUpdated (wxSpinEvent &event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_TRIGGER_POST_SPINCTRL
void OnTriggerPositionKeepCheckboxClick (wxCommandEvent &event)
wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_TRIGGER_POSITION_KEEP_CHECKBOX
void OnTriggerEdgeChoiceSelected (wxCommandEvent &event)
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_TRIGGER_EDGE_CHOICE
void OnRecordtogglebuttonClick (wxCommandEvent &event)
wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_RECORDTOGGLEBUTTON
void OnRecordMaxBuffersCheckboxClick (wxCommandEvent &event)
wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_RECORD_MAX_BUFFERS_CHECKBOX
void OnRecorddirtextctrlUpdated (wxCommandEvent &event)
wxEVT_COMMAND_TEXT_UPDATED event handler for ID_RECORDDIRTEXTCTRL
void OnRecorddirtextctrlEnter (wxCommandEvent &event)
wxEVT_COMMAND_TEXT_ENTER event handler for ID_RECORDDIRTEXTCTRL
void OnRecorddirbuttonClick (wxCommandEvent &event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_RECORDDIRBUTTON
void OnLeftWindowSashDragged (wxSashEvent &event)
wxEVT_SASH_DRAGGED event handler for ID_SASHLAYOUTWINDOW
void OnBackChooseColor1ButtonClick (wxCommandEvent &event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BACK_CHOOSE_COLOR_1_BUTTON
void OnSecPerDiv1ChoiceSelected (wxCommandEvent &event)
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_SEC_PER_DIV_1_CHOICE
void OnOffsetSec1SpinctrlUpdated (wxSpinEvent &event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_OFFSET_SEC_1_SPINCTRL
void OnGridChooseColor1ButtonClick (wxCommandEvent &event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_GRID_CHOOSE_COLOR_1_BUTTON
void OnGridLineWidth1SpinctrlUpdated (wxSpinEvent &event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_GRID_LINE_WIDTH_1_SPINCTRL
void OnGridLineType1ChoiceSelected (wxCommandEvent &event)
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_GRID_LINE_TYPE_1_CHOICE
void OnBackChooseColor2ButtonClick (wxCommandEvent &event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BACK_CHOOSE_COLOR_2_BUTTON
void OnSecPerDiv2ChoiceSelected (wxCommandEvent &event)
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_SEC_PER_DIV_2_CHOICE
void OnOffsetSec2SpinctrlUpdated (wxSpinEvent &event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_OFFSET_SEC_2_SPINCTRL
void OnGridChooseColor2ButtonClick (wxCommandEvent &event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_GRID_CHOOSE_COLOR_2_BUTTON
void OnGridLineWidth2SpinctrlUpdated (wxSpinEvent &event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_GRID_LINE_WIDTH_2_SPINCTRL
void OnGridLineType2ChoiceSelected (wxCommandEvent &event)
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_GRID_LINE_TYPE_2_CHOICE
void OnBackChooseColor3ButtonClick (wxCommandEvent &event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BACK_CHOOSE_COLOR_3_BUTTON
void OnSecPerDiv3ChoiceSelected (wxCommandEvent &event)
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_SEC_PER_DIV_3_CHOICE
void OnOffsetSec3SpinctrlUpdated (wxSpinEvent &event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_OFFSET_SEC_3_SPINCTRL
void OnGridChooseColor3ButtonClick (wxCommandEvent &event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_GRID_CHOOSE_COLOR_3_BUTTON
void OnGridLineWidth3SpinctrlUpdated (wxSpinEvent &event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_GRID_LINE_WIDTH_3_SPINCTRL
void OnGridLineType3ChoiceSelected (wxCommandEvent &event)
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_GRID_LINE_TYPE_3_CHOICE
void OnBackChooseColor4ButtonClick (wxCommandEvent &event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BACK_CHOOSE_COLOR_4_BUTTON
void OnSecPerDiv4ChoiceSelected (wxCommandEvent &event)
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_SEC_PER_DIV_4_CHOICE
void OnOffsetSec4SpinctrlUpdated (wxSpinEvent &event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_OFFSET_SEC_4_SPINCTRL
void OnGridChooseColor4ButtonClick (wxCommandEvent &event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_GRID_CHOOSE_COLOR_4_BUTTON
void OnGridLineWidth4SpinctrlUpdated (wxSpinEvent &event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_GRID_LINE_WIDTH_4_SPINCTRL
void OnGridLineType4ChoiceSelected (wxCommandEvent &event)
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_GRID_LINE_TYPE_4_CHOICE
void OnScopeHorizSplitterwindowSashPosChanged (wxSplitterEvent &event)
wxEVT_COMMAND_SPLITTER_SASH_POS_CHANGED event handler for ID_SCOPE_HORIZ_SPLITTERWINDOW
void OnExitToolClick (wxCommandEvent &event)
wxEVT_COMMAND_MENU_SELECTED event handler for ID_EXIT_TOOL
void OnViewLeftToolClick (wxCommandEvent &event)
wxEVT_COMMAND_MENU_SELECTED event handler for ID_VIEW_LEFT_TOOL
void OnViewBottomToolClick (wxCommandEvent &event)
wxEVT_COMMAND_MENU_SELECTED event handler for ID_VIEW_BOTTOM_TOOL
void OnViewScopeLeftTopToolClick (wxCommandEvent &event)
wxEVT_COMMAND_MENU_SELECTED event handler for ID_VIEW_SCOPE_LEFT_TOP_TOOL
void OnViewScopeRightTopToolClick (wxCommandEvent &event)
wxEVT_COMMAND_MENU_SELECTED event handler for ID_VIEW_SCOPE_RIGHT_TOP_TOOL
void OnViewScopeLeftBottomToolClick (wxCommandEvent &event)
wxEVT_COMMAND_MENU_SELECTED event handler for ID_VIEW_SCOPE_LEFT_BOTTOM_TOOL
void OnViewScopeRightBottomToolClick (wxCommandEvent &event)
wxEVT_COMMAND_MENU_SELECTED event handler for ID_VIEW_SCOPE_RIGHT_BOTTOM_TOOL
void OnHelpToolClick (wxCommandEvent &event)
wxEVT_COMMAND_MENU_SELECTED event handler for ID_HELP_TOOL
void OnGridLineWidth4SpinctrlTextUpdated (wxCommandEvent &event)
void OnOffsetSec4SpinctrlTextUpdated (wxCommandEvent &event)
void OnGridLineWidth3SpinctrlTextUpdated (wxCommandEvent &event)
void OnOffsetSec3SpinctrlTextUpdated (wxCommandEvent &event)
void OnGridLineWidth2SpinctrlTextUpdated (wxCommandEvent &event)
void OnOffsetSec2SpinctrlTextUpdated (wxCommandEvent &event)
void OnGridLineWidth1SpinctrlTextUpdated (wxCommandEvent &event)
void OnOffsetSec1SpinctrlTextUpdated (wxCommandEvent &event)
void OnTriggerPostSpinctrlTextUpdated (wxCommandEvent &event)
void OnScopeVertTopSplitterwindowSashPosChanged (wxSplitterEvent &event)
void OnScopeVertBottomSplitterwindowSashPosChanged (wxSplitterEvent &event)
void OnRecordEnd (wxCommandEvent &event)
wxBitmap GetBitmapResource (const wxString &name)
Retrieves bitmap resources.
wxIcon GetIconResource (const wxString &name)
Retrieves icon resources.
void UpdateSecPerDiv (int scope_index, int selection, wxSpinCtrl *offset_sec_control)
Static Public Member Functions
static bool ShowToolTips ()
Should we show tooltips?
static void ScopeRefresh (int scope_index, bool erase_background)
static void UpdateSamplesReadyLed (bool is_on)
static bool SetStsBarText (const wxString &text, int pane_index)
Public Attributes
wxSashLayoutWindow * m_bottom_pane
wxNotebook * m_common_settings_notebook
wxScrolledWindow * m_common_panel
wxBoxSizer * m_common_main_sizer
wxToggleButton * m_common_run_control
wxPanel * m_samples_ready_control
wxToggleButton * m_common_TTL_control
wxChoice * m_size_X_control
wxStaticBoxSizer * m_DAC_sizer
wxButton * m_ch_DAC_reset_control
wxSpinButton * m_ch_DAC_control
wxStaticText * m_DAC_offset_label
wxScrolledWindow * m_trigger_panel
wxBoxSizer * m_trigger_main_sizer
wxToggleButton * m_trigger_ext_control
wxToggleButton * m_trigger_auto_control
wxButton * m_force_trigger_control
wxSpinCtrl * m_trigger_post_control
wxCheckBox * m_trigger_position_keep_control
wxChoice * m_trigger_edge_control
wxStaticBoxSizer * m_trigger_channel_sizer
wxScrolledWindow * m_record_panel
wxBoxSizer * m_record_main_sizer
wxToggleButton * m_record_start_stop_control
wxCheckBox * m_record_max_buffers_check_box
wxSpinCtrl * m_record_max_buffers_control
wxBoxSizer * m_record_folder_sizer
wxTextCtrl * m_record_dir_control
wxButton * m_record_dir_browse_button
wxSashLayoutWindow * m_left_pane
wxNotebook * m_specific_settings_notebook
wxNotebook * m_specific_settings_scope_1_notebook
wxScrolledWindow * m_view_scope_1_panel
wxBoxSizer * m_view_1_main_sizer
wxPanel * m_back_color_1_control
wxStaticBox * m_main_sizer_1_text
wxChoice * m_sec_per_div_1_control
wxSpinCtrl * m_offset_sec_1_control
wxPanel * m_grid_color_1_control
wxSpinCtrl * m_grid_line_width_1_control
wxChoice * m_grid_line_type_1_control
wxScrolledWindow * m_cursor_1_panel
wxBoxSizer * m_cursor_1_main_sizer
wxNotebook * m_specific_settings_scope_2_notebook
wxScrolledWindow * m_view_scope_2_panel
wxBoxSizer * m_view_2_main_sizer
wxPanel * m_back_color_2_control
wxStaticBox * m_main_sizer_2_text
wxChoice * m_sec_per_div_2_control
wxSpinCtrl * m_offset_sec_2_control
wxPanel * m_grid_color_2_control
wxSpinCtrl * m_grid_line_width_2_control
wxChoice * m_grid_line_type_2_control
wxScrolledWindow * m_cursor_2_panel
wxBoxSizer * m_cursor_2_main_sizer
wxNotebook * m_specific_settings_scope_3_notebook
wxScrolledWindow * m_view_scope_3_panel
wxBoxSizer * m_view_3_main_sizer
wxPanel * m_back_color_3_control
wxStaticBox * m_main_sizer_3_text
wxChoice * m_sec_per_div_3_control
wxSpinCtrl * m_offset_sec_3_control
wxPanel * m_grid_color_3_control
wxSpinCtrl * m_grid_line_width_3_control
wxChoice * m_grid_line_type_3_control
wxScrolledWindow * m_cursor_3_panel
wxBoxSizer * m_cursor_3_main_sizer
wxNotebook * m_specific_settings_scope_4_notebook
wxScrolledWindow * m_view_scope_4_panel
wxBoxSizer * m_view_4_main_sizer
wxPanel * m_back_color_4_control
wxStaticBox * m_main_sizer_4_text
wxChoice * m_sec_per_div_4_control
wxSpinCtrl * m_offset_sec_4_control
wxPanel * m_grid_color_4_control
wxSpinCtrl * m_grid_line_width_4_control
wxChoice * m_grid_line_type_4_control
wxScrolledWindow * m_cursor_4_panel
wxBoxSizer * m_cursor_4_main_sizer
wxSashLayoutWindow * m_top_pane
wxNotebook * m_scope_notebook
wxSplitterWindow * m_scope_horiz_splitter
wxToolBar * m_main_toolbar
wxStatusBar * m_main_statusbar
wxSplitterWindow * m_scope_vert_splitter_top
wxSplitterWindow * m_scope_vert_splitter_bottom
Protected Types
enum SCOPE_POSITIONS { SCOPE_POS_TOP_LEFT = 0, SCOPE_POS_TOP_RIGHT, SCOPE_POS_BOTTOM_LEFT, SCOPE_POS_BOTTOM_RIGHT }
Protected Member Functions
bool CreateDynControls ()
bool UpdateControls (void)
bool UpdateGrid (int scope_index)
void UpdateGridLineWidth (int scope_index, int value)
void UpdateTriggerPost (int value)
void UpdateOffsetSec (int scope_index, int value)
bool UpdateRecordFolder (void)
void UpdateClock (double value)
void UpdateTriggerEdge (void)
void AdjustTriggerPost (void)
void UpdateUseTTL (void)
void DoStartStopRunning (void)
void DoShowHideLeftPane (void)
void DoShowHideBottomPane (void)
void DoShowHideScopeLeftTopPane (bool do_check)
void DoShowHideScopeRightTopPane (bool do_check)
void DoShowHideScopeLeftBottomPane (bool do_check)
void DoShowHideScopeRightBottomPane (bool do_check)
void CheckScopeSplitters (void)
void DoGridChooseColor (int scope_index, wxPanel *grid_color_control)
void DoChooseColor (int scope_index, wxPanel *back_color_control)
void UpdateDAC (void)
Protected Attributes
AppSettings * m_app_settings
DrawingPanel * m_scope_panel_array [SCOPE_NUM_PANELS]
Static Protected Attributes
static wxPanel * g_samples_ready_control = NULL
static DrawingPanel * g_scope_panel_array [SCOPE_NUM_PANELS]
static wxStatusBar * g_main_statusbar = NULL
Detailed Description
Compatibility
MainFrame class declaration
Definition at line 167 of file mainframe.h.
Member Enumeration Documentation
enum MainFrame::SCOPE_POSITIONS [protected]
Enumerator:
SCOPE_POS_TOP_LEFT
SCOPE_POS_TOP_RIGHT
SCOPE_POS_BOTTOM_LEFT
SCOPE_POS_BOTTOM_RIGHT
Definition at line 472 of file mainframe.h.
Constructor & Destructor Documentation
MainFrame::MainFrame ()
Constructors.
MainFrame type definition
MainFrame event table definition
MainFrame constructors
Definition at line 239 of file mainframe.cpp.
References g_main_frame.
MainFrame::MainFrame (wxWindow * parent, wxWindowID id = SYMBOL_MAINFRAME_IDNAME, const wxString & caption = SYMBOL_MAINFRAME_TITLE, const wxPoint & pos = SYMBOL_MAINFRAME_POSITION, const wxSize & size = SYMBOL_MAINFRAME_SIZE, long style = SYMBOL_MAINFRAME_STYLE)
Definition at line 244 of file mainframe.cpp.
References Create(), g_main_frame, m_scope_panel_array, and SCOPE_NUM_PANELS.
MainFrame::~MainFrame () [virtual]
Definition at line 253 of file mainframe.cpp.
References m_size_X_control.
Member Function Documentation
void MainFrame::AdjustTriggerPost (void) [protected]
Definition at line 2459 of file mainframe.cpp.
References m_app_settings, AppSettings::m_max_log_X, and m_trigger_post_control.
Referenced by OnSizeXChoiceSelected(), and UpdateControls().
void MainFrame::CheckScopeSplitters (void) [protected]
Definition at line 2541 of file mainframe.cpp.
References m_scope_horiz_splitter, m_scope_panel_array, m_scope_vert_splitter_bottom, m_scope_vert_splitter_top, SCOPE_NUM_PANELS, SCOPE_POS_BOTTOM_LEFT, SCOPE_POS_BOTTOM_RIGHT, SCOPE_POS_TOP_LEFT, SCOPE_POS_TOP_RIGHT, and ScopeRefresh().
Referenced by DoShowHideScopeLeftBottomPane(), DoShowHideScopeLeftTopPane(), DoShowHideScopeRightBottomPane(), DoShowHideScopeRightTopPane(), and OnSize().
bool MainFrame::Create (wxWindow * parent, wxWindowID id = SYMBOL_MAINFRAME_IDNAME, const wxString & caption = SYMBOL_MAINFRAME_TITLE, const wxPoint & pos = SYMBOL_MAINFRAME_POSITION, const wxSize & size = SYMBOL_MAINFRAME_SIZE, long style = SYMBOL_MAINFRAME_STYLE)
MainFrame creator
Definition at line 266 of file mainframe.cpp.
References CreateControls(), CreateDynControls(), DoShowHideBottomPane(), DoShowHideLeftPane(), DoShowHideScopeLeftBottomPane(), DoShowHideScopeLeftTopPane(), DoShowHideScopeRightBottomPane(), DoShowHideScopeRightTopPane(), DoStartStopRunning(), AppSettings::GetExecutablePath(), GetIconResource(), ID_VIEW_BOTTOM_TOOL, ID_VIEW_LEFT_TOOL, ID_VIEW_SCOPE_LEFT_BOTTOM_TOOL, ID_VIEW_SCOPE_LEFT_TOP_TOOL, ID_VIEW_SCOPE_RIGHT_BOTTOM_TOOL, ID_VIEW_SCOPE_RIGHT_TOP_TOOL, AppSettings::Load(), DrawingPanel::m_app_settings, m_app_settings, m_back_color_1_control, m_back_color_2_control, m_back_color_3_control, m_back_color_4_control, m_bottom_pane, m_ch_DAC_control, m_ch_DAC_reset_control, m_common_main_sizer, m_common_panel, m_common_run_control, m_common_settings_notebook, m_common_TTL_control, m_cursor_1_main_sizer, m_cursor_1_panel, m_cursor_2_main_sizer, m_cursor_2_panel, m_cursor_3_main_sizer, m_cursor_3_panel, m_cursor_4_main_sizer, m_cursor_4_panel, m_DAC_offset_label, m_DAC_sizer, m_force_trigger_control, m_grid_color_1_control, m_grid_color_2_control, m_grid_color_3_control, m_grid_color_4_control, m_grid_line_type_1_control, m_grid_line_type_2_control, m_grid_line_type_3_control, m_grid_line_type_4_control, m_grid_line_width_1_control, m_grid_line_width_2_control, m_grid_line_width_3_control, m_grid_line_width_4_control, m_left_pane, m_main_sizer_1_text, m_main_sizer_2_text, m_main_sizer_3_text, m_main_sizer_4_text, m_main_statusbar, m_main_toolbar, m_offset_sec_1_control, m_offset_sec_2_control, m_offset_sec_3_control, m_offset_sec_4_control, m_record_dir_browse_button, m_record_dir_control, m_record_folder_sizer, m_record_main_sizer, m_record_max_buffers_check_box, m_record_max_buffers_control, m_record_panel, m_record_start_stop_control, m_samples_ready_control, m_scope_horiz_splitter, m_scope_notebook, m_scope_panel_array, m_sec_per_div_1_control, m_sec_per_div_2_control, m_sec_per_div_3_control, m_sec_per_div_4_control, AppSettings::m_show_bottom_pane, AppSettings::m_show_left_pane, AppSettings::m_show_scope_left_bottom_pane, AppSettings::m_show_scope_left_top_pane, AppSettings::m_show_scope_right_bottom_pane, AppSettings::m_show_scope_right_top_pane, m_size_X_control, m_specific_settings_notebook, m_specific_settings_scope_1_notebook, m_specific_settings_scope_2_notebook, m_specific_settings_scope_3_notebook, m_specific_settings_scope_4_notebook, AppSettings::m_started, m_top_pane, m_trigger_auto_control, m_trigger_channel_sizer, m_trigger_edge_control, m_trigger_ext_control, m_trigger_main_sizer, m_trigger_panel, m_trigger_position_keep_control, m_trigger_post_control, m_view_1_main_sizer, m_view_2_main_sizer, m_view_3_main_sizer, m_view_4_main_sizer, m_view_scope_1_panel, m_view_scope_2_panel, m_view_scope_3_panel, m_view_scope_4_panel, SCOPE_NUM_PANELS, ScopeRefresh(), UpdateControls(), and UpdateSamplesReadyLed().
Referenced by MainFrame().
void MainFrame::CreateControls ()
Creates the controls and sizers.
Control creation for MainFrame
Definition at line 639 of file mainframe.cpp.
References CVT_V1724_NBLK_1, CVT_V1724_NBLK_1024, g_main_statusbar, g_samples_ready_control, AppSettings::get_default_path(), GetBitmapResource(), ID_BACK_CHOOSE_COLOR_1_BUTTON, ID_BACK_CHOOSE_COLOR_2_BUTTON, ID_BACK_CHOOSE_COLOR_3_BUTTON, ID_BACK_CHOOSE_COLOR_4_BUTTON, ID_BOTTOM_NOTEBOOK, ID_COMMON_RUN_TOGGLEBUTTON, ID_COMMON_SCROLLEDWINDOW, ID_CURSOR_1_SCROLLEDWINDOW, ID_CURSOR_2_SCROLLEDWINDOW, ID_CURSOR_3_SCROLLEDWINDOW, ID_CURSOR_4_SCROLLEDWINDOW, ID_DRAWING_PANEL, ID_EXIT_TOOL, ID_FRONT_PANEL_NIM_TOGGLEBUTTON, ID_GRID_CHOOSE_COLOR_1_BUTTON, ID_GRID_CHOOSE_COLOR_2_BUTTON, ID_GRID_CHOOSE_COLOR_3_BUTTON, ID_GRID_CHOOSE_COLOR_4_BUTTON, ID_GRID_COLOR_1_PANEL, ID_GRID_COLOR_2_PANEL, ID_GRID_COLOR_3_PANEL, ID_GRID_COLOR_4_PANEL, ID_GRID_LINE_TYPE_1_CHOICE, ID_GRID_LINE_TYPE_2_CHOICE, ID_GRID_LINE_TYPE_3_CHOICE, ID_GRID_LINE_TYPE_4_CHOICE, ID_GRID_LINE_WIDTH_1_SPINCTRL, ID_GRID_LINE_WIDTH_2_SPINCTRL, ID_GRID_LINE_WIDTH_3_SPINCTRL, ID_GRID_LINE_WIDTH_4_SPINCTRL, ID_HELP_TOOL, ID_LEFT_NOTEBOOK, ID_MAIN_DAC_OFFSET_SPINBUTTON, ID_MAIN_DAC_RESET_BUTTON, ID_MAIN_STATUSBAR, ID_MAIN_TOOLBAR, ID_OFFSET_SEC_1_SPINCTRL, ID_OFFSET_SEC_2_SPINCTRL, ID_OFFSET_SEC_3_SPINCTRL, ID_OFFSET_SEC_4_SPINCTRL, ID_PANEL, ID_PANEL3, ID_PANEL5, ID_PANEL6, ID_RECORD_MAX_BUFFERS_CHECKBOX, ID_RECORD_MAX_BUFFERS_SPINCTRL, ID_RECORD_SCROLLEDWINDOW, ID_RECORDDIRBUTTON, ID_RECORDDIRTEXTCTRL, ID_RECORDTOGGLEBUTTON, ID_SAMPLES_READY_PANEL, ID_SASHLAYOUTWINDOW, ID_SASHLAYOUTWINDOW1, ID_SASHLAYOUTWINDOW2, ID_SCOPE_1_VIEW_NOTEBOOK, ID_SCOPE_2_VIEW_NOTEBOOK, ID_SCOPE_3_VIEW_NOTEBOOK, ID_SCOPE_4_VIEW_NOTEBOOK, ID_SCOPE_HORIZ_SPLITTERWINDOW, ID_SCOPE_NOTEBOOK, ID_SCOPE_VERT_BOTTOM_SPLITTERWINDOW, ID_SCOPE_VERT_TOP_SPLITTERWINDOW, ID_SEC_PER_DIV_1_CHOICE, ID_SEC_PER_DIV_2_CHOICE, ID_SEC_PER_DIV_3_CHOICE, ID_SEC_PER_DIV_4_CHOICE, ID_SIZE_X_CHOICE, ID_TRIGGER_AUTO_TOGGLEBUTTON, ID_TRIGGER_EDGE_CHOICE, ID_TRIGGER_EXT_TOGGLEBUTTON, ID_TRIGGER_FORCE_BUTTON, ID_TRIGGER_POSITION_KEEP_CHECKBOX, ID_TRIGGER_POST_SPINCTRL, ID_TRIGGER_SCROLLEDWINDOW, ID_VIEW_1_SCROLLEDWINDOW, ID_VIEW_2_SCROLLEDWINDOW, ID_VIEW_3_SCROLLEDWINDOW, ID_VIEW_4_SCROLLEDWINDOW, ID_VIEW_BOTTOM_TOOL, ID_VIEW_LEFT_TOOL, ID_VIEW_SCOPE_LEFT_BOTTOM_TOOL, ID_VIEW_SCOPE_LEFT_TOP_TOOL, ID_VIEW_SCOPE_RIGHT_BOTTOM_TOOL, ID_VIEW_SCOPE_RIGHT_TOP_TOOL, m_app_settings, m_back_color_1_control, m_back_color_2_control, m_back_color_3_control, m_back_color_4_control, AppSettings::m_board_array, m_bottom_pane, m_ch_DAC_control, m_ch_DAC_reset_control, m_common_main_sizer, m_common_panel, m_common_run_control, m_common_settings_notebook, m_common_TTL_control, m_cursor_1_main_sizer, m_cursor_1_panel, m_cursor_2_main_sizer, m_cursor_2_panel, m_cursor_3_main_sizer, m_cursor_3_panel, m_cursor_4_main_sizer, m_cursor_4_panel, m_DAC_offset_label, m_DAC_sizer, m_force_trigger_control, m_grid_color_1_control, m_grid_color_2_control, m_grid_color_3_control, m_grid_color_4_control, m_grid_line_type_1_control, m_grid_line_type_2_control, m_grid_line_type_3_control, m_grid_line_type_4_control, m_grid_line_width_1_control, m_grid_line_width_2_control, m_grid_line_width_3_control, m_grid_line_width_4_control, m_left_pane, m_main_sizer_1_text, m_main_sizer_2_text, m_main_sizer_3_text, m_main_sizer_4_text, m_main_statusbar, m_main_toolbar, m_offset_sec_1_control, m_offset_sec_2_control, m_offset_sec_3_control, m_offset_sec_4_control, m_record_dir_browse_button, m_record_dir_control, m_record_folder_sizer, m_record_main_sizer, m_record_max_buffers_check_box, m_record_max_buffers_control, m_record_panel, m_record_start_stop_control, m_samples_ready_control, m_scope_horiz_splitter, m_scope_notebook, m_scope_panel_array, m_scope_vert_splitter_bottom, m_scope_vert_splitter_top, m_sec_per_div_1_control, m_sec_per_div_2_control, m_sec_per_div_3_control, m_sec_per_div_4_control, m_size_X_control, m_specific_settings_notebook, m_specific_settings_scope_1_notebook, m_specific_settings_scope_2_notebook, m_specific_settings_scope_3_notebook, m_specific_settings_scope_4_notebook, m_top_pane, m_trigger_auto_control, m_trigger_channel_sizer, m_trigger_edge_control, m_trigger_ext_control, m_trigger_main_sizer, m_trigger_panel, m_trigger_position_keep_control, m_trigger_post_control, m_view_1_main_sizer, m_view_2_main_sizer, m_view_3_main_sizer, m_view_4_main_sizer, m_view_scope_1_panel, m_view_scope_2_panel, m_view_scope_3_panel, m_view_scope_4_panel, OnSize(), SCOPE_NUM_PANELS, and ShowToolTips().
Referenced by Create().
bool MainFrame::CreateDynControls () [protected]
Definition at line 453 of file mainframe.cpp.
References CVT_V1740, m_app_settings, AppSettings::m_board_array, m_common_main_sizer, m_common_panel, m_cursor_1_main_sizer, m_cursor_1_panel, m_cursor_2_main_sizer, m_cursor_2_panel, m_cursor_3_main_sizer, m_cursor_3_panel, m_cursor_4_main_sizer, m_cursor_4_panel, m_DAC_offset_label, m_DAC_sizer, m_record_main_sizer, m_record_panel, m_trigger_channel_sizer, m_trigger_main_sizer, m_trigger_panel, m_view_1_main_sizer, m_view_2_main_sizer, m_view_3_main_sizer, m_view_4_main_sizer, m_view_scope_1_panel, m_view_scope_2_panel, m_view_scope_3_panel, m_view_scope_4_panel, VirtualCommonChControl::SetupBoard(), CursorChControl::SetupBoard(), ViewChControl::SetupBoard(), RecordChControl::SetupBoard(), TriggerChControl::SetupBoard(), and CommonChControl::SetupBoard().
Referenced by Create().
void MainFrame::DoChooseColor (int scope_index, wxPanel * back_color_control) [protected]
Definition at line 2072 of file mainframe.cpp.
References m_app_settings, AppSettings::m_background_color, AppSettings::m_mutex, ScopeRefresh(), and AppSettings::SetBackBrush().
Referenced by OnBackChooseColor1ButtonClick(), OnBackChooseColor2ButtonClick(), OnBackChooseColor3ButtonClick(), and OnBackChooseColor4ButtonClick().
void MainFrame::DoGridChooseColor (int scope_index, wxPanel * grid_color_control) [protected]
Definition at line 1792 of file mainframe.cpp.
References m_app_settings, AppSettings::m_grid_line_color, AppSettings::m_mutex, and UpdateGrid().
Referenced by OnGridChooseColor1ButtonClick(), OnGridChooseColor2ButtonClick(), OnGridChooseColor3ButtonClick(), and OnGridChooseColor4ButtonClick().
void MainFrame::DoShowHideBottomPane (void) [protected]
Definition at line 1770 of file mainframe.cpp.
References m_app_settings, m_bottom_pane, AppSettings::m_show_bottom_pane, SCOPE_NUM_PANELS, and ScopeRefresh().
Referenced by Create(), and OnViewBottomToolClick().
void MainFrame::DoShowHideLeftPane (void) [protected]
Definition at line 1747 of file mainframe.cpp.
References m_app_settings, m_left_pane, AppSettings::m_show_left_pane, SCOPE_NUM_PANELS, and ScopeRefresh().
Referenced by Create(), and OnViewLeftToolClick().
void MainFrame::DoShowHideScopeLeftBottomPane (bool do_check) [protected]
Definition at line 2527 of file mainframe.cpp.
References CheckScopeSplitters(), m_app_settings, m_scope_panel_array, AppSettings::m_show_scope_left_bottom_pane, and SCOPE_POS_BOTTOM_LEFT.
Referenced by Create(), and OnViewScopeLeftBottomToolClick().
void MainFrame::DoShowHideScopeLeftTopPane (bool do_check) [protected]
Definition at line 2511 of file mainframe.cpp.
References CheckScopeSplitters(), m_app_settings, m_scope_panel_array, AppSettings::m_show_scope_left_top_pane, and SCOPE_POS_TOP_LEFT.
Referenced by Create(), and OnViewScopeLeftTopToolClick().
void MainFrame::DoShowHideScopeRightBottomPane (bool do_check) [protected]
Definition at line 2534 of file mainframe.cpp.
References CheckScopeSplitters(), m_app_settings, m_scope_panel_array, AppSettings::m_show_scope_right_bottom_pane, and SCOPE_POS_BOTTOM_RIGHT.
Referenced by Create(), and OnViewScopeRightBottomToolClick().
void MainFrame::DoShowHideScopeRightTopPane (bool do_check) [protected]
Definition at line 2519 of file mainframe.cpp.
References CheckScopeSplitters(), m_app_settings, m_scope_panel_array, AppSettings::m_show_scope_right_top_pane, and SCOPE_POS_TOP_RIGHT.
Referenced by Create(), and OnViewScopeRightTopToolClick().
void MainFrame::DoStartStopRunning (void) [protected]
Definition at line 1646 of file mainframe.cpp.
References m_app_settings, AppSettings::m_board_array, m_common_run_control, m_common_TTL_control, m_size_X_control, SetStsBarText(), and STS_BAR_PANE_RUN.
Referenced by Create(), and OnCommonRunTogglebuttonClick().
wxBitmap MainFrame::GetBitmapResource (const wxString & name)
Retrieves bitmap resources.
Get bitmap resources
Definition at line 1474 of file mainframe.cpp.
References AppSettings::get_default_path().
Referenced by CreateControls().
wxIcon MainFrame::GetIconResource (const wxString & name)
Retrieves icon resources.
Get icon resources
Definition at line 1527 of file mainframe.cpp.
Referenced by Create().
void MainFrame::OnBackChooseColor1ButtonClick (wxCommandEvent & event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BACK_CHOOSE_COLOR_1_BUTTON
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON
Definition at line 2068 of file mainframe.cpp.
References DoChooseColor(), and m_back_color_1_control.
void MainFrame::OnBackChooseColor2ButtonClick (wxCommandEvent & event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BACK_CHOOSE_COLOR_2_BUTTON
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON
Definition at line 2737 of file mainframe.cpp.
References DoChooseColor(), and m_back_color_2_control.
void MainFrame::OnBackChooseColor3ButtonClick (wxCommandEvent & event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BACK_CHOOSE_COLOR_3_BUTTON
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON2
Definition at line 2814 of file mainframe.cpp.
References DoChooseColor(), and m_back_color_3_control.
void MainFrame::OnBackChooseColor4ButtonClick (wxCommandEvent & event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BACK_CHOOSE_COLOR_4_BUTTON
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON4
Definition at line 2891 of file mainframe.cpp.
References DoChooseColor(), and m_back_color_4_control.
void MainFrame::OnBottomWindowSashDragged (wxSashEvent & event)
wxEVT_SASH_DRAGGED event handler for ID_SASHLAYOUTWINDOW2
Definition at line 1592 of file mainframe.cpp.
References m_bottom_pane, SCOPE_NUM_PANELS, and ScopeRefresh().
void MainFrame::OnCloseWindow (wxCloseEvent & event)
wxEVT_CLOSE_WINDOW event handler for ID_MAIN_FRAME
Definition at line 1613 of file mainframe.cpp.
References DrawingPanel::Freeze(), m_app_settings, AppSettings::m_board_array, AppSettings::m_mutex, m_scope_panel_array, AppSettings::Save(), and SCOPE_NUM_PANELS.
void MainFrame::OnCommonRunTogglebuttonClick (wxCommandEvent & event)
wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_COMMON_RUN_TOGGLEBUTTON
Definition at line 1641 of file mainframe.cpp.
References DoStartStopRunning().
void MainFrame::OnExitToolClick (wxCommandEvent & event)
wxEVT_COMMAND_MENU_SELECTED event handler for ID_EXIT_TOOL
Definition at line 1546 of file mainframe.cpp.
void MainFrame::OnFrontPanelNimTogglebuttonClick (wxCommandEvent & event)
wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_FRONT_PANEL_NIM_TOGGLEBUTTON
wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_TOGGLEBUTTON
Definition at line 2442 of file mainframe.cpp.
References UpdateUseTTL().
void MainFrame::OnGridChooseColor1ButtonClick (wxCommandEvent & event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_GRID_CHOOSE_COLOR_1_BUTTON
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_GRID_CHOOSE_COLOR_BUTTON
Definition at line 1788 of file mainframe.cpp.
References DoGridChooseColor(), and m_grid_color_1_control.
void MainFrame::OnGridChooseColor2ButtonClick (wxCommandEvent & event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_GRID_CHOOSE_COLOR_2_BUTTON
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON1
Definition at line 2775 of file mainframe.cpp.
References DoGridChooseColor(), and m_grid_color_2_control.
void MainFrame::OnGridChooseColor3ButtonClick (wxCommandEvent & event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_GRID_CHOOSE_COLOR_3_BUTTON
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON3
Definition at line 2852 of file mainframe.cpp.
References DoGridChooseColor(), and m_grid_color_3_control.
void MainFrame::OnGridChooseColor4ButtonClick (wxCommandEvent & event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_GRID_CHOOSE_COLOR_4_BUTTON
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON5
Definition at line 2929 of file mainframe.cpp.
References DoGridChooseColor(), and m_grid_color_4_control.
void MainFrame::OnGridLineType1ChoiceSelected (wxCommandEvent & event)
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_GRID_LINE_TYPE_1_CHOICE
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_GRID_LINE_TYPE_CHOICE
Definition at line 2056 of file mainframe.cpp.
References m_app_settings, AppSettings::m_grid_line_type, m_grid_line_type_1_control, AppSettings::m_mutex, and UpdateGrid().
void MainFrame::OnGridLineType2ChoiceSelected (wxCommandEvent & event)
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_GRID_LINE_TYPE_2_CHOICE
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_CHOICE1
Definition at line 2803 of file mainframe.cpp.
References m_app_settings, AppSettings::m_grid_line_type, m_grid_line_type_2_control, AppSettings::m_mutex, and UpdateGrid().
void MainFrame::OnGridLineType3ChoiceSelected (wxCommandEvent & event)
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_GRID_LINE_TYPE_3_CHOICE
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_CHOICE3
Definition at line 2880 of file mainframe.cpp.
References m_app_settings, AppSettings::m_grid_line_type, m_grid_line_type_3_control, AppSettings::m_mutex, and UpdateGrid().
void MainFrame::OnGridLineType4ChoiceSelected (wxCommandEvent & event)
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_GRID_LINE_TYPE_4_CHOICE
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_CHOICE5
Definition at line 2957 of file mainframe.cpp.
References m_app_settings, AppSettings::m_grid_line_type, m_grid_line_type_4_control, AppSettings::m_mutex, and UpdateGrid().
void MainFrame::OnGridLineWidth1SpinctrlTextUpdated (wxCommandEvent & event)
wxEVT_COMMAND_TEXT_UPDATED event handler for ID_GRID_LINE_WIDTH_SPINCTRL
Definition at line 2171 of file mainframe.cpp.
References m_grid_line_width_1_control, and UpdateGridLineWidth().
void MainFrame::OnGridLineWidth1SpinctrlUpdated (wxSpinEvent & event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_GRID_LINE_WIDTH_1_SPINCTRL
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_GRID_LINE_WIDTH_SPINCTRL
Definition at line 2046 of file mainframe.cpp.
References UpdateGridLineWidth().
void MainFrame::OnGridLineWidth2SpinctrlTextUpdated (wxCommandEvent & event)
wxEVT_COMMAND_TEXT_UPDATED event handler for ID_SPINCTRL1
Definition at line 2793 of file mainframe.cpp.
References m_grid_line_width_2_control, and UpdateGridLineWidth().
void MainFrame::OnGridLineWidth2SpinctrlUpdated (wxSpinEvent & event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_GRID_LINE_WIDTH_2_SPINCTRL
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_SPINCTRL1
Definition at line 2784 of file mainframe.cpp.
References UpdateGridLineWidth().
void MainFrame::OnGridLineWidth3SpinctrlTextUpdated (wxCommandEvent & event)
wxEVT_COMMAND_TEXT_UPDATED event handler for ID_SPINCTRL3
Definition at line 2870 of file mainframe.cpp.
References m_grid_line_width_3_control, and UpdateGridLineWidth().
void MainFrame::OnGridLineWidth3SpinctrlUpdated (wxSpinEvent & event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_GRID_LINE_WIDTH_3_SPINCTRL
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_SPINCTRL3
Definition at line 2861 of file mainframe.cpp.
References UpdateGridLineWidth().
void MainFrame::OnGridLineWidth4SpinctrlTextUpdated (wxCommandEvent & event)
wxEVT_COMMAND_TEXT_UPDATED event handler for ID_SPINCTRL5
Definition at line 2947 of file mainframe.cpp.
References m_grid_line_width_4_control, and UpdateGridLineWidth().
void MainFrame::OnGridLineWidth4SpinctrlUpdated (wxSpinEvent & event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_GRID_LINE_WIDTH_4_SPINCTRL
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_SPINCTRL5
Definition at line 2938 of file mainframe.cpp.
References UpdateGridLineWidth().
void MainFrame::OnHelpToolClick (wxCommandEvent & event)
wxEVT_COMMAND_MENU_SELECTED event handler for ID_HELP_TOOL
Definition at line 2387 of file mainframe.cpp.
void MainFrame::OnLeftWindowSashDragged (wxSashEvent & event)
wxEVT_SASH_DRAGGED event handler for ID_SASHLAYOUTWINDOW
Definition at line 1556 of file mainframe.cpp.
References m_left_pane, SCOPE_NUM_PANELS, and ScopeRefresh().
void MainFrame::OnMainDacOffsetSpinbuttonUpdated (wxSpinEvent & event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_MAIN_DAC_OFFSET_SPINBUTTON
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_SPINBUTTON1
Definition at line 3010 of file mainframe.cpp.
References UpdateDAC().
void MainFrame::OnMainDacResetButtonClick (wxCommandEvent & event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_MAIN_DAC_RESET_BUTTON
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_BUTTON1
Definition at line 3000 of file mainframe.cpp.
References m_ch_DAC_control, and UpdateDAC().
void MainFrame::OnOffsetSec1SpinctrlTextUpdated (wxCommandEvent & event)
wxEVT_COMMAND_TEXT_UPDATED event handler for ID_OFFSET_SEC_SPINCTRL
Definition at line 2253 of file mainframe.cpp.
References m_offset_sec_1_control, and UpdateOffsetSec().
void MainFrame::OnOffsetSec1SpinctrlUpdated (wxSpinEvent & event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_OFFSET_SEC_1_SPINCTRL
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_OFFSET_SEC_SPINCTRL
Definition at line 2244 of file mainframe.cpp.
References UpdateOffsetSec().
void MainFrame::OnOffsetSec2SpinctrlTextUpdated (wxCommandEvent & event)
wxEVT_COMMAND_TEXT_UPDATED event handler for ID_SPINCTRL
Definition at line 2765 of file mainframe.cpp.
References m_offset_sec_2_control, and UpdateOffsetSec().
void MainFrame::OnOffsetSec2SpinctrlUpdated (wxSpinEvent & event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_OFFSET_SEC_2_SPINCTRL
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_SPINCTRL
Definition at line 2756 of file mainframe.cpp.
References UpdateOffsetSec().
void MainFrame::OnOffsetSec3SpinctrlTextUpdated (wxCommandEvent & event)
wxEVT_COMMAND_TEXT_UPDATED event handler for ID_SPINCTRL2
Definition at line 2842 of file mainframe.cpp.
References m_offset_sec_3_control, and UpdateOffsetSec().
void MainFrame::OnOffsetSec3SpinctrlUpdated (wxSpinEvent & event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_OFFSET_SEC_3_SPINCTRL
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_SPINCTRL2
Definition at line 2833 of file mainframe.cpp.
References UpdateOffsetSec().
void MainFrame::OnOffsetSec4SpinctrlTextUpdated (wxCommandEvent & event)
wxEVT_COMMAND_TEXT_UPDATED event handler for ID_SPINCTRL4
Definition at line 2919 of file mainframe.cpp.
References m_offset_sec_4_control, and UpdateOffsetSec().
void MainFrame::OnOffsetSec4SpinctrlUpdated (wxSpinEvent & event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_OFFSET_SEC_4_SPINCTRL
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_SPINCTRL4
Definition at line 2910 of file mainframe.cpp.
References UpdateOffsetSec().
void MainFrame::OnRecorddirbuttonClick (wxCommandEvent & event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_RECORDDIRBUTTON
Definition at line 2315 of file mainframe.cpp.
References m_record_dir_control, and UpdateRecordFolder().
void MainFrame::OnRecorddirtextctrlEnter (wxCommandEvent & event)
wxEVT_COMMAND_TEXT_ENTER event handler for ID_RECORDDIRTEXTCTRL
Definition at line 2343 of file mainframe.cpp.
References UpdateRecordFolder().
void MainFrame::OnRecorddirtextctrlUpdated (wxCommandEvent & event)
wxEVT_COMMAND_TEXT_UPDATED event handler for ID_RECORDDIRTEXTCTRL
Definition at line 2333 of file mainframe.cpp.
References m_record_dir_control.
void MainFrame::OnRecordEnd (wxCommandEvent & event)
Definition at line 2990 of file mainframe.cpp.
References m_record_start_stop_control, and OnRecordtogglebuttonClick().
void MainFrame::OnRecordMaxBuffersCheckboxClick (wxCommandEvent & event)
wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_RECORD_MAX_BUFFERS_CHECKBOX
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_EXT_CLOCK_CHOICE
wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_RECORD_MAX_BUFFERS_CHECKBOX
Definition at line 2985 of file mainframe.cpp.
References m_record_max_buffers_check_box, and m_record_max_buffers_control.
void MainFrame::OnRecordtogglebuttonClick (wxCommandEvent & event)
wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_RECORDTOGGLEBUTTON
Definition at line 2282 of file mainframe.cpp.
References m_app_settings, AppSettings::m_board_array, m_record_dir_browse_button, m_record_dir_control, m_record_max_buffers_check_box, m_record_max_buffers_control, m_record_start_stop_control, SetStsBarText(), and STS_BAR_PANE_REC.
Referenced by OnRecordEnd().
void MainFrame::OnScopeHorizSplitterwindowSashPosChanged (wxSplitterEvent & event)
wxEVT_COMMAND_SPLITTER_SASH_POS_CHANGED event handler for ID_SCOPE_HORIZ_SPLITTERWINDOW
Definition at line 2699 of file mainframe.cpp.
References SCOPE_NUM_PANELS, and ScopeRefresh().
void MainFrame::OnScopeVertBottomSplitterwindowSashPosChanged (wxSplitterEvent & event)
Definition at line 2721 of file mainframe.cpp.
References SCOPE_NUM_PANELS, and ScopeRefresh().
void MainFrame::OnScopeVertTopSplitterwindowSashPosChanged (wxSplitterEvent & event)
Definition at line 2710 of file mainframe.cpp.
References SCOPE_NUM_PANELS, and ScopeRefresh().
void MainFrame::OnSecPerDiv1ChoiceSelected (wxCommandEvent & event)
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_SEC_PER_DIV_1_CHOICE
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_SEC_PER_DIV_CHOICE
Definition at line 2213 of file mainframe.cpp.
References m_offset_sec_1_control, m_sec_per_div_1_control, and UpdateSecPerDiv().
void MainFrame::OnSecPerDiv2ChoiceSelected (wxCommandEvent & event)
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_SEC_PER_DIV_2_CHOICE
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_CHOICE
Definition at line 2746 of file mainframe.cpp.
References m_offset_sec_2_control, m_sec_per_div_2_control, and UpdateSecPerDiv().
void MainFrame::OnSecPerDiv3ChoiceSelected (wxCommandEvent & event)
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_SEC_PER_DIV_3_CHOICE
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_CHOICE2
Definition at line 2823 of file mainframe.cpp.
References m_offset_sec_3_control, m_sec_per_div_3_control, and UpdateSecPerDiv().
void MainFrame::OnSecPerDiv4ChoiceSelected (wxCommandEvent & event)
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_SEC_PER_DIV_4_CHOICE
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_CHOICE4
Definition at line 2900 of file mainframe.cpp.
References m_offset_sec_4_control, m_sec_per_div_4_control, and UpdateSecPerDiv().
void MainFrame::OnSize (wxSizeEvent & event)
wxEVT_SIZE event handler for ID_MAIN_FRAME
Definition at line 1576 of file mainframe.cpp.
References CheckScopeSplitters(), and m_main_toolbar.
Referenced by CreateControls().
void MainFrame::OnSizeXChoiceSelected (wxCommandEvent & event)
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_SIZE_X_CHOICE
Definition at line 2134 of file mainframe.cpp.
References AdjustTriggerPost(), m_app_settings, AppSettings::m_board_array, AppSettings::m_max_log_X, AppSettings::m_num_sample, m_size_X_control, SCOPE_NUM_PANELS, and ScopeRefresh().
void MainFrame::OnTriggerAutoTogglebuttonClick (wxCommandEvent & event)
wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_TRIGGER_AUTO_TOGGLEBUTTON
Definition at line 1686 of file mainframe.cpp.
References m_app_settings, AppSettings::m_mutex, m_trigger_auto_control, AppSettings::m_trigger_msk, SCOPE_NUM_PANELS, ScopeRefresh(), SetStsBarText(), STS_BAR_PANE_AUTO_TRIG, and AppSettings::SW_AUTO_TRIGGER_MSK.
void MainFrame::OnTriggerEdgeChoiceSelected (wxCommandEvent & event)
wxEVT_COMMAND_CHOICE_SELECTED event handler for ID_TRIGGER_EDGE_CHOICE
Definition at line 2407 of file mainframe.cpp.
References UpdateTriggerEdge().
void MainFrame::OnTriggerExtTogglebuttonClick (wxCommandEvent & event)
wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_TRIGGER_EXT_TOGGLEBUTTON
Definition at line 1707 of file mainframe.cpp.
References AppSettings::EXT_TRIGGER_MSK, m_app_settings, AppSettings::m_board_array, m_common_run_control, AppSettings::m_mutex, m_trigger_ext_control, AppSettings::m_trigger_msk, SCOPE_NUM_PANELS, ScopeRefresh(), SetStsBarText(), and STS_BAR_PANE_EXT_TRIG.
void MainFrame::OnTriggerForceButtonClick (wxCommandEvent & event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_TRIGGER_FORCE_BUTTON
Definition at line 1673 of file mainframe.cpp.
References m_app_settings, and AppSettings::m_board_array.
void MainFrame::OnTriggerPositionKeepCheckboxClick (wxCommandEvent & event)
wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_TRIGGER_POSITION_KEEP_CHECKBOX
Definition at line 2471 of file mainframe.cpp.
References m_app_settings, AppSettings::m_trigger_position_keep, and m_trigger_position_keep_control.
void MainFrame::OnTriggerPostSpinctrlTextUpdated (wxCommandEvent & event)
wxEVT_COMMAND_TEXT_UPDATED event handler for ID_TRIGGER_POST_SPINCTRL
Definition at line 2189 of file mainframe.cpp.
References m_trigger_post_control, and UpdateTriggerPost().
void MainFrame::OnTriggerPostSpinctrlUpdated (wxSpinEvent & event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_TRIGGER_POST_SPINCTRL
Definition at line 1732 of file mainframe.cpp.
References UpdateTriggerPost().
void MainFrame::OnViewBottomToolClick (wxCommandEvent & event)
wxEVT_COMMAND_MENU_SELECTED event handler for ID_VIEW_BOTTOM_TOOL
Definition at line 1765 of file mainframe.cpp.
References DoShowHideBottomPane().
void MainFrame::OnViewLeftToolClick (wxCommandEvent & event)
wxEVT_COMMAND_MENU_SELECTED event handler for ID_VIEW_LEFT_TOOL
Definition at line 1742 of file mainframe.cpp.
References DoShowHideLeftPane().
void MainFrame::OnViewScopeLeftBottomToolClick (wxCommandEvent & event)
wxEVT_COMMAND_MENU_SELECTED event handler for ID_VIEW_SCOPE_LEFT_BOTTOM_TOOL
Definition at line 2497 of file mainframe.cpp.
References DoShowHideScopeLeftBottomPane().
void MainFrame::OnViewScopeLeftTopToolClick (wxCommandEvent & event)
wxEVT_COMMAND_MENU_SELECTED event handler for ID_VIEW_SCOPE_LEFT_TOP_TOOL
wxEVT_COMMAND_MENU_SELECTED event handler for ID_TOOL
Definition at line 2479 of file mainframe.cpp.
References DoShowHideScopeLeftTopPane().
void MainFrame::OnViewScopeRightBottomToolClick (wxCommandEvent & event)
wxEVT_COMMAND_MENU_SELECTED event handler for ID_VIEW_SCOPE_RIGHT_BOTTOM_TOOL
Definition at line 2506 of file mainframe.cpp.
References DoShowHideScopeRightBottomPane().
void MainFrame::OnViewScopeRightTopToolClick (wxCommandEvent & event)
wxEVT_COMMAND_MENU_SELECTED event handler for ID_VIEW_SCOPE_RIGHT_TOP_TOOL
wxEVT_COMMAND_MENU_SELECTED event handler for ID_TOOL3
Definition at line 2488 of file mainframe.cpp.
References DoShowHideScopeRightTopPane().
void MainFrame::ScopeRefresh (int scope_index, bool erase_background) [static]
Definition at line 2092 of file mainframe.cpp.
References DrawingPanel::RefreshBackBitmap(), and DrawingPanel::RefreshLeftBackBitmap().
Referenced by CheckScopeSplitters(), Create(), DoChooseColor(), DoShowHideBottomPane(), DoShowHideLeftPane(), OnBottomWindowSashDragged(), OnLeftWindowSashDragged(), OnScopeHorizSplitterwindowSashPosChanged(), OnScopeVertBottomSplitterwindowSashPosChanged(), OnScopeVertTopSplitterwindowSashPosChanged(), OnSizeXChoiceSelected(), OnTriggerAutoTogglebuttonClick(), OnTriggerExtTogglebuttonClick(), UpdateClock(), UpdateControls(), UpdateGrid(), UpdateOffsetSec(), UpdateSecPerDiv(), UpdateTriggerEdge(), and UpdateTriggerPost().
bool MainFrame::SetStsBarText (const wxString & text, int pane_index) [static]
Definition at line 2393 of file mainframe.cpp.
References g_main_statusbar, and STS_BAR_NUM_PANES.
Referenced by DoStartStopRunning(), OnRecordtogglebuttonClick(), OnTriggerAutoTogglebuttonClick(), OnTriggerExtTogglebuttonClick(), UpdateClock(), UpdateControls(), UpdateTriggerEdge(), and UpdateUseTTL().
bool MainFrame::ShowToolTips () [static]
Should we show tooltips?
Definition at line 1465 of file mainframe.cpp.
Referenced by CreateControls().
void MainFrame::UpdateClock (double value) [protected]
wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_EXT_CLOCK_CHECKBOX
Definition at line 2361 of file mainframe.cpp.
References m_app_settings, SCOPE_NUM_PANELS, ScopeRefresh(), AppSettings::SetClock(), SetStsBarText(), and STS_BAR_PANE_EXT_CLOCK.
bool MainFrame::UpdateControls (void) [protected]
Definition at line 1809 of file mainframe.cpp.
References AdjustTriggerPost(), AppSettings::EXT_TRIGGER_MSK, m_app_settings, m_back_color_1_control, m_back_color_2_control, m_back_color_3_control, m_back_color_4_control, AppSettings::m_background_color, AppSettings::m_board_array, m_ch_DAC_control, m_common_TTL_control, PhysicalBoardChannel::m_DAC_offset_bit, m_DAC_sizer, m_grid_color_1_control, m_grid_color_2_control, m_grid_color_3_control, m_grid_color_4_control, AppSettings::m_grid_line_color, AppSettings::m_grid_line_type, m_grid_line_type_1_control, m_grid_line_type_2_control, m_grid_line_type_3_control, m_grid_line_type_4_control, AppSettings::m_grid_line_width, m_grid_line_width_1_control, m_grid_line_width_2_control, m_grid_line_width_3_control, m_grid_line_width_4_control, AppSettings::m_max_log_X, AppSettings::m_mutex, AppSettings::m_num_sample, AppSettings::m_offset_sec, m_offset_sec_1_control, m_offset_sec_2_control, m_offset_sec_3_control, m_offset_sec_4_control, AppSettings::m_post_trigger, m_record_dir_control, AppSettings::m_record_folder, AppSettings::m_sec_2_div, m_sec_per_div_1_control, m_sec_per_div_2_control, m_sec_per_div_3_control, m_sec_per_div_4_control, m_size_X_control, m_trigger_auto_control, m_trigger_edge_control, AppSettings::m_trigger_edge_type, m_trigger_ext_control, AppSettings::m_trigger_msk, AppSettings::m_trigger_position_keep, m_trigger_position_keep_control, m_trigger_post_control, AppSettings::m_use_ext_clock, AppSettings::m_use_TTL, SCOPE_NUM_PANELS, ScopeRefresh(), SEC_PER_DIV_TABLE, AppSettings::SetBackBrush(), SetStsBarText(), STS_BAR_PANE_AUTO_TRIG, STS_BAR_PANE_EXT_CLOCK, STS_BAR_PANE_EXT_TRIG, AppSettings::SW_AUTO_TRIGGER_MSK, UpdateDAC(), UpdateGrid(), UpdateRecordFolder(), UpdateTriggerEdge(), and UpdateUseTTL().
Referenced by Create().
void MainFrame::UpdateDAC (void) [protected]
Definition at line 3015 of file mainframe.cpp.
References m_app_settings, AppSettings::m_board_array, m_ch_DAC_control, PhysicalBoardChannel::m_DAC_offset_bit, and PhysicalBoardChannel::WriteDACOffset().
Referenced by OnMainDacOffsetSpinbuttonUpdated(), OnMainDacResetButtonClick(), and UpdateControls().
bool MainFrame::UpdateGrid (int scope_index) [protected]
Definition at line 2006 of file mainframe.cpp.
References AppSettings::DASH_DOT, AppSettings::DASHED, AppSettings::DOTTED, m_app_settings, AppSettings::m_grid_line_color, AppSettings::m_grid_line_type, AppSettings::m_mutex, AppSettings::NO_LINE, ScopeRefresh(), AppSettings::SetGridPen(), and AppSettings::SOLID.
Referenced by DoGridChooseColor(), OnGridLineType1ChoiceSelected(), OnGridLineType2ChoiceSelected(), OnGridLineType3ChoiceSelected(), OnGridLineType4ChoiceSelected(), UpdateControls(), and UpdateGridLineWidth().
void MainFrame::UpdateGridLineWidth (int scope_index, int value) [protected]
Definition at line 2177 of file mainframe.cpp.
References m_app_settings, AppSettings::m_grid_line_width, AppSettings::m_mutex, and UpdateGrid().
Referenced by OnGridLineWidth1SpinctrlTextUpdated(), OnGridLineWidth1SpinctrlUpdated(), OnGridLineWidth2SpinctrlTextUpdated(), OnGridLineWidth2SpinctrlUpdated(), OnGridLineWidth3SpinctrlTextUpdated(), OnGridLineWidth3SpinctrlUpdated(), OnGridLineWidth4SpinctrlTextUpdated(), and OnGridLineWidth4SpinctrlUpdated().
void MainFrame::UpdateOffsetSec (int scope_index, int value) [protected]
Definition at line 2259 of file mainframe.cpp.
References m_app_settings, AppSettings::m_mutex, AppSettings::m_offset_sec, and ScopeRefresh().
Referenced by OnOffsetSec1SpinctrlTextUpdated(), OnOffsetSec1SpinctrlUpdated(), OnOffsetSec2SpinctrlTextUpdated(), OnOffsetSec2SpinctrlUpdated(), OnOffsetSec3SpinctrlTextUpdated(), OnOffsetSec3SpinctrlUpdated(), OnOffsetSec4SpinctrlTextUpdated(), and OnOffsetSec4SpinctrlUpdated().
bool MainFrame::UpdateRecordFolder (void) [protected]
Definition at line 2267 of file mainframe.cpp.
References m_app_settings, m_record_dir_control, and AppSettings::m_record_folder.
Referenced by OnRecorddirbuttonClick(), OnRecorddirtextctrlEnter(), and UpdateControls().
void MainFrame::UpdateSamplesReadyLed (bool is_on) [static]
Definition at line 2114 of file mainframe.cpp.
References g_samples_ready_control.
Referenced by Create().
void MainFrame::UpdateSecPerDiv (int scope_index, int selection, wxSpinCtrl * offset_sec_control)
Definition at line 2218 of file mainframe.cpp.
References m_app_settings, AppSettings::m_max_log_X, AppSettings::m_offset_sec, AppSettings::m_post_trigger, AppSettings::m_sample_2_sec, AppSettings::m_sec_2_div, AppSettings::m_trigger_position_keep, ScopeRefresh(), SEC_PER_DIV_TABLE, and AppSettings::SetSec2Div().
Referenced by OnSecPerDiv1ChoiceSelected(), OnSecPerDiv2ChoiceSelected(), OnSecPerDiv3ChoiceSelected(), and OnSecPerDiv4ChoiceSelected().
void MainFrame::UpdateTriggerEdge (void) [protected]
Definition at line 2411 of file mainframe.cpp.
References AppSettings::FALLING_EDGE, m_app_settings, AppSettings::m_board_array, m_common_run_control, AppSettings::m_mutex, m_trigger_edge_control, AppSettings::m_trigger_edge_type, AppSettings::RISING_EDGE, SCOPE_NUM_PANELS, ScopeRefresh(), SetStsBarText(), and STS_BAR_PANE_TRIG_EDGE.
Referenced by OnTriggerEdgeChoiceSelected(), and UpdateControls().
void MainFrame::UpdateTriggerPost (int value) [protected]
Definition at line 2195 of file mainframe.cpp.
References m_app_settings, AppSettings::m_board_array, m_common_run_control, AppSettings::m_mutex, AppSettings::m_post_trigger, SCOPE_NUM_PANELS, and ScopeRefresh().
Referenced by OnTriggerPostSpinctrlTextUpdated(), and OnTriggerPostSpinctrlUpdated().
void MainFrame::UpdateUseTTL (void) [protected]
Definition at line 2447 of file mainframe.cpp.
References m_app_settings, AppSettings::m_board_array, m_common_TTL_control, AppSettings::m_mutex, AppSettings::m_use_TTL, SetStsBarText(), and STS_BAR_PANE_NIM.
Referenced by OnFrontPanelNimTogglebuttonClick(), and UpdateControls().
Member Data Documentation
wxStatusBar * MainFrame::g_main_statusbar = NULL [static, protected]
Definition at line 481 of file mainframe.h.
Referenced by CreateControls(), and SetStsBarText().
wxPanel * MainFrame::g_samples_ready_control = NULL [static, protected]
Definition at line 466 of file mainframe.h.
Referenced by CreateControls(), and UpdateSamplesReadyLed().
DrawingPanel * MainFrame::g_scope_panel_array [static, protected]
Definition at line 480 of file mainframe.h.
AppSettings* MainFrame::m_app_settings [protected]
Definition at line 468 of file mainframe.h.
Referenced by AdjustTriggerPost(), Create(), CreateControls(), CreateDynControls(), DoChooseColor(), DoGridChooseColor(), DoShowHideBottomPane(), DoShowHideLeftPane(), DoShowHideScopeLeftBottomPane(), DoShowHideScopeLeftTopPane(), DoShowHideScopeRightBottomPane(), DoShowHideScopeRightTopPane(), DoStartStopRunning(), OnCloseWindow(), OnGridLineType1ChoiceSelected(), OnGridLineType2ChoiceSelected(), OnGridLineType3ChoiceSelected(), OnGridLineType4ChoiceSelected(), OnRecordtogglebuttonClick(), OnSizeXChoiceSelected(), OnTriggerAutoTogglebuttonClick(), OnTriggerExtTogglebuttonClick(), OnTriggerForceButtonClick(), OnTriggerPositionKeepCheckboxClick(), UpdateClock(), UpdateControls(), UpdateDAC(), UpdateGrid(), UpdateGridLineWidth(), UpdateOffsetSec(), UpdateRecordFolder(), UpdateSecPerDiv(), UpdateTriggerEdge(), UpdateTriggerPost(), and UpdateUseTTL().
wxPanel* MainFrame::m_back_color_1_control
Definition at line 407 of file mainframe.h.
Referenced by Create(), CreateControls(), OnBackChooseColor1ButtonClick(), and UpdateControls().
wxPanel* MainFrame::m_back_color_2_control
Definition at line 419 of file mainframe.h.
Referenced by Create(), CreateControls(), OnBackChooseColor2ButtonClick(), and UpdateControls().
wxPanel* MainFrame::m_back_color_3_control
Definition at line 431 of file mainframe.h.
Referenced by Create(), CreateControls(), OnBackChooseColor3ButtonClick(), and UpdateControls().
wxPanel* MainFrame::m_back_color_4_control
Definition at line 443 of file mainframe.h.
Referenced by Create(), CreateControls(), OnBackChooseColor4ButtonClick(), and UpdateControls().
wxSashLayoutWindow* MainFrame::m_bottom_pane
Definition at line 373 of file mainframe.h.
Referenced by Create(), CreateControls(), DoShowHideBottomPane(), and OnBottomWindowSashDragged().
wxSpinButton* MainFrame::m_ch_DAC_control
Definition at line 383 of file mainframe.h.
Referenced by Create(), CreateControls(), OnMainDacResetButtonClick(), UpdateControls(), and UpdateDAC().
wxButton* MainFrame::m_ch_DAC_reset_control
Definition at line 382 of file mainframe.h.
Referenced by Create(), and CreateControls().
wxBoxSizer* MainFrame::m_common_main_sizer
Definition at line 376 of file mainframe.h.
Referenced by Create(), CreateControls(), and CreateDynControls().
wxScrolledWindow* MainFrame::m_common_panel
Definition at line 375 of file mainframe.h.
Referenced by Create(), CreateControls(), and CreateDynControls().
wxToggleButton* MainFrame::m_common_run_control
Definition at line 377 of file mainframe.h.
Referenced by Create(), CreateControls(), DoStartStopRunning(), OnTriggerExtTogglebuttonClick(), UpdateTriggerEdge(), and UpdateTriggerPost().
wxNotebook* MainFrame::m_common_settings_notebook
Definition at line 374 of file mainframe.h.
Referenced by Create(), and CreateControls().
wxToggleButton* MainFrame::m_common_TTL_control
Definition at line 379 of file mainframe.h.
Referenced by Create(), CreateControls(), DoStartStopRunning(), UpdateControls(), and UpdateUseTTL().
wxBoxSizer* MainFrame::m_cursor_1_main_sizer
Definition at line 415 of file mainframe.h.
Referenced by Create(), CreateControls(), and CreateDynControls().
wxScrolledWindow* MainFrame::m_cursor_1_panel
Definition at line 414 of file mainframe.h.
Referenced by Create(), CreateControls(), and CreateDynControls().
wxBoxSizer* MainFrame::m_cursor_2_main_sizer
Definition at line 427 of file mainframe.h.
Referenced by Create(), CreateControls(), and CreateDynControls().
wxScrolledWindow* MainFrame::m_cursor_2_panel
Definition at line 426 of file mainframe.h.
Referenced by Create(), CreateControls(), and CreateDynControls().
wxBoxSizer* MainFrame::m_cursor_3_main_sizer
Definition at line 439 of file mainframe.h.
Referenced by Create(), CreateControls(), and CreateDynControls().
wxScrolledWindow* MainFrame::m_cursor_3_panel
Definition at line 438 of file mainframe.h.
Referenced by Create(), CreateControls(), and CreateDynControls().
wxBoxSizer* MainFrame::m_cursor_4_main_sizer
Definition at line 451 of file mainframe.h.
Referenced by Create(), CreateControls(), and CreateDynControls().
wxScrolledWindow* MainFrame::m_cursor_4_panel
Definition at line 450 of file mainframe.h.
Referenced by Create(), CreateControls(), and CreateDynControls().
wxStaticText* MainFrame::m_DAC_offset_label
Definition at line 384 of file mainframe.h.
Referenced by Create(), CreateControls(), and CreateDynControls().
wxStaticBoxSizer* MainFrame::m_DAC_sizer
Definition at line 381 of file mainframe.h.
Referenced by Create(), CreateControls(), CreateDynControls(), and UpdateControls().
wxButton* MainFrame::m_force_trigger_control
Definition at line 389 of file mainframe.h.
Referenced by Create(), and CreateControls().
wxPanel* MainFrame::m_grid_color_1_control
Definition at line 411 of file mainframe.h.
Referenced by Create(), CreateControls(), OnGridChooseColor1ButtonClick(), and UpdateControls().
wxPanel* MainFrame::m_grid_color_2_control
Definition at line 423 of file mainframe.h.
Referenced by Create(), CreateControls(), OnGridChooseColor2ButtonClick(), and UpdateControls().
wxPanel* MainFrame::m_grid_color_3_control
Definition at line 435 of file mainframe.h.
Referenced by Create(), CreateControls(), OnGridChooseColor3ButtonClick(), and UpdateControls().
wxPanel* MainFrame::m_grid_color_4_control
Definition at line 447 of file mainframe.h.
Referenced by Create(), CreateControls(), OnGridChooseColor4ButtonClick(), and UpdateControls().
wxChoice* MainFrame::m_grid_line_type_1_control
Definition at line 413 of file mainframe.h.
Referenced by Create(), CreateControls(), OnGridLineType1ChoiceSelected(), and UpdateControls().
wxChoice* MainFrame::m_grid_line_type_2_control
Definition at line 425 of file mainframe.h.
Referenced by Create(), CreateControls(), OnGridLineType2ChoiceSelected(), and UpdateControls().
wxChoice* MainFrame::m_grid_line_type_3_control
Definition at line 437 of file mainframe.h.
Referenced by Create(), CreateControls(), OnGridLineType3ChoiceSelected(), and UpdateControls().
wxChoice* MainFrame::m_grid_line_type_4_control
Definition at line 449 of file mainframe.h.
Referenced by Create(), CreateControls(), OnGridLineType4ChoiceSelected(), and UpdateControls().
wxSpinCtrl* MainFrame::m_grid_line_width_1_control
Definition at line 412 of file mainframe.h.
Referenced by Create(), CreateControls(), OnGridLineWidth1SpinctrlTextUpdated(), and UpdateControls().
wxSpinCtrl* MainFrame::m_grid_line_width_2_control
Definition at line 424 of file mainframe.h.
Referenced by Create(), CreateControls(), OnGridLineWidth2SpinctrlTextUpdated(), and UpdateControls().
wxSpinCtrl* MainFrame::m_grid_line_width_3_control
Definition at line 436 of file mainframe.h.
Referenced by Create(), CreateControls(), OnGridLineWidth3SpinctrlTextUpdated(), and UpdateControls().
wxSpinCtrl* MainFrame::m_grid_line_width_4_control
Definition at line 448 of file mainframe.h.
Referenced by Create(), CreateControls(), OnGridLineWidth4SpinctrlTextUpdated(), and UpdateControls().
wxSashLayoutWindow* MainFrame::m_left_pane
Definition at line 402 of file mainframe.h.
Referenced by Create(), CreateControls(), DoShowHideLeftPane(), and OnLeftWindowSashDragged().
wxStaticBox* MainFrame::m_main_sizer_1_text
Definition at line 408 of file mainframe.h.
Referenced by Create(), and CreateControls().
wxStaticBox* MainFrame::m_main_sizer_2_text
Definition at line 420 of file mainframe.h.
Referenced by Create(), and CreateControls().
wxStaticBox* MainFrame::m_main_sizer_3_text
Definition at line 432 of file mainframe.h.
Referenced by Create(), and CreateControls().
wxStaticBox* MainFrame::m_main_sizer_4_text
Definition at line 444 of file mainframe.h.
Referenced by Create(), and CreateControls().
wxStatusBar* MainFrame::m_main_statusbar
Definition at line 456 of file mainframe.h.
Referenced by Create(), and CreateControls().
wxToolBar* MainFrame::m_main_toolbar
Definition at line 455 of file mainframe.h.
Referenced by Create(), CreateControls(), and OnSize().
wxSpinCtrl* MainFrame::m_offset_sec_1_control
Definition at line 410 of file mainframe.h.
Referenced by Create(), CreateControls(), OnOffsetSec1SpinctrlTextUpdated(), OnSecPerDiv1ChoiceSelected(), and UpdateControls().
wxSpinCtrl* MainFrame::m_offset_sec_2_control
Definition at line 422 of file mainframe.h.
Referenced by Create(), CreateControls(), OnOffsetSec2SpinctrlTextUpdated(), OnSecPerDiv2ChoiceSelected(), and UpdateControls().
wxSpinCtrl* MainFrame::m_offset_sec_3_control
Definition at line 434 of file mainframe.h.
Referenced by Create(), CreateControls(), OnOffsetSec3SpinctrlTextUpdated(), OnSecPerDiv3ChoiceSelected(), and UpdateControls().
wxSpinCtrl* MainFrame::m_offset_sec_4_control
Definition at line 446 of file mainframe.h.
Referenced by Create(), CreateControls(), OnOffsetSec4SpinctrlTextUpdated(), OnSecPerDiv4ChoiceSelected(), and UpdateControls().
wxButton* MainFrame::m_record_dir_browse_button
Definition at line 401 of file mainframe.h.
Referenced by Create(), CreateControls(), and OnRecordtogglebuttonClick().
wxTextCtrl* MainFrame::m_record_dir_control
Definition at line 400 of file mainframe.h.
Referenced by Create(), CreateControls(), OnRecorddirbuttonClick(), OnRecorddirtextctrlUpdated(), OnRecordtogglebuttonClick(), UpdateControls(), and UpdateRecordFolder().
wxBoxSizer* MainFrame::m_record_folder_sizer
Definition at line 399 of file mainframe.h.
Referenced by Create(), and CreateControls().
wxBoxSizer* MainFrame::m_record_main_sizer
Definition at line 395 of file mainframe.h.
Referenced by Create(), CreateControls(), and CreateDynControls().
wxCheckBox* MainFrame::m_record_max_buffers_check_box
Definition at line 397 of file mainframe.h.
Referenced by Create(), CreateControls(), OnRecordMaxBuffersCheckboxClick(), and OnRecordtogglebuttonClick().
wxSpinCtrl* MainFrame::m_record_max_buffers_control
Definition at line 398 of file mainframe.h.
Referenced by Create(), CreateControls(), OnRecordMaxBuffersCheckboxClick(), and OnRecordtogglebuttonClick().
wxScrolledWindow* MainFrame::m_record_panel
Definition at line 394 of file mainframe.h.
Referenced by Create(), CreateControls(), and CreateDynControls().
wxToggleButton* MainFrame::m_record_start_stop_control
Definition at line 396 of file mainframe.h.
Referenced by Create(), CreateControls(), OnRecordEnd(), and OnRecordtogglebuttonClick().
wxPanel* MainFrame::m_samples_ready_control
Definition at line 378 of file mainframe.h.
Referenced by Create(), and CreateControls().
wxSplitterWindow* MainFrame::m_scope_horiz_splitter
Definition at line 454 of file mainframe.h.
Referenced by CheckScopeSplitters(), Create(), and CreateControls().
wxNotebook* MainFrame::m_scope_notebook
Definition at line 453 of file mainframe.h.
Referenced by Create(), and CreateControls().
DrawingPanel* MainFrame::m_scope_panel_array[SCOPE_NUM_PANELS] [protected]
Definition at line 479 of file mainframe.h.
Referenced by CheckScopeSplitters(), Create(), CreateControls(), DoShowHideScopeLeftBottomPane(), DoShowHideScopeLeftTopPane(), DoShowHideScopeRightBottomPane(), DoShowHideScopeRightTopPane(), MainFrame(), and OnCloseWindow().
wxSplitterWindow* MainFrame::m_scope_vert_splitter_bottom
Definition at line 459 of file mainframe.h.
Referenced by CheckScopeSplitters(), and CreateControls().
wxSplitterWindow* MainFrame::m_scope_vert_splitter_top
Definition at line 458 of file mainframe.h.
Referenced by CheckScopeSplitters(), and CreateControls().
wxChoice* MainFrame::m_sec_per_div_1_control
Definition at line 409 of file mainframe.h.
Referenced by Create(), CreateControls(), OnSecPerDiv1ChoiceSelected(), and UpdateControls().
wxChoice* MainFrame::m_sec_per_div_2_control
Definition at line 421 of file mainframe.h.
Referenced by Create(), CreateControls(), OnSecPerDiv2ChoiceSelected(), and UpdateControls().
wxChoice* MainFrame::m_sec_per_div_3_control
Definition at line 433 of file mainframe.h.
Referenced by Create(), CreateControls(), OnSecPerDiv3ChoiceSelected(), and UpdateControls().
wxChoice* MainFrame::m_sec_per_div_4_control
Definition at line 445 of file mainframe.h.
Referenced by Create(), CreateControls(), OnSecPerDiv4ChoiceSelected(), and UpdateControls().
wxChoice* MainFrame::m_size_X_control
Definition at line 380 of file mainframe.h.
Referenced by Create(), CreateControls(), DoStartStopRunning(), OnSizeXChoiceSelected(), UpdateControls(), and ~MainFrame().
wxNotebook* MainFrame::m_specific_settings_notebook
Definition at line 403 of file mainframe.h.
Referenced by Create(), and CreateControls().
wxNotebook* MainFrame::m_specific_settings_scope_1_notebook
Definition at line 404 of file mainframe.h.
Referenced by Create(), and CreateControls().
wxNotebook* MainFrame::m_specific_settings_scope_2_notebook
Definition at line 416 of file mainframe.h.
Referenced by Create(), and CreateControls().
wxNotebook* MainFrame::m_specific_settings_scope_3_notebook
Definition at line 428 of file mainframe.h.
Referenced by Create(), and CreateControls().
wxNotebook* MainFrame::m_specific_settings_scope_4_notebook
Definition at line 440 of file mainframe.h.
Referenced by Create(), and CreateControls().
wxSashLayoutWindow* MainFrame::m_top_pane
Definition at line 452 of file mainframe.h.
Referenced by Create(), and CreateControls().
wxToggleButton* MainFrame::m_trigger_auto_control
Definition at line 388 of file mainframe.h.
Referenced by Create(), CreateControls(), OnTriggerAutoTogglebuttonClick(), and UpdateControls().
wxStaticBoxSizer* MainFrame::m_trigger_channel_sizer
Definition at line 393 of file mainframe.h.
Referenced by Create(), CreateControls(), and CreateDynControls().
wxChoice* MainFrame::m_trigger_edge_control
Definition at line 392 of file mainframe.h.
Referenced by Create(), CreateControls(), UpdateControls(), and UpdateTriggerEdge().
wxToggleButton* MainFrame::m_trigger_ext_control
Definition at line 387 of file mainframe.h.
Referenced by Create(), CreateControls(), OnTriggerExtTogglebuttonClick(), and UpdateControls().
wxBoxSizer* MainFrame::m_trigger_main_sizer
Definition at line 386 of file mainframe.h.
Referenced by Create(), CreateControls(), and CreateDynControls().
wxScrolledWindow* MainFrame::m_trigger_panel
Definition at line 385 of file mainframe.h.
Referenced by Create(), CreateControls(), and CreateDynControls().
wxCheckBox* MainFrame::m_trigger_position_keep_control
Definition at line 391 of file mainframe.h.
Referenced by Create(), CreateControls(), OnTriggerPositionKeepCheckboxClick(), and UpdateControls().
wxSpinCtrl* MainFrame::m_trigger_post_control
Definition at line 390 of file mainframe.h.
Referenced by AdjustTriggerPost(), Create(), CreateControls(), OnTriggerPostSpinctrlTextUpdated(), and UpdateControls().
wxBoxSizer* MainFrame::m_view_1_main_sizer
Definition at line 406 of file mainframe.h.
Referenced by Create(), CreateControls(), and CreateDynControls().
wxBoxSizer* MainFrame::m_view_2_main_sizer
Definition at line 418 of file mainframe.h.
Referenced by Create(), CreateControls(), and CreateDynControls().
wxBoxSizer* MainFrame::m_view_3_main_sizer
Definition at line 430 of file mainframe.h.
Referenced by Create(), CreateControls(), and CreateDynControls().
wxBoxSizer* MainFrame::m_view_4_main_sizer
Definition at line 442 of file mainframe.h.
Referenced by Create(), CreateControls(), and CreateDynControls().
wxScrolledWindow* MainFrame::m_view_scope_1_panel
Definition at line 405 of file mainframe.h.
Referenced by Create(), CreateControls(), and CreateDynControls().
wxScrolledWindow* MainFrame::m_view_scope_2_panel
Definition at line 417 of file mainframe.h.
Referenced by Create(), CreateControls(), and CreateDynControls().
wxScrolledWindow* MainFrame::m_view_scope_3_panel
Definition at line 429 of file mainframe.h.
Referenced by Create(), CreateControls(), and CreateDynControls().
wxScrolledWindow* MainFrame::m_view_scope_4_panel
Definition at line 441 of file mainframe.h.
Referenced by Create(), CreateControls(), and CreateDynControls().
The documentation for this class was generated from the following files:
mainframe.h
mainframe.cpp