CAENScope: DrawingLeftCanvas Class Reference
DrawingLeftCanvas Class Reference
#include <drawing_left_canvas.h>
Public Member Functions
DrawingLeftCanvas ()
Constructors.
DrawingLeftCanvas (int scope_index, wxWindow *parent, wxWindowID id=SYMBOL_DRAWINGLEFTCANVAS_IDNAME, const wxPoint &pos=SYMBOL_DRAWINGLEFTCANVAS_POSITION, const wxSize &size=SYMBOL_DRAWINGLEFTCANVAS_SIZE, long style=SYMBOL_DRAWINGLEFTCANVAS_STYLE)
~DrawingLeftCanvas ()
bool Create (wxWindow *parent, wxWindowID id=SYMBOL_DRAWINGLEFTCANVAS_IDNAME, const wxPoint &pos=SYMBOL_DRAWINGLEFTCANVAS_POSITION, const wxSize &size=SYMBOL_DRAWINGLEFTCANVAS_SIZE, long style=SYMBOL_DRAWINGLEFTCANVAS_STYLE)
Creation.
void CreateControls ()
Creates the controls and sizers.
void OnSize (wxSizeEvent &event)
wxEVT_SIZE event handler for ID_DRAWINGLEFTCANVAS
void OnPaint (wxPaintEvent &event)
wxEVT_PAINT event handler for ID_DRAWINGLEFTCANVAS
void OnEraseBackground (wxEraseEvent &event)
wxEVT_ERASE_BACKGROUND event handler for ID_DRAWINGLEFTCANVAS
wxBitmap GetBitmapResource (const wxString &name)
Retrieves bitmap resources.
wxIcon GetIconResource (const wxString &name)
Retrieves icon resources.
void RefreshBackBitmap (void)
Static Public Member Functions
static bool ShowToolTips ()
Should we show tooltips?
Protected Member Functions
void DrawBackground (wxDC &dc)
void DrawPosition (wxDC &dc)
Protected Attributes
wxBitmap * m_p_back_bitmap
DrawingPanel * m_parent
int m_pix_X
int m_pix_Y
bool m_first_time
int m_scope_index
Detailed Description
Compatibility
DrawingLeftCanvas class declaration
Definition at line 60 of file drawing_left_canvas.h.
Constructor & Destructor Documentation
DrawingLeftCanvas::DrawingLeftCanvas ()
Constructors.
DrawingLeftCanvas type definition
DrawingLeftCanvas event table definition
DrawingLeftCanvas constructors
Definition at line 64 of file drawing_left_canvas.cpp.
DrawingLeftCanvas::DrawingLeftCanvas (int scope_index, wxWindow * parent, wxWindowID id = SYMBOL_DRAWINGLEFTCANVAS_IDNAME, const wxPoint & pos = SYMBOL_DRAWINGLEFTCANVAS_POSITION, const wxSize & size = SYMBOL_DRAWINGLEFTCANVAS_SIZE, long style = SYMBOL_DRAWINGLEFTCANVAS_STYLE)
Definition at line 69 of file drawing_left_canvas.cpp.
References Create(), m_p_back_bitmap, and m_scope_index.
DrawingLeftCanvas::~DrawingLeftCanvas ()
Definition at line 75 of file drawing_left_canvas.cpp.
References m_p_back_bitmap.
Member Function Documentation
bool DrawingLeftCanvas::Create (wxWindow * parent, wxWindowID id = SYMBOL_DRAWINGLEFTCANVAS_IDNAME, const wxPoint & pos = SYMBOL_DRAWINGLEFTCANVAS_POSITION, const wxSize & size = SYMBOL_DRAWINGLEFTCANVAS_SIZE, long style = SYMBOL_DRAWINGLEFTCANVAS_STYLE)
Creation.
DrawingLeftCanvas creator
Definition at line 84 of file drawing_left_canvas.cpp.
References CreateControls().
Referenced by DrawingLeftCanvas().
void DrawingLeftCanvas::CreateControls ()
Creates the controls and sizers.
Control creation for DrawingLeftCanvas
Definition at line 102 of file drawing_left_canvas.cpp.
Referenced by Create().
void DrawingLeftCanvas::DrawBackground (wxDC & dc) [protected]
Definition at line 234 of file drawing_left_canvas.cpp.
References DrawingPanel::m_app_settings, AppSettings::m_back_brush, AppSettings::m_mutex, and m_parent.
Referenced by RefreshBackBitmap().
void DrawingLeftCanvas::DrawPosition (wxDC & dc) [protected]
Definition at line 189 of file drawing_left_canvas.cpp.
References GenericBoard::DrawPosition(), DrawingPanel::m_app_settings, AppSettings::m_board_array, and m_parent.
Referenced by RefreshBackBitmap().
wxBitmap DrawingLeftCanvas::GetBitmapResource (const wxString & name)
Retrieves bitmap resources.
Get bitmap resources
Definition at line 125 of file drawing_left_canvas.cpp.
wxIcon DrawingLeftCanvas::GetIconResource (const wxString & name)
Retrieves icon resources.
Get icon resources
Definition at line 138 of file drawing_left_canvas.cpp.
void DrawingLeftCanvas::OnEraseBackground (wxEraseEvent & event)
wxEVT_ERASE_BACKGROUND event handler for ID_DRAWINGLEFTCANVAS
Definition at line 185 of file drawing_left_canvas.cpp.
void DrawingLeftCanvas::OnPaint (wxPaintEvent & event)
wxEVT_PAINT event handler for ID_DRAWINGLEFTCANVAS
Definition at line 160 of file drawing_left_canvas.cpp.
References DrawingPanel::IsFreezed(), DrawingPanel::m_app_settings, m_first_time, m_p_back_bitmap, m_parent, and RefreshBackBitmap().
void DrawingLeftCanvas::OnSize (wxSizeEvent & event)
wxEVT_SIZE event handler for ID_DRAWINGLEFTCANVAS
Definition at line 150 of file drawing_left_canvas.cpp.
References RefreshBackBitmap().
void DrawingLeftCanvas::RefreshBackBitmap (void)
Definition at line 199 of file drawing_left_canvas.cpp.
References DrawBackground(), DrawPosition(), DrawingPanel::IsFreezed(), DrawingPanel::m_app_settings, AppSettings::m_board_array, m_p_back_bitmap, m_parent, m_pix_X, m_pix_Y, m_scope_index, DrawingCanvas::NUM_DIV_PER_SCREEN, GenericBoard::SetLeftDiv2Pix(), and GenericBoard::SetLeftPix().
Referenced by OnPaint(), OnSize(), and DrawingPanel::RefreshLeftBackBitmap().
bool DrawingLeftCanvas::ShowToolTips () [static]
Should we show tooltips?
Definition at line 116 of file drawing_left_canvas.cpp.
Member Data Documentation
bool DrawingLeftCanvas::m_first_time [protected]
Definition at line 113 of file drawing_left_canvas.h.
Referenced by OnPaint().
wxBitmap* DrawingLeftCanvas::m_p_back_bitmap [protected]
Definition at line 110 of file drawing_left_canvas.h.
Referenced by DrawingLeftCanvas(), OnPaint(), RefreshBackBitmap(), and ~DrawingLeftCanvas().
DrawingPanel* DrawingLeftCanvas::m_parent [protected]
Definition at line 111 of file drawing_left_canvas.h.
Referenced by DrawBackground(), DrawPosition(), OnPaint(), and RefreshBackBitmap().
int DrawingLeftCanvas::m_pix_X [protected]
Definition at line 112 of file drawing_left_canvas.h.
Referenced by RefreshBackBitmap().
int DrawingLeftCanvas::m_pix_Y [protected]
Definition at line 112 of file drawing_left_canvas.h.
Referenced by RefreshBackBitmap().
int DrawingLeftCanvas::m_scope_index [protected]
Definition at line 114 of file drawing_left_canvas.h.
Referenced by DrawingLeftCanvas(), and RefreshBackBitmap().
The documentation for this class was generated from the following files:
drawing_left_canvas.h
drawing_left_canvas.cpp