CAENScope: V1740BoardChannel Class Reference
V1740BoardChannel Class Reference
#include <V1740_board_channel.h>
Public Member Functions
V1740BoardChannel (GenericBoard *parent, int ch_index, cvt_board_data *p_data, void(*scope_refresh)(int, bool), wxMutex *p_data_mutex, AppSettings *p_app_settings)
~V1740BoardChannel (void)
bool ReadSamplesCache (UINT32 num_samples)
bool WriteDACOffset (void)
bool WriteChannelTrigger (void)
Detailed Description
Definition at line 27 of file V1740_board_channel.h.
Constructor & Destructor Documentation
V1740BoardChannel::V1740BoardChannel (GenericBoard * parent, int ch_index, cvt_board_data * p_data, void(*)(int, bool) scope_refresh, wxMutex * p_data_mutex, AppSettings * p_app_settings)
Definition at line 37 of file V1740_board_channel.cpp.
V1740BoardChannel::~V1740BoardChannel (void)
Definition at line 42 of file V1740_board_channel.cpp.
Member Function Documentation
bool V1740BoardChannel::ReadSamplesCache (UINT32 num_samples) [virtual]
Implements PhysicalBoardChannel.
Definition at line 130 of file V1740_board_channel.cpp.
References cvt_V1724_get_buffer_cache(), FALSE, GenericBoardChannel::m_ch_index, GenericBoardChannel::m_enabled, GenericBoardChannel::m_p_data_mutex, PhysicalBoardChannel::m_p_sample_buffer, and PhysicalBoardChannel::m_sample_buffer_size.
bool V1740BoardChannel::WriteChannelTrigger (void) [virtual]
Implements PhysicalBoardChannel.
Definition at line 193 of file V1740_board_channel.cpp.
References CVT_V1724_MAX_CHANNEL, cvt_V1724_set_channel_trigger(), FALSE, GenericBoard::GetSampleBit(), GenericBoardChannel::m_ch_index, GenericBoardChannel::m_parent, PhysicalBoardChannel::m_trigger_thr_sample, PhysicalBoardChannel::m_trigger_threshold_volt, and GenericBoardChannel::m_volt_2_bit.
bool V1740BoardChannel::WriteDACOffset (void) [virtual]
Implements PhysicalBoardChannel.
Definition at line 176 of file V1740_board_channel.cpp.
References CVT_V1724_MAX_CHANNEL, cvt_V1724_set_channel_offset(), FALSE, GenericBoard::GetDACUpdateFactor(), GenericBoardChannel::m_ch_index, PhysicalBoardChannel::m_DAC_offset_bit, and GenericBoardChannel::m_parent.
The documentation for this class was generated from the following files:
V1740_board_channel.h
V1740_board_channel.cpp