CAENScope: CommonChControlBase Class Reference
CommonChControlBase Class Reference
#include <common_ch_control_base.h>
Public Member Functions
CommonChControlBase ()
Constructors.
CommonChControlBase (wxWindow *parent, wxWindowID id, const wxPoint &pos, const wxSize &size, long style)
virtual void SetMediumLabel (double value)
virtual void SetOverloadBackground (const wxColor &color)
virtual void SetEnable (bool enable, bool disable_all)
Detailed Description
Includes
Forward declarations
Control identifiers
CommonChControlBase class declaration
Definition at line 36 of file common_ch_control_base.h.
Constructor & Destructor Documentation
CommonChControlBase::CommonChControlBase ()
Constructors.
CommonChControlBase type definition
CommonChControlBase event table definition
CommonChControlBase constructors
Definition at line 43 of file common_ch_control_base.cpp.
CommonChControlBase::CommonChControlBase (wxWindow * parent, wxWindowID id, const wxPoint & pos, const wxSize & size, long style)
Definition at line 47 of file common_ch_control_base.cpp.
Member Function Documentation
void CommonChControlBase::SetEnable (bool enable, bool disable_all) [virtual]
Reimplemented in CommonChControl.
Definition at line 57 of file common_ch_control_base.cpp.
Referenced by GenericBoardChannel::SetEnable().
void CommonChControlBase::SetMediumLabel (double value) [virtual]
Reimplemented in CommonChControl, and VirtualCommonChControl.
Definition at line 51 of file common_ch_control_base.cpp.
Referenced by GenericBoardChannel::DrawSamples().
void CommonChControlBase::SetOverloadBackground (const wxColor & color) [virtual]
Reimplemented in CommonChControl, and VirtualCommonChControl.
Definition at line 54 of file common_ch_control_base.cpp.
Referenced by GenericBoardChannel::DrawSamples().
The documentation for this class was generated from the following files:
common_ch_control_base.h
common_ch_control_base.cpp