CAENScope: DrawingCanvas Class Reference
DrawingCanvas Class Reference
#include <drawing_canvas.h>
Public Member Functions
DrawingCanvas ()
Constructors.
DrawingCanvas (int scope_index, wxWindow *parent, wxWindowID id=SYMBOL_DRAWINGCANVAS_IDNAME, const wxPoint &pos=SYMBOL_DRAWINGCANVAS_POSITION, const wxSize &size=SYMBOL_DRAWINGCANVAS_SIZE, long style=SYMBOL_DRAWINGCANVAS_STYLE)
~DrawingCanvas ()
bool Create (wxWindow *parent, wxWindowID id=SYMBOL_DRAWINGCANVAS_IDNAME, const wxPoint &pos=SYMBOL_DRAWINGCANVAS_POSITION, const wxSize &size=SYMBOL_DRAWINGCANVAS_SIZE, long style=SYMBOL_DRAWINGCANVAS_STYLE)
Creation.
void CreateControls ()
Creates the controls and sizers.
void OnSize (wxSizeEvent &event)
wxEVT_SIZE event handler for ID_DRAWING_CANVAS_DIALOG
void OnPaint (wxPaintEvent &event)
wxEVT_PAINT event handler for ID_DRAWING_CANVAS_DIALOG
void OnEraseBackground (wxEraseEvent &event)
wxEVT_ERASE_BACKGROUND event handler for ID_DRAWING_CANVAS_DIALOG
wxBitmap GetBitmapResource (const wxString &name)
Retrieves bitmap resources.
wxIcon GetIconResource (const wxString &name)
Retrieves icon resources.
void RefreshBackBitmap (void)
void RefreshSampleBitmap (wxBitmap *p_sample_bitmap)
Static Public Member Functions
static bool ShowToolTips ()
Should we show tooltips?
Static Public Attributes
static const int NUM_DIV_PER_SCREEN = 10
Protected Member Functions
void DrawGrid (wxDC &dc)
void DrawBackground (wxDC &dc)
void DrawCursor (wxDC &dc)
void DrawTrigger (wxDC &dc)
void DrawSamples (wxDC &dc)
Protected Attributes
wxBitmap * m_p_back_bitmap
wxBitmap * m_p_buffer_bitmap
DrawingPanel * m_parent
int m_pix_X
int m_pix_Y
bool m_first_time
int m_scope_index
Detailed Description
Compatibility
DrawingCanvas class declaration
Definition at line 62 of file drawing_canvas.h.
Constructor & Destructor Documentation
DrawingCanvas::DrawingCanvas ()
Constructors.
DrawingCanvas type definition
DrawingCanvas event table definition
DrawingCanvas constructors
Definition at line 65 of file drawing_canvas.cpp.
DrawingCanvas::DrawingCanvas (int scope_index, wxWindow * parent, wxWindowID id = SYMBOL_DRAWINGCANVAS_IDNAME, const wxPoint & pos = SYMBOL_DRAWINGCANVAS_POSITION, const wxSize & size = SYMBOL_DRAWINGCANVAS_SIZE, long style = SYMBOL_DRAWINGCANVAS_STYLE)
Definition at line 71 of file drawing_canvas.cpp.
References Create(), m_p_back_bitmap, m_p_buffer_bitmap, and m_scope_index.
DrawingCanvas::~DrawingCanvas ()
Definition at line 78 of file drawing_canvas.cpp.
References m_p_back_bitmap, and m_p_buffer_bitmap.
Member Function Documentation
bool DrawingCanvas::Create (wxWindow * parent, wxWindowID id = SYMBOL_DRAWINGCANVAS_IDNAME, const wxPoint & pos = SYMBOL_DRAWINGCANVAS_POSITION, const wxSize & size = SYMBOL_DRAWINGCANVAS_SIZE, long style = SYMBOL_DRAWINGCANVAS_STYLE)
Creation.
DrawingCanvas creator
Definition at line 88 of file drawing_canvas.cpp.
References CreateControls().
Referenced by DrawingCanvas().
void DrawingCanvas::CreateControls ()
Creates the controls and sizers.
Control creation for DrawingCanvas
Definition at line 106 of file drawing_canvas.cpp.
Referenced by Create().
void DrawingCanvas::DrawBackground (wxDC & dc) [protected]
Definition at line 312 of file drawing_canvas.cpp.
References DrawingPanel::m_app_settings, AppSettings::m_back_brush, AppSettings::m_mutex, and m_parent.
Referenced by RefreshBackBitmap().
void DrawingCanvas::DrawCursor (wxDC & dc) [protected]
Definition at line 250 of file drawing_canvas.cpp.
References GenericBoard::DrawCursor(), DrawingPanel::m_app_settings, AppSettings::m_board_array, and m_parent.
Referenced by RefreshBackBitmap().
void DrawingCanvas::DrawGrid (wxDC & dc) [protected]
Definition at line 154 of file drawing_canvas.cpp.
References DrawingPanel::m_app_settings, AppSettings::m_grid_pen, AppSettings::m_mid_grid_pen, AppSettings::m_mutex, m_parent, and NUM_DIV_PER_SCREEN.
Referenced by RefreshBackBitmap().
void DrawingCanvas::DrawSamples (wxDC & dc) [protected]
Definition at line 261 of file drawing_canvas.cpp.
References GenericBoard::DrawSamples(), DrawingPanel::m_app_settings, AppSettings::m_board_array, and m_parent.
Referenced by OnPaint().
void DrawingCanvas::DrawTrigger (wxDC & dc) [protected]
Definition at line 240 of file drawing_canvas.cpp.
References GenericBoard::DrawTrigger(), DrawingPanel::m_app_settings, AppSettings::m_board_array, and m_parent.
Referenced by RefreshBackBitmap().
wxBitmap DrawingCanvas::GetBitmapResource (const wxString & name)
Retrieves bitmap resources.
DrawingCanvas member function declarations
Get bitmap resources
Definition at line 219 of file drawing_canvas.cpp.
wxIcon DrawingCanvas::GetIconResource (const wxString & name)
Retrieves icon resources.
Get icon resources
Definition at line 232 of file drawing_canvas.cpp.
void DrawingCanvas::OnEraseBackground (wxEraseEvent & event)
wxEVT_ERASE_BACKGROUND event handler for ID_DRAWING_CANVAS_DIALOG
Definition at line 202 of file drawing_canvas.cpp.
void DrawingCanvas::OnPaint (wxPaintEvent & event)
wxEVT_PAINT event handler for ID_DRAWING_CANVAS_DIALOG
Definition at line 130 of file drawing_canvas.cpp.
References DrawSamples(), DrawingPanel::IsFreezed(), DrawingPanel::m_app_settings, m_first_time, m_p_back_bitmap, m_p_buffer_bitmap, m_parent, and RefreshBackBitmap().
void DrawingCanvas::OnSize (wxSizeEvent & event)
wxEVT_SIZE event handler for ID_DRAWING_CANVAS_DIALOG
DrawingCanvas event handler declarations
Definition at line 120 of file drawing_canvas.cpp.
References RefreshBackBitmap().
void DrawingCanvas::RefreshBackBitmap (void)
Definition at line 271 of file drawing_canvas.cpp.
References DrawBackground(), DrawCursor(), DrawGrid(), DrawTrigger(), DrawingPanel::IsFreezed(), DrawingPanel::m_app_settings, AppSettings::m_board_array, m_p_back_bitmap, m_p_buffer_bitmap, m_parent, m_pix_X, m_pix_Y, m_scope_index, NUM_DIV_PER_SCREEN, AppSettings::SetDiv2Pix(), GenericBoard::SetDiv2Pix(), and GenericBoard::SetPix().
Referenced by OnPaint(), OnSize(), and DrawingPanel::RefreshBackBitmap().
void DrawingCanvas::RefreshSampleBitmap (wxBitmap * p_sample_bitmap)
bool DrawingCanvas::ShowToolTips () [static]
Should we show tooltips?
Definition at line 210 of file drawing_canvas.cpp.
Member Data Documentation
bool DrawingCanvas::m_first_time [protected]
Definition at line 117 of file drawing_canvas.h.
Referenced by OnPaint().
wxBitmap* DrawingCanvas::m_p_back_bitmap [protected]
Definition at line 114 of file drawing_canvas.h.
Referenced by DrawingCanvas(), OnPaint(), RefreshBackBitmap(), and ~DrawingCanvas().
wxBitmap * DrawingCanvas::m_p_buffer_bitmap [protected]
Definition at line 114 of file drawing_canvas.h.
Referenced by DrawingCanvas(), OnPaint(), RefreshBackBitmap(), and ~DrawingCanvas().
DrawingPanel* DrawingCanvas::m_parent [protected]
Definition at line 115 of file drawing_canvas.h.
Referenced by DrawBackground(), DrawCursor(), DrawGrid(), DrawSamples(), DrawTrigger(), OnPaint(), and RefreshBackBitmap().
int DrawingCanvas::m_pix_X [protected]
Definition at line 116 of file drawing_canvas.h.
Referenced by RefreshBackBitmap().
int DrawingCanvas::m_pix_Y [protected]
Definition at line 116 of file drawing_canvas.h.
Referenced by RefreshBackBitmap().
int DrawingCanvas::m_scope_index [protected]
Definition at line 118 of file drawing_canvas.h.
Referenced by DrawingCanvas(), and RefreshBackBitmap().
const int DrawingCanvas::NUM_DIV_PER_SCREEN = 10 [static]
Definition at line 106 of file drawing_canvas.h.
Referenced by DrawGrid(), GenericBoardChannel::DrawPosition(), GenericBoardChannel::DrawSamples(), PhysicalBoardChannel::DrawTrigger(), DrawingLeftCanvas::RefreshBackBitmap(), and RefreshBackBitmap().
The documentation for this class was generated from the following files:
drawing_canvas.h
drawing_canvas.cpp