CAENScope: VirtualBoardChannel Class Reference
VirtualBoardChannel Class Reference
#include <virtual_board_channel.h>
Public Member Functions
VirtualBoardChannel (GenericBoard *parent, int ch_index, cvt_board_data *p_data, void(*scope_refresh)(int, bool), wxMutex *p_data_mutex, AppSettings *p_app_settings)
~VirtualBoardChannel (void)
virtual int GetSample (int i)
virtual double GetSampleVolt (int i)
virtual UINT32 GetBufferCount (void)
virtual void DrawTrigger (int scope_index, wxDC &dc)
bool LoadConfig (wxConfigBase *p_config, const wxString &base_section)
bool SaveConfig (wxConfigBase *p_config, const wxString &base_section)
wxString GetRecordChannelNumber (void)
const char * GetExpressionDef (void)
void SetExpressionDef (const char *expression_def)
Protected Member Functions
bool GetChannelValue (int channel_id, double &result)
bool GetChannelValueVolt (int channel_id, double &result)
bool GetChannelBufferCount (int channel_id, UINT32 &result)
Protected Attributes
RpnHandler * m_p_rpn_handler
int m_sample_index
Friends
class RpnHandler
Detailed Description
Definition at line 27 of file virtual_board_channel.h.
Constructor & Destructor Documentation
VirtualBoardChannel::VirtualBoardChannel (GenericBoard * parent, int ch_index, cvt_board_data * p_data, void(*)(int, bool) scope_refresh, wxMutex * p_data_mutex, AppSettings * p_app_settings)
Definition at line 40 of file virtual_board_channel.cpp.
References m_p_rpn_handler.
VirtualBoardChannel::~VirtualBoardChannel (void)
Definition at line 46 of file virtual_board_channel.cpp.
References m_p_rpn_handler.
Member Function Documentation
void VirtualBoardChannel::DrawTrigger (int scope_index, wxDC & dc) [virtual]
Implements GenericBoardChannel.
Definition at line 76 of file virtual_board_channel.cpp.
UINT32 VirtualBoardChannel::GetBufferCount (void) [inline, virtual]
Implements GenericBoardChannel.
Definition at line 70 of file virtual_board_channel.cpp.
References RpnHandler::GetBufferCount(), and m_p_rpn_handler.
bool VirtualBoardChannel::GetChannelBufferCount (int channel_id, UINT32 & result) [protected]
Definition at line 127 of file virtual_board_channel.cpp.
References GenericBoard::GetPhysicalChannelBufferCount(), and GenericBoardChannel::m_parent.
Referenced by RpnHandler::GetBufferCount().
bool VirtualBoardChannel::GetChannelValue (int channel_id, double & result) [protected]
Definition at line 119 of file virtual_board_channel.cpp.
References GenericBoard::GetPhysicalChannelValue(), GenericBoardChannel::m_parent, and m_sample_index.
bool VirtualBoardChannel::GetChannelValueVolt (int channel_id, double & result) [protected]
Definition at line 123 of file virtual_board_channel.cpp.
References GenericBoard::GetPhysicalChannelValueVolt(), GenericBoardChannel::m_parent, and m_sample_index.
Referenced by RpnHandler::DoEval().
const char * VirtualBoardChannel::GetExpressionDef (void)
Definition at line 131 of file virtual_board_channel.cpp.
References RpnHandler::Format(), and m_p_rpn_handler.
Referenced by VirtualChannelDefDialog::VirtualChannelDefDialog().
wxString VirtualBoardChannel::GetRecordChannelNumber (void) [virtual]
Reimplemented from GenericBoardChannel.
Definition at line 66 of file virtual_board_channel.cpp.
References GenericBoardChannel::m_ch_index.
int VirtualBoardChannel::GetSample (int i) [inline, virtual]
Implements GenericBoardChannel.
Definition at line 62 of file virtual_board_channel.cpp.
References GetSampleVolt(), and GenericBoardChannel::m_volt_2_bit.
double VirtualBoardChannel::GetSampleVolt (int i) [inline, virtual]
Implements GenericBoardChannel.
Definition at line 51 of file virtual_board_channel.cpp.
References RpnHandler::Eval(), m_p_rpn_handler, and m_sample_index.
Referenced by GetSample().
bool VirtualBoardChannel::LoadConfig (wxConfigBase * p_config, const wxString & base_section) [virtual]
Reimplemented from GenericBoardChannel.
Definition at line 81 of file virtual_board_channel.cpp.
References m_p_rpn_handler, and RpnHandler.
bool VirtualBoardChannel::SaveConfig (wxConfigBase * p_config, const wxString & base_section) [virtual]
Reimplemented from GenericBoardChannel.
Definition at line 99 of file virtual_board_channel.cpp.
References RpnHandler::Format(), m_p_rpn_handler, and GenericBoardChannel::SaveConfig().
void VirtualBoardChannel::SetExpressionDef (const char * expression_def)
Definition at line 137 of file virtual_board_channel.cpp.
References m_p_rpn_handler, RpnHandler::Parse(), and RpnHandler.
Referenced by VirtualChannelDefDialog::OnVchDefOkButtonClick().
Friends And Related Function Documentation
friend class RpnHandler [friend]
Definition at line 61 of file virtual_board_channel.h.
Referenced by LoadConfig(), and SetExpressionDef().
Member Data Documentation
RpnHandler* VirtualBoardChannel::m_p_rpn_handler [protected]
Definition at line 55 of file virtual_board_channel.h.
Referenced by GetBufferCount(), GetExpressionDef(), GetSampleVolt(), LoadConfig(), SaveConfig(), SetExpressionDef(), VirtualBoardChannel(), and ~VirtualBoardChannel().
int VirtualBoardChannel::m_sample_index [protected]
Definition at line 59 of file virtual_board_channel.h.
Referenced by GetChannelValue(), GetChannelValueVolt(), and GetSampleVolt().
The documentation for this class was generated from the following files:
virtual_board_channel.h
virtual_board_channel.cpp