CAENScope: V17XXBoard Class Reference
V17XXBoard Class Reference
#include <V17XX_board.h>
Public Types
enum BOARD_VARIANT { BV_VME = 0, BV_DESKTOP, BV_NIM }
Public Member Functions
V17XXBoard (int board_index, void(*scope_refresh)(int, bool), void(*update_samples_ready_led)(bool), wxMutex *p_data_mutex, AppSettings *p_app_settings, BOARD_VARIANT board_variant)
~V17XXBoard (void)
bool Open (long vme_handle)
GenericBoardChannel * CreateChannel (int ch_index, void(*scope_refresh)(int, bool), wxMutex *p_data_mutex)
bool WriteSampleBufferSize (void)
bool WriteTriggerMode (bool started)
bool WriteSoftwareTrigger (void)
bool SetFrontPanelIO (bool use_TTL)
bool ReadBoardData (UINT32 *p_max_num_samples, UINT32 *p_num_events)
bool DoStartAcquisition (void)
bool DoStopAcquisition (void)
bool Init (long vme_handle)
Static Public Member Functions
static bool GetBoardId (cvt_board_data data, int &board_id)
static bool v1724_get_system_info_wrapper (cvt_V1724_data *p_data, UINT16 *p_firmware_rev, CVT_V1724_ROM_CONFIG *p_rom_config, BOOL *p_is_board_type_correct, BOOL *p_is_firmware_rev_correct)
Protected Attributes
BOARD_VARIANT m_board_variant
Detailed Description
Definition at line 55 of file V17XX_board.h.
Member Enumeration Documentation
enum V17XXBoard::BOARD_VARIANT
Enumerator:
BV_VME
BV_DESKTOP
BV_NIM
Definition at line 58 of file V17XX_board.h.
Constructor & Destructor Documentation
V17XXBoard::V17XXBoard (int board_index, void(*)(int, bool) scope_refresh, void(*)(bool) update_samples_ready_led, wxMutex * p_data_mutex, AppSettings * p_app_settings, V17XXBoard::BOARD_VARIANT board_variant)
Definition at line 32 of file V17XX_board.cpp.
References m_board_variant, and GenericBoard::m_p_data.
V17XXBoard::~V17XXBoard (void)
Definition at line 39 of file V17XX_board.cpp.
References cvt_V1724_close(), and GenericBoard::m_p_data.
Member Function Documentation
GenericBoardChannel * V17XXBoard::CreateChannel (int ch_index, void(*)(int, bool) scope_refresh, wxMutex * p_data_mutex) [virtual]
Implements GenericBoard.
Reimplemented in V1740Board.
Definition at line 146 of file V17XX_board.cpp.
References GenericBoard::m_p_app_settings, and GenericBoard::m_p_data.
bool V17XXBoard::DoStartAcquisition (void) [virtual]
Implements GenericBoard.
Reimplemented in V1740Board.
Definition at line 210 of file V17XX_board.cpp.
References cvt_V1724_set_readout_mode(), cvt_V1724_start_acquisition(), FALSE, GenericBoard::m_channel_array, and GenericBoard::m_p_data.
bool V17XXBoard::DoStopAcquisition (void) [virtual]
Implements GenericBoard.
Definition at line 224 of file V17XX_board.cpp.
References cvt_V1724_stop_acquisition(), FALSE, and GenericBoard::m_p_data.
bool V17XXBoard::GetBoardId (cvt_board_data data, int & board_id) [static]
Definition at line 229 of file V17XX_board.cpp.
References cvt_read(), CVT_V1724_ROM_BOARD_ID_0_ADD, CVT_V1724_ROM_BOARD_ID_0_AM, CVT_V1724_ROM_BOARD_ID_0_DATA_SIZE, CVT_V1724_ROM_BOARD_ID_1_ADD, CVT_V1724_ROM_BOARD_ID_1_AM, CVT_V1724_ROM_BOARD_ID_1_DATA_SIZE, CVT_V1724_ROM_BOARD_ID_2_ADD, CVT_V1724_ROM_BOARD_ID_2_AM, and CVT_V1724_ROM_BOARD_ID_2_DATA_SIZE.
Referenced by AppSettings::Load().
bool V17XXBoard::Init (long vme_handle) [virtual]
Reimplemented from GenericBoard.
Reimplemented in V1721Board, V1731Board, and V1751Board.
Definition at line 54 of file V17XX_board.cpp.
References CVT_V1724_MIN_FIRMARE_REV, cvt_V1724_open(), GenericBoard::GetTypeString(), GenericBoard::m_p_app_settings, GenericBoard::m_p_data, AppSettings::m_use_TTL, SetFrontPanelIO(), v1724_get_system_info_wrapper(), and WriteTriggerMode().
Referenced by V1751Board::Init(), V1731Board::Init(), and V1721Board::Init().
bool V17XXBoard::Open (long vme_handle) [virtual]
Implements GenericBoard.
Definition at line 49 of file V17XX_board.cpp.
bool V17XXBoard::ReadBoardData (UINT32 * p_max_num_samples, UINT32 * p_num_events) [virtual]
Implements GenericBoard.
Definition at line 206 of file V17XX_board.cpp.
References cvt_V1724_read_data(), FALSE, and GenericBoard::m_p_data.
bool V17XXBoard::SetFrontPanelIO (bool use_TTL) [virtual]
Implements GenericBoard.
Definition at line 200 of file V17XX_board.cpp.
References cvt_V1724_data_clear(), CVT_V1724_FPIO_MODES_GPIO, cvt_V1724_set_front_panel_IO(), FALSE, and GenericBoard::m_p_data.
Referenced by Init(), V1751Board::Init(), V1731Board::Init(), and V1721Board::Init().
bool V17XXBoard::v1724_get_system_info_wrapper (cvt_V1724_data * p_data, UINT16 * p_firmware_rev, CVT_V1724_ROM_CONFIG * p_rom_config, BOOL * p_is_board_type_correct, BOOL * p_is_firmware_rev_correct) [static]
Definition at line 90 of file V17XX_board.cpp.
References CVT_V1720, CVT_V1721, CVT_V1724, cvt_V1724_get_system_info(), CVT_V1731, CVT_V1740, CVT_V1751, CVT_V17XX_RCFG_BOARD_ID_DT5720, CVT_V17XX_RCFG_BOARD_ID_DT5721, CVT_V17XX_RCFG_BOARD_ID_DT5724, CVT_V17XX_RCFG_BOARD_ID_DT5731, CVT_V17XX_RCFG_BOARD_ID_DT5740, CVT_V17XX_RCFG_BOARD_ID_DT5751, CVT_V17XX_RCFG_BOARD_ID_N6720, CVT_V17XX_RCFG_BOARD_ID_N6721, CVT_V17XX_RCFG_BOARD_ID_N6724, CVT_V17XX_RCFG_BOARD_ID_N6731, CVT_V17XX_RCFG_BOARD_ID_N6740, CVT_V17XX_RCFG_BOARD_ID_N6751, CVT_V17XX_RCFG_BOARD_ID_V1720, CVT_V17XX_RCFG_BOARD_ID_V1721, CVT_V17XX_RCFG_BOARD_ID_V1724, CVT_V17XX_RCFG_BOARD_ID_V1731, CVT_V17XX_RCFG_BOARD_ID_V1740, CVT_V17XX_RCFG_BOARD_ID_V1751, CVT_V17XX_RCFG_BOARD_ID_VX1720, CVT_V17XX_RCFG_BOARD_ID_VX1721, CVT_V17XX_RCFG_BOARD_ID_VX1724, CVT_V17XX_RCFG_BOARD_ID_VX1731, CVT_V17XX_RCFG_BOARD_ID_VX1740, CVT_V17XX_RCFG_BOARD_ID_VX1751, CVT_V1724_ROM_CONFIG::m_board_id, and cvt_V1724_data::m_type.
Referenced by Init().
bool V17XXBoard::WriteSampleBufferSize (void) [virtual]
Implements GenericBoard.
Reimplemented in V1740Board.
Definition at line 151 of file V17XX_board.cpp.
References CVT_V1724_ACQCTRL_ACQ_MODE_REGISTER_CTRL, cvt_V1724_data_clear(), cvt_V1724_get_buffer_samples(), cvt_V1724_set_acquisition_mode(), cvt_V1724_set_buffer_samples(), FALSE, AppSettings::m_max_log_X, AppSettings::m_num_sample, GenericBoard::m_p_app_settings, and GenericBoard::m_p_data.
bool V17XXBoard::WriteSoftwareTrigger (void) [virtual]
Implements GenericBoard.
Definition at line 193 of file V17XX_board.cpp.
References cvt_V1724_software_trigger(), FALSE, AppSettings::m_mutex, GenericBoard::m_p_app_settings, and GenericBoard::m_p_data.
bool V17XXBoard::WriteTriggerMode (bool started) [virtual]
Implements GenericBoard.
Definition at line 168 of file V17XX_board.cpp.
References cvt_V1724_data_clear(), cvt_V1724_set_trigger_mode(), AppSettings::EXT_TRIGGER_MSK, AppSettings::FALLING_EDGE, FALSE, GenericBoard::GetChEnableMsk(), GenericBoard::m_channel_array, GenericBoard::m_p_app_settings, GenericBoard::m_p_data, AppSettings::m_post_trigger, AppSettings::m_trigger_edge_type, AppSettings::m_trigger_msk, and AppSettings::NO_TRIGGER.
Referenced by Init(), V1751Board::Init(), V1731Board::Init(), and V1721Board::Init().
Member Data Documentation
BOARD_VARIANT V17XXBoard::m_board_variant [protected]
Definition at line 83 of file V17XX_board.h.
Referenced by V1751Board::GetChEnableMsk(), V1740Board::GetChEnableMsk(), V1731Board::GetChEnableMsk(), V1724Board::GetChEnableMsk(), V1721Board::GetChEnableMsk(), V1720Board::GetChEnableMsk(), V1751Board::GetTypeString(), V1740Board::GetTypeString(), V1731Board::GetTypeString(), V1724Board::GetTypeString(), V1721Board::GetTypeString(), V1720Board::GetTypeString(), and V17XXBoard().
The documentation for this class was generated from the following files:
V17XX_board.h
V17XX_board.cpp