CAENScope: TriggerChControl Class Reference
TriggerChControl Class Reference
#include <trigger_ch_control.h>
Public Member Functions
TriggerChControl ()
Constructors.
TriggerChControl (wxWindow *parent, wxWindowID id=SYMBOL_TRIGGERCHCONTROL_IDNAME, const wxPoint &pos=SYMBOL_TRIGGERCHCONTROL_POSITION, const wxSize &size=SYMBOL_TRIGGERCHCONTROL_SIZE, long style=SYMBOL_TRIGGERCHCONTROL_STYLE)
bool Create (wxWindow *parent, wxWindowID id=SYMBOL_TRIGGERCHCONTROL_IDNAME, const wxPoint &pos=SYMBOL_TRIGGERCHCONTROL_POSITION, const wxSize &size=SYMBOL_TRIGGERCHCONTROL_SIZE, long style=SYMBOL_TRIGGERCHCONTROL_STYLE)
Creation.
void CreateControls ()
Creates the controls and sizers.
void OnThresholdSpinctrlUpdated (wxSpinEvent &event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_THRESHOLD_SPINCTRL
void OnThrSamplesSpinctrlUpdated (wxSpinEvent &event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_THR_SAMPLES_SPINCTRL
void OnThresholdSpinctrlTextUpdated (wxCommandEvent &event)
void OnThrSamplesSpinctrlTextUpdated (wxCommandEvent &event)
wxBitmap GetBitmapResource (const wxString &name)
Retrieves bitmap resources.
wxIcon GetIconResource (const wxString &name)
Retrieves icon resources.
bool SetupBoard (GenericBoard *p_board, int ch_index, int ch_count)
bool UpdateControls ()
Static Public Member Functions
static bool ShowToolTips ()
Should we show tooltips?
Public Attributes
wxStaticBox * m_main_sizer_text
wxSpinCtrl * m_ch_threshold_control
wxSpinCtrl * m_thr_sample_control
Private Member Functions
void UpdateThreshold (int value)
void UpdateThrSamples (int value)
Private Attributes
GenericBoard * m_p_board
PhysicalBoardChannel * m_p_board_channel
int m_ch_index
int m_ch_count
Detailed Description
Compatibility
TriggerChControl class declaration
Definition at line 66 of file trigger_ch_control.h.
Constructor & Destructor Documentation
TriggerChControl::TriggerChControl ()
Constructors.
TriggerChControl type definition
TriggerChControl event table definition
TriggerChControl constructors
Definition at line 64 of file trigger_ch_control.cpp.
TriggerChControl::TriggerChControl (wxWindow * parent, wxWindowID id = SYMBOL_TRIGGERCHCONTROL_IDNAME, const wxPoint & pos = SYMBOL_TRIGGERCHCONTROL_POSITION, const wxSize & size = SYMBOL_TRIGGERCHCONTROL_SIZE, long style = SYMBOL_TRIGGERCHCONTROL_STYLE)
Definition at line 68 of file trigger_ch_control.cpp.
References Create().
Member Function Documentation
bool TriggerChControl::Create (wxWindow * parent, wxWindowID id = SYMBOL_TRIGGERCHCONTROL_IDNAME, const wxPoint & pos = SYMBOL_TRIGGERCHCONTROL_POSITION, const wxSize & size = SYMBOL_TRIGGERCHCONTROL_SIZE, long style = SYMBOL_TRIGGERCHCONTROL_STYLE)
Creation.
TriggerChControl creator
Definition at line 77 of file trigger_ch_control.cpp.
References CreateControls(), m_ch_threshold_control, m_main_sizer_text, and m_thr_sample_control.
Referenced by TriggerChControl().
void TriggerChControl::CreateControls ()
Creates the controls and sizers.
Control creation for TriggerChControl
Definition at line 102 of file trigger_ch_control.cpp.
References ID_THR_SAMPLES_SPINCTRL, ID_THRESHOLD_SPINCTRL, m_ch_threshold_control, m_main_sizer_text, m_thr_sample_control, and ShowToolTips().
Referenced by Create().
wxBitmap TriggerChControl::GetBitmapResource (const wxString & name)
Retrieves bitmap resources.
Get bitmap resources
Definition at line 143 of file trigger_ch_control.cpp.
wxIcon TriggerChControl::GetIconResource (const wxString & name)
Retrieves icon resources.
Get icon resources
Definition at line 156 of file trigger_ch_control.cpp.
void TriggerChControl::OnThresholdSpinctrlTextUpdated (wxCommandEvent & event)
wxEVT_COMMAND_TEXT_UPDATED event handler for ID_THRESHOLD_SPINCTRL
Definition at line 212 of file trigger_ch_control.cpp.
References m_ch_threshold_control, and UpdateThreshold().
void TriggerChControl::OnThresholdSpinctrlUpdated (wxSpinEvent & event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_THRESHOLD_SPINCTRL
Definition at line 169 of file trigger_ch_control.cpp.
References UpdateThreshold().
void TriggerChControl::OnThrSamplesSpinctrlTextUpdated (wxCommandEvent & event)
wxEVT_COMMAND_TEXT_UPDATED event handler for ID_THR_SAMPLES_SPINCTRL
Definition at line 222 of file trigger_ch_control.cpp.
References m_thr_sample_control, and UpdateThrSamples().
void TriggerChControl::OnThrSamplesSpinctrlUpdated (wxSpinEvent & event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_THR_SAMPLES_SPINCTRL
Definition at line 179 of file trigger_ch_control.cpp.
References UpdateThrSamples().
bool TriggerChControl::SetupBoard (GenericBoard * p_board, int ch_index, int ch_count)
Definition at line 184 of file trigger_ch_control.cpp.
References m_ch_count, m_ch_index, GenericBoard::m_channel_array, m_p_board, and m_p_board_channel.
Referenced by MainFrame::CreateDynControls().
bool TriggerChControl::ShowToolTips () [static]
Should we show tooltips?
Definition at line 134 of file trigger_ch_control.cpp.
Referenced by CreateControls().
bool TriggerChControl::UpdateControls (void)
Definition at line 197 of file trigger_ch_control.cpp.
References m_ch_count, m_ch_threshold_control, m_main_sizer_text, m_p_board_channel, m_thr_sample_control, PhysicalBoardChannel::m_trigger_thr_sample, PhysicalBoardChannel::m_trigger_threshold_volt, and PhysicalBoardChannel::WriteChannelTrigger().
void TriggerChControl::UpdateThreshold (int value) [private]
Definition at line 228 of file trigger_ch_control.cpp.
References m_p_board_channel, PhysicalBoardChannel::m_trigger_threshold_volt, SCOPE_NUM_PANELS, GenericBoardChannel::ScopeRefresh, and PhysicalBoardChannel::WriteChannelTrigger().
Referenced by OnThresholdSpinctrlTextUpdated(), and OnThresholdSpinctrlUpdated().
void TriggerChControl::UpdateThrSamples (int value) [private]
Definition at line 238 of file trigger_ch_control.cpp.
References m_p_board_channel, PhysicalBoardChannel::m_trigger_thr_sample, SCOPE_NUM_PANELS, GenericBoardChannel::ScopeRefresh, and PhysicalBoardChannel::WriteChannelTrigger().
Referenced by OnThrSamplesSpinctrlTextUpdated(), and OnThrSamplesSpinctrlUpdated().
Member Data Documentation
int TriggerChControl::m_ch_count [private]
Definition at line 119 of file trigger_ch_control.h.
Referenced by SetupBoard(), and UpdateControls().
int TriggerChControl::m_ch_index [private]
Definition at line 118 of file trigger_ch_control.h.
Referenced by SetupBoard().
wxSpinCtrl* TriggerChControl::m_ch_threshold_control
Definition at line 108 of file trigger_ch_control.h.
Referenced by Create(), CreateControls(), OnThresholdSpinctrlTextUpdated(), and UpdateControls().
wxStaticBox* TriggerChControl::m_main_sizer_text
Definition at line 107 of file trigger_ch_control.h.
Referenced by Create(), CreateControls(), and UpdateControls().
GenericBoard* TriggerChControl::m_p_board [private]
Definition at line 116 of file trigger_ch_control.h.
Referenced by SetupBoard().
PhysicalBoardChannel* TriggerChControl::m_p_board_channel [private]
Definition at line 117 of file trigger_ch_control.h.
Referenced by SetupBoard(), UpdateControls(), UpdateThreshold(), and UpdateThrSamples().
wxSpinCtrl* TriggerChControl::m_thr_sample_control
Definition at line 109 of file trigger_ch_control.h.
Referenced by Create(), CreateControls(), OnThrSamplesSpinctrlTextUpdated(), and UpdateControls().
The documentation for this class was generated from the following files:
trigger_ch_control.h
trigger_ch_control.cpp