CAENScope: V1731Board Class Reference
V1731Board Class Reference
#include <V1731_board.h>
Public Member Functions
V1731Board (int board_index, void(*scope_refresh)(int, bool), void(*update_samples_ready_led)(bool), wxMutex *p_data_mutex, AppSettings *p_app_settings, V17XXBoard::BOARD_VARIANT board_variant, bool is_des_mode)
wxString GetTypeString ()
CVT_V17XX_TYPES GetType ()
double GetClockMHz () const
int GetSampleBit () const
double GetVolt2Bit () const
bool Init (long vme_handle)
UINT8 GetChEnableMsk () const
bool GetBoardMemory (UINT32 &num_ksamples_per_channel)
virtual double GetDACUpdateFactor (void)
Protected Attributes
bool m_is_des_mode
Detailed Description
Definition at line 31 of file V1731_board.h.
Constructor & Destructor Documentation
V1731Board::V1731Board (int board_index, void(*)(int, bool) scope_refresh, void(*)(bool) update_samples_ready_led, wxMutex * p_data_mutex, AppSettings * p_app_settings, V17XXBoard::BOARD_VARIANT board_variant, bool is_des_mode)
Definition at line 32 of file V1731_board.cpp.
Member Function Documentation
bool V1731Board::GetBoardMemory (UINT32 & num_ksamples_per_channel) [virtual]
Implements GenericBoard.
Definition at line 84 of file V1731_board.cpp.
References cvt_read(), CVT_V1724_BOARD_INFO_ADD, CVT_V1724_BOARD_INFO_AM, CVT_V1724_BOARD_INFO_DATA_SIZE, CVT_V1724_GET_BRDINF_BLOCK_SIZE_KW, and GenericBoard::m_p_data.
UINT8 V1731Board::GetChEnableMsk () const [inline, virtual]
Implements GenericBoard.
Definition at line 56 of file V1731_board.h.
References V17XXBoard::BV_DESKTOP, V17XXBoard::BV_NIM, V17XXBoard::BV_VME, V17XXBoard::m_board_variant, and m_is_des_mode.
Referenced by Init().
double V1731Board::GetClockMHz () const [inline, virtual]
Implements GenericBoard.
Definition at line 52 of file V1731_board.h.
References CVT_V1731_BOARD_CLOCK_INDEX, CVT_V1731_DES_BOARD_CLOCK_INDEX, CVT_V17XX_BOARD_CLOCK_KHZ, and m_is_des_mode.
virtual double V1731Board::GetDACUpdateFactor (void) [inline, virtual]
Reimplemented from GenericBoard.
Definition at line 72 of file V1731_board.h.
int V1731Board::GetSampleBit () const [inline, virtual]
Implements GenericBoard.
Definition at line 53 of file V1731_board.h.
CVT_V17XX_TYPES V1731Board::GetType () [inline, virtual]
Implements GenericBoard.
Definition at line 51 of file V1731_board.h.
References CVT_V1731.
wxString V1731Board::GetTypeString () [inline, virtual]
Implements GenericBoard.
Definition at line 38 of file V1731_board.h.
References V17XXBoard::BV_DESKTOP, V17XXBoard::BV_NIM, V17XXBoard::BV_VME, V17XXBoard::m_board_variant, and m_is_des_mode.
double V1731Board::GetVolt2Bit () const [inline, virtual]
Implements GenericBoard.
Definition at line 54 of file V1731_board.h.
bool V1731Board::Init (long vme_handle) [virtual]
Reimplemented from V17XXBoard.
Definition at line 37 of file V1731_board.cpp.
References cvt_V1724_adc_calib(), cvt_V1724_set_des_mode(), cvt_V1724_software_reset(), FALSE, GetChEnableMsk(), V17XXBoard::Init(), m_is_des_mode, GenericBoard::m_p_app_settings, GenericBoard::m_p_data, AppSettings::m_use_TTL, V17XXBoard::SetFrontPanelIO(), and V17XXBoard::WriteTriggerMode().
Member Data Documentation
bool V1731Board::m_is_des_mode [protected]
Definition at line 72 of file V1731_board.h.
Referenced by GetChEnableMsk(), GetClockMHz(), GetTypeString(), and Init().
The documentation for this class was generated from the following files:
V1731_board.h
V1731_board.cpp