CAENScope: GenericBoard Class Reference
GenericBoard Class Reference
#include <generic_board.h>
Public Member Functions
GenericBoard (int board_index, void(*scope_refresh)(int, bool), void(*update_samples_ready_led)(bool), wxMutex *p_data_mutex, AppSettings *p_app_settings)
virtual ~GenericBoard (void)
virtual bool LoadConfig (wxConfigBase *p_config, const wxString &base_section)
virtual bool SaveConfig (wxConfigBase *p_config, const wxString &base_section)
virtual GenericBoardChannel * CreateVirtualChannel (int ch_index, void(*scope_refresh)(int, bool), wxMutex *p_data_mutex)
virtual bool GetPhysicalChannelValue (int ch_index, int sample_index, double &result)
virtual bool GetPhysicalChannelValueVolt (int ch_index, int sample_index, double &result)
virtual bool GetPhysicalChannelBufferCount (int ch_index, UINT32 &result)
virtual double GetDACUpdateFactor (void)
virtual UINT8 GetChEnableMsk () const =0
virtual wxString GetTypeString ()=0
virtual CVT_V17XX_TYPES GetType ()=0
virtual double GetClockMHz () const =0
virtual int GetSampleBit () const =0
virtual double GetVolt2Bit () const =0
virtual bool Open (long vme_handle)=0
virtual GenericBoardChannel * CreateChannel (int ch_index, void(*scope_refresh)(int, bool), wxMutex *p_data_mutex)=0
virtual bool WriteSampleBufferSize (void)=0
virtual bool WriteTriggerMode (bool started)=0
virtual bool WriteSoftwareTrigger (void)=0
virtual bool SetFrontPanelIO (bool use_TTL)=0
virtual bool ReadBoardData (UINT32 *p_max_num_samples, UINT32 *p_num_events)=0
virtual bool DoStartAcquisition (void)=0
virtual bool DoStopAcquisition (void)=0
virtual bool GetBoardMemory (UINT32 &num_ksamples_per_channel)=0
virtual bool Init (long)
void DrawTrigger (int scope_index, wxDC &dc)
void DrawCursor (int scope_index, wxDC &dc)
void DrawSamples (int scope_index, wxDC &dc)
void SetDiv2Pix (int scope_index, double div_2_pix_Y)
void SetLeftDiv2Pix (int scope_index, double div_2_pix_Y)
void SetSec2Div (int scope_index, double sec_2_div)
void SetPix (int scope_index, int pix_X, int pix_Y)
void SetLeftPix (int scope_index, int pix_X, int pix_Y)
void DrawPosition (int scope_index, wxDC &dc)
bool DoStartRunning (void)
void DoStopRunning (void)
bool ToggleRecordStatus (const wxString &path, const wxString &file_name, const wxString &timestamp, bool start, bool use_max_buffer, int max_buffer)
bool IsRunning (void)
void SetRunning (bool value)
Public Attributes
wxArrayPtrVoid m_channel_array
wxArrayPtrVoid m_virtual_channel_array
wxMutex * m_p_data_mutex
void(* ScopeRefresh)(int, bool)
void(* UpdateSamplesReadyLed)(bool)
Protected Attributes
cvt_board_data * m_p_data
BoardWorkerThread * m_p_worker_thread
bool m_is_running
AppSettings * m_p_app_settings
int m_board_index
bool m_is_recording
int m_record_max_buffers
bool m_record_use_max_buffers
Friends
class BoardWorkerThread
Detailed Description
Definition at line 34 of file generic_board.h.
Constructor & Destructor Documentation
GenericBoard::GenericBoard (int board_index, void(*)(int, bool) scope_refresh, void(*)(bool) update_samples_ready_led, wxMutex * p_data_mutex, AppSettings * p_app_settings)
Definition at line 33 of file generic_board.cpp.
References m_is_recording, m_is_running, m_p_data, m_record_max_buffers, and m_record_use_max_buffers.
GenericBoard::~GenericBoard (void) [virtual]
Definition at line 45 of file generic_board.cpp.
References DoStopRunning(), m_channel_array, and m_virtual_channel_array.
Member Function Documentation
virtual GenericBoardChannel* GenericBoard::CreateChannel (int ch_index, void(*)(int, bool) scope_refresh, wxMutex * p_data_mutex) [pure virtual]
Implemented in V1740Board, and V17XXBoard.
Referenced by LoadConfig().
GenericBoardChannel * GenericBoard::CreateVirtualChannel (int ch_index, void(*)(int, bool) scope_refresh, wxMutex * p_data_mutex) [virtual]
Definition at line 436 of file generic_board.cpp.
References m_p_app_settings, and m_p_data.
Referenced by V1740Board::LoadConfig(), and LoadConfig().
virtual bool GenericBoard::DoStartAcquisition (void) [pure virtual]
Implemented in V1740Board, and V17XXBoard.
Referenced by DoStartRunning().
bool GenericBoard::DoStartRunning (void)
Definition at line 185 of file generic_board.cpp.
References BoardWorkerThread, DoStartAcquisition(), DoStopRunning(), IsRunning(), m_p_worker_thread, and SetRunning().
virtual bool GenericBoard::DoStopAcquisition (void) [pure virtual]
Implemented in V17XXBoard.
Referenced by DoStopRunning().
void GenericBoard::DoStopRunning (void)
Definition at line 220 of file generic_board.cpp.
References DoStopAcquisition(), IsRunning(), m_p_worker_thread, and SetRunning().
Referenced by DoStartRunning(), and ~GenericBoard().
void GenericBoard::DrawCursor (int scope_index, wxDC & dc)
Definition at line 252 of file generic_board.cpp.
References GenericBoardChannel::DrawCursor(), m_channel_array, and m_virtual_channel_array.
Referenced by DrawingCanvas::DrawCursor().
void GenericBoard::DrawPosition (int scope_index, wxDC & dc)
Definition at line 286 of file generic_board.cpp.
References GenericBoardChannel::DrawPosition(), m_channel_array, and m_virtual_channel_array.
Referenced by DrawingLeftCanvas::DrawPosition().
void GenericBoard::DrawSamples (int scope_index, wxDC & dc)
Definition at line 374 of file generic_board.cpp.
References GenericBoardChannel::DrawSamples(), m_channel_array, and m_virtual_channel_array.
Referenced by DrawingCanvas::DrawSamples().
void GenericBoard::DrawTrigger (int scope_index, wxDC & dc)
Definition at line 269 of file generic_board.cpp.
References GenericBoardChannel::DrawTrigger(), m_channel_array, and m_virtual_channel_array.
Referenced by DrawingCanvas::DrawTrigger().
virtual bool GenericBoard::GetBoardMemory (UINT32 & num_ksamples_per_channel) [pure virtual]
Implemented in V1720Board, V1721Board, V1724Board, V1731Board, V1740Board, and V1751Board.
virtual UINT8 GenericBoard::GetChEnableMsk () const [pure virtual]
Implemented in V1720Board, V1721Board, V1724Board, V1731Board, V1740Board, and V1751Board.
Referenced by V17XXBoard::WriteTriggerMode().
virtual double GenericBoard::GetClockMHz () const [pure virtual]
Implemented in V1720Board, V1721Board, V1724Board, V1731Board, V1740Board, and V1751Board.
Referenced by AppSettings::Load().
virtual double GenericBoard::GetDACUpdateFactor (void) [inline, virtual]
Reimplemented in V1720Board, V1721Board, V1731Board, V1740Board, and V1751Board.
Definition at line 56 of file generic_board.h.
Referenced by V17XXBoardChannel::WriteDACOffset(), and V1740BoardChannel::WriteDACOffset().
bool GenericBoard::GetPhysicalChannelBufferCount (int ch_index, UINT32 & result) [virtual]
Definition at line 462 of file generic_board.cpp.
References m_channel_array.
Referenced by VirtualBoardChannel::GetChannelBufferCount().
bool GenericBoard::GetPhysicalChannelValue (int ch_index, int sample_index, double & result) [virtual]
Definition at line 441 of file generic_board.cpp.
References m_channel_array.
Referenced by VirtualBoardChannel::GetChannelValue().
bool GenericBoard::GetPhysicalChannelValueVolt (int ch_index, int sample_index, double & result) [virtual]
Definition at line 451 of file generic_board.cpp.
References m_channel_array.
Referenced by VirtualBoardChannel::GetChannelValueVolt().
virtual int GenericBoard::GetSampleBit () const [pure virtual]
Implemented in V1720Board, V1721Board, V1724Board, V1731Board, V1740Board, and V1751Board.
Referenced by GenericBoardChannel::GenericBoardChannel(), V17XXBoardChannel::WriteChannelTrigger(), and V1740BoardChannel::WriteChannelTrigger().
virtual CVT_V17XX_TYPES GenericBoard::GetType () [pure virtual]
Implemented in V1720Board, V1721Board, V1724Board, V1731Board, V1740Board, and V1751Board.
virtual wxString GenericBoard::GetTypeString () [pure virtual]
Implemented in V1720Board, V1721Board, V1724Board, V1731Board, V1740Board, and V1751Board.
Referenced by V17XXBoard::Init().
virtual double GenericBoard::GetVolt2Bit () const [pure virtual]
Implemented in V1720Board, V1721Board, V1724Board, V1731Board, V1740Board, and V1751Board.
Referenced by GenericBoardChannel::GenericBoardChannel().
virtual bool GenericBoard::Init (long) [inline, virtual]
Reimplemented in V1721Board, V1731Board, V1751Board, and V17XXBoard.
Definition at line 77 of file generic_board.h.
bool GenericBoard::IsRunning (void)
Definition at line 425 of file generic_board.cpp.
References m_is_running, AppSettings::m_mutex, and m_p_app_settings.
Referenced by DoStartRunning(), DoStopRunning(), and CommonChControl::OnEnableTogglebuttonClick().
bool GenericBoard::LoadConfig (wxConfigBase * p_config, const wxString & base_section) [virtual]
Reimplemented in V1740Board.
Definition at line 64 of file generic_board.cpp.
References CreateChannel(), CreateVirtualChannel(), cvt_board_data::m_base_address, m_channel_array, m_p_data, m_p_data_mutex, m_virtual_channel_array, and ScopeRefresh.
virtual bool GenericBoard::Open (long vme_handle) [pure virtual]
Implemented in V17XXBoard.
virtual bool GenericBoard::ReadBoardData (UINT32 * p_max_num_samples, UINT32 * p_num_events) [pure virtual]
Implemented in V17XXBoard.
Referenced by BoardWorkerThread::Entry().
bool GenericBoard::SaveConfig (wxConfigBase * p_config, const wxString & base_section) [virtual]
Reimplemented in V1740Board.
Definition at line 144 of file generic_board.cpp.
References cvt_board_data::m_base_address, m_channel_array, m_p_data, and m_virtual_channel_array.
void GenericBoard::SetDiv2Pix (int scope_index, double div_2_pix_Y)
Definition at line 304 of file generic_board.cpp.
References m_channel_array, m_virtual_channel_array, and GenericBoardChannel::SetDiv2Pix().
Referenced by DrawingCanvas::RefreshBackBitmap().
virtual bool GenericBoard::SetFrontPanelIO (bool use_TTL) [pure virtual]
Implemented in V17XXBoard.
void GenericBoard::SetLeftDiv2Pix (int scope_index, double div_2_pix_Y)
Definition at line 322 of file generic_board.cpp.
References m_channel_array, m_virtual_channel_array, and GenericBoardChannel::SetLeftDiv2Pix().
Referenced by DrawingLeftCanvas::RefreshBackBitmap().
void GenericBoard::SetLeftPix (int scope_index, int pix_X, int pix_Y)
Definition at line 356 of file generic_board.cpp.
References m_channel_array, m_virtual_channel_array, and GenericBoardChannel::SetLeftPix().
Referenced by DrawingLeftCanvas::RefreshBackBitmap().
void GenericBoard::SetPix (int scope_index, int pix_X, int pix_Y)
Definition at line 339 of file generic_board.cpp.
References m_channel_array, m_virtual_channel_array, and GenericBoardChannel::SetPix().
Referenced by DrawingCanvas::RefreshBackBitmap().
void GenericBoard::SetRunning (bool value)
Definition at line 431 of file generic_board.cpp.
References m_is_running, AppSettings::m_mutex, and m_p_app_settings.
Referenced by DoStartRunning(), and DoStopRunning().
void GenericBoard::SetSec2Div (int scope_index, double sec_2_div)
bool GenericBoard::ToggleRecordStatus (const wxString & path, const wxString & file_name, const wxString & timestamp, bool start, bool use_max_buffer, int max_buffer)
Definition at line 392 of file generic_board.cpp.
References m_board_index, m_channel_array, m_is_recording, GenericBoardChannel::m_p_record_ch_control, m_record_max_buffers, m_record_use_max_buffers, m_virtual_channel_array, and GenericBoardChannel::ToggleRecordStatus().
virtual bool GenericBoard::WriteSampleBufferSize (void) [pure virtual]
Implemented in V1740Board, and V17XXBoard.
virtual bool GenericBoard::WriteSoftwareTrigger (void) [pure virtual]
Implemented in V17XXBoard.
Referenced by BoardWorkerThread::Entry().
virtual bool GenericBoard::WriteTriggerMode (bool started) [pure virtual]
Implemented in V17XXBoard.
Referenced by CommonChControl::OnEnableTogglebuttonClick().
Friends And Related Function Documentation
friend class BoardWorkerThread [friend]
Definition at line 104 of file generic_board.h.
Referenced by DoStartRunning().
Member Data Documentation
int GenericBoard::m_board_index [protected]
Definition at line 100 of file generic_board.h.
Referenced by ToggleRecordStatus().
wxArrayPtrVoid GenericBoard::m_channel_array
Definition at line 42 of file generic_board.h.
Referenced by VirtualChannelDefDialog::Create(), V17XXBoard::DoStartAcquisition(), DrawCursor(), DrawPosition(), DrawSamples(), DrawTrigger(), BoardWorkerThread::Entry(), GetPhysicalChannelBufferCount(), GetPhysicalChannelValue(), GetPhysicalChannelValueVolt(), V1740Board::LoadConfig(), LoadConfig(), V1740Board::SaveConfig(), SaveConfig(), SetDiv2Pix(), SetLeftDiv2Pix(), SetLeftPix(), SetPix(), ViewChControl::SetupBoard(), TriggerChControl::SetupBoard(), RecordChControl::SetupBoard(), CursorChControl::SetupBoard(), CommonChControl::SetupBoard(), ToggleRecordStatus(), V17XXBoard::WriteTriggerMode(), and ~GenericBoard().
bool GenericBoard::m_is_recording [protected]
Definition at line 101 of file generic_board.h.
Referenced by BoardWorkerThread::Entry(), GenericBoard(), and ToggleRecordStatus().
bool GenericBoard::m_is_running [protected]
Definition at line 98 of file generic_board.h.
Referenced by GenericBoard(), IsRunning(), and SetRunning().
AppSettings* GenericBoard::m_p_app_settings [protected]
Definition at line 99 of file generic_board.h.
Referenced by V17XXBoard::CreateChannel(), V1740Board::CreateChannel(), CreateVirtualChannel(), BoardWorkerThread::Entry(), V17XXBoard::Init(), V1751Board::Init(), V1731Board::Init(), V1721Board::Init(), IsRunning(), SetRunning(), V17XXBoard::WriteSampleBufferSize(), V1740Board::WriteSampleBufferSize(), V17XXBoard::WriteSoftwareTrigger(), and V17XXBoard::WriteTriggerMode().
cvt_board_data* GenericBoard::m_p_data [protected]
Definition at line 96 of file generic_board.h.
Referenced by V17XXBoard::CreateChannel(), V1740Board::CreateChannel(), CreateVirtualChannel(), V17XXBoard::DoStartAcquisition(), V1740Board::DoStartAcquisition(), V17XXBoard::DoStopAcquisition(), GenericBoard(), V1751Board::GetBoardMemory(), V1740Board::GetBoardMemory(), V1731Board::GetBoardMemory(), V1724Board::GetBoardMemory(), V1721Board::GetBoardMemory(), V1720Board::GetBoardMemory(), V17XXBoard::Init(), V1751Board::Init(), V1731Board::Init(), V1721Board::Init(), V1740Board::LoadConfig(), LoadConfig(), V17XXBoard::ReadBoardData(), V1740Board::SaveConfig(), SaveConfig(), V17XXBoard::SetFrontPanelIO(), V17XXBoard::V17XXBoard(), V17XXBoard::WriteSampleBufferSize(), V1740Board::WriteSampleBufferSize(), V17XXBoard::WriteSoftwareTrigger(), V17XXBoard::WriteTriggerMode(), and V17XXBoard::~V17XXBoard().
wxMutex* GenericBoard::m_p_data_mutex
Definition at line 44 of file generic_board.h.
Referenced by V1740Board::LoadConfig(), and LoadConfig().
BoardWorkerThread* GenericBoard::m_p_worker_thread [protected]
Definition at line 97 of file generic_board.h.
Referenced by DoStartRunning(), and DoStopRunning().
int GenericBoard::m_record_max_buffers [protected]
Definition at line 102 of file generic_board.h.
Referenced by BoardWorkerThread::Entry(), GenericBoard(), and ToggleRecordStatus().
bool GenericBoard::m_record_use_max_buffers [protected]
Definition at line 103 of file generic_board.h.
Referenced by BoardWorkerThread::Entry(), GenericBoard(), and ToggleRecordStatus().
wxArrayPtrVoid GenericBoard::m_virtual_channel_array
Definition at line 43 of file generic_board.h.
Referenced by DrawCursor(), DrawPosition(), DrawSamples(), DrawTrigger(), BoardWorkerThread::Entry(), V1740Board::LoadConfig(), LoadConfig(), V1740Board::SaveConfig(), SaveConfig(), SetDiv2Pix(), SetLeftDiv2Pix(), SetLeftPix(), SetPix(), VirtualCommonChControl::SetupBoard(), ViewChControl::SetupBoard(), RecordChControl::SetupBoard(), CursorChControl::SetupBoard(), ToggleRecordStatus(), and ~GenericBoard().
void(* GenericBoard::ScopeRefresh)(int, bool)
Definition at line 45 of file generic_board.h.
Referenced by BoardWorkerThread::Entry(), V1740Board::LoadConfig(), and LoadConfig().
void(* GenericBoard::UpdateSamplesReadyLed)(bool)
Definition at line 46 of file generic_board.h.
Referenced by BoardWorkerThread::Entry().
The documentation for this class was generated from the following files:
generic_board.h
generic_board.cpp