CAENScope: InfoDialog Class Reference
InfoDialog Class Reference
#include <infodialog.h>
Public Member Functions
InfoDialog ()
Constructors.
InfoDialog (wxWindow *parent, wxWindowID id=SYMBOL_INFODIALOG_IDNAME, const wxString &caption=SYMBOL_INFODIALOG_TITLE, const wxPoint &pos=SYMBOL_INFODIALOG_POSITION, const wxSize &size=SYMBOL_INFODIALOG_SIZE, long style=SYMBOL_INFODIALOG_STYLE)
bool Create (wxWindow *parent, wxWindowID id=SYMBOL_INFODIALOG_IDNAME, const wxString &caption=SYMBOL_INFODIALOG_TITLE, const wxPoint &pos=SYMBOL_INFODIALOG_POSITION, const wxSize &size=SYMBOL_INFODIALOG_SIZE, long style=SYMBOL_INFODIALOG_STYLE)
Creation.
void CreateControls ()
Creates the controls and sizers.
void OnOkButtonClick (wxCommandEvent &event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_OK_BUTTON
void OnHyperlink (wxCommandEvent &event)
wxBitmap GetBitmapResource (const wxString &name)
Retrieves bitmap resources.
wxIcon GetIconResource (const wxString &name)
Retrieves icon resources.
Static Public Member Functions
static bool ShowToolTips ()
Should we show tooltips?
Public Attributes
wxPanel * m_left_panel
wxBoxSizer * m_left_sizer
wxStaticText * m_caenvmetool_rev
Detailed Description
Compatibility
InfoDialog class declaration
Definition at line 65 of file infodialog.h.
Constructor & Destructor Documentation
InfoDialog::InfoDialog ()
Constructors.
InfoDialog type definition
InfoDialog event table definition
InfoDialog constructors
Definition at line 67 of file infodialog.cpp.
InfoDialog::InfoDialog (wxWindow * parent, wxWindowID id = SYMBOL_INFODIALOG_IDNAME, const wxString & caption = SYMBOL_INFODIALOG_TITLE, const wxPoint & pos = SYMBOL_INFODIALOG_POSITION, const wxSize & size = SYMBOL_INFODIALOG_SIZE, long style = SYMBOL_INFODIALOG_STYLE)
Definition at line 71 of file infodialog.cpp.
References Create().
Member Function Documentation
bool InfoDialog::Create (wxWindow * parent, wxWindowID id = SYMBOL_INFODIALOG_IDNAME, const wxString & caption = SYMBOL_INFODIALOG_TITLE, const wxPoint & pos = SYMBOL_INFODIALOG_POSITION, const wxSize & size = SYMBOL_INFODIALOG_SIZE, long style = SYMBOL_INFODIALOG_STYLE)
Creation.
InfoDialog creator
Definition at line 80 of file infodialog.cpp.
References CreateControls(), GetIconResource(), m_caenvmetool_rev, m_left_panel, and m_left_sizer.
Referenced by InfoDialog().
void InfoDialog::CreateControls ()
Creates the controls and sizers.
Control creation for InfoDialog
Definition at line 107 of file infodialog.cpp.
References wxHyperlinkCtrl::AutoBrowse(), cvt_V1724_SW_rev(), GetBitmapResource(), ID_HYPERLINK, ID_OK_BUTTON, ID_PANEL1, ID_PANEL2, m_caenvmetool_rev, m_left_panel, m_left_sizer, wxHyperlinkCtrl::SetLinkCursor(), wxHyperlinkCtrl::SetURL(), ShowToolTips(), and wxHyperlinkCtrl::UpdateLink().
Referenced by Create().
wxBitmap InfoDialog::GetBitmapResource (const wxString & name)
Retrieves bitmap resources.
Get bitmap resources
Definition at line 193 of file infodialog.cpp.
References AppSettings::get_default_path().
Referenced by CreateControls().
wxIcon InfoDialog::GetIconResource (const wxString & name)
Retrieves icon resources.
Get icon resources
Definition at line 211 of file infodialog.cpp.
Referenced by Create().
void InfoDialog::OnHyperlink (wxCommandEvent & event)
void InfoDialog::OnOkButtonClick (wxCommandEvent & event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_OK_BUTTON
Definition at line 232 of file infodialog.cpp.
bool InfoDialog::ShowToolTips () [static]
Should we show tooltips?
Definition at line 184 of file infodialog.cpp.
Referenced by CreateControls().
Member Data Documentation
wxStaticText* InfoDialog::m_caenvmetool_rev
Definition at line 104 of file infodialog.h.
Referenced by Create(), and CreateControls().
wxPanel* InfoDialog::m_left_panel
Definition at line 102 of file infodialog.h.
Referenced by Create(), and CreateControls().
wxBoxSizer* InfoDialog::m_left_sizer
Definition at line 103 of file infodialog.h.
Referenced by Create(), and CreateControls().
The documentation for this class was generated from the following files:
infodialog.h
infodialog.cpp