CAENScope: V1721Board Class Reference
V1721Board Class Reference
#include <V1721_board.h>
Public Member Functions
V1721Board (int board_index, void(*scope_refresh)(int, bool), void(*update_samples_ready_led)(bool), wxMutex *p_data_mutex, AppSettings *p_app_settings, V17XXBoard::BOARD_VARIANT board_variant)
wxString GetTypeString ()
CVT_V17XX_TYPES GetType ()
double GetClockMHz () const
int GetSampleBit () const
double GetVolt2Bit () const
bool Init (long vme_handle)
UINT8 GetChEnableMsk () const
bool GetBoardMemory (UINT32 &num_ksamples_per_channel)
virtual double GetDACUpdateFactor (void)
Detailed Description
Definition at line 31 of file V1721_board.h.
Constructor & Destructor Documentation
V1721Board::V1721Board (int board_index, void(*)(int, bool) scope_refresh, void(*)(bool) update_samples_ready_led, wxMutex * p_data_mutex, AppSettings * p_app_settings, V17XXBoard::BOARD_VARIANT board_variant)
Definition at line 32 of file V1721_board.cpp.
Member Function Documentation
bool V1721Board::GetBoardMemory (UINT32 & num_ksamples_per_channel) [virtual]
Implements GenericBoard.
Definition at line 76 of file V1721_board.cpp.
References cvt_read(), CVT_V1724_BOARD_INFO_ADD, CVT_V1724_BOARD_INFO_AM, CVT_V1724_BOARD_INFO_DATA_SIZE, CVT_V1724_GET_BRDINF_BLOCK_SIZE_KW, and GenericBoard::m_p_data.
UINT8 V1721Board::GetChEnableMsk () const [inline, virtual]
Implements GenericBoard.
Definition at line 57 of file V1721_board.h.
References V17XXBoard::BV_DESKTOP, V17XXBoard::BV_NIM, V17XXBoard::BV_VME, and V17XXBoard::m_board_variant.
Referenced by Init().
double V1721Board::GetClockMHz () const [inline, virtual]
Implements GenericBoard.
Definition at line 53 of file V1721_board.h.
References CVT_V1721_BOARD_CLOCK_INDEX, and CVT_V17XX_BOARD_CLOCK_KHZ.
virtual double V1721Board::GetDACUpdateFactor (void) [inline, virtual]
Reimplemented from GenericBoard.
Definition at line 73 of file V1721_board.h.
int V1721Board::GetSampleBit () const [inline, virtual]
Implements GenericBoard.
Definition at line 54 of file V1721_board.h.
CVT_V17XX_TYPES V1721Board::GetType () [inline, virtual]
Implements GenericBoard.
Definition at line 52 of file V1721_board.h.
References CVT_V1721.
wxString V1721Board::GetTypeString () [inline, virtual]
Implements GenericBoard.
Definition at line 38 of file V1721_board.h.
References V17XXBoard::BV_DESKTOP, V17XXBoard::BV_NIM, V17XXBoard::BV_VME, and V17XXBoard::m_board_variant.
double V1721Board::GetVolt2Bit () const [inline, virtual]
Implements GenericBoard.
Definition at line 55 of file V1721_board.h.
bool V1721Board::Init (long vme_handle) [virtual]
Reimplemented from V17XXBoard.
Definition at line 37 of file V1721_board.cpp.
References cvt_V1724_adc_calib(), cvt_V1724_software_reset(), GetChEnableMsk(), V17XXBoard::Init(), GenericBoard::m_p_app_settings, GenericBoard::m_p_data, AppSettings::m_use_TTL, V17XXBoard::SetFrontPanelIO(), and V17XXBoard::WriteTriggerMode().
The documentation for this class was generated from the following files:
V1721_board.h
V1721_board.cpp