CAENScope: V1740Board Class Reference
V1740Board Class Reference
#include <V1740_board.h>
Public Member Functions
V1740Board (int board_index, void(*scope_refresh)(int, bool), void(*update_samples_ready_led)(bool), wxMutex *p_data_mutex, AppSettings *p_app_settings, V17XXBoard::BOARD_VARIANT board_variant)
wxString GetTypeString ()
CVT_V17XX_TYPES GetType ()
double GetClockMHz () const
int GetSampleBit () const
double GetVolt2Bit () const
UINT8 GetChEnableMsk () const
bool GetBoardMemory (UINT32 &num_ksamples_per_channel)
virtual double GetDACUpdateFactor (void)
virtual GenericBoardChannel * CreateChannel (int ch_index, void(*scope_refresh)(int, bool), wxMutex *p_data_mutex)
virtual bool LoadConfig (wxConfigBase *p_config, const wxString &base_section)
virtual bool SaveConfig (wxConfigBase *p_config, const wxString &base_section)
bool WriteSampleBufferSize (void)
bool DoStartAcquisition (void)
Public Attributes
int m_channel_group
Detailed Description
Definition at line 31 of file V1740_board.h.
Constructor & Destructor Documentation
V1740Board::V1740Board (int board_index, void(*)(int, bool) scope_refresh, void(*)(bool) update_samples_ready_led, wxMutex * p_data_mutex, AppSettings * p_app_settings, V17XXBoard::BOARD_VARIANT board_variant)
Definition at line 33 of file V1740_board.cpp.
Member Function Documentation
GenericBoardChannel * V1740Board::CreateChannel (int ch_index, void(*)(int, bool) scope_refresh, wxMutex * p_data_mutex) [virtual]
Reimplemented from V17XXBoard.
Definition at line 52 of file V1740_board.cpp.
References GenericBoard::m_p_app_settings, and GenericBoard::m_p_data.
Referenced by LoadConfig().
bool V1740Board::DoStartAcquisition (void) [virtual]
Reimplemented from V17XXBoard.
Definition at line 200 of file V1740_board.cpp.
References cvt_V1724_set_readout_mode(), cvt_V1724_start_acquisition(), FALSE, m_channel_group, and GenericBoard::m_p_data.
bool V1740Board::GetBoardMemory (UINT32 & num_ksamples_per_channel) [virtual]
Implements GenericBoard.
Definition at line 37 of file V1740_board.cpp.
References cvt_read(), CVT_V1724_BOARD_INFO_ADD, CVT_V1724_BOARD_INFO_AM, CVT_V1724_BOARD_INFO_DATA_SIZE, CVT_V1724_GET_BRDINF_BLOCK_SIZE_KW, CVT_V1724_MAX_CHANNEL, and GenericBoard::m_p_data.
UINT8 V1740Board::GetChEnableMsk () const [inline, virtual]
Implements GenericBoard.
Definition at line 57 of file V1740_board.h.
References V17XXBoard::BV_DESKTOP, V17XXBoard::BV_NIM, V17XXBoard::BV_VME, and V17XXBoard::m_board_variant.
double V1740Board::GetClockMHz () const [inline, virtual]
Implements GenericBoard.
Definition at line 54 of file V1740_board.h.
References CVT_V1740_BOARD_CLOCK_INDEX, and CVT_V17XX_BOARD_CLOCK_KHZ.
virtual double V1740Board::GetDACUpdateFactor (void) [inline, virtual]
Reimplemented from GenericBoard.
Definition at line 73 of file V1740_board.h.
int V1740Board::GetSampleBit () const [inline, virtual]
Implements GenericBoard.
Definition at line 55 of file V1740_board.h.
CVT_V17XX_TYPES V1740Board::GetType () [inline, virtual]
Implements GenericBoard.
Definition at line 52 of file V1740_board.h.
References CVT_V1740.
wxString V1740Board::GetTypeString () [inline, virtual]
Implements GenericBoard.
Definition at line 38 of file V1740_board.h.
References V17XXBoard::BV_DESKTOP, V17XXBoard::BV_NIM, V17XXBoard::BV_VME, and V17XXBoard::m_board_variant.
double V1740Board::GetVolt2Bit () const [inline, virtual]
Implements GenericBoard.
Definition at line 56 of file V1740_board.h.
bool V1740Board::LoadConfig (wxConfigBase * p_config, const wxString & base_section) [virtual]
Reimplemented from GenericBoard.
Definition at line 56 of file V1740_board.cpp.
References CreateChannel(), GenericBoard::CreateVirtualChannel(), CVT_V1724_MAX_CHANNEL, cvt_board_data::m_base_address, GenericBoard::m_channel_array, m_channel_group, GenericBoard::m_p_data, GenericBoard::m_p_data_mutex, GenericBoard::m_virtual_channel_array, and GenericBoard::ScopeRefresh.
bool V1740Board::SaveConfig (wxConfigBase * p_config, const wxString & base_section) [virtual]
Reimplemented from GenericBoard.
Definition at line 140 of file V1740_board.cpp.
References cvt_board_data::m_base_address, GenericBoard::m_channel_array, m_channel_group, GenericBoard::m_p_data, and GenericBoard::m_virtual_channel_array.
bool V1740Board::WriteSampleBufferSize (void) [virtual]
Reimplemented from V17XXBoard.
Definition at line 185 of file V1740_board.cpp.
References CVT_V1724_ACQCTRL_ACQ_MODE_REGISTER_CTRL, cvt_V1724_data_clear(), cvt_V1724_get_buffer_samples(), CVT_V1724_MAX_CHANNEL, cvt_V1724_set_acquisition_mode(), cvt_V1724_set_buffer_samples(), FALSE, AppSettings::m_max_log_X, AppSettings::m_num_sample, GenericBoard::m_p_app_settings, and GenericBoard::m_p_data.
Member Data Documentation
int V1740Board::m_channel_group
Definition at line 81 of file V1740_board.h.
Referenced by DoStartAcquisition(), LoadConfig(), and SaveConfig().
The documentation for this class was generated from the following files:
V1740_board.h
V1740_board.cpp