CAENScope: VirtualChannelDefDialog Class Reference
VirtualChannelDefDialog Class Reference
#include <virtual_channel_def_dialog.h>
Public Member Functions
VirtualChannelDefDialog ()
Constructors.
VirtualChannelDefDialog (VirtualBoardChannel *board_channel, wxWindow *parent, wxWindowID id=SYMBOL_VIRTUALCHANNELDEFDIALOG_IDNAME, const wxString &caption=SYMBOL_VIRTUALCHANNELDEFDIALOG_TITLE, const wxPoint &pos=SYMBOL_VIRTUALCHANNELDEFDIALOG_POSITION, const wxSize &size=SYMBOL_VIRTUALCHANNELDEFDIALOG_SIZE, long style=SYMBOL_VIRTUALCHANNELDEFDIALOG_STYLE)
bool Create (wxWindow *parent, wxWindowID id=SYMBOL_VIRTUALCHANNELDEFDIALOG_IDNAME, const wxString &caption=SYMBOL_VIRTUALCHANNELDEFDIALOG_TITLE, const wxPoint &pos=SYMBOL_VIRTUALCHANNELDEFDIALOG_POSITION, const wxSize &size=SYMBOL_VIRTUALCHANNELDEFDIALOG_SIZE, long style=SYMBOL_VIRTUALCHANNELDEFDIALOG_STYLE)
Creation.
void CreateControls ()
Creates the controls and sizers.
void OnVchDefAddChannelButtonClick (wxCommandEvent &event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_DEF_ADD_CHANNEL_BUTTON
void OnVchDefAddConstantButtonClick (wxCommandEvent &event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_DEF_ADD_CONSTANT_BUTTON
void OnVchDefAddOperatorButtonClick (wxCommandEvent &event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_DEF_ADD_OPERATOR_BUTTON
void OnVchDefRemoveButtonClick (wxCommandEvent &event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_DEF_REMOVE_BUTTON
void OnVchMoveUpButtonClick (wxCommandEvent &event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_MOVE_UP_BUTTON
void OnVchMoveDwButtonClick (wxCommandEvent &event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_MOVE_DW_BUTTON
void OnVchDefOkButtonClick (wxCommandEvent &event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_DEF_OK_BUTTON
void OnVchDefCancelButtonClick (wxCommandEvent &event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_DEF_CANCEL_BUTTON
void OnVchDefTestButtonClick (wxCommandEvent &event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_DEF_TEST_BUTTON
wxBitmap GetBitmapResource (const wxString &name)
Retrieves bitmap resources.
wxIcon GetIconResource (const wxString &name)
Retrieves icon resources.
Static Public Member Functions
static bool ShowToolTips ()
Should we show tooltips?
Public Attributes
wxPanel * m_left_panel
wxBoxSizer * m_left_sizer
wxChoice * m_channel_ctrl
wxSpinCtrl * m_constant_ctrl
wxChoice * m_operator_ctrl
wxListBox * m_definition_ctrl
Protected Member Functions
wxString MakeExpressionDef (void)
Protected Attributes
VirtualBoardChannel * m_p_board_channel
Detailed Description
Compatibility
VirtualChannelDefDialog class declaration
Definition at line 80 of file virtual_channel_def_dialog.h.
Constructor & Destructor Documentation
VirtualChannelDefDialog::VirtualChannelDefDialog ()
Constructors.
VirtualChannelDefDialog type definition
VirtualChannelDefDialog event table definition
VirtualChannelDefDialog constructors
Definition at line 80 of file virtual_channel_def_dialog.cpp.
VirtualChannelDefDialog::VirtualChannelDefDialog (VirtualBoardChannel * board_channel, wxWindow * parent, wxWindowID id = SYMBOL_VIRTUALCHANNELDEFDIALOG_IDNAME, const wxString & caption = SYMBOL_VIRTUALCHANNELDEFDIALOG_TITLE, const wxPoint & pos = SYMBOL_VIRTUALCHANNELDEFDIALOG_POSITION, const wxSize & size = SYMBOL_VIRTUALCHANNELDEFDIALOG_SIZE, long style = SYMBOL_VIRTUALCHANNELDEFDIALOG_STYLE)
Definition at line 85 of file virtual_channel_def_dialog.cpp.
References Create(), VirtualBoardChannel::GetExpressionDef(), m_definition_ctrl, and m_p_board_channel.
Member Function Documentation
bool VirtualChannelDefDialog::Create (wxWindow * parent, wxWindowID id = SYMBOL_VIRTUALCHANNELDEFDIALOG_IDNAME, const wxString & caption = SYMBOL_VIRTUALCHANNELDEFDIALOG_TITLE, const wxPoint & pos = SYMBOL_VIRTUALCHANNELDEFDIALOG_POSITION, const wxSize & size = SYMBOL_VIRTUALCHANNELDEFDIALOG_SIZE, long style = SYMBOL_VIRTUALCHANNELDEFDIALOG_STYLE)
Creation.
VirtualChannelDefDialog creator
Definition at line 103 of file virtual_channel_def_dialog.cpp.
References CreateControls(), GenericBoardChannel::GetParent(), GenericBoard::m_channel_array, m_channel_ctrl, m_constant_ctrl, m_definition_ctrl, m_left_panel, m_left_sizer, m_operator_ctrl, and m_p_board_channel.
Referenced by VirtualChannelDefDialog().
void VirtualChannelDefDialog::CreateControls ()
Creates the controls and sizers.
Control creation for VirtualChannelDefDialog
Definition at line 148 of file virtual_channel_def_dialog.cpp.
References ID_VCH_DEF_ADD_CHANNEL_BUTTON, ID_VCH_DEF_ADD_CONSTANT_BUTTON, ID_VCH_DEF_ADD_OPERATOR_BUTTON, ID_VCH_DEF_CANCEL_BUTTON, ID_VCH_DEF_CHANNEL_CHOICE, ID_VCH_DEF_CONSTANT_SPINCTRL, ID_VCH_DEF_DEFINTION_LISTBOX, ID_VCH_DEF_LEFT_PANEL, ID_VCH_DEF_OK_BUTTON, ID_VCH_DEF_OPERATOR_CHOICE, ID_VCH_DEF_REMOVE_BUTTON, ID_VCH_DEF_RIGHT_PANEL, ID_VCH_DEF_TEST_BUTTON, ID_VCH_MOVE_DW_BUTTON, ID_VCH_MOVE_UP_BUTTON, m_channel_ctrl, m_constant_ctrl, m_definition_ctrl, m_left_panel, m_left_sizer, m_operator_ctrl, and ShowToolTips().
Referenced by Create().
wxBitmap VirtualChannelDefDialog::GetBitmapResource (const wxString & name)
Retrieves bitmap resources.
Get bitmap resources
Definition at line 418 of file virtual_channel_def_dialog.cpp.
wxIcon VirtualChannelDefDialog::GetIconResource (const wxString & name)
Retrieves icon resources.
Get icon resources
Definition at line 431 of file virtual_channel_def_dialog.cpp.
wxString VirtualChannelDefDialog::MakeExpressionDef (void) [protected]
Definition at line 496 of file virtual_channel_def_dialog.cpp.
References m_definition_ctrl.
Referenced by OnVchDefOkButtonClick(), and OnVchDefTestButtonClick().
void VirtualChannelDefDialog::OnVchDefAddChannelButtonClick (wxCommandEvent & event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_DEF_ADD_CHANNEL_BUTTON
Definition at line 443 of file virtual_channel_def_dialog.cpp.
References m_channel_ctrl, and m_definition_ctrl.
void VirtualChannelDefDialog::OnVchDefAddConstantButtonClick (wxCommandEvent & event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_DEF_ADD_CONSTANT_BUTTON
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_ADD_CONSTANT_BUTTON
Definition at line 298 of file virtual_channel_def_dialog.cpp.
References RpnHandler::Format(), m_constant_ctrl, and m_definition_ctrl.
void VirtualChannelDefDialog::OnVchDefAddOperatorButtonClick (wxCommandEvent & event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_DEF_ADD_OPERATOR_BUTTON
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_ADD_OPERATOR_BUTTON
Definition at line 318 of file virtual_channel_def_dialog.cpp.
References m_definition_ctrl, and m_operator_ctrl.
void VirtualChannelDefDialog::OnVchDefCancelButtonClick (wxCommandEvent & event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_DEF_CANCEL_BUTTON
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_CANCEL_BUTTON
Definition at line 380 of file virtual_channel_def_dialog.cpp.
void VirtualChannelDefDialog::OnVchDefOkButtonClick (wxCommandEvent & event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_DEF_OK_BUTTON
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_OK_BUTTON
Definition at line 356 of file virtual_channel_def_dialog.cpp.
References RpnHandler::Format(), m_p_board_channel, MakeExpressionDef(), RpnHandler::RpnHandler(), VirtualBoardChannel::SetExpressionDef(), and RpnHandler::Test().
void VirtualChannelDefDialog::OnVchDefRemoveButtonClick (wxCommandEvent & event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_DEF_REMOVE_BUTTON
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_REMOVE_BUTTON
Definition at line 340 of file virtual_channel_def_dialog.cpp.
References m_definition_ctrl.
void VirtualChannelDefDialog::OnVchDefTestButtonClick (wxCommandEvent & event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_DEF_TEST_BUTTON
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_TEST_BUTTON
Definition at line 390 of file virtual_channel_def_dialog.cpp.
References MakeExpressionDef(), RpnHandler::RpnHandler(), and RpnHandler::Test().
void VirtualChannelDefDialog::OnVchMoveDwButtonClick (wxCommandEvent & event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_MOVE_DW_BUTTON
Definition at line 483 of file virtual_channel_def_dialog.cpp.
References m_definition_ctrl.
void VirtualChannelDefDialog::OnVchMoveUpButtonClick (wxCommandEvent & event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_VCH_MOVE_UP_BUTTON
Definition at line 466 of file virtual_channel_def_dialog.cpp.
References m_definition_ctrl.
bool VirtualChannelDefDialog::ShowToolTips () [static]
Should we show tooltips?
Definition at line 409 of file virtual_channel_def_dialog.cpp.
Referenced by CreateControls().
Member Data Documentation
wxChoice* VirtualChannelDefDialog::m_channel_ctrl
Definition at line 142 of file virtual_channel_def_dialog.h.
Referenced by Create(), CreateControls(), and OnVchDefAddChannelButtonClick().
wxSpinCtrl* VirtualChannelDefDialog::m_constant_ctrl
Definition at line 143 of file virtual_channel_def_dialog.h.
Referenced by Create(), CreateControls(), and OnVchDefAddConstantButtonClick().
wxListBox* VirtualChannelDefDialog::m_definition_ctrl
Definition at line 145 of file virtual_channel_def_dialog.h.
Referenced by Create(), CreateControls(), MakeExpressionDef(), OnVchDefAddChannelButtonClick(), OnVchDefAddConstantButtonClick(), OnVchDefAddOperatorButtonClick(), OnVchDefRemoveButtonClick(), OnVchMoveDwButtonClick(), OnVchMoveUpButtonClick(), and VirtualChannelDefDialog().
wxPanel* VirtualChannelDefDialog::m_left_panel
Definition at line 140 of file virtual_channel_def_dialog.h.
Referenced by Create(), and CreateControls().
wxBoxSizer* VirtualChannelDefDialog::m_left_sizer
Definition at line 141 of file virtual_channel_def_dialog.h.
Referenced by Create(), and CreateControls().
wxChoice* VirtualChannelDefDialog::m_operator_ctrl
Definition at line 144 of file virtual_channel_def_dialog.h.
Referenced by Create(), CreateControls(), and OnVchDefAddOperatorButtonClick().
VirtualBoardChannel* VirtualChannelDefDialog::m_p_board_channel [protected]
Definition at line 148 of file virtual_channel_def_dialog.h.
Referenced by Create(), OnVchDefOkButtonClick(), and VirtualChannelDefDialog().
The documentation for this class was generated from the following files:
virtual_channel_def_dialog.h
virtual_channel_def_dialog.cpp