CAENScope: RpnHandler Class Reference
RpnHandler Class Reference
#include <rpn_handler.h>
Public Member Functions
RpnHandler (VirtualBoardChannel *parent, const char *expression_def)
~RpnHandler (void)
bool Parse (const char *expression_def)
const char * Format (void)
bool Test (void)
bool Eval (double &result)
unsigned int GetBufferCount (void)
Protected Member Functions
bool DoEval (double *p_result)
Protected Attributes
RpnItem * m_rpn_items_array
RpnItem * m_tmp_rpn_items_array
int m_rpn_array_alloc_size
int m_rpn_array_real_size
char * m_expression_def
VirtualBoardChannel * m_parent
int m_ref_channel_index
Detailed Description
Definition at line 72 of file rpn_handler.h.
Constructor & Destructor Documentation
RpnHandler::RpnHandler (VirtualBoardChannel * parent, const char * expression_def)
Definition at line 29 of file rpn_handler.cpp.
References m_expression_def, m_parent, m_ref_channel_index, m_rpn_array_alloc_size, m_rpn_array_real_size, m_rpn_items_array, m_tmp_rpn_items_array, and Parse().
Referenced by VirtualChannelDefDialog::OnVchDefOkButtonClick(), and VirtualChannelDefDialog::OnVchDefTestButtonClick().
RpnHandler::~RpnHandler (void)
Definition at line 41 of file rpn_handler.cpp.
References m_expression_def, m_rpn_items_array, and m_tmp_rpn_items_array.
Member Function Documentation
bool RpnHandler::DoEval (double * p_result) [protected]
Definition at line 154 of file rpn_handler.cpp.
References VirtualBoardChannel::GetChannelValueVolt(), m_parent, RpnItem::m_processed, m_rpn_array_real_size, m_rpn_items_array, m_tmp_rpn_items_array, RpnItem::m_type, RpnItem::m_value, RPN_OPERAND_CH0, RPN_OPERAND_CH1, RPN_OPERAND_CH2, RPN_OPERAND_CH3, RPN_OPERAND_CH4, RPN_OPERAND_CH5, RPN_OPERAND_CH6, RPN_OPERAND_CH7, RPN_OPERAND_CONST, RPN_OPERATOR_ADD, RPN_OPERATOR_DIV, RPN_OPERATOR_MUL, and RPN_OPERATOR_SUB.
Referenced by Eval(), and Test().
bool RpnHandler::Eval (double & result)
Definition at line 150 of file rpn_handler.cpp.
References DoEval().
Referenced by VirtualBoardChannel::GetSampleVolt().
const char * RpnHandler::Format (void)
Definition at line 139 of file rpn_handler.cpp.
References m_expression_def.
Referenced by VirtualBoardChannel::GetExpressionDef(), VirtualChannelDefDialog::OnVchDefAddConstantButtonClick(), VirtualChannelDefDialog::OnVchDefOkButtonClick(), and VirtualBoardChannel::SaveConfig().
unsigned int RpnHandler::GetBufferCount (void)
Definition at line 331 of file rpn_handler.cpp.
References VirtualBoardChannel::GetChannelBufferCount(), m_parent, and m_ref_channel_index.
Referenced by VirtualBoardChannel::GetBufferCount().
bool RpnHandler::Parse (const char * expression_def)
Definition at line 52 of file rpn_handler.cpp.
References m_expression_def, RpnItem::m_processed, m_ref_channel_index, m_rpn_array_alloc_size, m_rpn_array_real_size, m_rpn_items_array, m_tmp_rpn_items_array, RpnItem::m_type, RpnItem::m_value, RPN_OPERAND_CH0, RPN_OPERAND_CH1, RPN_OPERAND_CH2, RPN_OPERAND_CH3, RPN_OPERAND_CH4, RPN_OPERAND_CH5, RPN_OPERAND_CH6, RPN_OPERAND_CH7, RPN_OPERAND_CONST, RpnTypesNames, and stricmp.
Referenced by RpnHandler(), and VirtualBoardChannel::SetExpressionDef().
bool RpnHandler::Test (void)
Definition at line 143 of file rpn_handler.cpp.
References DoEval().
Referenced by VirtualChannelDefDialog::OnVchDefOkButtonClick(), and VirtualChannelDefDialog::OnVchDefTestButtonClick().
Member Data Documentation
char* RpnHandler::m_expression_def [protected]
Definition at line 88 of file rpn_handler.h.
Referenced by Format(), Parse(), RpnHandler(), and ~RpnHandler().
VirtualBoardChannel* RpnHandler::m_parent [protected]
Definition at line 90 of file rpn_handler.h.
Referenced by DoEval(), GetBufferCount(), and RpnHandler().
int RpnHandler::m_ref_channel_index [protected]
Definition at line 91 of file rpn_handler.h.
Referenced by GetBufferCount(), Parse(), and RpnHandler().
int RpnHandler::m_rpn_array_alloc_size [protected]
Definition at line 86 of file rpn_handler.h.
Referenced by Parse(), and RpnHandler().
int RpnHandler::m_rpn_array_real_size [protected]
Definition at line 87 of file rpn_handler.h.
Referenced by DoEval(), Parse(), and RpnHandler().
RpnItem* RpnHandler::m_rpn_items_array [protected]
Definition at line 84 of file rpn_handler.h.
Referenced by DoEval(), Parse(), RpnHandler(), and ~RpnHandler().
RpnItem* RpnHandler::m_tmp_rpn_items_array [protected]
Definition at line 85 of file rpn_handler.h.
Referenced by DoEval(), Parse(), RpnHandler(), and ~RpnHandler().
The documentation for this class was generated from the following files:
rpn_handler.h
rpn_handler.cpp