CAENScope: DrawingPanel Class Reference
DrawingPanel Class Reference
#include <drawing_panel.h>
Public Member Functions
DrawingPanel ()
Constructors.
DrawingPanel (int scope_index, wxWindow *parent, wxWindowID id=SYMBOL_DRAWINGPANEL_IDNAME, const wxPoint &pos=SYMBOL_DRAWINGPANEL_POSITION, const wxSize &size=SYMBOL_DRAWINGPANEL_SIZE, long style=SYMBOL_DRAWINGPANEL_STYLE)
~DrawingPanel ()
bool Create (wxWindow *parent, wxWindowID id=SYMBOL_DRAWINGPANEL_IDNAME, const wxPoint &pos=SYMBOL_DRAWINGPANEL_POSITION, const wxSize &size=SYMBOL_DRAWINGPANEL_SIZE, long style=SYMBOL_DRAWINGPANEL_STYLE)
Creation.
void CreateControls ()
Creates the controls and sizers.
void OnSize (wxSizeEvent &event)
wxEVT_SIZE event handler for ID_MYDIALOG
void OnPaint (wxPaintEvent &event)
wxEVT_PAINT event handler for ID_MYDIALOG
void OnEraseBackground (wxEraseEvent &event)
wxEVT_ERASE_BACKGROUND event handler for ID_MYDIALOG
wxBitmap GetBitmapResource (const wxString &name)
Retrieves bitmap resources.
wxIcon GetIconResource (const wxString &name)
Retrieves icon resources.
void Freeze (void)
bool IsFreezed (void)
void RefreshBackBitmap (void)
void RefreshLeftBackBitmap (void)
Static Public Member Functions
static bool ShowToolTips ()
Should we show tooltips?
Public Attributes
DrawingLeftCanvas * m_draw_left_canvas
DrawingCanvas * m_draw_canvas
AppSettings * m_app_settings
Protected Attributes
bool m_freezed
int m_scope_index
wxMutex m_mutex
Detailed Description
DrawingPanel class declaration
Definition at line 69 of file drawing_panel.h.
Constructor & Destructor Documentation
DrawingPanel::DrawingPanel ()
Constructors.
DrawingPanel type definition
DrawingPanel event table definition
DrawingPanel constructors
Definition at line 63 of file drawing_panel.cpp.
DrawingPanel::DrawingPanel (int scope_index, wxWindow * parent, wxWindowID id = SYMBOL_DRAWINGPANEL_IDNAME, const wxPoint & pos = SYMBOL_DRAWINGPANEL_POSITION, const wxSize & size = SYMBOL_DRAWINGPANEL_SIZE, long style = SYMBOL_DRAWINGPANEL_STYLE)
Definition at line 67 of file drawing_panel.cpp.
References Create(), and m_scope_index.
DrawingPanel::~DrawingPanel ()
Definition at line 74 of file drawing_panel.cpp.
Member Function Documentation
bool DrawingPanel::Create (wxWindow * parent, wxWindowID id = SYMBOL_DRAWINGPANEL_IDNAME, const wxPoint & pos = SYMBOL_DRAWINGPANEL_POSITION, const wxSize & size = SYMBOL_DRAWINGPANEL_SIZE, long style = SYMBOL_DRAWINGPANEL_STYLE)
Creation.
DrawingPanel creator
Definition at line 81 of file drawing_panel.cpp.
References CreateControls(), m_draw_canvas, and m_draw_left_canvas.
Referenced by DrawingPanel().
void DrawingPanel::CreateControls ()
Creates the controls and sizers.
Control creation for DrawingPanel
Definition at line 106 of file drawing_panel.cpp.
References ID_DRAW_PANEL, ID_LEFT_PANEL, m_draw_canvas, m_draw_left_canvas, and m_scope_index.
Referenced by Create().
void DrawingPanel::Freeze (void)
Definition at line 184 of file drawing_panel.cpp.
References m_app_settings, m_freezed, and AppSettings::m_mutex.
Referenced by MainFrame::OnCloseWindow().
wxBitmap DrawingPanel::GetBitmapResource (const wxString & name)
Retrieves bitmap resources.
Get bitmap resources
Definition at line 138 of file drawing_panel.cpp.
wxIcon DrawingPanel::GetIconResource (const wxString & name)
Retrieves icon resources.
Get icon resources
Definition at line 151 of file drawing_panel.cpp.
bool DrawingPanel::IsFreezed (void) [inline]
Definition at line 118 of file drawing_panel.h.
References m_freezed.
Referenced by DrawingLeftCanvas::OnPaint(), DrawingCanvas::OnPaint(), DrawingLeftCanvas::RefreshBackBitmap(), and DrawingCanvas::RefreshBackBitmap().
void DrawingPanel::OnEraseBackground (wxEraseEvent & event)
wxEVT_ERASE_BACKGROUND event handler for ID_MYDIALOG
wxEVT_ERASE_BACKGROUND event handler for ID_DRAW_CANVAS_PANEL
Definition at line 171 of file drawing_panel.cpp.
void DrawingPanel::OnPaint (wxPaintEvent & event)
wxEVT_PAINT event handler for ID_MYDIALOG
wxEVT_PAINT event handler for ID_DRAW_CANVAS_PANEL
Definition at line 163 of file drawing_panel.cpp.
void DrawingPanel::OnSize (wxSizeEvent & event)
wxEVT_SIZE event handler for ID_MYDIALOG
Definition at line 180 of file drawing_panel.cpp.
void DrawingPanel::RefreshBackBitmap (void)
Definition at line 190 of file drawing_panel.cpp.
References m_draw_canvas, and DrawingCanvas::RefreshBackBitmap().
Referenced by MainFrame::ScopeRefresh().
void DrawingPanel::RefreshLeftBackBitmap (void)
Definition at line 195 of file drawing_panel.cpp.
References m_draw_left_canvas, and DrawingLeftCanvas::RefreshBackBitmap().
Referenced by MainFrame::ScopeRefresh().
bool DrawingPanel::ShowToolTips () [static]
Should we show tooltips?
Definition at line 129 of file drawing_panel.cpp.
Member Data Documentation
AppSettings* DrawingPanel::m_app_settings
Definition at line 116 of file drawing_panel.h.
Referenced by MainFrame::Create(), DrawingLeftCanvas::DrawBackground(), DrawingCanvas::DrawBackground(), DrawingCanvas::DrawCursor(), DrawingCanvas::DrawGrid(), DrawingLeftCanvas::DrawPosition(), DrawingCanvas::DrawSamples(), DrawingCanvas::DrawTrigger(), Freeze(), DrawingLeftCanvas::OnPaint(), DrawingCanvas::OnPaint(), DrawingLeftCanvas::RefreshBackBitmap(), and DrawingCanvas::RefreshBackBitmap().
DrawingCanvas* DrawingPanel::m_draw_canvas
Definition at line 115 of file drawing_panel.h.
Referenced by Create(), CreateControls(), and RefreshBackBitmap().
DrawingLeftCanvas* DrawingPanel::m_draw_left_canvas
Definition at line 114 of file drawing_panel.h.
Referenced by Create(), CreateControls(), and RefreshLeftBackBitmap().
bool DrawingPanel::m_freezed [protected]
Definition at line 122 of file drawing_panel.h.
Referenced by Freeze(), and IsFreezed().
wxMutex DrawingPanel::m_mutex [protected]
Definition at line 125 of file drawing_panel.h.
int DrawingPanel::m_scope_index [protected]
Definition at line 123 of file drawing_panel.h.
Referenced by CreateControls(), and DrawingPanel().
The documentation for this class was generated from the following files:
drawing_panel.h
drawing_panel.cpp