CAENScope: ViewChControl Class Reference
ViewChControl Class Reference
#include <view_ch_control.h>
Public Member Functions
ViewChControl ()
Constructors.
ViewChControl (wxWindow *parent, wxWindowID id=SYMBOL_VIEWCHCONTROL_IDNAME, const wxPoint &pos=SYMBOL_VIEWCHCONTROL_POSITION, const wxSize &size=SYMBOL_VIEWCHCONTROL_SIZE, long style=SYMBOL_VIEWCHCONTROL_STYLE)
bool Create (wxWindow *parent, wxWindowID id=SYMBOL_VIEWCHCONTROL_IDNAME, const wxPoint &pos=SYMBOL_VIEWCHCONTROL_POSITION, const wxSize &size=SYMBOL_VIEWCHCONTROL_SIZE, long style=SYMBOL_VIEWCHCONTROL_STYLE)
Creation.
void CreateControls ()
Creates the controls and sizers.
void OnViewEnableTogglebuttonClick (wxCommandEvent &event)
wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_VIEW_ENABLE_TOGGLEBUTTON
void OnChooseColorButtonClick (wxCommandEvent &event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_CHOOSE_COLOR_BUTTON
void OnLineWidthSpinctrlUpdated (wxSpinEvent &event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_LINE_WIDTH_SPINCTRL
void OnOffsetYResetButtonClick (wxCommandEvent &event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_OFFSET_Y_RESET_BUTTON
void OnSpinbutton1Updated (wxSpinEvent &event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_SPINBUTTON1
void OnVoltPerDivSpinctrlUpdated (wxSpinEvent &event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_VOLT_PER_DIV_SPINCTRL
void OnLineWidthSpinctrlTextUpdated (wxCommandEvent &event)
void OnVoltPerDivSpinctrlTextUpdated (wxCommandEvent &event)
wxBitmap GetBitmapResource (const wxString &name)
Retrieves bitmap resources.
wxIcon GetIconResource (const wxString &name)
Retrieves icon resources.
bool SetupBoard (GenericBoard *p_board, int ch_index, int ch_count, int m_scope_index, bool is_virtual)
bool UpdateControls ()
Static Public Member Functions
static bool ShowToolTips ()
Should we show tooltips?
Public Attributes
wxStaticBox * m_main_sizer_text
wxToggleButton * m_view_enable_control
wxPanel * m_color_control
wxSpinCtrl * m_line_width_control
wxButton * m_ch_offset_reset_control
wxSpinButton * m_ch_offset_control
wxSpinCtrl * m_ch_volt_per_div_control
Protected Member Functions
void UpdateLinePen (void)
void UpdateLineWidth (int value)
void UpdateOffset (void)
void UpdateVoltPerDiv (int value)
Private Attributes
GenericBoard * m_p_board
GenericBoardChannel * m_p_board_channel
int m_ch_index
int m_ch_count
int m_scope_index
bool m_is_virtual
Detailed Description
Compatibility
ViewChControl class declaration
Definition at line 75 of file view_ch_control.h.
Constructor & Destructor Documentation
ViewChControl::ViewChControl ()
Constructors.
ViewChControl type definition
ViewChControl event table definition
ViewChControl constructors
Definition at line 74 of file view_ch_control.cpp.
ViewChControl::ViewChControl (wxWindow * parent, wxWindowID id = SYMBOL_VIEWCHCONTROL_IDNAME, const wxPoint & pos = SYMBOL_VIEWCHCONTROL_POSITION, const wxSize & size = SYMBOL_VIEWCHCONTROL_SIZE, long style = SYMBOL_VIEWCHCONTROL_STYLE)
Definition at line 78 of file view_ch_control.cpp.
References Create().
Member Function Documentation
bool ViewChControl::Create (wxWindow * parent, wxWindowID id = SYMBOL_VIEWCHCONTROL_IDNAME, const wxPoint & pos = SYMBOL_VIEWCHCONTROL_POSITION, const wxSize & size = SYMBOL_VIEWCHCONTROL_SIZE, long style = SYMBOL_VIEWCHCONTROL_STYLE)
Creation.
ViewChControl creator
Definition at line 87 of file view_ch_control.cpp.
References CreateControls(), m_ch_offset_control, m_ch_offset_reset_control, m_ch_volt_per_div_control, m_color_control, m_line_width_control, m_main_sizer_text, and m_view_enable_control.
Referenced by ViewChControl().
void ViewChControl::CreateControls ()
Creates the controls and sizers.
Control creation for ViewChControl
Definition at line 116 of file view_ch_control.cpp.
References ID_CHOOSE_COLOR_BUTTON, ID_COLOR_PANEL, ID_LINE_WIDTH_SPINCTRL, ID_OFFSET_Y_RESET_BUTTON, ID_SPINBUTTON1, ID_VIEW_ENABLE_TOGGLEBUTTON, ID_VOLT_PER_DIV_SPINCTRL, m_ch_offset_control, m_ch_offset_reset_control, m_ch_volt_per_div_control, m_color_control, m_line_width_control, m_main_sizer_text, m_view_enable_control, and ShowToolTips().
Referenced by Create().
wxBitmap ViewChControl::GetBitmapResource (const wxString & name)
Retrieves bitmap resources.
Get bitmap resources
Definition at line 192 of file view_ch_control.cpp.
wxIcon ViewChControl::GetIconResource (const wxString & name)
Retrieves icon resources.
Get icon resources
Definition at line 205 of file view_ch_control.cpp.
void ViewChControl::OnChooseColorButtonClick (wxCommandEvent & event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_CHOOSE_COLOR_BUTTON
Definition at line 262 of file view_ch_control.cpp.
References m_color_control, GenericBoardChannel::m_line_color, m_p_board_channel, m_scope_index, and UpdateLinePen().
void ViewChControl::OnLineWidthSpinctrlTextUpdated (wxCommandEvent & event)
wxEVT_COMMAND_TEXT_UPDATED event handler for ID_LINE_WIDTH_SPINCTRL
Definition at line 304 of file view_ch_control.cpp.
References m_line_width_control, and UpdateLineWidth().
void ViewChControl::OnLineWidthSpinctrlUpdated (wxSpinEvent & event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_LINE_WIDTH_SPINCTRL
Definition at line 283 of file view_ch_control.cpp.
References UpdateLineWidth().
void ViewChControl::OnOffsetYResetButtonClick (wxCommandEvent & event)
wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_OFFSET_Y_RESET_BUTTON
Definition at line 353 of file view_ch_control.cpp.
References m_ch_offset_control, and UpdateOffset().
void ViewChControl::OnSpinbutton1Updated (wxSpinEvent & event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_SPINBUTTON1
Definition at line 363 of file view_ch_control.cpp.
References UpdateOffset().
void ViewChControl::OnViewEnableTogglebuttonClick (wxCommandEvent & event)
wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_VIEW_ENABLE_TOGGLEBUTTON
Definition at line 372 of file view_ch_control.cpp.
References m_p_board_channel, m_scope_index, GenericBoardChannel::m_scope_view_enabled, m_view_enable_control, and GenericBoardChannel::ScopeRefresh.
void ViewChControl::OnVoltPerDivSpinctrlTextUpdated (wxCommandEvent & event)
wxEVT_COMMAND_TEXT_UPDATED event handler for ID_VOLT_PER_DIV_SPINCTRL
Definition at line 342 of file view_ch_control.cpp.
References m_ch_volt_per_div_control, and UpdateVoltPerDiv().
void ViewChControl::OnVoltPerDivSpinctrlUpdated (wxSpinEvent & event)
wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_VOLT_PER_DIV_SPINCTRL
Definition at line 333 of file view_ch_control.cpp.
References UpdateVoltPerDiv().
bool ViewChControl::SetupBoard (GenericBoard * p_board, int ch_index, int ch_count, int m_scope_index, bool is_virtual)
Definition at line 214 of file view_ch_control.cpp.
References m_ch_count, m_ch_index, GenericBoard::m_channel_array, m_is_virtual, m_p_board, m_p_board_channel, m_scope_index, GenericBoard::m_virtual_channel_array, and UpdateControls().
Referenced by MainFrame::CreateDynControls().
bool ViewChControl::ShowToolTips () [static]
Should we show tooltips?
Definition at line 183 of file view_ch_control.cpp.
Referenced by CreateControls().
bool ViewChControl::UpdateControls (void)
Definition at line 238 of file view_ch_control.cpp.
References m_ch_count, m_ch_offset_control, m_ch_volt_per_div_control, m_color_control, m_is_virtual, GenericBoardChannel::m_line_color, GenericBoardChannel::m_line_width, m_line_width_control, m_main_sizer_text, GenericBoardChannel::m_offset_y, m_p_board_channel, m_scope_index, GenericBoardChannel::m_scope_view_enabled, m_view_enable_control, GenericBoardChannel::m_volt_2_div, and UpdateLinePen().
Referenced by SetupBoard().
void ViewChControl::UpdateLinePen (void) [protected]
Definition at line 289 of file view_ch_control.cpp.
References GenericBoardChannel::m_line_color, m_p_board_channel, m_scope_index, GenericBoardChannel::ScopeRefresh, and GenericBoardChannel::SetLinePen().
Referenced by OnChooseColorButtonClick(), UpdateControls(), and UpdateLineWidth().
void ViewChControl::UpdateLineWidth (int value) [protected]
Definition at line 311 of file view_ch_control.cpp.
References GenericBoardChannel::m_line_width, m_p_board_channel, m_scope_index, and UpdateLinePen().
Referenced by OnLineWidthSpinctrlTextUpdated(), and OnLineWidthSpinctrlUpdated().
void ViewChControl::UpdateOffset (void) [protected]
Definition at line 317 of file view_ch_control.cpp.
References m_ch_offset_control, GenericBoardChannel::m_offset_y, m_p_board_channel, m_scope_index, and GenericBoardChannel::ScopeRefresh.
Referenced by OnOffsetYResetButtonClick(), and OnSpinbutton1Updated().
void ViewChControl::UpdateVoltPerDiv (int value) [protected]
Definition at line 322 of file view_ch_control.cpp.
References m_p_board_channel, m_scope_index, GenericBoardChannel::ScopeRefresh, and GenericBoardChannel::SetVolt2Div().
Referenced by OnVoltPerDivSpinctrlTextUpdated(), and OnVoltPerDivSpinctrlUpdated().
Member Data Documentation
int ViewChControl::m_ch_count [private]
Definition at line 145 of file view_ch_control.h.
Referenced by SetupBoard(), and UpdateControls().
int ViewChControl::m_ch_index [private]
Definition at line 144 of file view_ch_control.h.
Referenced by SetupBoard().
wxSpinButton* ViewChControl::m_ch_offset_control
Definition at line 134 of file view_ch_control.h.
Referenced by Create(), CreateControls(), OnOffsetYResetButtonClick(), UpdateControls(), and UpdateOffset().
wxButton* ViewChControl::m_ch_offset_reset_control
Definition at line 133 of file view_ch_control.h.
Referenced by Create(), and CreateControls().
wxSpinCtrl* ViewChControl::m_ch_volt_per_div_control
Definition at line 135 of file view_ch_control.h.
Referenced by Create(), CreateControls(), OnVoltPerDivSpinctrlTextUpdated(), and UpdateControls().
wxPanel* ViewChControl::m_color_control
Definition at line 131 of file view_ch_control.h.
Referenced by Create(), CreateControls(), OnChooseColorButtonClick(), and UpdateControls().
bool ViewChControl::m_is_virtual [private]
Definition at line 147 of file view_ch_control.h.
Referenced by SetupBoard(), and UpdateControls().
wxSpinCtrl* ViewChControl::m_line_width_control
Definition at line 132 of file view_ch_control.h.
Referenced by Create(), CreateControls(), OnLineWidthSpinctrlTextUpdated(), and UpdateControls().
wxStaticBox* ViewChControl::m_main_sizer_text
Definition at line 129 of file view_ch_control.h.
Referenced by Create(), CreateControls(), and UpdateControls().
GenericBoard* ViewChControl::m_p_board [private]
Definition at line 142 of file view_ch_control.h.
Referenced by SetupBoard().
GenericBoardChannel* ViewChControl::m_p_board_channel [private]
Definition at line 143 of file view_ch_control.h.
Referenced by OnChooseColorButtonClick(), OnViewEnableTogglebuttonClick(), SetupBoard(), UpdateControls(), UpdateLinePen(), UpdateLineWidth(), UpdateOffset(), and UpdateVoltPerDiv().
int ViewChControl::m_scope_index [private]
Definition at line 146 of file view_ch_control.h.
Referenced by OnChooseColorButtonClick(), OnViewEnableTogglebuttonClick(), SetupBoard(), UpdateControls(), UpdateLinePen(), UpdateLineWidth(), UpdateOffset(), and UpdateVoltPerDiv().
wxToggleButton* ViewChControl::m_view_enable_control
Definition at line 130 of file view_ch_control.h.
Referenced by Create(), CreateControls(), OnViewEnableTogglebuttonClick(), and UpdateControls().
The documentation for this class was generated from the following files:
view_ch_control.h
view_ch_control.cpp