CAENScope: cvt_V1724.h File Reference
cvt_V1724.h File Reference
V1724 VME board definitions.
#include "cvt_common_defs.h"
#include "cvt_board_commons.h"
Classes
struct cvt_V1724_data
V1724 board data structure.
struct CVT_V1724_ROM_CONFIG
V1724 board ROM configuration.
union PACKED_1
Defines
#define CVT_V1724_THRESHOLD_NUM 8
Number of threshold registers.
#define CVT_V1724_OUT_BUFFER_ADD 0x0000
Output buffer relative address.
#define CVT_V1724_BROAD_CH_CTRL_ADD 0x8000
Control channel broadcast register relative address (Write only).
#define CVT_V1724_BROAD_CH_SET_CTRL_ADD 0x8004
Set control channel broadcast register relative address (Write only).
#define CVT_V1724_BROAD_CH_CLEAR_CTRL_ADD 0x8008
Clear control channel broadcast register relative address (Write only).
#define CVT_V1724_BROAD_NUM_BLOCK_ADD 0x800C
Number of blocks broadcast register relative address (Write only).
#define CVT_V1724_BROAD_CH_BUFF_FLUSH_ADD 0x8010
Number of buffers to be removed channel broadcast register relative address (Write only).
#define CVT_V1724_BROAD_CH_RND_ACC_ADD 0x8014
Read random Access channel broadcast register relative address (Write only).
#define CVT_V1724_BROAD_CH_CUSSIZE_ADD 0x8020
CustomSize channel broadcast register relative address (Write only).
#define CVT_V1724_BROAD_CH_ZSTH_ADD 0x8024
Zero suppression threshold channel broadcast register relative address (Write only).
#define CVT_V1724_BROAD_ADC_CONF_ADD 0x809c
ADC configuration broadcast register relative address (Write only).
#define CVT_V1724_ACQ_CONTROL_ADD 0x8100
Acquisiton Control register relative address.
#define CVT_V1724_ACQ_STATUS_ADD 0x8104
Acquisiton Status register relative address.
#define CVT_V1724_SW_TRIGGER_ADD 0x8108
Software trigger register relative address.
#define CVT_V1724_TRIGGER_SRC_ENABLE_ADD 0x810C
Trigger source enable register relative address.
#define CVT_V1724_FP_TRIGGER_OUT_ENABLE_ADD 0x8110
Front panel trigger out enable mask register relative address.
#define CVT_V1724_POST_TRIG_ADD 0x8114
Post trigger register relative address.
#define CVT_V1724_FRONT_PANEL_IO_ADD 0x8118
Front panel IO register relative address.
#define CVT_V1724_FRONT_PANEL_IO_CTRL_ADD 0x811C
Front panel IO Control register relative address.
#define CVT_V1724_CH_ENABLE_ADD 0x8120
Channel enable mask register relative address.
#define CVT_V1724_FW_REV_ADD 0x8124
Firmware Revision register relative address.
#define CVT_V1724_DOWNSAMPLE_FACT_ADD 0x8128
DownSample factor register relative address.
#define CVT_V1724_EVENT_STORED_ADD 0x812C
Event stored register relative address.
#define CVT_V1724_MON_SET_ADD 0x8138
Monitor output set register relative address.
#define CVT_V1724_SW_SYNC_ADD 0x813C
Sw sync register relative address.
#define CVT_V1724_BOARD_INFO_ADD 0x8140
Board's information register relative address.
#define CVT_V1724_MON_MODE_ADD 0x8144
Monitor output mode register relative address.
#define CVT_V1724_TEST_IO_ADD 0x8168
I/O Test register relative address.
#define CVT_V1724_VME_CONTROL_ADD 0xEF00
VME Control register relative address.
#define CVT_V1724_VME_STATUS_ADD 0xEF04
VME Status register relative address.
#define CVT_V1724_BOARD_ID_ADD 0xEF08
Geo Address register relative address.
#define CVT_V1724_MCST_CBLT_ADD_CTRL_ADD 0xEF0C
MCST/CBLT Address and control register relative address.
#define CVT_V1724_RELOCATION_ADDRESS_ADD 0xEF10
Relocation address register relative address.
#define CVT_V1724_INT_STATUS_ID_ADD 0xEF14
Interrupt status id register relative address.
#define CVT_V1724_INT_EVENT_NUM_ADD 0xEF18
Interrupt event number register relative address.
#define CVT_V1724_BLT_EVENT_NUM_ADD 0xEF1C
BLT event number register relative address.
#define CVT_V1724_SCRATCH_ADD 0xEF20
Scratch register relative address.
#define CVT_V1724_SW_RESET_ADD 0xEF24
Software reset register relative address.
#define CVT_V1724_SW_CLEAR_ADD 0xEF28
Software clear register relative address.
#define CVT_V1724_FLASH_EN_ADD 0xEF2C
Flash enable relative address.
#define CVT_V1724_FLASH_DATA_ADD 0xEF30
Flash data relative address.
#define CVT_V1724_RELOAD_CONFIG_ADD 0xEF34
Configuration Reload relative address.
#define CVT_V1724_BASE_ADDRESS_ADD 0xEF38
Base Address relative address.
#define CVT_V1724_ROM_CHKSUM_ADD 0xF000
Configuration ROM checksum relative address.
#define CVT_V1724_ROM_CHKSUM_LEN_2_ADD 0xF004
Configuration ROM checksum length (MSB) relative address.
#define CVT_V1724_ROM_CHKSUM_LEN_1_ADD 0xF008
Configuration ROM checksum length relative address.
#define CVT_V1724_ROM_CHKSUM_LEN_0_ADD 0xF00C
Configuration ROM checksum length (LSB) relative address.
#define CVT_V1724_ROM_CONST_2_ADD 0xF010
Configuration ROM constant (MSB) relative address.
#define CVT_V1724_ROM_CONST_1_ADD 0xF014
Configuration ROM constant relative address.
#define CVT_V1724_ROM_CONST_0_ADD 0xF018
Configuration ROM constant (LSB) relative address.
#define CVT_V1724_ROM_C_CODE_ADD 0xF01C
Configuration ROM c_code relative address.
#define CVT_V1724_ROM_R_CODE_ADD 0xF020
Configuration ROM r_code relative address.
#define CVT_V1724_ROM_OUI_2_ADD 0xF024
Configuration ROM Manufacturer identifier (IEEE OUI) (MSB) relative address.
#define CVT_V1724_ROM_OUI_1_ADD 0xF028
Configuration ROM Manufacturer identifier (IEEE OUI) relative address.
#define CVT_V1724_ROM_OUI_0_ADD 0xF02C
Configuration ROM Manufacturer identifier (IEEE OUI) (LSB) relative address.
#define CVT_V1724_ROM_VERSION_ADD 0xF030
Configuration ROM Purchased version of the Mod.V1724 relative address.
#define CVT_V1724_ROM_BOARD_ID_2_ADD 0xF034
Configuration ROM Board identifier (MSB) relative address.
#define CVT_V1724_ROM_BOARD_ID_1_ADD 0xF038
Configuration ROM Board identifier relative address.
#define CVT_V1724_ROM_BOARD_ID_0_ADD 0xF03C
Configuration ROM Board identifier (LSB) relative address.
#define CVT_V1724_ROM_REVISION_3_ADD 0xF040
Configuration ROM Hardware revision identifier relative address.
#define CVT_V1724_ROM_REVISION_2_ADD 0xF044
Configuration ROM Hardware revision identifier relative address.
#define CVT_V1724_ROM_REVISION_1_ADD 0xF048
Configuration ROM Hardware revision identifier relative address.
#define CVT_V1724_ROM_REVISION_0_ADD 0xF04C
Configuration ROM Hardware revision identifier relative address.
#define CVT_V1724_ROM_SERIAL_1_ADD 0xF080
Configuration ROM Serial number (MSB) relative address.
#define CVT_V1724_ROM_SERIAL_0_ADD 0xF084
Configuration ROM Serial number (LSB) relative address.
#define CVT_V1724_ROM_VCXO_TYPE_ADD 0xF088
Configuration ROM VCXO type relative address.
#define CVT_V1724_CH0_RESERVED_RND_ACC_ADD 0x1014
CH 0 Read Block channel broadcast reserved register relative address.
#define CVT_V1724_CH0_ZSTH_ADD 0x1024
CH 0 Zero suppression threshold register relative address.
#define CVT_V1724_CH0_THRESHOLD_ADD 0x1080
CH 0 Threshold register relative address.
#define CVT_V1724_CH0_TIME_OVER_UNDER_THR_ADD 0x1084
CH 0 Over/Under Threshold Samples register relative address.
#define CVT_V1724_CH0_STATUS_ADD 0x1088
CH 0 status register relative address.
#define CVT_V1724_CH0_FW_REV_ADD 0x108C
CH 0 firmware revision register relative address.
#define CVT_V1724_CH0_BUFF_OCCUPANCY_ADD 0x1094
CH 0 Number of Buffers Filled register relative address.
#define CVT_V1724_CH0_DAC_CONF_ADD 0x1098
CH 0 DAC Data Configuration register relative address.
#define CVT_V1724_CH0_ADC_CONF_ADD 0x109C
CH 0 Configuration register relative address.
#define CVT_V1724_CH0_RESERVED_ADC_DEBUG_ADD 0x10A0
CH 0 ADC Debug Reserved register relative address.
#define CVT_V1724_CH0_RESERVED_MEM_DATA_ADD 0x10A4
CH 0 Memory test data Reserved register relative address.
#define CVT_V1724_CH0_RESERVED_MEM_ADDRESS_ADD 0x10A8
CH 0 Memory test address Reserved register relative address.
#define CVT_V1724_CH1_RESERVED_RND_ACC_ADD 0x1114
CH 1 Read Block channel broadcast reserved register relative address.
#define CVT_V1724_CH1_ZSTH_ADD 0x1124
CH 1 Zero suppression threshold register relative address.
#define CVT_V1724_CH1_THRESHOLD_ADD 0x1180
CH 1 Threshold register relative address.
#define CVT_V1724_CH1_TIME_OVER_UNDER_THR_ADD 0x1184
CH 1 Over/Under Threshold Samples register relative address.
#define CVT_V1724_CH1_STATUS_ADD 0x1188
CH 1 status register relative address.
#define CVT_V1724_CH1_FW_REV_ADD 0x118C
CH 1 firmware revision register relative address.
#define CVT_V1724_CH1_BUFF_OCCUPANCY_ADD 0x1194
CH 1 Number of Buffers Filled register relative address.
#define CVT_V1724_CH1_DAC_CONF_ADD 0x1198
CH 1 DAC Data Configuration register relative address.
#define CVT_V1724_CH1_ADC_CONF_ADD 0x119C
CH 1 Configuration register relative address.
#define CVT_V1724_CH1_RESERVED_ADC_DEBUG_ADD 0x11A0
CH 1 ADC Debug Reserved register relative address.
#define CVT_V1724_CH1_RESERVED_MEM_DATA_ADD 0x11A4
CH 1 Memory test data Reserved register relative address.
#define CVT_V1724_CH1_RESERVED_MEM_ADDRESS_ADD 0x11A8
CH 1 Memory test address Reserved register relative address.
#define CVT_V1724_CH2_RESERVED_RND_ACC_ADD 0x1214
CH 2 Read Block channel broadcast reserved register relative address.
#define CVT_V1724_CH2_ZSTH_ADD 0x1224
CH 2 Zero suppression threshold register relative address.
#define CVT_V1724_CH2_THRESHOLD_ADD 0x1280
CH 2 Threshold register relative address.
#define CVT_V1724_CH2_TIME_OVER_UNDER_THR_ADD 0x1284
CH 2 Over/Under Threshold Samples register relative address.
#define CVT_V1724_CH2_STATUS_ADD 0x1288
CH 2 status register relative address.
#define CVT_V1724_CH2_FW_REV_ADD 0x128C
CH 2 firmware revision register relative address.
#define CVT_V1724_CH2_BUFF_OCCUPANCY_ADD 0x1294
CH 2 Number of Buffers Filled register relative address.
#define CVT_V1724_CH2_DAC_CONF_ADD 0x1298
CH 2 DAC Data Configuration register relative address.
#define CVT_V1724_CH2_ADC_CONF_ADD 0x129C
CH 2 Configuration register relative address.
#define CVT_V1724_CH2_RESERVED_ADC_DEBUG_ADD 0x12A0
CH 2 ADC Debug Reserved register relative address.
#define CVT_V1724_CH2_RESERVED_MEM_DATA_ADD 0x12A4
CH 2 Memory test data Reserved register relative address.
#define CVT_V1724_CH2_RESERVED_MEM_ADDRESS_ADD 0x12A8
CH 2 Memory test address Reserved register relative address.
#define CVT_V1724_CH3_RESERVED_RND_ACC_ADD 0x1314
CH 3 Read Block channel broadcast reserved register relative address.
#define CVT_V1724_CH3_ZSTH_ADD 0x1324
CH 3 Zero suppression threshold register relative address.
#define CVT_V1724_CH3_THRESHOLD_ADD 0x1380
CH 3 Threshold register relative address.
#define CVT_V1724_CH3_TIME_OVER_UNDER_THR_ADD 0x1384
CH 3 Over/Under Threshold Samples register relative address.
#define CVT_V1724_CH3_STATUS_ADD 0x1388
CH 3 status register relative address.
#define CVT_V1724_CH3_FW_REV_ADD 0x138C
CH 3 firmware revision register relative address.
#define CVT_V1724_CH3_BUFF_OCCUPANCY_ADD 0x1394
CH 3 Number of Buffers Filled register relative address.
#define CVT_V1724_CH3_DAC_CONF_ADD 0x1398
CH 3 DAC Data Configuration register relative address.
#define CVT_V1724_CH3_ADC_CONF_ADD 0x139C
CH 3 Configuration register relative address.
#define CVT_V1724_CH3_RESERVED_ADC_DEBUG_ADD 0x13A0
CH 3 ADC Debug Reserved register relative address.
#define CVT_V1724_CH3_RESERVED_MEM_DATA_ADD 0x13A4
CH 3 Memory test data Reserved register relative address.
#define CVT_V1724_CH3_RESERVED_MEM_ADDRESS_ADD 0x13A8
CH 3 Memory test address Reserved register relative address.
#define CVT_V1724_CH4_RESERVED_RND_ACC_ADD 0x1414
CH 4 Read Block channel broadcast reserved register relative address.
#define CVT_V1724_CH4_ZSTH_ADD 0x1424
CH 4 Zero suppression threshold register relative address.
#define CVT_V1724_CH4_THRESHOLD_ADD 0x1480
CH 4 Threshold register relative address.
#define CVT_V1724_CH4_TIME_OVER_UNDER_THR_ADD 0x1484
CH 4 Over/Under Threshold Samples register relative address.
#define CVT_V1724_CH4_STATUS_ADD 0x1488
CH 4 status register relative address.
#define CVT_V1724_CH4_FW_REV_ADD 0x148C
CH 4 firmware revision register relative address.
#define CVT_V1724_CH4_BUFF_OCCUPANCY_ADD 0x1494
CH 4 Number of Buffers Filled register relative address.
#define CVT_V1724_CH4_DAC_CONF_ADD 0x1498
CH 4 DAC Data Configuration register relative address.
#define CVT_V1724_CH4_ADC_CONF_ADD 0x149C
CH 4 Configuration register relative address.
#define CVT_V1724_CH4_RESERVED_ADC_DEBUG_ADD 0x14A0
CH 4 ADC Debug Reserved register relative address.
#define CVT_V1724_CH4_RESERVED_MEM_DATA_ADD 0x14A4
CH 4 Memory test data Reserved register relative address.
#define CVT_V1724_CH4_RESERVED_MEM_ADDRESS_ADD 0x14A8
CH 4 Memory test address Reserved register relative address.
#define CVT_V1724_CH5_RESERVED_RND_ACC_ADD 0x1514
CH 5 Read Block channel broadcast reserved register relative address.
#define CVT_V1724_CH5_ZSTH_ADD 0x1524
CH 5 Zero suppression threshold register relative address.
#define CVT_V1724_CH5_THRESHOLD_ADD 0x1580
CH 5 Threshold register relative address.
#define CVT_V1724_CH5_TIME_OVER_UNDER_THR_ADD 0x1584
CH 5 Over/Under Threshold Samples register relative address.
#define CVT_V1724_CH5_STATUS_ADD 0x1588
CH 5 status register relative address.
#define CVT_V1724_CH5_FW_REV_ADD 0x158C
CH 5 firmware revision register relative address.
#define CVT_V1724_CH5_BUFF_OCCUPANCY_ADD 0x1594
CH 5 Number of Buffers Filled register relative address.
#define CVT_V1724_CH5_DAC_CONF_ADD 0x1598
CH 5 DAC Data Configuration register relative address.
#define CVT_V1724_CH5_ADC_CONF_ADD 0x159C
CH 5 Configuration register relative address.
#define CVT_V1724_CH5_RESERVED_ADC_DEBUG_ADD 0x15A0
CH 5 ADC Debug Reserved register relative address.
#define CVT_V1724_CH5_RESERVED_MEM_DATA_ADD 0x15A4
CH 5 Memory test data Reserved register relative address.
#define CVT_V1724_CH5_RESERVED_MEM_ADDRESS_ADD 0x15A8
CH 5 Memory test address Reserved register relative address.
#define CVT_V1724_CH6_RESERVED_RND_ACC_ADD 0x1614
CH 6 Read Block channel broadcast reserved register relative address.
#define CVT_V1724_CH6_ZSTH_ADD 0x1624
CH 6 Zero suppression threshold register relative address.
#define CVT_V1724_CH6_THRESHOLD_ADD 0x1680
CH 6 Threshold register relative address.
#define CVT_V1724_CH6_TIME_OVER_UNDER_THR_ADD 0x1684
CH 6 Over/Under Threshold Samples register relative address.
#define CVT_V1724_CH6_STATUS_ADD 0x1688
CH 6 status register relative address.
#define CVT_V1724_CH6_FW_REV_ADD 0x168C
CH 6 firmware revision register relative address.
#define CVT_V1724_CH6_BUFF_OCCUPANCY_ADD 0x1694
CH 6 Number of Buffers Filled register relative address.
#define CVT_V1724_CH6_DAC_CONF_ADD 0x1698
CH 6 DAC Data Configuration register relative address.
#define CVT_V1724_CH6_ADC_CONF_ADD 0x169C
CH 6 Configuration register relative address.
#define CVT_V1724_CH6_RESERVED_ADC_DEBUG_ADD 0x16A0
CH 6 ADC Debug Reserved register relative address.
#define CVT_V1724_CH6_RESERVED_MEM_DATA_ADD 0x16A4
CH 6 Memory test data Reserved register relative address.
#define CVT_V1724_CH6_RESERVED_MEM_ADDRESS_ADD 0x16A8
CH 6 Memory test address Reserved register relative address.
#define CVT_V1724_CH7_RESERVED_RND_ACC_ADD 0x1714
CH 7 Read Block channel broadcast reserved register relative address.
#define CVT_V1724_CH7_ZSTH_ADD 0x1724
CH 7 Zero suppression threshold register relative address.
#define CVT_V1724_CH7_THRESHOLD_ADD 0x1780
CH 7 Threshold register relative address.
#define CVT_V1724_CH7_TIME_OVER_UNDER_THR_ADD 0x1784
CH 7 Over/Under Threshold Samples register relative address.
#define CVT_V1724_CH7_STATUS_ADD 0x1788
CH 7 status register relative address.
#define CVT_V1724_CH7_FW_REV_ADD 0x178C
CH 7 firmware revision register relative address.
#define CVT_V1724_CH7_BUFF_OCCUPANCY_ADD 0x1794
CH 7 Number of Buffers Filled register relative address.
#define CVT_V1724_CH7_DAC_CONF_ADD 0x1798
CH 7 DAC Data Configuration register relative address.
#define CVT_V1724_CH7_ADC_CONF_ADD 0x179C
CH 7 Configuration register relative address.
#define CVT_V1724_CH7_RESERVED_ADC_DEBUG_ADD 0x17A0
CH 7 ADC Debug Reserved register relative address.
#define CVT_V1724_CH7_RESERVED_MEM_DATA_ADD 0x17A4
CH 7 Memory test data Reserved register relative address.
#define CVT_V1724_CH7_RESERVED_MEM_ADDRESS_ADD 0x17A8
CH 7 Memory test address Reserved register relative address.
#define CVT_V1724_OUT_BUFFER_DATA_SIZE cvD64
Output buffer data buffer.
#define CVT_V1724_BROAD_CH_CTRL_DATA_SIZE cvD32
Control channel broadcast register data size (Write only).
#define CVT_V1724_BROAD_CH_SET_CTRL_DATA_SIZE cvD32
Set control channel broadcast register data size (Write only).
#define CVT_V1724_BROAD_CH_CLEAR_CTRL_DATA_SIZE cvD32
Clear control channel broadcast register data size (Write only).
#define CVT_V1724_BROAD_NUM_BLOCK_DATA_SIZE cvD32
Number of blocks broadcast register data size(Write only).
#define CVT_V1724_BROAD_CH_BUFF_FLUSH_DATA_SIZE cvD32
Number of buffers to be removed channel broadcast register data size(Write only).
#define CVT_V1724_BROAD_CH_RND_ACC_DATA_SIZE cvD32
Parameters to Random access channel broadcast register data size (Write only).
#define CVT_V1724_BROAD_CH_CUSSIZE_DATA_SIZE cvD32
Custom Size channel broadcast register data size (Write only).
#define CVT_V1724_BROAD_CH_ZSTH_DATA_SIZE cvD32
Zero suppression threshold channel broadcast register data size (Write only).
#define CVT_V1724_BROAD_ADC_CONF_DATA_SIZE cvD32
ADC configuration broadcast register data size (Write only).
#define CVT_V1724_ACQ_CONTROL_DATA_SIZE cvD32
Acquisiton Control register data size.
#define CVT_V1724_ACQ_STATUS_DATA_SIZE cvD32
Acquisiton Status register data size.
#define CVT_V1724_SW_TRIGGER_DATA_SIZE cvD32
Software trigger register data size.
#define CVT_V1724_TRIGGER_SRC_ENABLE_DATA_SIZE cvD32
Trigger source enable register data size.
#define CVT_V1724_FP_TRIGGER_OUT_ENABLE_DATA_SIZE cvD32
Front panel trigger out enable mask register data size.
#define CVT_V1724_POST_TRIG_DATA_SIZE cvD32
Post trigger register data size.
#define CVT_V1724_FRONT_PANEL_IO_DATA_SIZE cvD32
Front panel IO register data size.
#define CVT_V1724_FRONT_PANEL_IO_CTRL_DATA_SIZE cvD32
Front panel IO Control register data size.
#define CVT_V1724_CH_ENABLE_DATA_SIZE cvD32
Channel enable mask register data size.
#define CVT_V1724_FW_REV_DATA_SIZE cvD32
Firmware Revision register data size.
#define CVT_V1724_DOWNSAMPLE_FACT_DATA_SIZE cvD32
DownSample factor register data size.
#define CVT_V1724_EVENT_STORED_DATA_SIZE cvD32
Event stored register data size.
#define CVT_V1724_MON_SET_DATA_SIZE cvD32
Monitor output set register data size.
#define CVT_V1724_SW_SYNC_DATA_SIZE cvD32
Sw sync register data size.
#define CVT_V1724_BOARD_INFO_DATA_SIZE cvD32
Board's information register data size.
#define CVT_V1724_MON_MODE_DATA_SIZE cvD32
Monitor output mode register data size.
#define CVT_V1724_TEST_IO_DATA_SIZE cvD32
I/O Test register data size.
#define CVT_V1724_VME_CONTROL_DATA_SIZE cvD32
VME Control register data size.
#define CVT_V1724_VME_STATUS_DATA_SIZE cvD32
VME Status register data size.
#define CVT_V1724_BOARD_ID_DATA_SIZE cvD32
Geo Address register data size.
#define CVT_V1724_MCST_CBLT_ADD_CTRL_DATA_SIZE cvD32
MCST/CBLT Address and control register data size.
#define CVT_V1724_RELOCATION_ADDRESS_DATA_SIZE cvD32
Relocation address register data size.
#define CVT_V1724_INT_STATUS_ID_DATA_SIZE cvD32
Interrupt status id register data size.
#define CVT_V1724_INT_EVENT_NUM_DATA_SIZE cvD32
Interrupt event number register data size.
#define CVT_V1724_BLT_EVENT_NUM_DATA_SIZE cvD32
BLT event number register data size.
#define CVT_V1724_SCRATCH_DATA_SIZE cvD32
Scratch register data size.
#define CVT_V1724_SW_RESET_DATA_SIZE cvD32
Software reset register data size.
#define CVT_V1724_SW_CLEAR_DATA_SIZE cvD32
Software clear register data size.
#define CVT_V1724_FLASH_EN_DATA_SIZE cvD32
Flash enable data size.
#define CVT_V1724_FLASH_DATA_DATA_SIZE cvD32
Flash data data size.
#define CVT_V1724_RELOAD_CONFIG_DATA_SIZE cvD32
Configuration Reload data size.
#define CVT_V1724_BASE_ADDRESS_DATA_SIZE cvD32
Base Address data size.
#define CVT_V1724_ROM_CHKSUM_DATA_SIZE cvD32
Configuration ROM checksum data size.
#define CVT_V1724_ROM_CHKSUM_LEN_2_DATA_SIZE cvD32
Configuration ROM checksum length (MSB) data size.
#define CVT_V1724_ROM_CHKSUM_LEN_1_DATA_SIZE cvD32
Configuration ROM checksum length data size.
#define CVT_V1724_ROM_CHKSUM_LEN_0_DATA_SIZE cvD32
Configuration ROM checksum length (LSB) data size.
#define CVT_V1724_ROM_CONST_2_DATA_SIZE cvD32
Configuration ROM constant (MSB) data size.
#define CVT_V1724_ROM_CONST_1_DATA_SIZE cvD32
Configuration ROM constant data size.
#define CVT_V1724_ROM_CONST_0_DATA_SIZE cvD32
Configuration ROM constant (LSB) data size.
#define CVT_V1724_ROM_C_CODE_DATA_SIZE cvD32
Configuration ROM c_code data size.
#define CVT_V1724_ROM_R_CODE_DATA_SIZE cvD32
Configuration ROM r_code data size.
#define CVT_V1724_ROM_OUI_2_DATA_SIZE cvD32
Configuration ROM Manufacturer identifier (IEEE OUI) (MSB) data size.
#define CVT_V1724_ROM_OUI_1_DATA_SIZE cvD32
Configuration ROM Manufacturer identifier (IEEE OUI) data size.
#define CVT_V1724_ROM_OUI_0_DATA_SIZE cvD32
Configuration ROM Manufacturer identifier (IEEE OUI) (LSB) data size.
#define CVT_V1724_ROM_VERSION_DATA_SIZE cvD32
Configuration ROM Purchased version of the Mod.V1724 data size.
#define CVT_V1724_ROM_BOARD_ID_2_DATA_SIZE cvD32
Configuration ROM Board identifier (MSB) data size.
#define CVT_V1724_ROM_BOARD_ID_1_DATA_SIZE cvD32
Configuration ROM Board identifier data size.
#define CVT_V1724_ROM_BOARD_ID_0_DATA_SIZE cvD32
Configuration ROM Board identifier (LSB) data size.
#define CVT_V1724_ROM_REVISION_3_DATA_SIZE cvD32
Configuration ROM Hardware revision identifier data size.
#define CVT_V1724_ROM_REVISION_2_DATA_SIZE cvD32
Configuration ROM Hardware revision identifier data size.
#define CVT_V1724_ROM_REVISION_1_DATA_SIZE cvD32
Configuration ROM Hardware revision identifier data size.
#define CVT_V1724_ROM_REVISION_0_DATA_SIZE cvD32
Configuration ROM Hardware revision identifier data size.
#define CVT_V1724_ROM_SERIAL_1_DATA_SIZE cvD32
Configuration ROM Serial number (MSB) data size.
#define CVT_V1724_ROM_SERIAL_0_DATA_SIZE cvD32
Configuration ROM Serial number (LSB) data size.
#define CVT_V1724_ROM_VCXO_TYPE_DATA_SIZE cvD32
Configuration ROM VCXO type data size.
#define CVT_V1724_CH0_RESERVED_RND_ACC_DATA_SIZE cvD32
CH 0 Read Block channel broadcast reserved register data size.
#define CVT_V1724_CH0_ZSTH_DATA_SIZE cvD32
Ch 0 Zero suppression threshold register data size).
#define CVT_V1724_CH0_THRESHOLD_DATA_SIZE cvD32
CH 0 Threshold register data size.
#define CVT_V1724_CH0_TIME_OVER_UNDER_THR_DATA_SIZE cvD32
CH 0 Over/Under Threshold Samples register data size.
#define CVT_V1724_CH0_STATUS_DATA_SIZE cvD32
CH 0 status register data size.
#define CVT_V1724_CH0_FW_REV_DATA_SIZE cvD32
CH 0 firmware revision register data size.
#define CVT_V1724_CH0_BUFF_OCCUPANCY_DATA_SIZE cvD32
CH 0 Number of Buffers Filled register data size.
#define CVT_V1724_CH0_DAC_CONF_DATA_SIZE cvD32
CH 0 DAC Data Configuration register data size.
#define CVT_V1724_CH0_ADC_CONF_DATA_SIZE cvD32
CH 0 Configuration register data size.
#define CVT_V1724_CH0_RESERVED_ADC_DEBUG_DATA_SIZE cvD32
CH 0 ADC Debug Reserved register data size.
#define CVT_V1724_CH0_RESERVED_MEM_DATA_DATA_SIZE cvD32
CH 0 Memory test data Reserved register data size.
#define CVT_V1724_CH0_RESERVED_MEM_ADDRESS_DATA_SIZE cvD32
CH 0 Memory test address Reserved register data size.
#define CVT_V1724_CH1_RESERVED_RND_ACC_DATA_SIZE cvD32
CH 1 Read Block channel broadcast reserved register data size.
#define CVT_V1724_CH1_ZSTH_DATA_SIZE cvD32
Ch 1 Zero suppression threshold register data size).
#define CVT_V1724_CH1_THRESHOLD_DATA_SIZE cvD32
CH 1 Threshold register data size.
#define CVT_V1724_CH1_TIME_OVER_UNDER_THR_DATA_SIZE cvD32
CH 1 Over/Under Threshold Samples register data size.
#define CVT_V1724_CH1_STATUS_DATA_SIZE cvD32
CH 1 status register data size.
#define CVT_V1724_CH1_FW_REV_DATA_SIZE cvD32
CH 1 firmware revision register data size.
#define CVT_V1724_CH1_BUFF_OCCUPANCY_DATA_SIZE cvD32
CH 1 Number of Buffers Filled register data size.
#define CVT_V1724_CH1_DAC_CONF_DATA_SIZE cvD32
CH 1 DAC Data Configuration register data size.
#define CVT_V1724_CH1_ADC_CONF_DATA_SIZE cvD32
CH 1 Configuration register data size.
#define CVT_V1724_CH1_RESERVED_ADC_DEBUG_DATA_SIZE cvD32
CH 1 ADC Debug Reserved register data size.
#define CVT_V1724_CH1_RESERVED_MEM_DATA_DATA_SIZE cvD32
CH 1 Memory test data Reserved register data size.
#define CVT_V1724_CH1_RESERVED_MEM_ADDRESS_DATA_SIZE cvD32
CH 1 Memory test address Reserved register data size.
#define CVT_V1724_CH2_RESERVED_RND_ACC_DATA_SIZE cvD32
CH 2 Read Block channel broadcast reserved register data size.
#define CVT_V1724_CH2_ZSTH_DATA_SIZE cvD32
Ch 2 Zero suppression threshold register data size).
#define CVT_V1724_CH2_THRESHOLD_DATA_SIZE cvD32
CH 2 Threshold register data size.
#define CVT_V1724_CH2_TIME_OVER_UNDER_THR_DATA_SIZE cvD32
CH 2 Over/Under Threshold Samples register data size.
#define CVT_V1724_CH2_STATUS_DATA_SIZE cvD32
CH 2 status register data size.
#define CVT_V1724_CH2_FW_REV_DATA_SIZE cvD32
CH 2 firmware revision register data size.
#define CVT_V1724_CH2_BUFF_OCCUPANCY_DATA_SIZE cvD32
CH 2 Number of Buffers Filled register data size.
#define CVT_V1724_CH2_DAC_CONF_DATA_SIZE cvD32
CH 2 DAC Data Configuration register data size.
#define CVT_V1724_CH2_ADC_CONF_DATA_SIZE cvD32
CH 2 Configuration register data size.
#define CVT_V1724_CH2_RESERVED_ADC_DEBUG_DATA_SIZE cvD32
CH 2 ADC Debug Reserved register data size.
#define CVT_V1724_CH2_RESERVED_MEM_DATA_DATA_SIZE cvD32
CH 2 Memory test data Reserved register data size.
#define CVT_V1724_CH2_RESERVED_MEM_ADDRESS_DATA_SIZE cvD32
CH 2 Memory test address Reserved register data size.
#define CVT_V1724_CH3_RESERVED_RND_ACC_DATA_SIZE cvD32
CH 3 Read Block channel broadcast reserved register data size.
#define CVT_V1724_CH3_ZSTH_DATA_SIZE cvD32
Ch 3 Zero suppression threshold register data size).
#define CVT_V1724_CH3_THRESHOLD_DATA_SIZE cvD32
CH 3 Threshold register data size.
#define CVT_V1724_CH3_TIME_OVER_UNDER_THR_DATA_SIZE cvD32
CH 3 Over/Under Threshold Samples register data size.
#define CVT_V1724_CH3_STATUS_DATA_SIZE cvD32
CH 3 status register data size.
#define CVT_V1724_CH3_FW_REV_DATA_SIZE cvD32
CH 3 firmware revision register data size.
#define CVT_V1724_CH3_BUFF_OCCUPANCY_DATA_SIZE cvD32
CH 3 Number of Buffers Filled register data size.
#define CVT_V1724_CH3_DAC_CONF_DATA_SIZE cvD32
CH 3 DAC Data Configuration register data size.
#define CVT_V1724_CH3_ADC_CONF_DATA_SIZE cvD32
CH 3 Configuration register data size.
#define CVT_V1724_CH3_RESERVED_ADC_DEBUG_DATA_SIZE cvD32
CH 3 ADC Debug Reserved register data size.
#define CVT_V1724_CH3_RESERVED_MEM_DATA_DATA_SIZE cvD32
CH 3 Memory test data Reserved register data size.
#define CVT_V1724_CH3_RESERVED_MEM_ADDRESS_DATA_SIZE cvD32
CH 3 Memory test address Reserved register data size.
#define CVT_V1724_CH4_RESERVED_RND_ACC_DATA_SIZE cvD32
CH 4 Read Block channel broadcast reserved register data size.
#define CVT_V1724_CH4_ZSTH_DATA_SIZE cvD32
Ch 4 Zero suppression threshold register data size).
#define CVT_V1724_CH4_THRESHOLD_DATA_SIZE cvD32
CH 4 Threshold register data size.
#define CVT_V1724_CH4_TIME_OVER_UNDER_THR_DATA_SIZE cvD32
CH 4 Over/Under Threshold Samples register data size.
#define CVT_V1724_CH4_STATUS_DATA_SIZE cvD32
CH 4 status register data size.
#define CVT_V1724_CH4_FW_REV_DATA_SIZE cvD32
CH 4 firmware revision register data size.
#define CVT_V1724_CH4_BUFF_OCCUPANCY_DATA_SIZE cvD32
CH 4 Number of Buffers Filled register data size.
#define CVT_V1724_CH4_DAC_CONF_DATA_SIZE cvD32
CH 4 DAC Data Configuration register data size.
#define CVT_V1724_CH4_ADC_CONF_DATA_SIZE cvD32
CH 4 Configuration register data size.
#define CVT_V1724_CH4_RESERVED_ADC_DEBUG_DATA_SIZE cvD32
CH 4 ADC Debug Reserved register data size.
#define CVT_V1724_CH4_RESERVED_MEM_DATA_DATA_SIZE cvD32
CH 4 Memory test data Reserved register data size.
#define CVT_V1724_CH4_RESERVED_MEM_ADDRESS_DATA_SIZE cvD32
CH 4 Memory test address Reserved register data size.
#define CVT_V1724_CH5_RESERVED_RND_ACC_DATA_SIZE cvD32
CH 5 Read Block channel broadcast reserved register data size.
#define CVT_V1724_CH5_ZSTH_DATA_SIZE cvD32
Ch 5 Zero suppression threshold register data size).
#define CVT_V1724_CH5_THRESHOLD_DATA_SIZE cvD32
CH 5 Threshold register data size.
#define CVT_V1724_CH5_TIME_OVER_UNDER_THR_DATA_SIZE cvD32
CH 5 Over/Under Threshold Samples register data size.
#define CVT_V1724_CH5_STATUS_DATA_SIZE cvD32
CH 5 status register data size.
#define CVT_V1724_CH5_FW_REV_DATA_SIZE cvD32
CH 5 firmware revision register data size.
#define CVT_V1724_CH5_BUFF_OCCUPANCY_DATA_SIZE cvD32
CH 5 Number of Buffers Filled register data size.
#define CVT_V1724_CH5_DAC_CONF_DATA_SIZE cvD32
CH 5 DAC Data Configuration register data size.
#define CVT_V1724_CH5_ADC_CONF_DATA_SIZE cvD32
CH 5 Configuration register data size.
#define CVT_V1724_CH5_RESERVED_ADC_DEBUG_DATA_SIZE cvD32
CH 5 ADC Debug Reserved register data size.
#define CVT_V1724_CH5_RESERVED_MEM_DATA_DATA_SIZE cvD32
CH 5 Memory test data Reserved register data size.
#define CVT_V1724_CH5_RESERVED_MEM_ADDRESS_DATA_SIZE cvD32
CH 5 Memory test address Reserved register data size.
#define CVT_V1724_CH6_RESERVED_RND_ACC_DATA_SIZE cvD32
CH 6 Read Block channel broadcast reserved register data size.
#define CVT_V1724_CH6_ZSTH_DATA_SIZE cvD32
Ch 6 Zero suppression threshold register data size).
#define CVT_V1724_CH6_THRESHOLD_DATA_SIZE cvD32
CH 6 Threshold register data size.
#define CVT_V1724_CH6_TIME_OVER_UNDER_THR_DATA_SIZE cvD32
CH 6 Over/Under Threshold Samples register data size.
#define CVT_V1724_CH6_STATUS_DATA_SIZE cvD32
CH 6 status register data size.
#define CVT_V1724_CH6_FW_REV_DATA_SIZE cvD32
CH 6 firmware revision register data size.
#define CVT_V1724_CH6_BUFF_OCCUPANCY_DATA_SIZE cvD32
CH 6 Number of Buffers Filled register data size.
#define CVT_V1724_CH6_DAC_CONF_DATA_SIZE cvD32
CH 6 DAC Data Configuration register data size.
#define CVT_V1724_CH6_ADC_CONF_DATA_SIZE cvD32
CH 6 Configuration register data size.
#define CVT_V1724_CH6_RESERVED_ADC_DEBUG_DATA_SIZE cvD32
CH 6 ADC Debug Reserved register data size.
#define CVT_V1724_CH6_RESERVED_MEM_DATA_DATA_SIZE cvD32
CH 6 Memory test data Reserved register data size.
#define CVT_V1724_CH6_RESERVED_MEM_ADDRESS_DATA_SIZE cvD32
CH 6 Memory test address Reserved register data size.
#define CVT_V1724_CH7_RESERVED_RND_ACC_DATA_SIZE cvD32
CH 7 Read Block channel broadcast reserved register data size.
#define CVT_V1724_CH7_ZSTH_DATA_SIZE cvD32
Ch 7 Zero suppression threshold register data size).
#define CVT_V1724_CH7_THRESHOLD_DATA_SIZE cvD32
CH 7 Threshold register data size.
#define CVT_V1724_CH7_TIME_OVER_UNDER_THR_DATA_SIZE cvD32
CH 7 Over/Under Threshold Samples register data size.
#define CVT_V1724_CH7_STATUS_DATA_SIZE cvD32
CH 7 status register data size.
#define CVT_V1724_CH7_FW_REV_DATA_SIZE cvD32
CH 7 firmware revision register data size.
#define CVT_V1724_CH7_BUFF_OCCUPANCY_DATA_SIZE cvD32
CH 7 Number of Buffers Filled register data size.
#define CVT_V1724_CH7_DAC_CONF_DATA_SIZE cvD32
CH 7 DAC Data Configuration register data size.
#define CVT_V1724_CH7_ADC_CONF_DATA_SIZE cvD32
CH 7 Configuration register data size.
#define CVT_V1724_CH7_RESERVED_ADC_DEBUG_DATA_SIZE cvD32
CH 7 ADC Debug Reserved register data size.
#define CVT_V1724_CH7_RESERVED_MEM_DATA_DATA_SIZE cvD32
CH 7 Memory test data Reserved register data size.
#define CVT_V1724_CH7_RESERVED_MEM_ADDRESS_DATA_SIZE cvD32
CH 7 Memory test address Reserved register data size.
#define CVT_V1724_OUT_BUFFER_AM cvA32_S_MBLT
Output buffer data buffer address modifier.
#define CVT_V1724_BROAD_CH_CTRL_AM cvA32_S_DATA
Control channel broadcast register address modifier (Write only).
#define CVT_V1724_BROAD_CH_SET_CTRL_AM cvA32_S_DATA
Set control channel broadcast register address modifier (Write only).
#define CVT_V1724_BROAD_CH_CLEAR_CTRL_AM cvA32_S_DATA
Clear control channel broadcast register address modifier (Write only).
#define CVT_V1724_BROAD_NUM_BLOCK_AM cvA32_S_DATA
Number of blocks broadcast register address modifiere(Write only).
#define CVT_V1724_BROAD_CH_BUFF_FLUSH_AM cvA32_S_DATA
Number of buffers to be removed channel broadcast register address modifiere(Write only).
#define CVT_V1724_BROAD_CH_RND_ACC_AM cvA32_S_DATA
Parameters to Random access channel broadcast register address modifier (Write only).
#define CVT_V1724_BROAD_CH_CUSSIZE_AM cvA32_S_DATA
Custom Size register channel broadcast address modifier (Write only).
#define CVT_V1724_BROAD_CH_ZSTH_AM cvA32_S_DATA
Zero suppression threshold register channel broadcast address modifier (Write only).
#define CVT_V1724_BROAD_ADC_CONF_AM cvA32_S_DATA
ADC configuration broadcast register address modifier (Write only).
#define CVT_V1724_ACQ_CONTROL_AM cvA32_S_DATA
Acquisiton Control register address modifier.
#define CVT_V1724_ACQ_STATUS_AM cvA32_S_DATA
Acquisiton Status register address modifier.
#define CVT_V1724_SW_TRIGGER_AM cvA32_S_DATA
Software trigger register address modifier.
#define CVT_V1724_TRIGGER_SRC_ENABLE_AM cvA32_S_DATA
Trigger source enable register address modifier.
#define CVT_V1724_FP_TRIGGER_OUT_ENABLE_AM cvA32_S_DATA
Front panel trigger out enable mask register address modifier.
#define CVT_V1724_POST_TRIG_AM cvA32_S_DATA
Post trigger register address modifier.
#define CVT_V1724_FRONT_PANEL_IO_AM cvA32_S_DATA
Front panel IO register address modifier.
#define CVT_V1724_FRONT_PANEL_IO_CTRL_AM cvA32_S_DATA
Front panel IO Control register address modifier.
#define CVT_V1724_CH_ENABLE_AM cvA32_S_DATA
Channel enable mask register address modifier.
#define CVT_V1724_FW_REV_AM cvA32_S_DATA
Firmware Revision register address modifier.
#define CVT_V1724_DOWNSAMPLE_FACT_AM cvA32_S_DATA
DownSample factor register address modifier.
#define CVT_V1724_EVENT_STORED_AM cvA32_S_DATA
Event stored register address modifier.
#define CVT_V1724_MON_SET_AM cvA32_S_DATA
Monitor output set register address modifier.
#define CVT_V1724_SW_SYNC_AM cvA32_S_DATA
Sw sync register address modifier.
#define CVT_V1724_BOARD_INFO_AM cvA32_S_DATA
Board's information register address modifier.
#define CVT_V1724_MON_MODE_AM cvA32_S_DATA
Monitor output mode register address modifier.
#define CVT_V1724_TEST_IO_AM cvA32_S_DATA
I/O Test register address modifier.
#define CVT_V1724_VME_CONTROL_AM cvA32_S_DATA
VME Control register address modifier.
#define CVT_V1724_VME_STATUS_AM cvA32_S_DATA
VME Status register address modifier.
#define CVT_V1724_BOARD_ID_AM cvA32_S_DATA
Geo Address register address modifier.
#define CVT_V1724_MCST_CBLT_ADD_CTRL_AM cvA32_S_DATA
MCST/CBLT Address and control register address modifier.
#define CVT_V1724_RELOCATION_ADDRESS_AM cvA32_S_DATA
Relocation address register address modifier.
#define CVT_V1724_INT_STATUS_ID_AM cvA32_S_DATA
Interrupt status id register address modifier.
#define CVT_V1724_INT_EVENT_NUM_AM cvA32_S_DATA
Interrupt event number register address modifier.
#define CVT_V1724_BLT_EVENT_NUM_AM cvA32_S_DATA
BLT event number register address modifier.
#define CVT_V1724_SCRATCH_AM cvA32_S_DATA
Scratch register address modifier.
#define CVT_V1724_SW_RESET_AM cvA32_S_DATA
Software reset register address modifier.
#define CVT_V1724_SW_CLEAR_AM cvA32_S_DATA
Software clear register address modifier.
#define CVT_V1724_FLASH_EN_AM cvA32_S_DATA
Flash enable address modifier.
#define CVT_V1724_FLASH_DATA_AM cvA32_S_DATA
Flash data address modifier.
#define CVT_V1724_RELOAD_CONFIG_AM cvA32_S_DATA
Configuration Reload address modifier.
#define CVT_V1724_BASE_ADDRESS_AM cvA32_S_DATA
Base Address address modifier.
#define CVT_V1724_ROM_CHKSUM_AM cvA32_S_DATA
Configuration ROM checksum address modifier.
#define CVT_V1724_ROM_CHKSUM_LEN_2_AM cvA32_S_DATA
Configuration ROM checksum length (MSB) address modifier.
#define CVT_V1724_ROM_CHKSUM_LEN_1_AM cvA32_S_DATA
Configuration ROM checksum length address modifier.
#define CVT_V1724_ROM_CHKSUM_LEN_0_AM cvA32_S_DATA
Configuration ROM checksum length (LSB) address modifier.
#define CVT_V1724_ROM_CONST_2_AM cvA32_S_DATA
Configuration ROM constant (MSB) address modifier.
#define CVT_V1724_ROM_CONST_1_AM cvA32_S_DATA
Configuration ROM constant address modifier.
#define CVT_V1724_ROM_CONST_0_AM cvA32_S_DATA
Configuration ROM constant (LSB) address modifier.
#define CVT_V1724_ROM_C_CODE_AM cvA32_S_DATA
Configuration ROM c_code address modifier.
#define CVT_V1724_ROM_R_CODE_AM cvA32_S_DATA
Configuration ROM r_code address modifier.
#define CVT_V1724_ROM_OUI_2_AM cvA32_S_DATA
Configuration ROM Manufacturer identifier (IEEE OUI) (MSB) address modifier.
#define CVT_V1724_ROM_OUI_1_AM cvA32_S_DATA
Configuration ROM Manufacturer identifier (IEEE OUI) address modifier.
#define CVT_V1724_ROM_OUI_0_AM cvA32_S_DATA
Configuration ROM Manufacturer identifier (IEEE OUI) (LSB) address modifier.
#define CVT_V1724_ROM_VERSION_AM cvA32_S_DATA
Configuration ROM Purchased version of the Mod.V1724 address modifier.
#define CVT_V1724_ROM_BOARD_ID_2_AM cvA32_S_DATA
Configuration ROM Board identifier (MSB) address modifier.
#define CVT_V1724_ROM_BOARD_ID_1_AM cvA32_S_DATA
Configuration ROM Board identifier address modifier.
#define CVT_V1724_ROM_BOARD_ID_0_AM cvA32_S_DATA
Configuration ROM Board identifier (LSB) address modifier.
#define CVT_V1724_ROM_REVISION_3_AM cvA32_S_DATA
Configuration ROM Hardware revision identifier address modifier.
#define CVT_V1724_ROM_REVISION_2_AM cvA32_S_DATA
Configuration ROM Hardware revision identifier address modifier.
#define CVT_V1724_ROM_REVISION_1_AM cvA32_S_DATA
Configuration ROM Hardware revision identifier address modifier.
#define CVT_V1724_ROM_REVISION_0_AM cvA32_S_DATA
Configuration ROM Hardware revision identifier address modifier.
#define CVT_V1724_ROM_SERIAL_1_AM cvA32_S_DATA
Configuration ROM Serial number (MSB) address modifier.
#define CVT_V1724_ROM_SERIAL_0_AM cvA32_S_DATA
Configuration ROM Serial number (LSB) address modifier.
#define CVT_V1724_ROM_VCXO_TYPE_AM cvA32_S_DATA
Configuration ROM VCXO type address modifier.
#define CVT_V1724_CH0_RESERVED_RND_ACC_AM cvA32_S_DATA
CH 0 Read Block channel broadcast reserved register address modifier.
#define CVT_V1724_CH0_ZSTH_AM cvA32_S_DATA
CH 0 Zero suppression threshold register address modifier.
#define CVT_V1724_CH0_THRESHOLD_AM cvA32_S_DATA
CH 0 Threshold register address modifier.
#define CVT_V1724_CH0_TIME_OVER_UNDER_THR_AM cvA32_S_DATA
CH 0 Over/Under Threshold Samples register address modifier.
#define CVT_V1724_CH0_STATUS_AM cvA32_S_DATA
CH 0 status register address modifier.
#define CVT_V1724_CH0_FW_REV_AM cvA32_S_DATA
CH 0 firmware revision register address modifier.
#define CVT_V1724_CH0_BUFF_OCCUPANCY_AM cvA32_S_DATA
CH 0 Number of Buffers Filled register address modifier.
#define CVT_V1724_CH0_DAC_CONF_AM cvA32_S_DATA
CH 0 DAC Data Configuration register address modifier.
#define CVT_V1724_CH0_ADC_CONF_AM cvA32_S_DATA
CH 0 Configuration register address modifier.
#define CVT_V1724_CH0_RESERVED_ADC_DEBUG_AM cvA32_S_DATA
CH 0 ADC Debug Reserved register address modifier.
#define CVT_V1724_CH0_RESERVED_MEM_DATA_AM cvA32_S_DATA
CH 0 Memory test data Reserved register address modifier.
#define CVT_V1724_CH0_RESERVED_MEM_ADDRESS_AM cvA32_S_DATA
CH 0 Memory test address Reserved register address modifier.
#define CVT_V1724_CH1_RESERVED_RND_ACC_AM cvA32_S_DATA
CH 1 Read Block channel broadcast reserved register address modifier.
#define CVT_V1724_CH1_ZSTH_AM cvA32_S_DATA
CH 1 Zero suppression threshold register address modifier.
#define CVT_V1724_CH1_THRESHOLD_AM cvA32_S_DATA
CH 1 Threshold register address modifier.
#define CVT_V1724_CH1_TIME_OVER_UNDER_THR_AM cvA32_S_DATA
CH 1 Over/Under Threshold Samples register address modifier.
#define CVT_V1724_CH1_STATUS_AM cvA32_S_DATA
CH 1 status register address modifier.
#define CVT_V1724_CH1_FW_REV_AM cvA32_S_DATA
CH 1 firmware revision register address modifier.
#define CVT_V1724_CH1_BUFF_OCCUPANCY_AM cvA32_S_DATA
CH 1 Number of Buffers Filled register address modifier.
#define CVT_V1724_CH1_DAC_CONF_AM cvA32_S_DATA
CH 1 DAC Data Configuration register address modifier.
#define CVT_V1724_CH1_ADC_CONF_AM cvA32_S_DATA
CH 1 Configuration register address modifier.
#define CVT_V1724_CH1_RESERVED_ADC_DEBUG_AM cvA32_S_DATA
CH 1 ADC Debug Reserved register address modifier.
#define CVT_V1724_CH1_RESERVED_MEM_DATA_AM cvA32_S_DATA
CH 1 Memory test data Reserved register address modifier.
#define CVT_V1724_CH1_RESERVED_MEM_ADDRESS_AM cvA32_S_DATA
CH 1 Memory test address Reserved register address modifier.
#define CVT_V1724_CH2_RESERVED_RND_ACC_AM cvA32_S_DATA
CH 2 Read Block channel broadcast reserved register address modifier.
#define CVT_V1724_CH2_ZSTH_AM cvA32_S_DATA
CH 2 Zero suppression threshold register address modifier.
#define CVT_V1724_CH2_THRESHOLD_AM cvA32_S_DATA
CH 2 Threshold register address modifier.
#define CVT_V1724_CH2_TIME_OVER_UNDER_THR_AM cvA32_S_DATA
CH 2 Over/Under Threshold Samples register address modifier.
#define CVT_V1724_CH2_STATUS_AM cvA32_S_DATA
CH 2 status register address modifier.
#define CVT_V1724_CH2_FW_REV_AM cvA32_S_DATA
CH 2 firmware revision register address modifier.
#define CVT_V1724_CH2_BUFF_OCCUPANCY_AM cvA32_S_DATA
CH 2 Number of Buffers Filled register address modifier.
#define CVT_V1724_CH2_DAC_CONF_AM cvA32_S_DATA
CH 2 DAC Data Configuration register address modifier.
#define CVT_V1724_CH2_ADC_CONF_AM cvA32_S_DATA
CH 2 Configuration register address modifier.
#define CVT_V1724_CH2_RESERVED_ADC_DEBUG_AM cvA32_S_DATA
CH 2 ADC Debug Reserved register address modifier.
#define CVT_V1724_CH2_RESERVED_MEM_DATA_AM cvA32_S_DATA
CH 2 Memory test data Reserved register address modifier.
#define CVT_V1724_CH2_RESERVED_MEM_ADDRESS_AM cvA32_S_DATA
CH 2 Memory test address Reserved register address modifier.
#define CVT_V1724_CH3_RESERVED_RND_ACC_AM cvA32_S_DATA
CH 3 Read Block channel broadcast reserved register address modifier.
#define CVT_V1724_CH3_ZSTH_AM cvA32_S_DATA
CH 3 Zero suppression threshold register address modifier.
#define CVT_V1724_CH3_THRESHOLD_AM cvA32_S_DATA
CH 3 Threshold register address modifier.
#define CVT_V1724_CH3_TIME_OVER_UNDER_THR_AM cvA32_S_DATA
CH 3 Over/Under Threshold Samples register address modifier.
#define CVT_V1724_CH3_STATUS_AM cvA32_S_DATA
CH 3 status register address modifier.
#define CVT_V1724_CH3_FW_REV_AM cvA32_S_DATA
CH 3 firmware revision register address modifier.
#define CVT_V1724_CH3_BUFF_OCCUPANCY_AM cvA32_S_DATA
CH 3 Number of Buffers Filled register address modifier.
#define CVT_V1724_CH3_DAC_CONF_AM cvA32_S_DATA
CH 3 DAC Data Configuration register address modifier.
#define CVT_V1724_CH3_ADC_CONF_AM cvA32_S_DATA
CH 3 Configuration register address modifier.
#define CVT_V1724_CH3_RESERVED_ADC_DEBUG_AM cvA32_S_DATA
CH 3 ADC Debug Reserved register address modifier.
#define CVT_V1724_CH3_RESERVED_MEM_DATA_AM cvA32_S_DATA
CH 3 Memory test data Reserved register address modifier.
#define CVT_V1724_CH3_RESERVED_MEM_ADDRESS_AM cvA32_S_DATA
CH 3 Memory test address Reserved register address modifier.
#define CVT_V1724_CH4_RESERVED_RND_ACC_AM cvA32_S_DATA
CH 4 Read Block channel broadcast reserved register address modifier.
#define CVT_V1724_CH4_ZSTH_AM cvA32_S_DATA
CH 4 Zero suppression threshold register address modifier.
#define CVT_V1724_CH4_THRESHOLD_AM cvA32_S_DATA
CH 4 Threshold register address modifier.
#define CVT_V1724_CH4_TIME_OVER_UNDER_THR_AM cvA32_S_DATA
CH 4 Over/Under Threshold Samples register address modifier.
#define CVT_V1724_CH4_STATUS_AM cvA32_S_DATA
CH 4 status register address modifier.
#define CVT_V1724_CH4_FW_REV_AM cvA32_S_DATA
CH 4 firmware revision register address modifier.
#define CVT_V1724_CH4_BUFF_OCCUPANCY_AM cvA32_S_DATA
CH 4 Number of Buffers Filled register address modifier.
#define CVT_V1724_CH4_DAC_CONF_AM cvA32_S_DATA
CH 4 DAC Data Configuration register address modifier.
#define CVT_V1724_CH4_ADC_CONF_AM cvA32_S_DATA
CH 4 Configuration register address modifier.
#define CVT_V1724_CH4_RESERVED_ADC_DEBUG_AM cvA32_S_DATA
CH 4 ADC Debug Reserved register address modifier.
#define CVT_V1724_CH4_RESERVED_MEM_DATA_AM cvA32_S_DATA
CH 4 Memory test data Reserved register address modifier.
#define CVT_V1724_CH4_RESERVED_MEM_ADDRESS_AM cvA32_S_DATA
CH 4 Memory test address Reserved register address modifier.
#define CVT_V1724_CH5_RESERVED_RND_ACC_AM cvA32_S_DATA
CH 5 Read Block channel broadcast reserved register address modifier.
#define CVT_V1724_CH5_ZSTH_AM cvA32_S_DATA
CH 5 Zero suppression threshold register address modifier.
#define CVT_V1724_CH5_THRESHOLD_AM cvA32_S_DATA
CH 5 Threshold register address modifier.
#define CVT_V1724_CH5_TIME_OVER_UNDER_THR_AM cvA32_S_DATA
CH 5 Over/Under Threshold Samples register address modifier.
#define CVT_V1724_CH5_STATUS_AM cvA32_S_DATA
CH 5 status register address modifier.
#define CVT_V1724_CH5_FW_REV_AM cvA32_S_DATA
CH 5 firmware revision register address modifier.
#define CVT_V1724_CH5_BUFF_OCCUPANCY_AM cvA32_S_DATA
CH 5 Number of Buffers Filled register address modifier.
#define CVT_V1724_CH5_DAC_CONF_AM cvA32_S_DATA
CH 5 DAC Data Configuration register address modifier.
#define CVT_V1724_CH5_ADC_CONF_AM cvA32_S_DATA
CH 5 Configuration register address modifier.
#define CVT_V1724_CH5_RESERVED_ADC_DEBUG_AM cvA32_S_DATA
CH 5 ADC Debug Reserved register address modifier.
#define CVT_V1724_CH5_RESERVED_MEM_DATA_AM cvA32_S_DATA
CH 5 Memory test data Reserved register address modifier.
#define CVT_V1724_CH5_RESERVED_MEM_ADDRESS_AM cvA32_S_DATA
CH 5 Memory test address Reserved register address modifier.
#define CVT_V1724_CH6_RESERVED_RND_ACC_AM cvA32_S_DATA
CH 6 Read Block channel broadcast reserved register address modifier.
#define CVT_V1724_CH6_ZSTH_AM cvA32_S_DATA
CH 6 Zero suppression threshold register address modifier.
#define CVT_V1724_CH6_THRESHOLD_AM cvA32_S_DATA
CH 6 Threshold register address modifier.
#define CVT_V1724_CH6_TIME_OVER_UNDER_THR_AM cvA32_S_DATA
CH 6 Over/Under Threshold Samples register address modifier.
#define CVT_V1724_CH6_STATUS_AM cvA32_S_DATA
CH 6 status register address modifier.
#define CVT_V1724_CH6_FW_REV_AM cvA32_S_DATA
CH 6 firmware revision register address modifier.
#define CVT_V1724_CH6_BUFF_OCCUPANCY_AM cvA32_S_DATA
CH 6 Number of Buffers Filled register address modifier.
#define CVT_V1724_CH6_DAC_CONF_AM cvA32_S_DATA
CH 6 DAC Data Configuration register address modifier.
#define CVT_V1724_CH6_ADC_CONF_AM cvA32_S_DATA
CH 6 Configuration register address modifier.
#define CVT_V1724_CH6_RESERVED_ADC_DEBUG_AM cvA32_S_DATA
CH 6 ADC Debug Reserved register address modifier.
#define CVT_V1724_CH6_RESERVED_MEM_DATA_AM cvA32_S_DATA
CH 6 Memory test data Reserved register address modifier.
#define CVT_V1724_CH6_RESERVED_MEM_ADDRESS_AM cvA32_S_DATA
CH 6 Memory test address Reserved register address modifier.
#define CVT_V1724_CH7_RESERVED_RND_ACC_AM cvA32_S_DATA
CH 7 Read Block channel broadcast reserved register address modifier.
#define CVT_V1724_CH7_ZSTH_AM cvA32_S_DATA
CH 7 Zero suppression threshold register address modifier.
#define CVT_V1724_CH7_THRESHOLD_AM cvA32_S_DATA
CH 7 Threshold register address modifier.
#define CVT_V1724_CH7_TIME_OVER_UNDER_THR_AM cvA32_S_DATA
CH 7 Over/Under Threshold Samples register address modifier.
#define CVT_V1724_CH7_STATUS_AM cvA32_S_DATA
CH 7 status register address modifier.
#define CVT_V1724_CH7_FW_REV_AM cvA32_S_DATA
CH 7 firmware revision register address modifier.
#define CVT_V1724_CH7_BUFF_OCCUPANCY_AM cvA32_S_DATA
CH 7 Number of Buffers Filled register address modifier.
#define CVT_V1724_CH7_DAC_CONF_AM cvA32_S_DATA
CH 7 DAC Data Configuration register address modifier.
#define CVT_V1724_CH7_ADC_CONF_AM cvA32_S_DATA
CH 7 Configuration register address modifier.
#define CVT_V1724_CH7_RESERVED_ADC_DEBUG_AM cvA32_S_DATA
CH 7 ADC Debug Reserved register address modifier.
#define CVT_V1724_CH7_RESERVED_MEM_DATA_AM cvA32_S_DATA
CH 7 Memory test data Reserved register address modifier.
#define CVT_V1724_CH7_RESERVED_MEM_ADDRESS_AM cvA32_S_DATA
CH 7 Memory test address Reserved register address modifier.
#define CVT_V1724_MAX_CHANNEL 8
The number of channels.
#define CVT_V1724_GET_INT_LEVEL(reg) (((UINT32)reg)& CVT_V1724_VME_CTRL_INT_LEVEL_MSK)
Extract the interrupt level from UINT32 value.
#define CVT_V1724_SET_INT_LEVEL(reg, value) reg= (((UINT32)reg)& ~CVT_V1724_VME_CTRL_INT_LEVEL_MSK)| ((UINT32)value& CVT_V1724_VME_CTRL_INT_LEVEL_MSK)
Sets the interrupt level value into UINT32 value.
#define CVT_V1724_GET_CH_RND_ACC_BLOCK_ADD(reg) (((UINT32)reg)& CVT_V1724_BROAD_CHRNDACC_BLOCK_ADD_MSK)
Extract the Address of Block to be read from UINT32 value.
#define CVT_V1724_SET_CH_RND_ACC_BLOCK_ADD(reg, value) reg= (((UINT32)reg)& ~CVT_V1724_BROAD_CHRNDACC_BLOCK_ADD_MSK)| ((UINT32)value& CVT_V1724_BROAD_CHRNDACC_BLOCK_ADD_MSK)
Sets the Address of Block to be read into UINT32 value.
#define CVT_V1724_GET_CH_RND_ACC_SAMPLE_NUM(reg) ((((UINT32)reg)& CVT_V1724_BROAD_CHRNDACC_SAMPLE_NUM_MSK)>> 10)
Extract the Number of samples to be read from UINT32 value.
#define CVT_V1724_SET_CH_RND_ACC_SAMPLE_NUM(reg, value) reg= (((UINT32)reg)& ~CVT_V1724_BROAD_CHRNDACC_SAMPLE_NUM_MSK)| ((((UINT32)value)<< 10)& CVT_V1724_BROAD_CHRNDACC_SAMPLE_NUM_MSK)
Sets the Number of samples to be read into UINT32 value.
#define CVT_V1724_GET_CH_RND_ACC_OFFSET(reg) ((((UINT32)reg)& CVT_V1724_BROAD_CHRNDACC_OFFSET_MSK)>> 22)
Extract the Offset of Address Data from UINT32 value.
#define CVT_V1724_SET_CH_RND_ACC_OFFSET(reg, value) reg= (((UINT32)reg)& ~CVT_V1724_BROAD_CHRNDACC_OFFSET_MSK)| ((((UINT32)value)<< 22)& CVT_V1724_BROAD_CHRNDACC_OFFSET_MSK)
Sets the Offset of Address Data into UINT32 value.
#define CVT_V1724_GET_BRDINF_ID(reg) (((UINT32)reg)& CVT_V1724_BRDINF_ID_MSK)
Extract the Board info ID from UINT32 value.
#define CVT_V1724_GET_BRDINF_BLOCK_SIZE_MUL(reg) ((((UINT32)reg)& CVT_V1724_BRDINF_CH_BLOCK_SIZE_MUL_MSK)>> 8)
Extract the channel block size multiplier from UINT32 value.
#define CVT_V1724_GET_BRDINF_BLOCK_SIZE_KW(reg) (((UINT32)reg)& CVT_V1724_BRDINF_CH_BLOCK_SIZE_MUL_MSK)
Extract the channel block size (as number of KWORD 32) from UINT32 value.
#define CVT_V1724_GET_ACQCTRL_ACQ_MODE(reg) (((UINT32)reg)& CVT_V1724_ACQCTRL_ACQ_MODE_MSK)
Extract the acquisition mode value from UINT32 value.
#define CVT_V1724_SET_ACQCTRL_ACQ_MODE(reg, value) reg= (((UINT32)reg)& ~CVT_V1724_ACQCTRL_ACQ_MODE_MSK)| ((UINT32)value& CVT_V1724_ACQCTRL_ACQ_MODE_MSK)
Sets the acquisition mode value into UINT32 value.
#define CVT_V1724_GET_FRONT_PANEL_IO(reg) (((UINT32)reg)& CVT_V1724_FPIO_MSK)
Extract front panel data from UINT32 value.
#define CVT_V1724_SET_FRONT_PANEL_IO(reg, value) reg= (((UINT32)reg)& ~CVT_V1724_FPIO_MSK)| ((UINT32)value& CVT_V1724_FPIO_MSK)
Sets front panel data into UINT32 value.
#define CVT_V1724_GET_FPIO_CTRL_DIR(reg) ((((UINT32)reg)& CVT_V1724_FPIO_CTRL_DIR_MSK)>> 2)
Extract the Front panel IO direction from UINT32 value.
#define CVT_V1724_SET_FPIO_CTRL_DIR(reg, value) reg= (((UINT32)reg)& ~CVT_V1724_FPIO_CTRL_DIR_MSK)| ((((UINT32)value)<< 2)& CVT_V1724_FPIO_CTRL_DIR_MSK)
Sets the Front panel IO direction into UINT32 value.
#define CVT_V1724_GET_FPIO_CTRL_MODE(reg) ((((UINT32)reg)& CVT_V1724_FPIO_CTRL_MODE_MSK)>> 6)
Extract the Front panel IO mode from UINT32 value.
#define CVT_V1724_SET_FPIO_CTRL_MODE(reg, value) reg= (((UINT32)reg)& ~CVT_V1724_FPIO_CTRL_MODE_MSK)| ((((UINT32)value)<< 6)& CVT_V1724_FPIO_CTRL_MODE_MSK)
Sets the Front panel IO mode into UINT32 value.
#define CVT_V1724_GET_CH_DAC_CONF(reg) (((UINT32)reg)& CVT_V1724_CHDAC_DATA_MSK)
Extract DAC's data from UINT32 value.
#define CVT_V1724_SET_CH_DAC_CONF(reg, value) reg= (((UINT32)reg)& ~CVT_V1724_CHDAC_DATA_MSK)| ((UINT32)value& CVT_V1724_CHDAC_DATA_MSK)
Sets DAC's data into UINT32 value.
#define CVT_V1724_GET_MCST_CBLT_ADD(reg) (((UINT32)reg)& CVT_V1724_MCST_CBLT_ADD_MSK)
Extract the Base Address of from UINT32 value.
#define CVT_V1724_SET_MCST_CBLT_ADD(reg, value) reg= (((UINT32)reg)& ~CVT_V1724_MCST_CBLT_ADD_MSK)| ((UINT32)value& CVT_V1724_MCST_CBLT_ADD_MSK)
Sets the Base Address into UINT32 value.
#define CVT_V1724_GET_MCST_CBLT_CTRL(reg) ((((UINT32)reg)& CVT_V1724_MCST_CBLT_CTRL_MSK)>> 8)
Extract the MCST-CBLT Control from UINT32 value.
#define CVT_V1724_SET_MCST_CBLT_CTRL(reg, value) reg= (((UINT32)reg)& ~CVT_V1724_MCST_CBLT_CTRL_MSK)| ((((UINT32)value)<< 8)& CVT_V1724_MCST_CBLT_CTRL_MSK)
Sets MCST-CBLT Control into UINT32 value.
#define V1724_FLASH_PAGE_SIZE 264
#define CVT_V1724_MIN_FIRMARE_REV 0x0002
#define V1724_HEADER_TAG_MSK 0xA0000000
The V1724 Header tag msk.
#define CVT_V1724_IS_HEADER_TAG(data_0) ((data_0& 0xF0000000)== V1724_HEADER_TAG_MSK)
Checks if type is header tag.
#define CVT_V1724_GET_EVENT_TAG(data_0) ((UINT32)((((UINT32)data_0)>>28)& 0x0000000f))
Gets the tag of this event.
#define CVT_V1724_GET_EVENT_SIZE(data_0) ((UINT32)(((UINT32)data_0)& 0x0fffffff))
Gets the size of this event.
#define CVT_V1724_GET_EVENT_ACTIVE_CHANNELS(data_1) ((UINT32)(((UINT32)data_1)& 0x000000ff))
Gets the active channel mask of this event.
#define CVT_V1724_GET_EVENT_BOARD_ID(data_1) ((UINT32)((((UINT32)data_1)>>27)& 0x0000001f))
Gets the board id of this event.
#define CVT_V1724_GET_EVENT_COUNT(data_2) ((UINT32)(((UINT32)data_2)& 0x00ffffff))
Gets the counter of this event.
#define CVT_V1724_GET_EVENT_TRIGGER_TIME_TAG(data_3) ((UINT32)(((UINT32)data_3)& 0xffffffff))
Gets the Trigger time tag of this event.
#define PACKED_1
#define _INLINE_
#define CVT_V1724_MAX_BLT_EVENT_NUM 4
The maximum number of blt_event per readout cycle.
Typedefs
typedef union PACKED_1 CVT_V1724_HEADER
Enumerations
enum CVT_V17XX_TYPES {
CVT_V1724 = 0, CVT_V1721, CVT_V1731, CVT_V1720,
CVT_V1740, CVT_V1751
}
The V17XX board type.
enum CVT_V1724_REG_INDEX {
CVT_V1724_OUT_BUFFER_INDEX, CVT_V1724_BROAD_CH_CTRL_INDEX, CVT_V1724_BROAD_CH_SET_CTRL_INDEX, CVT_V1724_BROAD_CH_CLEAR_CTRL_INDEX,
CVT_V1724_BROAD_NUM_BLOCK_INDEX, CVT_V1724_BROAD_CH_BUFF_FLUSH_INDEX, CVT_V1724_BROAD_CH_RND_ACC_INDEX, CVT_V1724_BROAD_CH_CUSSIZE_INDEX,
CVT_V1724_BROAD_CH_ZSTH_INDEX, CVT_V1724_BROAD_ADC_CONF_INDEX, CVT_V1724_ACQ_CONTROL_INDEX, CVT_V1724_ACQ_STATUS_INDEX,
CVT_V1724_SW_TRIGGER_INDEX, CVT_V1724_TRIGGER_SRC_ENABLE_INDEX, CVT_V1724_FP_TRIGGER_OUT_ENABLE_INDEX, CVT_V1724_POST_TRIG_INDEX,
CVT_V1724_FRONT_PANEL_IO_INDEX, CVT_V1724_FRONT_PANEL_IO_CTRL_INDEX, CVT_V1724_CH_ENABLE_INDEX, CVT_V1724_FW_REV_INDEX,
CVT_V1724_DOWNSAMPLE_FACT_INDEX, CVT_V1724_EVENT_STORED_INDEX, CVT_V1724_MON_SET_INDEX, CVT_V1724_SW_SYNC_INDEX,
CVT_V1724_BOARD_INFO_INDEX, CVT_V1724_MON_MODE_INDEX, CVT_V1724_TEST_IO_INDEX, CVT_V1724_VME_CONTROL_INDEX,
CVT_V1724_VME_STATUS_INDEX, CVT_V1724_BOARD_ID_INDEX, CVT_V1724_MCST_CBLT_ADD_CTRL_INDEX, CVT_V1724_RELOCATION_ADDRESS_INDEX,
CVT_V1724_INT_STATUS_ID_INDEX, CVT_V1724_INT_EVENT_NUM_INDEX, CVT_V1724_BLT_EVENT_NUM_INDEX, CVT_V1724_SCRATCH_INDEX,
CVT_V1724_SW_RESET_INDEX, CVT_V1724_SW_CLEAR_INDEX, CVT_V1724_FLASH_EN_INDEX, CVT_V1724_FLASH_DATA_INDEX,
CVT_V1724_RELOAD_CONFIG_INDEX, CVT_V1724_BASE_ADDRESS_INDEX, CVT_V1724_ROM_CHKSUM_INDEX, CVT_V1724_ROM_CHKSUM_LEN_2_INDEX,
CVT_V1724_ROM_CHKSUM_LEN_1_INDEX, CVT_V1724_ROM_CHKSUM_LEN_0_INDEX, CVT_V1724_ROM_CONST_2_INDEX, CVT_V1724_ROM_CONST_1_INDEX,
CVT_V1724_ROM_CONST_0_INDEX, CVT_V1724_ROM_C_CODE_INDEX, CVT_V1724_ROM_R_CODE_INDEX, CVT_V1724_ROM_OUI_2_INDEX,
CVT_V1724_ROM_OUI_1_INDEX, CVT_V1724_ROM_OUI_0_INDEX, CVT_V1724_ROM_VERSION_INDEX, CVT_V1724_ROM_BOARD_ID_2_INDEX,
CVT_V1724_ROM_BOARD_ID_1_INDEX, CVT_V1724_ROM_BOARD_ID_0_INDEX, CVT_V1724_ROM_REVISION_3_INDEX, CVT_V1724_ROM_REVISION_2_INDEX,
CVT_V1724_ROM_REVISION_1_INDEX, CVT_V1724_ROM_REVISION_0_INDEX, CVT_V1724_ROM_SERIAL_1_INDEX, CVT_V1724_ROM_SERIAL_0_INDEX,
CVT_V1724_ROM_VCXO_TYPE_INDEX, CVT_V1724_CH0_RESERVED_RND_ACC_INDEX, CVT_V1724_CH0_ZSTH_INDEX, CVT_V1724_CH0_THRESHOLD_INDEX,
CVT_V1724_CH0_TIME_OVER_UNDER_THR_INDEX, CVT_V1724_CH0_STATUS_INDEX, CVT_V1724_CH0_FW_REV_INDEX, CVT_V1724_CH0_BUFF_OCCUPANCY_INDEX,
CVT_V1724_CH0_DAC_CONF_INDEX, CVT_V1724_CH0_ADC_CONF_INDEX, CVT_V1724_CH0_RESERVED_ADC_DEBUG_INDEX, CVT_V1724_CH0_RESERVED_MEM_DATA_INDEX,
CVT_V1724_CH0_RESERVED_MEM_ADDRESS_INDEX, CVT_V1724_CH1_RESERVED_RND_ACC_INDEX, CVT_V1724_CH1_ZSTH_INDEX, CVT_V1724_CH1_THRESHOLD_INDEX,
CVT_V1724_CH1_TIME_OVER_UNDER_THR_INDEX, CVT_V1724_CH1_STATUS_INDEX, CVT_V1724_CH1_FW_REV_INDEX, CVT_V1724_CH1_BUFF_OCCUPANCY_INDEX,
CVT_V1724_CH1_DAC_CONF_INDEX, CVT_V1724_CH1_ADC_CONF_INDEX, CVT_V1724_CH1_RESERVED_ADC_DEBUG_INDEX, CVT_V1724_CH1_RESERVED_MEM_DATA_INDEX,
CVT_V1724_CH1_RESERVED_MEM_ADDRESS_INDEX, CVT_V1724_CH2_RESERVED_RND_ACC_INDEX, CVT_V1724_CH2_ZSTH_INDEX, CVT_V1724_CH2_THRESHOLD_INDEX,
CVT_V1724_CH2_TIME_OVER_UNDER_THR_INDEX, CVT_V1724_CH2_STATUS_INDEX, CVT_V1724_CH2_FW_REV_INDEX, CVT_V1724_CH2_BUFF_OCCUPANCY_INDEX,
CVT_V1724_CH2_DAC_CONF_INDEX, CVT_V1724_CH2_ADC_CONF_INDEX, CVT_V1724_CH2_RESERVED_ADC_DEBUG_INDEX, CVT_V1724_CH2_RESERVED_MEM_DATA_INDEX,
CVT_V1724_CH2_RESERVED_MEM_ADDRESS_INDEX, CVT_V1724_CH3_RESERVED_RND_ACC_INDEX, CVT_V1724_CH3_ZSTH_INDEX, CVT_V1724_CH3_THRESHOLD_INDEX,
CVT_V1724_CH3_TIME_OVER_UNDER_THR_INDEX, CVT_V1724_CH3_STATUS_INDEX, CVT_V1724_CH3_FW_REV_INDEX, CVT_V1724_CH3_BUFF_OCCUPANCY_INDEX,
CVT_V1724_CH3_DAC_CONF_INDEX, CVT_V1724_CH3_ADC_CONF_INDEX, CVT_V1724_CH3_RESERVED_ADC_DEBUG_INDEX, CVT_V1724_CH3_RESERVED_MEM_DATA_INDEX,
CVT_V1724_CH3_RESERVED_MEM_ADDRESS_INDEX, CVT_V1724_CH4_RESERVED_RND_ACC_INDEX, CVT_V1724_CH4_ZSTH_INDEX, CVT_V1724_CH4_THRESHOLD_INDEX,
CVT_V1724_CH4_TIME_OVER_UNDER_THR_INDEX, CVT_V1724_CH4_STATUS_INDEX, CVT_V1724_CH4_FW_REV_INDEX, CVT_V1724_CH4_BUFF_OCCUPANCY_INDEX,
CVT_V1724_CH4_DAC_CONF_INDEX, CVT_V1724_CH4_ADC_CONF_INDEX, CVT_V1724_CH4_RESERVED_ADC_DEBUG_INDEX, CVT_V1724_CH4_RESERVED_MEM_DATA_INDEX,
CVT_V1724_CH4_RESERVED_MEM_ADDRESS_INDEX, CVT_V1724_CH5_RESERVED_RND_ACC_INDEX, CVT_V1724_CH5_ZSTH_INDEX, CVT_V1724_CH5_THRESHOLD_INDEX,
CVT_V1724_CH5_TIME_OVER_UNDER_THR_INDEX, CVT_V1724_CH5_STATUS_INDEX, CVT_V1724_CH5_FW_REV_INDEX, CVT_V1724_CH5_BUFF_OCCUPANCY_INDEX,
CVT_V1724_CH5_DAC_CONF_INDEX, CVT_V1724_CH5_ADC_CONF_INDEX, CVT_V1724_CH5_RESERVED_ADC_DEBUG_INDEX, CVT_V1724_CH5_RESERVED_MEM_DATA_INDEX,
CVT_V1724_CH5_RESERVED_MEM_ADDRESS_INDEX, CVT_V1724_CH6_RESERVED_RND_ACC_INDEX, CVT_V1724_CH6_ZSTH_INDEX, CVT_V1724_CH6_THRESHOLD_INDEX,
CVT_V1724_CH6_TIME_OVER_UNDER_THR_INDEX, CVT_V1724_CH6_STATUS_INDEX, CVT_V1724_CH6_FW_REV_INDEX, CVT_V1724_CH6_BUFF_OCCUPANCY_INDEX,
CVT_V1724_CH6_DAC_CONF_INDEX, CVT_V1724_CH6_ADC_CONF_INDEX, CVT_V1724_CH6_RESERVED_ADC_DEBUG_INDEX, CVT_V1724_CH6_RESERVED_MEM_DATA_INDEX,
CVT_V1724_CH6_RESERVED_MEM_ADDRESS_INDEX, CVT_V1724_CH7_RESERVED_RND_ACC_INDEX, CVT_V1724_CH7_ZSTH_INDEX, CVT_V1724_CH7_THRESHOLD_INDEX,
CVT_V1724_CH7_TIME_OVER_UNDER_THR_INDEX, CVT_V1724_CH7_STATUS_INDEX, CVT_V1724_CH7_FW_REV_INDEX, CVT_V1724_CH7_BUFF_OCCUPANCY_INDEX,
CVT_V1724_CH7_DAC_CONF_INDEX, CVT_V1724_CH7_ADC_CONF_INDEX, CVT_V1724_CH7_RESERVED_ADC_DEBUG_INDEX, CVT_V1724_CH7_RESERVED_MEM_DATA_INDEX,
CVT_V1724_CH7_RESERVED_MEM_ADDRESS_INDEX, CVT_V1724_LAST_INDEX
}
The registers indexes.
enum CVT_V1724_VME_CONTROL_MSK { CVT_V1724_VME_CTRL_INT_LEVEL_MSK = 0x0007, CVT_V1724_VME_CTRL_BERR_ENABLE_MSK = 0x0010, CVT_V1724_VME_CTRL_ALIGN64_MSK = 0x0020, CVT_V1724_VME_CTRL_RELOC_MSK = 0x0040 }
Control register bitmasks.
enum CVT_V1724_VME_STATUS_MSK { CVT_V1724_VME_STS_DATA_READY_MSK = 0x0001, CVT_V1724_VME_STS_FULL_MSK = 0x0002, CVT_V1724_VME_STS_BERR_FLAG_MSK = 0x0004, CVT_V1724_VME_STS_PURGED_MSK = 0x0008 }
Status register bitmasks.
enum CVT_V1724_TRIGGER_SRC_ENABLE_MSK {
CVT_V1724_TRGEN_CH0_MSK = 0x00000001, CVT_V1724_TRGEN_CH1_MSK = 0x00000002, CVT_V1724_TRGEN_CH2_MSK = 0x00000004, CVT_V1724_TRGEN_CH3_MSK = 0x00000008,
CVT_V1724_TRGEN_CH4_MSK = 0x00000010, CVT_V1724_TRGEN_CH5_MSK = 0x00000020, CVT_V1724_TRGEN_CH6_MSK = 0x00000040, CVT_V1724_TRGEN_CH7_MSK = 0x00000080,
CVT_V1724_TRGEN_EXT_MSK = 0x40000000, CVT_V1724_TRGEN_SW_MSK = 0x80000000
}
Trigger enable bitmasks.
enum CVT_V1724_FP_TRIGGER_OUT_ENABLE_MSK {
CVT_V1724_FPTRGEN_CH0_MSK = 0x00000001, CVT_V1724_FPTRGEN_CH1_MSK = 0x00000002, CVT_V1724_FPTRGEN_CH2_MSK = 0x00000004, CVT_V1724_FPTRGEN_CH3_MSK = 0x00000008,
CVT_V1724_FPTRGEN_CH4_MSK = 0x00000010, CVT_V1724_FPTRGEN_CH5_MSK = 0x00000020, CVT_V1724_FPTRGEN_CH6_MSK = 0x00000040, CVT_V1724_FPTRGEN_CH7_MSK = 0x00000080,
CVT_V1724_FPTRGEN_EXT_MSK = 0x40000000, CVT_V1724_FPTRGEN_SW_MSK = 0x80000000
}
Front Panel Trigger Out enable bitmasks.
enum CVT_V1724_BROAD_CH_CONTROL_MSK {
CVT_V1724_BROAD_CHCTRL_GATE_MODE_MSK = 0x00000001, CVT_V1724_BROAD_CHCTRL_TRG_OVERLAP_MSK = 0x00000002, CVT_V1724_BROAD_CHCTRL_MEM_TEST_ENABLE_MSK = 0x00000008, CVT_V1724_BROAD_CHCTRL_MEM_ACC_MODE_MSK = 0x00000010,
CVT_V1724_BROAD_CHCTRL_TRG_OUT_THR_MSK = 0x00000040, CVT_V1724_BROAD_CHCTRL_DES_MODE_MSK = 0x00001000
}
CVT_V1724_BROAD_CH_CTRL: Control register bitmasks.
enum CVT_V1724_BROAD_CH_RND_ACC_MSK { CVT_V1724_BROAD_CHRNDACC_BLOCK_ADD_MSK = 0x000003FF, CVT_V1724_BROAD_CHRNDACC_SAMPLE_NUM_MSK = 0x003FFC00, CVT_V1724_BROAD_CHRNDACC_OFFSET_MSK = 0xFFC00000 }
CVT_V1724_BROAD_CH_RND_ACC register bitmasks.
enum CVT_V1724_BOARD_INFO_MSK { CVT_V1724_BRDINF_ID_MSK = 0x000000ff, CVT_V1724_BRDINF_CH_BLOCK_SIZE_MUL_MSK = 0x0000ff00 }
CVT_V1724_BOARD_INFO register bitmasks.
enum CVT_V1724_ACQ_CONTROL_MSK { CVT_V1724_ACQCTRL_ACQ_MODE_MSK = 0x00000003, CVT_V1724_ACQCTRL_START_MSK = 0x00000004, CVT_V1724_ACQCTRL_EVENT_COUNTER_ALL_MSK = 0x00000008, CVT_V1724_ACQCTRL_DOWNSAMPLE_MSK = 0x00000010 }
CVT_V1724_ACQ_CONTROL register bitmasks.
enum CVT_V1724_ACQ_CONTROL_ACQ_MODES { CVT_V1724_ACQCTRL_ACQ_MODE_REGISTER_CTRL = 0, CVT_V1724_ACQCTRL_ACQ_MODE_S_IN_CTRL = 1, CVT_V1724_ACQCTRL_ACQ_MODE_S_IN_GATE = 2, CVT_V1724_ACQCTRL_ACQ_MODE_MULTIBOARD_SYNC = 3 }
CVT_V1724_ACQ_CONTROL_MSK acquisition modes.
enum CVT_V1724_ACQ_STATUS_MSK {
CVT_V1724_ACQSTS_MEB_NOT_EMPTY_MSK = 0x00000001, CVT_V1724_ACQSTS_MEB_FULL_MSK = 0x00000002, CVT_V1724_ACQSTS_RUN_MSK = 0x00000004, CVT_V1724_ACQSTS_EVENT_RDY_MSK = 0x00000008,
CVT_V1724_ACQSTS_EVENT_FULL_MSK = 0x00000010, CVT_V1724_ACQSTS_CLKEXT_MSK = 0x00000020, CVT_V1724_ACQSTS_PLL_BYPASS_MSK = 0x00000040, CVT_V1724_ACQSTS_PLL_STATUS_MSK = 0x00000080,
CVT_V1724_ACQSTS_S_IN_MSK = 0x00008000
}
CVT_V1724_ACQ_STATUS register bitmasks.
enum CVT_V1724_CH_ENABLE_MSK {
CVT_V1724_CHEN_CH0_MSK = 0x0001, CVT_V1724_CHEN_CH1_MSK = 0x0002, CVT_V1724_CHEN_CH2_MSK = 0x0004, CVT_V1724_CHEN_CH3_MSK = 0x0008,
CVT_V1724_CHEN_CH4_MSK = 0x0010, CVT_V1724_CHEN_CH5_MSK = 0x0020, CVT_V1724_CHEN_CH6_MSK = 0x0040, CVT_V1724_CHEN_CH7_MSK = 0x0080
}
CVT_V1724_CH_ENABLE register bitmasks.
enum CVT_V1724_CH_ADC_CONF_MSK { CVT_V1724_CHADCCONF_DITHER_MSK = 0x00000001, CVT_V1724_CHADCCONF_CLK_DUTY_STAB_MSK = 0x00000002, CVT_V1724_CHADCCONF_RND_MSK = 0x00000004 }
ADC CH Configuration register bitmasks for V1724/V1720 only.
enum CVT_V1724_CH_ADC_CONF_MSK_2 { CVT_V1724_CHADCCONF_CAL_MSK_2 = 0x00000002 }
ADC CH Configuration register bitmasks for V1731/V1721 only.
enum CVT_V1724_FRONT_PANEL_IO_MSK { CVT_V1724_FPIO_MSK = 0x0000FFFF }
Front Panel IO data register bitmasks.
enum CVT_V1724_FRONT_PANEL_IO_CTRL_MSK { CVT_V1724_FPIO_CTRL_TTL_MSK = 0x00000001, CVT_V1724_FPIO_CTRL_OUT_DIS_MSK = 0x00000002, CVT_V1724_FPIO_CTRL_DIR_MSK = 0x0000003C, CVT_V1724_FPIO_CTRL_MODE_MSK = 0x000000C0 }
Front Panel IO control register bitmasks.
enum CVT_V1724_FRONT_PANEL_IO_MODES { CVT_V1724_FPIO_MODES_GPIO = 0, CVT_V1724_FPIO_MODES_PROGIO = 1, CVT_V1724_FPIO_MODES_PATTERN = 2 }
Front Panel IO modes.
enum CVT_V1724_DAC_CONF_MSK { CVT_V1724_CHDAC_DATA_MSK = 0x0000FFFF, CVT_V1724_CHDAC_SET_A_MSK = 0x00100000, CVT_V1724_CHDAC_SET_B_MSK = 0x00240000 }
CH DAC data configuration register bitmasks.
enum CVT_V1724_CH_STATUS_MSK {
CVT_V1724_CHSTS_FIFO_FULL_MSK = 0x00000001, CVT_V1724_CHSTS_FIFO_EMPTY_MSK = 0x00000002, CVT_V1724_CHSTS_DAC_BUSY_MSK = 0x00000004, CVT_V1724_CHSTS_BIST_END_MSK = 0x00000008,
CVT_V1724_CHSTS_BIST_OK_MSK = 0x00000010, CVT_V1724_CHSTS_BLOCK_REM_OK_MSK = 0x00000020, CVT_V1724_CHSTS_CAL_RUN_MSK = 0x00000040
}
CH status register bitmasks.
enum CVT_V1724_NUM_BLOCKS {
CVT_V1724_NBLK_1 = 0, CVT_V1724_NBLK_2, CVT_V1724_NBLK_4, CVT_V1724_NBLK_8,
CVT_V1724_NBLK_16, CVT_V1724_NBLK_32, CVT_V1724_NBLK_64, CVT_V1724_NBLK_128,
CVT_V1724_NBLK_256, CVT_V1724_NBLK_512, CVT_V1724_NBLK_1024
}
The number for blocks.
enum CVT_V1724_EXTCLOCK { CVT_V1724_EXTCLK_10000KHz = 0, CVT_V1724_EXTCLK_40000KHz, CVT_V1724_EXTCLK_50000KHz, CVT_V1724_EXTCLK_62500KHz }
External clock allowed values.
enum CVT_V17XX_BOARD_CLOCK_INDEX {
CVT_V1724_BOARD_CLOCK_INDEX = 0, CVT_V1721_BOARD_CLOCK_INDEX, CVT_V1731_BOARD_CLOCK_INDEX, CVT_V1731_DES_BOARD_CLOCK_INDEX,
CVT_V1720_BOARD_CLOCK_INDEX, CVT_V1740_BOARD_CLOCK_INDEX, CVT_V1751_BOARD_CLOCK_INDEX, CVT_V1751_DES_BOARD_CLOCK_INDEX
}
Boards internal clock indexer for CVT_V17XX_BOARD_CLOCK_KHZ[].
enum CVT_V1724_MCST_CBLT_ADD_CTRL_MSK { CVT_V1724_MCST_CBLT_ADD_MSK = 0x000000FF, CVT_V1724_MCST_CBLT_CTRL_MSK = 0x00000300 }
V1724 MCST-CBLT Address/Control register bit masks.
enum CVT_V1724_MCST_CBLT_CTRL_BOARDS { CVT_V1724_MCST_CBLT_CTRL_DISABLED_BOARD = 0, CVT_V1724_MCST_CBLT_CTRL_LAST_BOARD = 1, CVT_V1724_MCST_CBLT_CTRL_FIRST_BOARD = 2, CVT_V1724_MCST_CBLT_CTRL_MID_BOARD = 3 }
V1724 MCST-CBLT control boards.
enum CVT_V1724_FLASH_OPCODES { CVT_V1724_FOP_PAGE_ERASE = 0x0081, CVT_V1724_FOP_PAGE_PROG_TH_BUF1 = 0x0082, CVT_V1724_FOP_PAGE_READ = 0x00D2 }
V1724 Flash register opcodes.
enum CVT_V1724_FLASH_BANK { CVT_V1724_ROM_FLASH_PAGE = 0, CVT_V1724_PLL_FLASH_PAGE = 1, CVT_V1724_FB_STANDARD = 48, CVT_V1724_FB_BACKUP = 2072 }
V1724 Flash banks.
enum CVT_V1724_FLASH_EN_MSK { CVT_V1724_FLEN_EN_MSK = 0x00000001 }
Flash enable register bitmasks.
enum CVT_V1724_MON_MODES {
CVT_V1724_MONMODE_TRIGGER_MAJ = 0, CVT_V1724_MONMODE_TEST = 1, CVT_V1724_MONMODE_MONITOR = 2, CVT_V1724_MONMODE_OCCUPANCY = 3,
CVT_V1724_MONMODE_SW_CTRL = 4
}
V1724 Output monitor mode.
enum CVT_V17XX_ROM_CFG_VCXO_TYPE { CVT_V17XX_RCFG_VCXO_500 = 1, CVT_V17XX_RCFG_VCXO_1000 = 0 }
Configurazion ROM VCXO types.
enum CVT_V17XX_ROM_CFG_BOARD_ID {
CVT_V17XX_RCFG_BOARD_ID_V1724 = 0x00000000| 1724, CVT_V17XX_RCFG_BOARD_ID_VX1724 = 0x00010000| 1724, CVT_V17XX_RCFG_BOARD_ID_V1721 = 0x00000000| 1721, CVT_V17XX_RCFG_BOARD_ID_VX1721 = 0x00010000| 1721,
CVT_V17XX_RCFG_BOARD_ID_V1731 = 0x00000000| 1731, CVT_V17XX_RCFG_BOARD_ID_VX1731 = 0x00010000| 1731, CVT_V17XX_RCFG_BOARD_ID_V1720 = 0x00000000| 1720, CVT_V17XX_RCFG_BOARD_ID_VX1720 = 0x00010000| 1720,
CVT_V17XX_RCFG_BOARD_ID_V1740 = 0x00000000| 1740, CVT_V17XX_RCFG_BOARD_ID_VX1740 = 0x00010000| 1740, CVT_V17XX_RCFG_BOARD_ID_V1751 = 0x00000000| 1751, CVT_V17XX_RCFG_BOARD_ID_VX1751 = 0x00010000| 1751
}
Configurazion ROM board IDs.
Functions
CVT_DLL_API BOOL cvt_V1724_open (cvt_V1724_data *p_data, UINT16 base_address, long vme_handle, CVT_V17XX_TYPES type)
V1724 VME boards data initialization.
CVT_DLL_API BOOL cvt_V1724_close (cvt_V1724_data *p_data)
V1724 VME boards closing and resource free.
CVT_DLL_API BOOL cvt_V1724_read_data (cvt_V1724_data *p_data, UINT32 *p_ch_max_samples, UINT32 *p_num_events)
Reads data from the board's channels and stores to user buffer.
CVT_DLL_API BOOL cvt_V1724_get_buffer_cache (cvt_V1724_data *p_data, UINT16 event_index, UINT8 ch_index, UINT16 *p_buff, UINT32 *p_buff_size, UINT8 *p_board_id, UINT32 *p_trigger_time_tag, UINT32 *p_event_counter)
Reads data cache from previous cvt_V1724_read_data data call.
CVT_DLL_API BOOL cvt_V1724_set_trigger_mode (cvt_V1724_data *p_data, BOOL falling_edge_enable, BOOL ext_trigger_enable, BOOL sw_trigger_enable, UINT8 ch_trigger_enable_msk, BOOL trigger_overlap_enable, UINT32 post_trigger)
Setups the triggering parameters.
CVT_DLL_API BOOL cvt_V1724_get_trigger_mode (cvt_V1724_data *p_data, BOOL *p_falling_edge_enable, BOOL *p_ext_trigger_enable, BOOL *p_sw_trigger_enable, UINT8 *p_ch_trigger_enable_msk, BOOL *p_trigger_overlap_enable, UINT32 *p_post_trigger)
Gets the trigger out settings.
CVT_DLL_API BOOL cvt_V1724_get_fp_trigger_out (cvt_V1724_data *p_data, BOOL *p_ext_trigger_enable, BOOL *p_sw_trigger_enable, UINT8 *p_ch_trigger_enable_msk)
Gets the front panel trigger output settings.
CVT_DLL_API BOOL cvt_V1724_set_fp_trigger_out (cvt_V1724_data *p_data, BOOL ext_trigger_enable, BOOL sw_trigger_enable, UINT8 ch_trigger_enable_msk)
Setups the front panel triggering output parameters.
CVT_DLL_API BOOL cvt_V1724_start_acquisition (cvt_V1724_data *p_data, UINT8 ch_msk)
Starts the acquisition for the spcified channel mask.
CVT_DLL_API BOOL cvt_V1724_stop_acquisition (cvt_V1724_data *p_data)
Stops the acquisition.
CVT_DLL_API BOOL cvt_V1724_set_acquisition_mode (cvt_V1724_data *p_data, BOOL sample_enable, CVT_V1724_NUM_BLOCKS block_size, CVT_V1724_ACQ_CONTROL_ACQ_MODES acquisition_mode, BOOL count_all_trigger, UINT32 downsample_factor)
Setups the acquisition mode parameters.
CVT_DLL_API BOOL cvt_V1724_get_acquisition_mode (cvt_V1724_data *p_data, BOOL *p_sample_enable, CVT_V1724_NUM_BLOCKS *p_block_size)
Gets the acquisition mode parameters.
CVT_DLL_API BOOL cvt_V1724_get_acquisition_status (cvt_V1724_data *p_data, BOOL *p_is_MEB_not_empty, BOOL *p_is_MEB_full, BOOL *p_is_running, BOOL *p_some_event_ready, BOOL *p_event_full, BOOL *p_s_in)
Gets the acquisition status parameters.
CVT_DLL_API BOOL cvt_V1724_get_buffer_samples (cvt_V1724_data *p_data, UINT16 *p_num_k_samples, CVT_V1724_NUM_BLOCKS *p_num_block_read)
Returns the maximum number of samples per events for each channel.
CVT_DLL_API BOOL cvt_V1724_set_buffer_samples (cvt_V1724_data *p_data, UINT16 num_k_samples, CVT_V1724_NUM_BLOCKS *p_num_block_written)
Sets the maximum number of samples per events for each channel.
CVT_DLL_API BOOL cvt_V1724_set_dither_enable (cvt_V1724_data *p_data, UINT8 ch_msk, BOOL dither_value)
Setups the channels' dithering feature (V1724/V1720 only).
CVT_DLL_API BOOL cvt_V1724_get_dither_enable (cvt_V1724_data *p_data, UINT8 ch_index, BOOL *p_dither_value)
Gets the specified channel' dithering feature status (V1724/V1720 only).
CVT_DLL_API BOOL cvt_V1724_set_adc_conf (cvt_V1724_data *p_data, UINT8 ch_msk, BOOL dither_value, BOOL clk_duty_stab_value, BOOL randomize_value)
Setups the channels' adc configuration (V1724/V1720 only).
CVT_DLL_API BOOL cvt_V1724_get_adc_conf (cvt_V1724_data *p_data, UINT8 ch_index, BOOL *p_dither_value, BOOL *p_clk_duty_stab_value, BOOL *p_randomize_value)
Gets the specified channel' adc configuration (V1724/V1720 only).
CVT_DLL_API BOOL cvt_V1724_adc_calib (cvt_V1724_data *p_data, UINT8 ch_msk)
Performs the specified ADCs' channels calibration (V1731/V1721 only).
CVT_DLL_API BOOL cvt_V1724_adc_temp (cvt_V1724_data *p_data, UINT8 ch_msk, UINT32 *tempadc)
Reads the specified ADCs' channels temperature (V1751 only).
CVT_DLL_API BOOL cvt_V1724_set_des_mode (cvt_V1724_data *p_data, BOOL is_des_mode)
Switchs to DES mode or normal mode (V1731 only).
CVT_DLL_API BOOL cvt_V1724_set_interrupt (cvt_V1724_data *p_data, UINT8 level, UINT32 status_id, UINT16 event_number)
Setups interrupt parameters.
CVT_DLL_API BOOL cvt_V1724_get_interrupt (cvt_V1724_data *p_data, UINT8 *p_level, UINT32 *p_status_id, UINT16 *p_event_number)
Gets interrupt parameters.
CVT_DLL_API BOOL cvt_V1724_set_readout_mode (cvt_V1724_data *p_data, BOOL enable_bus_error, UINT32 BLT_event_number)
Setups data readout mode parameters.
CVT_DLL_API BOOL cvt_V1724_get_readout_mode (cvt_V1724_data *p_data, BOOL *p_enable_bus_error, UINT32 *p_BLT_event_number)
Gets data readout mode parameters.
CVT_DLL_API BOOL cvt_V1724_software_reset (cvt_V1724_data *p_data)
Performs a software reset.
CVT_DLL_API BOOL cvt_V1724_data_clear (cvt_V1724_data *p_data)
Performs a data clear.
CVT_DLL_API BOOL cvt_V1724_set_channel_offset (cvt_V1724_data *p_data, UINT8 ch_msk, UINT16 offset_value)
Sets channels' offset.
CVT_DLL_API BOOL cvt_V1724_get_channel_offset (cvt_V1724_data *p_data, UINT8 ch_index, UINT16 *p_offset_value)
Sets specified channel' offset.
CVT_DLL_API BOOL cvt_V1724_set_channel_trigger (cvt_V1724_data *p_data, UINT8 ch_msk, UINT32 trigger_threshold, UINT32 threshold_samples)
Sets channels' trigger parameters.
CVT_DLL_API BOOL cvt_V1724_get_channel_trigger (cvt_V1724_data *p_data, UINT8 ch_index, UINT32 *p_trigger_threshold, UINT32 *p_threshold_samples)
Gets the specified channel' trigger parameters.
CVT_DLL_API BOOL cvt_V1724_set_front_panel_IO (cvt_V1724_data *p_data, BOOL use_TTL, BOOL out_en, UINT8 dir_msk, CVT_V1724_FRONT_PANEL_IO_MODES mode)
Sets front panel's IO.
CVT_DLL_API BOOL cvt_V1724_get_front_panel_IO (cvt_V1724_data *p_data, BOOL *p_use_TTL, BOOL *p_is_out_en, UINT8 *p_dir_msk, CVT_V1724_FRONT_PANEL_IO_MODES *p_mode)
Gets front panel's IO.
CVT_DLL_API BOOL cvt_V1724_software_trigger (cvt_V1724_data *p_data)
Performs a software trigger.
CVT_DLL_API BOOL cvt_V1724_get_channel_status (cvt_V1724_data *p_data, UINT8 ch_index, BOOL *p_is_dac_busy, BOOL *p_is_fifo_full, BOOL *p_is_fifo_almost_full, BOOL *p_is_block_remove_ok)
Gets information about board status.
CVT_DLL_API BOOL cvt_V1724_get_system_info (cvt_V1724_data *p_data, UINT16 *p_firmware_rev, CVT_V1724_ROM_CONFIG *p_rom_config, BOOL *p_is_board_type_correct, BOOL *p_is_firmware_rev_correct)
Gets board's system information.
CVT_DLL_API BOOL cvt_V1724_get_channel_info (cvt_V1724_data *p_data, UINT8 ch_index, UINT16 *p_firmware_rev)
Gets board's system information.
CVT_DLL_API BOOL cvt_V1724_set_MCST_CBLT (cvt_V1724_data *p_data, UINT8 address, MCST_CBLT_board_pos pos)
Setups MCST/CBLT parameters for this board.
CVT_DLL_API BOOL cvt_V1724_get_MCST_CBLT (cvt_V1724_data *p_data, UINT8 *p_address, MCST_CBLT_board_pos *p_pos)
Gets MCST/CBLT parameters from board.
CVT_DLL_API BOOL cvt_V1724_write_flash_page (cvt_V1724_data *p_data, const UINT8 *page_buff, UINT32 page_index)
Writes a page into board's flash.
CVT_DLL_API BOOL cvt_V1724_read_flash_page (cvt_V1724_data *p_data, UINT8 *page_buff, UINT32 page_index)
Reads a page from board's flash.
CVT_DLL_API BOOL cvt_V1724_erase_flash_page (cvt_V1724_data *p_data, UINT32 page_index)
Erases a board's flash page.
CVT_DLL_API BOOL cvt_V1724_fw_upgrade (cvt_V1724_data *p_data, const UINT8 *data_buff, UINT32 data_size, CVT_V1724_FLASH_BANK flash_bank, BOOL(*call_back)(UINT32 written_bytes))
Performs a full flash upgrade onto specific bank (standard or backup).
CVT_DLL_API BOOL cvt_V1724_pll_upgrade (cvt_V1724_data *p_data, const char *filename)
Loads PLL from file and stores into flash.
CVT_DLL_API const char * cvt_V1724_SW_rev (void)
Returns the SDK software release.
Variables
static const UINT32 CVT_V1724_EXTCLOCK_KHZ []
External clock allowed values (KHz).
static const UINT32 CVT_V17XX_BOARD_CLOCK_KHZ []
Boards internal clock values (KHz): use CVT_V17XX_BOARD_CLOCK_INDEX enumeration as indexer.
Detailed Description
V1724 VME board definitions.
Author:
NDA
Version:
1.0
Date:
10/2006
Provides methods, properties and defines to handle V1724 VME boards
Definition in file cvt_V1724.h.
Define Documentation
#define _INLINE_
Definition at line 1405 of file cvt_V1724.h.
#define CVT_V1724_ACQ_CONTROL_ADD 0x8100
Acquisiton Control register relative address.
Definition at line 83 of file cvt_V1724.h.
#define CVT_V1724_ACQ_CONTROL_AM cvA32_S_DATA
Acquisiton Control register address modifier.
Definition at line 474 of file cvt_V1724.h.
#define CVT_V1724_ACQ_CONTROL_DATA_SIZE cvD32
Acquisiton Control register data size.
Definition at line 273 of file cvt_V1724.h.
#define CVT_V1724_ACQ_STATUS_ADD 0x8104
Acquisiton Status register relative address.
Definition at line 84 of file cvt_V1724.h.
#define CVT_V1724_ACQ_STATUS_AM cvA32_S_DATA
Acquisiton Status register address modifier.
Definition at line 475 of file cvt_V1724.h.
#define CVT_V1724_ACQ_STATUS_DATA_SIZE cvD32
Acquisiton Status register data size.
Definition at line 274 of file cvt_V1724.h.
#define CVT_V1724_BASE_ADDRESS_ADD 0xEF38
Base Address relative address.
Definition at line 115 of file cvt_V1724.h.
#define CVT_V1724_BASE_ADDRESS_AM cvA32_S_DATA
Base Address address modifier.
Definition at line 506 of file cvt_V1724.h.
#define CVT_V1724_BASE_ADDRESS_DATA_SIZE cvD32
Base Address data size.
Definition at line 305 of file cvt_V1724.h.
#define CVT_V1724_BLT_EVENT_NUM_ADD 0xEF1C
BLT event number register relative address.
Definition at line 108 of file cvt_V1724.h.
#define CVT_V1724_BLT_EVENT_NUM_AM cvA32_S_DATA
BLT event number register address modifier.
Definition at line 499 of file cvt_V1724.h.
#define CVT_V1724_BLT_EVENT_NUM_DATA_SIZE cvD32
BLT event number register data size.
Definition at line 298 of file cvt_V1724.h.
#define CVT_V1724_BOARD_ID_ADD 0xEF08
Geo Address register relative address.
Definition at line 103 of file cvt_V1724.h.
#define CVT_V1724_BOARD_ID_AM cvA32_S_DATA
Geo Address register address modifier.
Definition at line 494 of file cvt_V1724.h.
#define CVT_V1724_BOARD_ID_DATA_SIZE cvD32
Geo Address register data size.
Definition at line 293 of file cvt_V1724.h.
#define CVT_V1724_BOARD_INFO_ADD 0x8140
Board's information register relative address.
Definition at line 97 of file cvt_V1724.h.
Referenced by V1751Board::GetBoardMemory(), V1740Board::GetBoardMemory(), V1731Board::GetBoardMemory(), V1724Board::GetBoardMemory(), V1721Board::GetBoardMemory(), and V1720Board::GetBoardMemory().
#define CVT_V1724_BOARD_INFO_AM cvA32_S_DATA
Board's information register address modifier.
Definition at line 488 of file cvt_V1724.h.
Referenced by V1751Board::GetBoardMemory(), V1740Board::GetBoardMemory(), V1731Board::GetBoardMemory(), V1724Board::GetBoardMemory(), V1721Board::GetBoardMemory(), and V1720Board::GetBoardMemory().
#define CVT_V1724_BOARD_INFO_DATA_SIZE cvD32
Board's information register data size.
Definition at line 287 of file cvt_V1724.h.
Referenced by V1751Board::GetBoardMemory(), V1740Board::GetBoardMemory(), V1731Board::GetBoardMemory(), V1724Board::GetBoardMemory(), V1721Board::GetBoardMemory(), and V1720Board::GetBoardMemory().
#define CVT_V1724_BROAD_ADC_CONF_ADD 0x809c
ADC configuration broadcast register relative address (Write only).
Definition at line 79 of file cvt_V1724.h.
#define CVT_V1724_BROAD_ADC_CONF_AM cvA32_S_DATA
ADC configuration broadcast register address modifier (Write only).
Definition at line 470 of file cvt_V1724.h.
#define CVT_V1724_BROAD_ADC_CONF_DATA_SIZE cvD32
ADC configuration broadcast register data size (Write only).
Definition at line 270 of file cvt_V1724.h.
#define CVT_V1724_BROAD_CH_BUFF_FLUSH_ADD 0x8010
Number of buffers to be removed channel broadcast register relative address (Write only).
Definition at line 75 of file cvt_V1724.h.
#define CVT_V1724_BROAD_CH_BUFF_FLUSH_AM cvA32_S_DATA
Number of buffers to be removed channel broadcast register address modifiere(Write only).
Definition at line 466 of file cvt_V1724.h.
#define CVT_V1724_BROAD_CH_BUFF_FLUSH_DATA_SIZE cvD32
Number of buffers to be removed channel broadcast register data size(Write only).
Definition at line 266 of file cvt_V1724.h.
#define CVT_V1724_BROAD_CH_CLEAR_CTRL_ADD 0x8008
Clear control channel broadcast register relative address (Write only).
Definition at line 73 of file cvt_V1724.h.
#define CVT_V1724_BROAD_CH_CLEAR_CTRL_AM cvA32_S_DATA
Clear control channel broadcast register address modifier (Write only).
Definition at line 464 of file cvt_V1724.h.
#define CVT_V1724_BROAD_CH_CLEAR_CTRL_DATA_SIZE cvD32
Clear control channel broadcast register data size (Write only).
Definition at line 264 of file cvt_V1724.h.
#define CVT_V1724_BROAD_CH_CTRL_ADD 0x8000
Control channel broadcast register relative address (Write only).
Definition at line 71 of file cvt_V1724.h.
#define CVT_V1724_BROAD_CH_CTRL_AM cvA32_S_DATA
Control channel broadcast register address modifier (Write only).
Definition at line 462 of file cvt_V1724.h.
#define CVT_V1724_BROAD_CH_CTRL_DATA_SIZE cvD32
Control channel broadcast register data size (Write only).
Definition at line 262 of file cvt_V1724.h.
#define CVT_V1724_BROAD_CH_CUSSIZE_ADD 0x8020
CustomSize channel broadcast register relative address (Write only).
Definition at line 77 of file cvt_V1724.h.
#define CVT_V1724_BROAD_CH_CUSSIZE_AM cvA32_S_DATA
Custom Size register channel broadcast address modifier (Write only).
Definition at line 468 of file cvt_V1724.h.
#define CVT_V1724_BROAD_CH_CUSSIZE_DATA_SIZE cvD32
Custom Size channel broadcast register data size (Write only).
Definition at line 268 of file cvt_V1724.h.
#define CVT_V1724_BROAD_CH_RND_ACC_ADD 0x8014
Read random Access channel broadcast register relative address (Write only).
Definition at line 76 of file cvt_V1724.h.
#define CVT_V1724_BROAD_CH_RND_ACC_AM cvA32_S_DATA
Parameters to Random access channel broadcast register address modifier (Write only).
Definition at line 467 of file cvt_V1724.h.
#define CVT_V1724_BROAD_CH_RND_ACC_DATA_SIZE cvD32
Parameters to Random access channel broadcast register data size (Write only).
Definition at line 267 of file cvt_V1724.h.
#define CVT_V1724_BROAD_CH_SET_CTRL_ADD 0x8004
Set control channel broadcast register relative address (Write only).
Definition at line 72 of file cvt_V1724.h.
#define CVT_V1724_BROAD_CH_SET_CTRL_AM cvA32_S_DATA
Set control channel broadcast register address modifier (Write only).
Definition at line 463 of file cvt_V1724.h.
#define CVT_V1724_BROAD_CH_SET_CTRL_DATA_SIZE cvD32
Set control channel broadcast register data size (Write only).
Definition at line 263 of file cvt_V1724.h.
#define CVT_V1724_BROAD_CH_ZSTH_ADD 0x8024
Zero suppression threshold channel broadcast register relative address (Write only).
Definition at line 78 of file cvt_V1724.h.
#define CVT_V1724_BROAD_CH_ZSTH_AM cvA32_S_DATA
Zero suppression threshold register channel broadcast address modifier (Write only).
Definition at line 469 of file cvt_V1724.h.
#define CVT_V1724_BROAD_CH_ZSTH_DATA_SIZE cvD32
Zero suppression threshold channel broadcast register data size (Write only).
Definition at line 269 of file cvt_V1724.h.
#define CVT_V1724_BROAD_NUM_BLOCK_ADD 0x800C
Number of blocks broadcast register relative address (Write only).
Definition at line 74 of file cvt_V1724.h.
#define CVT_V1724_BROAD_NUM_BLOCK_AM cvA32_S_DATA
Number of blocks broadcast register address modifiere(Write only).
Definition at line 465 of file cvt_V1724.h.
#define CVT_V1724_BROAD_NUM_BLOCK_DATA_SIZE cvD32
Number of blocks broadcast register data size(Write only).
Definition at line 265 of file cvt_V1724.h.
#define CVT_V1724_CH0_ADC_CONF_ADD 0x109C
CH 0 Configuration register relative address.
Definition at line 150 of file cvt_V1724.h.
#define CVT_V1724_CH0_ADC_CONF_AM cvA32_S_DATA
CH 0 Configuration register address modifier.
Definition at line 541 of file cvt_V1724.h.
#define CVT_V1724_CH0_ADC_CONF_DATA_SIZE cvD32
CH 0 Configuration register data size.
Definition at line 340 of file cvt_V1724.h.
#define CVT_V1724_CH0_BUFF_OCCUPANCY_ADD 0x1094
CH 0 Number of Buffers Filled register relative address.
Definition at line 148 of file cvt_V1724.h.
#define CVT_V1724_CH0_BUFF_OCCUPANCY_AM cvA32_S_DATA
CH 0 Number of Buffers Filled register address modifier.
Definition at line 539 of file cvt_V1724.h.
#define CVT_V1724_CH0_BUFF_OCCUPANCY_DATA_SIZE cvD32
CH 0 Number of Buffers Filled register data size.
Definition at line 338 of file cvt_V1724.h.
#define CVT_V1724_CH0_DAC_CONF_ADD 0x1098
CH 0 DAC Data Configuration register relative address.
Definition at line 149 of file cvt_V1724.h.
#define CVT_V1724_CH0_DAC_CONF_AM cvA32_S_DATA
CH 0 DAC Data Configuration register address modifier.
Definition at line 540 of file cvt_V1724.h.
#define CVT_V1724_CH0_DAC_CONF_DATA_SIZE cvD32
CH 0 DAC Data Configuration register data size.
Definition at line 339 of file cvt_V1724.h.
#define CVT_V1724_CH0_FW_REV_ADD 0x108C
CH 0 firmware revision register relative address.
Definition at line 147 of file cvt_V1724.h.
#define CVT_V1724_CH0_FW_REV_AM cvA32_S_DATA
CH 0 firmware revision register address modifier.
Definition at line 538 of file cvt_V1724.h.
#define CVT_V1724_CH0_FW_REV_DATA_SIZE cvD32
CH 0 firmware revision register data size.
Definition at line 337 of file cvt_V1724.h.
#define CVT_V1724_CH0_RESERVED_ADC_DEBUG_ADD 0x10A0
CH 0 ADC Debug Reserved register relative address.
Definition at line 151 of file cvt_V1724.h.
#define CVT_V1724_CH0_RESERVED_ADC_DEBUG_AM cvA32_S_DATA
CH 0 ADC Debug Reserved register address modifier.
Definition at line 542 of file cvt_V1724.h.
#define CVT_V1724_CH0_RESERVED_ADC_DEBUG_DATA_SIZE cvD32
CH 0 ADC Debug Reserved register data size.
Definition at line 341 of file cvt_V1724.h.
#define CVT_V1724_CH0_RESERVED_MEM_ADDRESS_ADD 0x10A8
CH 0 Memory test address Reserved register relative address.
Definition at line 153 of file cvt_V1724.h.
#define CVT_V1724_CH0_RESERVED_MEM_ADDRESS_AM cvA32_S_DATA
CH 0 Memory test address Reserved register address modifier.
Definition at line 544 of file cvt_V1724.h.
#define CVT_V1724_CH0_RESERVED_MEM_ADDRESS_DATA_SIZE cvD32
CH 0 Memory test address Reserved register data size.
Definition at line 343 of file cvt_V1724.h.
#define CVT_V1724_CH0_RESERVED_MEM_DATA_ADD 0x10A4
CH 0 Memory test data Reserved register relative address.
Definition at line 152 of file cvt_V1724.h.
#define CVT_V1724_CH0_RESERVED_MEM_DATA_AM cvA32_S_DATA
CH 0 Memory test data Reserved register address modifier.
Definition at line 543 of file cvt_V1724.h.
#define CVT_V1724_CH0_RESERVED_MEM_DATA_DATA_SIZE cvD32
CH 0 Memory test data Reserved register data size.
Definition at line 342 of file cvt_V1724.h.
#define CVT_V1724_CH0_RESERVED_RND_ACC_ADD 0x1014
CH 0 Read Block channel broadcast reserved register relative address.
Definition at line 142 of file cvt_V1724.h.
#define CVT_V1724_CH0_RESERVED_RND_ACC_AM cvA32_S_DATA
CH 0 Read Block channel broadcast reserved register address modifier.
Definition at line 533 of file cvt_V1724.h.
#define CVT_V1724_CH0_RESERVED_RND_ACC_DATA_SIZE cvD32
CH 0 Read Block channel broadcast reserved register data size.
Definition at line 332 of file cvt_V1724.h.
#define CVT_V1724_CH0_STATUS_ADD 0x1088
CH 0 status register relative address.
Definition at line 146 of file cvt_V1724.h.
#define CVT_V1724_CH0_STATUS_AM cvA32_S_DATA
CH 0 status register address modifier.
Definition at line 537 of file cvt_V1724.h.
#define CVT_V1724_CH0_STATUS_DATA_SIZE cvD32
CH 0 status register data size.
Definition at line 336 of file cvt_V1724.h.
#define CVT_V1724_CH0_THRESHOLD_ADD 0x1080
CH 0 Threshold register relative address.
Definition at line 144 of file cvt_V1724.h.
#define CVT_V1724_CH0_THRESHOLD_AM cvA32_S_DATA
CH 0 Threshold register address modifier.
Definition at line 535 of file cvt_V1724.h.
#define CVT_V1724_CH0_THRESHOLD_DATA_SIZE cvD32
CH 0 Threshold register data size.
Definition at line 334 of file cvt_V1724.h.
#define CVT_V1724_CH0_TIME_OVER_UNDER_THR_ADD 0x1084
CH 0 Over/Under Threshold Samples register relative address.
Definition at line 145 of file cvt_V1724.h.
#define CVT_V1724_CH0_TIME_OVER_UNDER_THR_AM cvA32_S_DATA
CH 0 Over/Under Threshold Samples register address modifier.
Definition at line 536 of file cvt_V1724.h.
#define CVT_V1724_CH0_TIME_OVER_UNDER_THR_DATA_SIZE cvD32
CH 0 Over/Under Threshold Samples register data size.
Definition at line 335 of file cvt_V1724.h.
#define CVT_V1724_CH0_ZSTH_ADD 0x1024
CH 0 Zero suppression threshold register relative address.
Definition at line 143 of file cvt_V1724.h.
#define CVT_V1724_CH0_ZSTH_AM cvA32_S_DATA
CH 0 Zero suppression threshold register address modifier.
Definition at line 534 of file cvt_V1724.h.
#define CVT_V1724_CH0_ZSTH_DATA_SIZE cvD32
Ch 0 Zero suppression threshold register data size).
Definition at line 333 of file cvt_V1724.h.
#define CVT_V1724_CH1_ADC_CONF_ADD 0x119C
CH 1 Configuration register relative address.
Definition at line 164 of file cvt_V1724.h.
#define CVT_V1724_CH1_ADC_CONF_AM cvA32_S_DATA
CH 1 Configuration register address modifier.
Definition at line 556 of file cvt_V1724.h.
#define CVT_V1724_CH1_ADC_CONF_DATA_SIZE cvD32
CH 1 Configuration register data size.
Definition at line 355 of file cvt_V1724.h.
#define CVT_V1724_CH1_BUFF_OCCUPANCY_ADD 0x1194
CH 1 Number of Buffers Filled register relative address.
Definition at line 162 of file cvt_V1724.h.
#define CVT_V1724_CH1_BUFF_OCCUPANCY_AM cvA32_S_DATA
CH 1 Number of Buffers Filled register address modifier.
Definition at line 554 of file cvt_V1724.h.
#define CVT_V1724_CH1_BUFF_OCCUPANCY_DATA_SIZE cvD32
CH 1 Number of Buffers Filled register data size.
Definition at line 353 of file cvt_V1724.h.
#define CVT_V1724_CH1_DAC_CONF_ADD 0x1198
CH 1 DAC Data Configuration register relative address.
Definition at line 163 of file cvt_V1724.h.
#define CVT_V1724_CH1_DAC_CONF_AM cvA32_S_DATA
CH 1 DAC Data Configuration register address modifier.
Definition at line 555 of file cvt_V1724.h.
#define CVT_V1724_CH1_DAC_CONF_DATA_SIZE cvD32
CH 1 DAC Data Configuration register data size.
Definition at line 354 of file cvt_V1724.h.
#define CVT_V1724_CH1_FW_REV_ADD 0x118C
CH 1 firmware revision register relative address.
Definition at line 161 of file cvt_V1724.h.
#define CVT_V1724_CH1_FW_REV_AM cvA32_S_DATA
CH 1 firmware revision register address modifier.
Definition at line 553 of file cvt_V1724.h.
#define CVT_V1724_CH1_FW_REV_DATA_SIZE cvD32
CH 1 firmware revision register data size.
Definition at line 352 of file cvt_V1724.h.
#define CVT_V1724_CH1_RESERVED_ADC_DEBUG_ADD 0x11A0
CH 1 ADC Debug Reserved register relative address.
Definition at line 165 of file cvt_V1724.h.
#define CVT_V1724_CH1_RESERVED_ADC_DEBUG_AM cvA32_S_DATA
CH 1 ADC Debug Reserved register address modifier.
Definition at line 557 of file cvt_V1724.h.
#define CVT_V1724_CH1_RESERVED_ADC_DEBUG_DATA_SIZE cvD32
CH 1 ADC Debug Reserved register data size.
Definition at line 356 of file cvt_V1724.h.
#define CVT_V1724_CH1_RESERVED_MEM_ADDRESS_ADD 0x11A8
CH 1 Memory test address Reserved register relative address.
Definition at line 167 of file cvt_V1724.h.
#define CVT_V1724_CH1_RESERVED_MEM_ADDRESS_AM cvA32_S_DATA
CH 1 Memory test address Reserved register address modifier.
Definition at line 559 of file cvt_V1724.h.
#define CVT_V1724_CH1_RESERVED_MEM_ADDRESS_DATA_SIZE cvD32
CH 1 Memory test address Reserved register data size.
Definition at line 358 of file cvt_V1724.h.
#define CVT_V1724_CH1_RESERVED_MEM_DATA_ADD 0x11A4
CH 1 Memory test data Reserved register relative address.
Definition at line 166 of file cvt_V1724.h.
#define CVT_V1724_CH1_RESERVED_MEM_DATA_AM cvA32_S_DATA
CH 1 Memory test data Reserved register address modifier.
Definition at line 558 of file cvt_V1724.h.
#define CVT_V1724_CH1_RESERVED_MEM_DATA_DATA_SIZE cvD32
CH 1 Memory test data Reserved register data size.
Definition at line 357 of file cvt_V1724.h.
#define CVT_V1724_CH1_RESERVED_RND_ACC_ADD 0x1114
CH 1 Read Block channel broadcast reserved register relative address.
Definition at line 156 of file cvt_V1724.h.
#define CVT_V1724_CH1_RESERVED_RND_ACC_AM cvA32_S_DATA
CH 1 Read Block channel broadcast reserved register address modifier.
Definition at line 548 of file cvt_V1724.h.
#define CVT_V1724_CH1_RESERVED_RND_ACC_DATA_SIZE cvD32
CH 1 Read Block channel broadcast reserved register data size.
Definition at line 347 of file cvt_V1724.h.
#define CVT_V1724_CH1_STATUS_ADD 0x1188
CH 1 status register relative address.
Definition at line 160 of file cvt_V1724.h.
#define CVT_V1724_CH1_STATUS_AM cvA32_S_DATA
CH 1 status register address modifier.
Definition at line 552 of file cvt_V1724.h.
#define CVT_V1724_CH1_STATUS_DATA_SIZE cvD32
CH 1 status register data size.
Definition at line 351 of file cvt_V1724.h.
#define CVT_V1724_CH1_THRESHOLD_ADD 0x1180
CH 1 Threshold register relative address.
Definition at line 158 of file cvt_V1724.h.
#define CVT_V1724_CH1_THRESHOLD_AM cvA32_S_DATA
CH 1 Threshold register address modifier.
Definition at line 550 of file cvt_V1724.h.
#define CVT_V1724_CH1_THRESHOLD_DATA_SIZE cvD32
CH 1 Threshold register data size.
Definition at line 349 of file cvt_V1724.h.
#define CVT_V1724_CH1_TIME_OVER_UNDER_THR_ADD 0x1184
CH 1 Over/Under Threshold Samples register relative address.
Definition at line 159 of file cvt_V1724.h.
#define CVT_V1724_CH1_TIME_OVER_UNDER_THR_AM cvA32_S_DATA
CH 1 Over/Under Threshold Samples register address modifier.
Definition at line 551 of file cvt_V1724.h.
#define CVT_V1724_CH1_TIME_OVER_UNDER_THR_DATA_SIZE cvD32
CH 1 Over/Under Threshold Samples register data size.
Definition at line 350 of file cvt_V1724.h.
#define CVT_V1724_CH1_ZSTH_ADD 0x1124
CH 1 Zero suppression threshold register relative address.
Definition at line 157 of file cvt_V1724.h.
#define CVT_V1724_CH1_ZSTH_AM cvA32_S_DATA
CH 1 Zero suppression threshold register address modifier.
Definition at line 549 of file cvt_V1724.h.
#define CVT_V1724_CH1_ZSTH_DATA_SIZE cvD32
Ch 1 Zero suppression threshold register data size).
Definition at line 348 of file cvt_V1724.h.
#define CVT_V1724_CH2_ADC_CONF_ADD 0x129C
CH 2 Configuration register relative address.
Definition at line 178 of file cvt_V1724.h.
#define CVT_V1724_CH2_ADC_CONF_AM cvA32_S_DATA
CH 2 Configuration register address modifier.
Definition at line 571 of file cvt_V1724.h.
#define CVT_V1724_CH2_ADC_CONF_DATA_SIZE cvD32
CH 2 Configuration register data size.
Definition at line 370 of file cvt_V1724.h.
#define CVT_V1724_CH2_BUFF_OCCUPANCY_ADD 0x1294
CH 2 Number of Buffers Filled register relative address.
Definition at line 176 of file cvt_V1724.h.
#define CVT_V1724_CH2_BUFF_OCCUPANCY_AM cvA32_S_DATA
CH 2 Number of Buffers Filled register address modifier.
Definition at line 569 of file cvt_V1724.h.
#define CVT_V1724_CH2_BUFF_OCCUPANCY_DATA_SIZE cvD32
CH 2 Number of Buffers Filled register data size.
Definition at line 368 of file cvt_V1724.h.
#define CVT_V1724_CH2_DAC_CONF_ADD 0x1298
CH 2 DAC Data Configuration register relative address.
Definition at line 177 of file cvt_V1724.h.
#define CVT_V1724_CH2_DAC_CONF_AM cvA32_S_DATA
CH 2 DAC Data Configuration register address modifier.
Definition at line 570 of file cvt_V1724.h.
#define CVT_V1724_CH2_DAC_CONF_DATA_SIZE cvD32
CH 2 DAC Data Configuration register data size.
Definition at line 369 of file cvt_V1724.h.
#define CVT_V1724_CH2_FW_REV_ADD 0x128C
CH 2 firmware revision register relative address.
Definition at line 175 of file cvt_V1724.h.
#define CVT_V1724_CH2_FW_REV_AM cvA32_S_DATA
CH 2 firmware revision register address modifier.
Definition at line 568 of file cvt_V1724.h.
#define CVT_V1724_CH2_FW_REV_DATA_SIZE cvD32
CH 2 firmware revision register data size.
Definition at line 367 of file cvt_V1724.h.
#define CVT_V1724_CH2_RESERVED_ADC_DEBUG_ADD 0x12A0
CH 2 ADC Debug Reserved register relative address.
Definition at line 179 of file cvt_V1724.h.
#define CVT_V1724_CH2_RESERVED_ADC_DEBUG_AM cvA32_S_DATA
CH 2 ADC Debug Reserved register address modifier.
Definition at line 572 of file cvt_V1724.h.
#define CVT_V1724_CH2_RESERVED_ADC_DEBUG_DATA_SIZE cvD32
CH 2 ADC Debug Reserved register data size.
Definition at line 371 of file cvt_V1724.h.
#define CVT_V1724_CH2_RESERVED_MEM_ADDRESS_ADD 0x12A8
CH 2 Memory test address Reserved register relative address.
Definition at line 181 of file cvt_V1724.h.
#define CVT_V1724_CH2_RESERVED_MEM_ADDRESS_AM cvA32_S_DATA
CH 2 Memory test address Reserved register address modifier.
Definition at line 574 of file cvt_V1724.h.
#define CVT_V1724_CH2_RESERVED_MEM_ADDRESS_DATA_SIZE cvD32
CH 2 Memory test address Reserved register data size.
Definition at line 373 of file cvt_V1724.h.
#define CVT_V1724_CH2_RESERVED_MEM_DATA_ADD 0x12A4
CH 2 Memory test data Reserved register relative address.
Definition at line 180 of file cvt_V1724.h.
#define CVT_V1724_CH2_RESERVED_MEM_DATA_AM cvA32_S_DATA
CH 2 Memory test data Reserved register address modifier.
Definition at line 573 of file cvt_V1724.h.
#define CVT_V1724_CH2_RESERVED_MEM_DATA_DATA_SIZE cvD32
CH 2 Memory test data Reserved register data size.
Definition at line 372 of file cvt_V1724.h.
#define CVT_V1724_CH2_RESERVED_RND_ACC_ADD 0x1214
CH 2 Read Block channel broadcast reserved register relative address.
Definition at line 170 of file cvt_V1724.h.
#define CVT_V1724_CH2_RESERVED_RND_ACC_AM cvA32_S_DATA
CH 2 Read Block channel broadcast reserved register address modifier.
Definition at line 563 of file cvt_V1724.h.
#define CVT_V1724_CH2_RESERVED_RND_ACC_DATA_SIZE cvD32
CH 2 Read Block channel broadcast reserved register data size.
Definition at line 362 of file cvt_V1724.h.
#define CVT_V1724_CH2_STATUS_ADD 0x1288
CH 2 status register relative address.
Definition at line 174 of file cvt_V1724.h.
#define CVT_V1724_CH2_STATUS_AM cvA32_S_DATA
CH 2 status register address modifier.
Definition at line 567 of file cvt_V1724.h.
#define CVT_V1724_CH2_STATUS_DATA_SIZE cvD32
CH 2 status register data size.
Definition at line 366 of file cvt_V1724.h.
#define CVT_V1724_CH2_THRESHOLD_ADD 0x1280
CH 2 Threshold register relative address.
Definition at line 172 of file cvt_V1724.h.
#define CVT_V1724_CH2_THRESHOLD_AM cvA32_S_DATA
CH 2 Threshold register address modifier.
Definition at line 565 of file cvt_V1724.h.
#define CVT_V1724_CH2_THRESHOLD_DATA_SIZE cvD32
CH 2 Threshold register data size.
Definition at line 364 of file cvt_V1724.h.
#define CVT_V1724_CH2_TIME_OVER_UNDER_THR_ADD 0x1284
CH 2 Over/Under Threshold Samples register relative address.
Definition at line 173 of file cvt_V1724.h.
#define CVT_V1724_CH2_TIME_OVER_UNDER_THR_AM cvA32_S_DATA
CH 2 Over/Under Threshold Samples register address modifier.
Definition at line 566 of file cvt_V1724.h.
#define CVT_V1724_CH2_TIME_OVER_UNDER_THR_DATA_SIZE cvD32
CH 2 Over/Under Threshold Samples register data size.
Definition at line 365 of file cvt_V1724.h.
#define CVT_V1724_CH2_ZSTH_ADD 0x1224
CH 2 Zero suppression threshold register relative address.
Definition at line 171 of file cvt_V1724.h.
#define CVT_V1724_CH2_ZSTH_AM cvA32_S_DATA
CH 2 Zero suppression threshold register address modifier.
Definition at line 564 of file cvt_V1724.h.
#define CVT_V1724_CH2_ZSTH_DATA_SIZE cvD32
Ch 2 Zero suppression threshold register data size).
Definition at line 363 of file cvt_V1724.h.
#define CVT_V1724_CH3_ADC_CONF_ADD 0x139C
CH 3 Configuration register relative address.
Definition at line 192 of file cvt_V1724.h.
#define CVT_V1724_CH3_ADC_CONF_AM cvA32_S_DATA
CH 3 Configuration register address modifier.
Definition at line 586 of file cvt_V1724.h.
#define CVT_V1724_CH3_ADC_CONF_DATA_SIZE cvD32
CH 3 Configuration register data size.
Definition at line 385 of file cvt_V1724.h.
#define CVT_V1724_CH3_BUFF_OCCUPANCY_ADD 0x1394
CH 3 Number of Buffers Filled register relative address.
Definition at line 190 of file cvt_V1724.h.
#define CVT_V1724_CH3_BUFF_OCCUPANCY_AM cvA32_S_DATA
CH 3 Number of Buffers Filled register address modifier.
Definition at line 584 of file cvt_V1724.h.
#define CVT_V1724_CH3_BUFF_OCCUPANCY_DATA_SIZE cvD32
CH 3 Number of Buffers Filled register data size.
Definition at line 383 of file cvt_V1724.h.
#define CVT_V1724_CH3_DAC_CONF_ADD 0x1398
CH 3 DAC Data Configuration register relative address.
Definition at line 191 of file cvt_V1724.h.
#define CVT_V1724_CH3_DAC_CONF_AM cvA32_S_DATA
CH 3 DAC Data Configuration register address modifier.
Definition at line 585 of file cvt_V1724.h.
#define CVT_V1724_CH3_DAC_CONF_DATA_SIZE cvD32
CH 3 DAC Data Configuration register data size.
Definition at line 384 of file cvt_V1724.h.
#define CVT_V1724_CH3_FW_REV_ADD 0x138C
CH 3 firmware revision register relative address.
Definition at line 189 of file cvt_V1724.h.
#define CVT_V1724_CH3_FW_REV_AM cvA32_S_DATA
CH 3 firmware revision register address modifier.
Definition at line 583 of file cvt_V1724.h.
#define CVT_V1724_CH3_FW_REV_DATA_SIZE cvD32
CH 3 firmware revision register data size.
Definition at line 382 of file cvt_V1724.h.
#define CVT_V1724_CH3_RESERVED_ADC_DEBUG_ADD 0x13A0
CH 3 ADC Debug Reserved register relative address.
Definition at line 193 of file cvt_V1724.h.
#define CVT_V1724_CH3_RESERVED_ADC_DEBUG_AM cvA32_S_DATA
CH 3 ADC Debug Reserved register address modifier.
Definition at line 587 of file cvt_V1724.h.
#define CVT_V1724_CH3_RESERVED_ADC_DEBUG_DATA_SIZE cvD32
CH 3 ADC Debug Reserved register data size.
Definition at line 386 of file cvt_V1724.h.
#define CVT_V1724_CH3_RESERVED_MEM_ADDRESS_ADD 0x13A8
CH 3 Memory test address Reserved register relative address.
Definition at line 195 of file cvt_V1724.h.
#define CVT_V1724_CH3_RESERVED_MEM_ADDRESS_AM cvA32_S_DATA
CH 3 Memory test address Reserved register address modifier.
Definition at line 589 of file cvt_V1724.h.
#define CVT_V1724_CH3_RESERVED_MEM_ADDRESS_DATA_SIZE cvD32
CH 3 Memory test address Reserved register data size.
Definition at line 388 of file cvt_V1724.h.
#define CVT_V1724_CH3_RESERVED_MEM_DATA_ADD 0x13A4
CH 3 Memory test data Reserved register relative address.
Definition at line 194 of file cvt_V1724.h.
#define CVT_V1724_CH3_RESERVED_MEM_DATA_AM cvA32_S_DATA
CH 3 Memory test data Reserved register address modifier.
Definition at line 588 of file cvt_V1724.h.
#define CVT_V1724_CH3_RESERVED_MEM_DATA_DATA_SIZE cvD32
CH 3 Memory test data Reserved register data size.
Definition at line 387 of file cvt_V1724.h.
#define CVT_V1724_CH3_RESERVED_RND_ACC_ADD 0x1314
CH 3 Read Block channel broadcast reserved register relative address.
Definition at line 184 of file cvt_V1724.h.
#define CVT_V1724_CH3_RESERVED_RND_ACC_AM cvA32_S_DATA
CH 3 Read Block channel broadcast reserved register address modifier.
Definition at line 578 of file cvt_V1724.h.
#define CVT_V1724_CH3_RESERVED_RND_ACC_DATA_SIZE cvD32
CH 3 Read Block channel broadcast reserved register data size.
Definition at line 377 of file cvt_V1724.h.
#define CVT_V1724_CH3_STATUS_ADD 0x1388
CH 3 status register relative address.
Definition at line 188 of file cvt_V1724.h.
#define CVT_V1724_CH3_STATUS_AM cvA32_S_DATA
CH 3 status register address modifier.
Definition at line 582 of file cvt_V1724.h.
#define CVT_V1724_CH3_STATUS_DATA_SIZE cvD32
CH 3 status register data size.
Definition at line 381 of file cvt_V1724.h.
#define CVT_V1724_CH3_THRESHOLD_ADD 0x1380
CH 3 Threshold register relative address.
Definition at line 186 of file cvt_V1724.h.
#define CVT_V1724_CH3_THRESHOLD_AM cvA32_S_DATA
CH 3 Threshold register address modifier.
Definition at line 580 of file cvt_V1724.h.
#define CVT_V1724_CH3_THRESHOLD_DATA_SIZE cvD32
CH 3 Threshold register data size.
Definition at line 379 of file cvt_V1724.h.
#define CVT_V1724_CH3_TIME_OVER_UNDER_THR_ADD 0x1384
CH 3 Over/Under Threshold Samples register relative address.
Definition at line 187 of file cvt_V1724.h.
#define CVT_V1724_CH3_TIME_OVER_UNDER_THR_AM cvA32_S_DATA
CH 3 Over/Under Threshold Samples register address modifier.
Definition at line 581 of file cvt_V1724.h.
#define CVT_V1724_CH3_TIME_OVER_UNDER_THR_DATA_SIZE cvD32
CH 3 Over/Under Threshold Samples register data size.
Definition at line 380 of file cvt_V1724.h.
#define CVT_V1724_CH3_ZSTH_ADD 0x1324
CH 3 Zero suppression threshold register relative address.
Definition at line 185 of file cvt_V1724.h.
#define CVT_V1724_CH3_ZSTH_AM cvA32_S_DATA
CH 3 Zero suppression threshold register address modifier.
Definition at line 579 of file cvt_V1724.h.
#define CVT_V1724_CH3_ZSTH_DATA_SIZE cvD32
Ch 3 Zero suppression threshold register data size).
Definition at line 378 of file cvt_V1724.h.
#define CVT_V1724_CH4_ADC_CONF_ADD 0x149C
CH 4 Configuration register relative address.
Definition at line 206 of file cvt_V1724.h.
#define CVT_V1724_CH4_ADC_CONF_AM cvA32_S_DATA
CH 4 Configuration register address modifier.
Definition at line 601 of file cvt_V1724.h.
#define CVT_V1724_CH4_ADC_CONF_DATA_SIZE cvD32
CH 4 Configuration register data size.
Definition at line 400 of file cvt_V1724.h.
#define CVT_V1724_CH4_BUFF_OCCUPANCY_ADD 0x1494
CH 4 Number of Buffers Filled register relative address.
Definition at line 204 of file cvt_V1724.h.
#define CVT_V1724_CH4_BUFF_OCCUPANCY_AM cvA32_S_DATA
CH 4 Number of Buffers Filled register address modifier.
Definition at line 599 of file cvt_V1724.h.
#define CVT_V1724_CH4_BUFF_OCCUPANCY_DATA_SIZE cvD32
CH 4 Number of Buffers Filled register data size.
Definition at line 398 of file cvt_V1724.h.
#define CVT_V1724_CH4_DAC_CONF_ADD 0x1498
CH 4 DAC Data Configuration register relative address.
Definition at line 205 of file cvt_V1724.h.
#define CVT_V1724_CH4_DAC_CONF_AM cvA32_S_DATA
CH 4 DAC Data Configuration register address modifier.
Definition at line 600 of file cvt_V1724.h.
#define CVT_V1724_CH4_DAC_CONF_DATA_SIZE cvD32
CH 4 DAC Data Configuration register data size.
Definition at line 399 of file cvt_V1724.h.
#define CVT_V1724_CH4_FW_REV_ADD 0x148C
CH 4 firmware revision register relative address.
Definition at line 203 of file cvt_V1724.h.
#define CVT_V1724_CH4_FW_REV_AM cvA32_S_DATA
CH 4 firmware revision register address modifier.
Definition at line 598 of file cvt_V1724.h.
#define CVT_V1724_CH4_FW_REV_DATA_SIZE cvD32
CH 4 firmware revision register data size.
Definition at line 397 of file cvt_V1724.h.
#define CVT_V1724_CH4_RESERVED_ADC_DEBUG_ADD 0x14A0
CH 4 ADC Debug Reserved register relative address.
Definition at line 207 of file cvt_V1724.h.
#define CVT_V1724_CH4_RESERVED_ADC_DEBUG_AM cvA32_S_DATA
CH 4 ADC Debug Reserved register address modifier.
Definition at line 602 of file cvt_V1724.h.
#define CVT_V1724_CH4_RESERVED_ADC_DEBUG_DATA_SIZE cvD32
CH 4 ADC Debug Reserved register data size.
Definition at line 401 of file cvt_V1724.h.
#define CVT_V1724_CH4_RESERVED_MEM_ADDRESS_ADD 0x14A8
CH 4 Memory test address Reserved register relative address.
Definition at line 209 of file cvt_V1724.h.
#define CVT_V1724_CH4_RESERVED_MEM_ADDRESS_AM cvA32_S_DATA
CH 4 Memory test address Reserved register address modifier.
Definition at line 604 of file cvt_V1724.h.
#define CVT_V1724_CH4_RESERVED_MEM_ADDRESS_DATA_SIZE cvD32
CH 4 Memory test address Reserved register data size.
Definition at line 403 of file cvt_V1724.h.
#define CVT_V1724_CH4_RESERVED_MEM_DATA_ADD 0x14A4
CH 4 Memory test data Reserved register relative address.
Definition at line 208 of file cvt_V1724.h.
#define CVT_V1724_CH4_RESERVED_MEM_DATA_AM cvA32_S_DATA
CH 4 Memory test data Reserved register address modifier.
Definition at line 603 of file cvt_V1724.h.
#define CVT_V1724_CH4_RESERVED_MEM_DATA_DATA_SIZE cvD32
CH 4 Memory test data Reserved register data size.
Definition at line 402 of file cvt_V1724.h.
#define CVT_V1724_CH4_RESERVED_RND_ACC_ADD 0x1414
CH 4 Read Block channel broadcast reserved register relative address.
Definition at line 198 of file cvt_V1724.h.
#define CVT_V1724_CH4_RESERVED_RND_ACC_AM cvA32_S_DATA
CH 4 Read Block channel broadcast reserved register address modifier.
Definition at line 593 of file cvt_V1724.h.
#define CVT_V1724_CH4_RESERVED_RND_ACC_DATA_SIZE cvD32
CH 4 Read Block channel broadcast reserved register data size.
Definition at line 392 of file cvt_V1724.h.
#define CVT_V1724_CH4_STATUS_ADD 0x1488
CH 4 status register relative address.
Definition at line 202 of file cvt_V1724.h.
#define CVT_V1724_CH4_STATUS_AM cvA32_S_DATA
CH 4 status register address modifier.
Definition at line 597 of file cvt_V1724.h.
#define CVT_V1724_CH4_STATUS_DATA_SIZE cvD32
CH 4 status register data size.
Definition at line 396 of file cvt_V1724.h.
#define CVT_V1724_CH4_THRESHOLD_ADD 0x1480
CH 4 Threshold register relative address.
Definition at line 200 of file cvt_V1724.h.
#define CVT_V1724_CH4_THRESHOLD_AM cvA32_S_DATA
CH 4 Threshold register address modifier.
Definition at line 595 of file cvt_V1724.h.
#define CVT_V1724_CH4_THRESHOLD_DATA_SIZE cvD32
CH 4 Threshold register data size.
Definition at line 394 of file cvt_V1724.h.
#define CVT_V1724_CH4_TIME_OVER_UNDER_THR_ADD 0x1484
CH 4 Over/Under Threshold Samples register relative address.
Definition at line 201 of file cvt_V1724.h.
#define CVT_V1724_CH4_TIME_OVER_UNDER_THR_AM cvA32_S_DATA
CH 4 Over/Under Threshold Samples register address modifier.
Definition at line 596 of file cvt_V1724.h.
#define CVT_V1724_CH4_TIME_OVER_UNDER_THR_DATA_SIZE cvD32
CH 4 Over/Under Threshold Samples register data size.
Definition at line 395 of file cvt_V1724.h.
#define CVT_V1724_CH4_ZSTH_ADD 0x1424
CH 4 Zero suppression threshold register relative address.
Definition at line 199 of file cvt_V1724.h.
#define CVT_V1724_CH4_ZSTH_AM cvA32_S_DATA
CH 4 Zero suppression threshold register address modifier.
Definition at line 594 of file cvt_V1724.h.
#define CVT_V1724_CH4_ZSTH_DATA_SIZE cvD32
Ch 4 Zero suppression threshold register data size).
Definition at line 393 of file cvt_V1724.h.
#define CVT_V1724_CH5_ADC_CONF_ADD 0x159C
CH 5 Configuration register relative address.
Definition at line 220 of file cvt_V1724.h.
#define CVT_V1724_CH5_ADC_CONF_AM cvA32_S_DATA
CH 5 Configuration register address modifier.
Definition at line 616 of file cvt_V1724.h.
#define CVT_V1724_CH5_ADC_CONF_DATA_SIZE cvD32
CH 5 Configuration register data size.
Definition at line 415 of file cvt_V1724.h.
#define CVT_V1724_CH5_BUFF_OCCUPANCY_ADD 0x1594
CH 5 Number of Buffers Filled register relative address.
Definition at line 218 of file cvt_V1724.h.
#define CVT_V1724_CH5_BUFF_OCCUPANCY_AM cvA32_S_DATA
CH 5 Number of Buffers Filled register address modifier.
Definition at line 614 of file cvt_V1724.h.
#define CVT_V1724_CH5_BUFF_OCCUPANCY_DATA_SIZE cvD32
CH 5 Number of Buffers Filled register data size.
Definition at line 413 of file cvt_V1724.h.
#define CVT_V1724_CH5_DAC_CONF_ADD 0x1598
CH 5 DAC Data Configuration register relative address.
Definition at line 219 of file cvt_V1724.h.
#define CVT_V1724_CH5_DAC_CONF_AM cvA32_S_DATA
CH 5 DAC Data Configuration register address modifier.
Definition at line 615 of file cvt_V1724.h.
#define CVT_V1724_CH5_DAC_CONF_DATA_SIZE cvD32
CH 5 DAC Data Configuration register data size.
Definition at line 414 of file cvt_V1724.h.
#define CVT_V1724_CH5_FW_REV_ADD 0x158C
CH 5 firmware revision register relative address.
Definition at line 217 of file cvt_V1724.h.
#define CVT_V1724_CH5_FW_REV_AM cvA32_S_DATA
CH 5 firmware revision register address modifier.
Definition at line 613 of file cvt_V1724.h.
#define CVT_V1724_CH5_FW_REV_DATA_SIZE cvD32
CH 5 firmware revision register data size.
Definition at line 412 of file cvt_V1724.h.
#define CVT_V1724_CH5_RESERVED_ADC_DEBUG_ADD 0x15A0
CH 5 ADC Debug Reserved register relative address.
Definition at line 221 of file cvt_V1724.h.
#define CVT_V1724_CH5_RESERVED_ADC_DEBUG_AM cvA32_S_DATA
CH 5 ADC Debug Reserved register address modifier.
Definition at line 617 of file cvt_V1724.h.
#define CVT_V1724_CH5_RESERVED_ADC_DEBUG_DATA_SIZE cvD32
CH 5 ADC Debug Reserved register data size.
Definition at line 416 of file cvt_V1724.h.
#define CVT_V1724_CH5_RESERVED_MEM_ADDRESS_ADD 0x15A8
CH 5 Memory test address Reserved register relative address.
Definition at line 223 of file cvt_V1724.h.
#define CVT_V1724_CH5_RESERVED_MEM_ADDRESS_AM cvA32_S_DATA
CH 5 Memory test address Reserved register address modifier.
Definition at line 619 of file cvt_V1724.h.
#define CVT_V1724_CH5_RESERVED_MEM_ADDRESS_DATA_SIZE cvD32
CH 5 Memory test address Reserved register data size.
Definition at line 418 of file cvt_V1724.h.
#define CVT_V1724_CH5_RESERVED_MEM_DATA_ADD 0x15A4
CH 5 Memory test data Reserved register relative address.
Definition at line 222 of file cvt_V1724.h.
#define CVT_V1724_CH5_RESERVED_MEM_DATA_AM cvA32_S_DATA
CH 5 Memory test data Reserved register address modifier.
Definition at line 618 of file cvt_V1724.h.
#define CVT_V1724_CH5_RESERVED_MEM_DATA_DATA_SIZE cvD32
CH 5 Memory test data Reserved register data size.
Definition at line 417 of file cvt_V1724.h.
#define CVT_V1724_CH5_RESERVED_RND_ACC_ADD 0x1514
CH 5 Read Block channel broadcast reserved register relative address.
Definition at line 212 of file cvt_V1724.h.
#define CVT_V1724_CH5_RESERVED_RND_ACC_AM cvA32_S_DATA
CH 5 Read Block channel broadcast reserved register address modifier.
Definition at line 608 of file cvt_V1724.h.
#define CVT_V1724_CH5_RESERVED_RND_ACC_DATA_SIZE cvD32
CH 5 Read Block channel broadcast reserved register data size.
Definition at line 407 of file cvt_V1724.h.
#define CVT_V1724_CH5_STATUS_ADD 0x1588
CH 5 status register relative address.
Definition at line 216 of file cvt_V1724.h.
#define CVT_V1724_CH5_STATUS_AM cvA32_S_DATA
CH 5 status register address modifier.
Definition at line 612 of file cvt_V1724.h.
#define CVT_V1724_CH5_STATUS_DATA_SIZE cvD32
CH 5 status register data size.
Definition at line 411 of file cvt_V1724.h.
#define CVT_V1724_CH5_THRESHOLD_ADD 0x1580
CH 5 Threshold register relative address.
Definition at line 214 of file cvt_V1724.h.
#define CVT_V1724_CH5_THRESHOLD_AM cvA32_S_DATA
CH 5 Threshold register address modifier.
Definition at line 610 of file cvt_V1724.h.
#define CVT_V1724_CH5_THRESHOLD_DATA_SIZE cvD32
CH 5 Threshold register data size.
Definition at line 409 of file cvt_V1724.h.
#define CVT_V1724_CH5_TIME_OVER_UNDER_THR_ADD 0x1584
CH 5 Over/Under Threshold Samples register relative address.
Definition at line 215 of file cvt_V1724.h.
#define CVT_V1724_CH5_TIME_OVER_UNDER_THR_AM cvA32_S_DATA
CH 5 Over/Under Threshold Samples register address modifier.
Definition at line 611 of file cvt_V1724.h.
#define CVT_V1724_CH5_TIME_OVER_UNDER_THR_DATA_SIZE cvD32
CH 5 Over/Under Threshold Samples register data size.
Definition at line 410 of file cvt_V1724.h.
#define CVT_V1724_CH5_ZSTH_ADD 0x1524
CH 5 Zero suppression threshold register relative address.
Definition at line 213 of file cvt_V1724.h.
#define CVT_V1724_CH5_ZSTH_AM cvA32_S_DATA
CH 5 Zero suppression threshold register address modifier.
Definition at line 609 of file cvt_V1724.h.
#define CVT_V1724_CH5_ZSTH_DATA_SIZE cvD32
Ch 5 Zero suppression threshold register data size).
Definition at line 408 of file cvt_V1724.h.
#define CVT_V1724_CH6_ADC_CONF_ADD 0x169C
CH 6 Configuration register relative address.
Definition at line 234 of file cvt_V1724.h.
#define CVT_V1724_CH6_ADC_CONF_AM cvA32_S_DATA
CH 6 Configuration register address modifier.
Definition at line 631 of file cvt_V1724.h.
#define CVT_V1724_CH6_ADC_CONF_DATA_SIZE cvD32
CH 6 Configuration register data size.
Definition at line 430 of file cvt_V1724.h.
#define CVT_V1724_CH6_BUFF_OCCUPANCY_ADD 0x1694
CH 6 Number of Buffers Filled register relative address.
Definition at line 232 of file cvt_V1724.h.
#define CVT_V1724_CH6_BUFF_OCCUPANCY_AM cvA32_S_DATA
CH 6 Number of Buffers Filled register address modifier.
Definition at line 629 of file cvt_V1724.h.
#define CVT_V1724_CH6_BUFF_OCCUPANCY_DATA_SIZE cvD32
CH 6 Number of Buffers Filled register data size.
Definition at line 428 of file cvt_V1724.h.
#define CVT_V1724_CH6_DAC_CONF_ADD 0x1698
CH 6 DAC Data Configuration register relative address.
Definition at line 233 of file cvt_V1724.h.
#define CVT_V1724_CH6_DAC_CONF_AM cvA32_S_DATA
CH 6 DAC Data Configuration register address modifier.
Definition at line 630 of file cvt_V1724.h.
#define CVT_V1724_CH6_DAC_CONF_DATA_SIZE cvD32
CH 6 DAC Data Configuration register data size.
Definition at line 429 of file cvt_V1724.h.
#define CVT_V1724_CH6_FW_REV_ADD 0x168C
CH 6 firmware revision register relative address.
Definition at line 231 of file cvt_V1724.h.
#define CVT_V1724_CH6_FW_REV_AM cvA32_S_DATA
CH 6 firmware revision register address modifier.
Definition at line 628 of file cvt_V1724.h.
#define CVT_V1724_CH6_FW_REV_DATA_SIZE cvD32
CH 6 firmware revision register data size.
Definition at line 427 of file cvt_V1724.h.
#define CVT_V1724_CH6_RESERVED_ADC_DEBUG_ADD 0x16A0
CH 6 ADC Debug Reserved register relative address.
Definition at line 235 of file cvt_V1724.h.
#define CVT_V1724_CH6_RESERVED_ADC_DEBUG_AM cvA32_S_DATA
CH 6 ADC Debug Reserved register address modifier.
Definition at line 632 of file cvt_V1724.h.
#define CVT_V1724_CH6_RESERVED_ADC_DEBUG_DATA_SIZE cvD32
CH 6 ADC Debug Reserved register data size.
Definition at line 431 of file cvt_V1724.h.
#define CVT_V1724_CH6_RESERVED_MEM_ADDRESS_ADD 0x16A8
CH 6 Memory test address Reserved register relative address.
Definition at line 237 of file cvt_V1724.h.
#define CVT_V1724_CH6_RESERVED_MEM_ADDRESS_AM cvA32_S_DATA
CH 6 Memory test address Reserved register address modifier.
Definition at line 634 of file cvt_V1724.h.
#define CVT_V1724_CH6_RESERVED_MEM_ADDRESS_DATA_SIZE cvD32
CH 6 Memory test address Reserved register data size.
Definition at line 433 of file cvt_V1724.h.
#define CVT_V1724_CH6_RESERVED_MEM_DATA_ADD 0x16A4
CH 6 Memory test data Reserved register relative address.
Definition at line 236 of file cvt_V1724.h.
#define CVT_V1724_CH6_RESERVED_MEM_DATA_AM cvA32_S_DATA
CH 6 Memory test data Reserved register address modifier.
Definition at line 633 of file cvt_V1724.h.
#define CVT_V1724_CH6_RESERVED_MEM_DATA_DATA_SIZE cvD32
CH 6 Memory test data Reserved register data size.
Definition at line 432 of file cvt_V1724.h.
#define CVT_V1724_CH6_RESERVED_RND_ACC_ADD 0x1614
CH 6 Read Block channel broadcast reserved register relative address.
Definition at line 226 of file cvt_V1724.h.
#define CVT_V1724_CH6_RESERVED_RND_ACC_AM cvA32_S_DATA
CH 6 Read Block channel broadcast reserved register address modifier.
Definition at line 623 of file cvt_V1724.h.
#define CVT_V1724_CH6_RESERVED_RND_ACC_DATA_SIZE cvD32
CH 6 Read Block channel broadcast reserved register data size.
Definition at line 422 of file cvt_V1724.h.
#define CVT_V1724_CH6_STATUS_ADD 0x1688
CH 6 status register relative address.
Definition at line 230 of file cvt_V1724.h.
#define CVT_V1724_CH6_STATUS_AM cvA32_S_DATA
CH 6 status register address modifier.
Definition at line 627 of file cvt_V1724.h.
#define CVT_V1724_CH6_STATUS_DATA_SIZE cvD32
CH 6 status register data size.
Definition at line 426 of file cvt_V1724.h.
#define CVT_V1724_CH6_THRESHOLD_ADD 0x1680
CH 6 Threshold register relative address.
Definition at line 228 of file cvt_V1724.h.
#define CVT_V1724_CH6_THRESHOLD_AM cvA32_S_DATA
CH 6 Threshold register address modifier.
Definition at line 625 of file cvt_V1724.h.
#define CVT_V1724_CH6_THRESHOLD_DATA_SIZE cvD32
CH 6 Threshold register data size.
Definition at line 424 of file cvt_V1724.h.
#define CVT_V1724_CH6_TIME_OVER_UNDER_THR_ADD 0x1684
CH 6 Over/Under Threshold Samples register relative address.
Definition at line 229 of file cvt_V1724.h.
#define CVT_V1724_CH6_TIME_OVER_UNDER_THR_AM cvA32_S_DATA
CH 6 Over/Under Threshold Samples register address modifier.
Definition at line 626 of file cvt_V1724.h.
#define CVT_V1724_CH6_TIME_OVER_UNDER_THR_DATA_SIZE cvD32
CH 6 Over/Under Threshold Samples register data size.
Definition at line 425 of file cvt_V1724.h.
#define CVT_V1724_CH6_ZSTH_ADD 0x1624
CH 6 Zero suppression threshold register relative address.
Definition at line 227 of file cvt_V1724.h.
#define CVT_V1724_CH6_ZSTH_AM cvA32_S_DATA
CH 6 Zero suppression threshold register address modifier.
Definition at line 624 of file cvt_V1724.h.
#define CVT_V1724_CH6_ZSTH_DATA_SIZE cvD32
Ch 6 Zero suppression threshold register data size).
Definition at line 423 of file cvt_V1724.h.
#define CVT_V1724_CH7_ADC_CONF_ADD 0x179C
CH 7 Configuration register relative address.
Definition at line 248 of file cvt_V1724.h.
#define CVT_V1724_CH7_ADC_CONF_AM cvA32_S_DATA
CH 7 Configuration register address modifier.
Definition at line 646 of file cvt_V1724.h.
#define CVT_V1724_CH7_ADC_CONF_DATA_SIZE cvD32
CH 7 Configuration register data size.
Definition at line 445 of file cvt_V1724.h.
#define CVT_V1724_CH7_BUFF_OCCUPANCY_ADD 0x1794
CH 7 Number of Buffers Filled register relative address.
Definition at line 246 of file cvt_V1724.h.
#define CVT_V1724_CH7_BUFF_OCCUPANCY_AM cvA32_S_DATA
CH 7 Number of Buffers Filled register address modifier.
Definition at line 644 of file cvt_V1724.h.
#define CVT_V1724_CH7_BUFF_OCCUPANCY_DATA_SIZE cvD32
CH 7 Number of Buffers Filled register data size.
Definition at line 443 of file cvt_V1724.h.
#define CVT_V1724_CH7_DAC_CONF_ADD 0x1798
CH 7 DAC Data Configuration register relative address.
Definition at line 247 of file cvt_V1724.h.
#define CVT_V1724_CH7_DAC_CONF_AM cvA32_S_DATA
CH 7 DAC Data Configuration register address modifier.
Definition at line 645 of file cvt_V1724.h.
#define CVT_V1724_CH7_DAC_CONF_DATA_SIZE cvD32
CH 7 DAC Data Configuration register data size.
Definition at line 444 of file cvt_V1724.h.
#define CVT_V1724_CH7_FW_REV_ADD 0x178C
CH 7 firmware revision register relative address.
Definition at line 245 of file cvt_V1724.h.
#define CVT_V1724_CH7_FW_REV_AM cvA32_S_DATA
CH 7 firmware revision register address modifier.
Definition at line 643 of file cvt_V1724.h.
#define CVT_V1724_CH7_FW_REV_DATA_SIZE cvD32
CH 7 firmware revision register data size.
Definition at line 442 of file cvt_V1724.h.
#define CVT_V1724_CH7_RESERVED_ADC_DEBUG_ADD 0x17A0
CH 7 ADC Debug Reserved register relative address.
Definition at line 249 of file cvt_V1724.h.
#define CVT_V1724_CH7_RESERVED_ADC_DEBUG_AM cvA32_S_DATA
CH 7 ADC Debug Reserved register address modifier.
Definition at line 647 of file cvt_V1724.h.
#define CVT_V1724_CH7_RESERVED_ADC_DEBUG_DATA_SIZE cvD32
CH 7 ADC Debug Reserved register data size.
Definition at line 446 of file cvt_V1724.h.
#define CVT_V1724_CH7_RESERVED_MEM_ADDRESS_ADD 0x17A8
CH 7 Memory test address Reserved register relative address.
Definition at line 251 of file cvt_V1724.h.
#define CVT_V1724_CH7_RESERVED_MEM_ADDRESS_AM cvA32_S_DATA
CH 7 Memory test address Reserved register address modifier.
Definition at line 649 of file cvt_V1724.h.
#define CVT_V1724_CH7_RESERVED_MEM_ADDRESS_DATA_SIZE cvD32
CH 7 Memory test address Reserved register data size.
Definition at line 448 of file cvt_V1724.h.
#define CVT_V1724_CH7_RESERVED_MEM_DATA_ADD 0x17A4
CH 7 Memory test data Reserved register relative address.
Definition at line 250 of file cvt_V1724.h.
#define CVT_V1724_CH7_RESERVED_MEM_DATA_AM cvA32_S_DATA
CH 7 Memory test data Reserved register address modifier.
Definition at line 648 of file cvt_V1724.h.
#define CVT_V1724_CH7_RESERVED_MEM_DATA_DATA_SIZE cvD32
CH 7 Memory test data Reserved register data size.
Definition at line 447 of file cvt_V1724.h.
#define CVT_V1724_CH7_RESERVED_RND_ACC_ADD 0x1714
CH 7 Read Block channel broadcast reserved register relative address.
Definition at line 240 of file cvt_V1724.h.
#define CVT_V1724_CH7_RESERVED_RND_ACC_AM cvA32_S_DATA
CH 7 Read Block channel broadcast reserved register address modifier.
Definition at line 638 of file cvt_V1724.h.
#define CVT_V1724_CH7_RESERVED_RND_ACC_DATA_SIZE cvD32
CH 7 Read Block channel broadcast reserved register data size.
Definition at line 437 of file cvt_V1724.h.
#define CVT_V1724_CH7_STATUS_ADD 0x1788
CH 7 status register relative address.
Definition at line 244 of file cvt_V1724.h.
#define CVT_V1724_CH7_STATUS_AM cvA32_S_DATA
CH 7 status register address modifier.
Definition at line 642 of file cvt_V1724.h.
#define CVT_V1724_CH7_STATUS_DATA_SIZE cvD32
CH 7 status register data size.
Definition at line 441 of file cvt_V1724.h.
#define CVT_V1724_CH7_THRESHOLD_ADD 0x1780
CH 7 Threshold register relative address.
Definition at line 242 of file cvt_V1724.h.
#define CVT_V1724_CH7_THRESHOLD_AM cvA32_S_DATA
CH 7 Threshold register address modifier.
Definition at line 640 of file cvt_V1724.h.
#define CVT_V1724_CH7_THRESHOLD_DATA_SIZE cvD32
CH 7 Threshold register data size.
Definition at line 439 of file cvt_V1724.h.
#define CVT_V1724_CH7_TIME_OVER_UNDER_THR_ADD 0x1784
CH 7 Over/Under Threshold Samples register relative address.
Definition at line 243 of file cvt_V1724.h.
#define CVT_V1724_CH7_TIME_OVER_UNDER_THR_AM cvA32_S_DATA
CH 7 Over/Under Threshold Samples register address modifier.
Definition at line 641 of file cvt_V1724.h.
#define CVT_V1724_CH7_TIME_OVER_UNDER_THR_DATA_SIZE cvD32
CH 7 Over/Under Threshold Samples register data size.
Definition at line 440 of file cvt_V1724.h.
#define CVT_V1724_CH7_ZSTH_ADD 0x1724
CH 7 Zero suppression threshold register relative address.
Definition at line 241 of file cvt_V1724.h.
#define CVT_V1724_CH7_ZSTH_AM cvA32_S_DATA
CH 7 Zero suppression threshold register address modifier.
Definition at line 639 of file cvt_V1724.h.
#define CVT_V1724_CH7_ZSTH_DATA_SIZE cvD32
Ch 7 Zero suppression threshold register data size).
Definition at line 438 of file cvt_V1724.h.
#define CVT_V1724_CH_ENABLE_ADD 0x8120
Channel enable mask register relative address.
Definition at line 91 of file cvt_V1724.h.
#define CVT_V1724_CH_ENABLE_AM cvA32_S_DATA
Channel enable mask register address modifier.
Definition at line 482 of file cvt_V1724.h.
#define CVT_V1724_CH_ENABLE_DATA_SIZE cvD32
Channel enable mask register data size.
Definition at line 281 of file cvt_V1724.h.
#define CVT_V1724_DOWNSAMPLE_FACT_ADD 0x8128
DownSample factor register relative address.
Definition at line 93 of file cvt_V1724.h.
#define CVT_V1724_DOWNSAMPLE_FACT_AM cvA32_S_DATA
DownSample factor register address modifier.
Definition at line 484 of file cvt_V1724.h.
#define CVT_V1724_DOWNSAMPLE_FACT_DATA_SIZE cvD32
DownSample factor register data size.
Definition at line 283 of file cvt_V1724.h.
#define CVT_V1724_EVENT_STORED_ADD 0x812C
Event stored register relative address.
Definition at line 94 of file cvt_V1724.h.
#define CVT_V1724_EVENT_STORED_AM cvA32_S_DATA
Event stored register address modifier.
Definition at line 485 of file cvt_V1724.h.
#define CVT_V1724_EVENT_STORED_DATA_SIZE cvD32
Event stored register data size.
Definition at line 284 of file cvt_V1724.h.
#define CVT_V1724_FLASH_DATA_ADD 0xEF30
Flash data relative address.
Definition at line 113 of file cvt_V1724.h.
#define CVT_V1724_FLASH_DATA_AM cvA32_S_DATA
Flash data address modifier.
Definition at line 504 of file cvt_V1724.h.
#define CVT_V1724_FLASH_DATA_DATA_SIZE cvD32
Flash data data size.
Definition at line 303 of file cvt_V1724.h.
#define CVT_V1724_FLASH_EN_ADD 0xEF2C
Flash enable relative address.
Definition at line 112 of file cvt_V1724.h.
#define CVT_V1724_FLASH_EN_AM cvA32_S_DATA
Flash enable address modifier.
Definition at line 503 of file cvt_V1724.h.
#define CVT_V1724_FLASH_EN_DATA_SIZE cvD32
Flash enable data size.
Definition at line 302 of file cvt_V1724.h.
#define CVT_V1724_FP_TRIGGER_OUT_ENABLE_ADD 0x8110
Front panel trigger out enable mask register relative address.
Definition at line 87 of file cvt_V1724.h.
#define CVT_V1724_FP_TRIGGER_OUT_ENABLE_AM cvA32_S_DATA
Front panel trigger out enable mask register address modifier.
Definition at line 478 of file cvt_V1724.h.
#define CVT_V1724_FP_TRIGGER_OUT_ENABLE_DATA_SIZE cvD32
Front panel trigger out enable mask register data size.
Definition at line 277 of file cvt_V1724.h.
#define CVT_V1724_FRONT_PANEL_IO_ADD 0x8118
Front panel IO register relative address.
Definition at line 89 of file cvt_V1724.h.
#define CVT_V1724_FRONT_PANEL_IO_AM cvA32_S_DATA
Front panel IO register address modifier.
Definition at line 480 of file cvt_V1724.h.
#define CVT_V1724_FRONT_PANEL_IO_CTRL_ADD 0x811C
Front panel IO Control register relative address.
Definition at line 90 of file cvt_V1724.h.
#define CVT_V1724_FRONT_PANEL_IO_CTRL_AM cvA32_S_DATA
Front panel IO Control register address modifier.
Definition at line 481 of file cvt_V1724.h.
#define CVT_V1724_FRONT_PANEL_IO_CTRL_DATA_SIZE cvD32
Front panel IO Control register data size.
Definition at line 280 of file cvt_V1724.h.
#define CVT_V1724_FRONT_PANEL_IO_DATA_SIZE cvD32
Front panel IO register data size.
Definition at line 279 of file cvt_V1724.h.
#define CVT_V1724_FW_REV_ADD 0x8124
Firmware Revision register relative address.
Definition at line 92 of file cvt_V1724.h.
#define CVT_V1724_FW_REV_AM cvA32_S_DATA
Firmware Revision register address modifier.
Definition at line 483 of file cvt_V1724.h.
#define CVT_V1724_FW_REV_DATA_SIZE cvD32
Firmware Revision register data size.
Definition at line 282 of file cvt_V1724.h.
#define CVT_V1724_GET_ACQCTRL_ACQ_MODE (reg) (((UINT32)reg)& CVT_V1724_ACQCTRL_ACQ_MODE_MSK)
Extract the acquisition mode value from UINT32 value.
Definition at line 999 of file cvt_V1724.h.
#define CVT_V1724_GET_BRDINF_BLOCK_SIZE_KW (reg) (((UINT32)reg)& CVT_V1724_BRDINF_CH_BLOCK_SIZE_MUL_MSK)
Extract the channel block size (as number of KWORD 32) from UINT32 value.
Definition at line 984 of file cvt_V1724.h.
Referenced by V1751Board::GetBoardMemory(), V1740Board::GetBoardMemory(), V1731Board::GetBoardMemory(), V1724Board::GetBoardMemory(), V1721Board::GetBoardMemory(), and V1720Board::GetBoardMemory().
#define CVT_V1724_GET_BRDINF_BLOCK_SIZE_MUL (reg) ((((UINT32)reg)& CVT_V1724_BRDINF_CH_BLOCK_SIZE_MUL_MSK)>> 8)
Extract the channel block size multiplier from UINT32 value.
Definition at line 983 of file cvt_V1724.h.
#define CVT_V1724_GET_BRDINF_ID (reg) (((UINT32)reg)& CVT_V1724_BRDINF_ID_MSK)
Extract the Board info ID from UINT32 value.
Definition at line 982 of file cvt_V1724.h.
#define CVT_V1724_GET_CH_DAC_CONF (reg) (((UINT32)reg)& CVT_V1724_CHDAC_DATA_MSK)
Extract DAC's data from UINT32 value.
Definition at line 1129 of file cvt_V1724.h.
#define CVT_V1724_GET_CH_RND_ACC_BLOCK_ADD (reg) (((UINT32)reg)& CVT_V1724_BROAD_CHRNDACC_BLOCK_ADD_MSK)
Extract the Address of Block to be read from UINT32 value.
Definition at line 962 of file cvt_V1724.h.
#define CVT_V1724_GET_CH_RND_ACC_OFFSET (reg) ((((UINT32)reg)& CVT_V1724_BROAD_CHRNDACC_OFFSET_MSK)>> 22)
Extract the Offset of Address Data from UINT32 value.
Definition at line 968 of file cvt_V1724.h.
#define CVT_V1724_GET_CH_RND_ACC_SAMPLE_NUM (reg) ((((UINT32)reg)& CVT_V1724_BROAD_CHRNDACC_SAMPLE_NUM_MSK)>> 10)
Extract the Number of samples to be read from UINT32 value.
Definition at line 965 of file cvt_V1724.h.
#define CVT_V1724_GET_EVENT_ACTIVE_CHANNELS (data_1) ((UINT32)(((UINT32)data_1)& 0x000000ff))
Gets the active channel mask of this event.
Definition at line 1392 of file cvt_V1724.h.
#define CVT_V1724_GET_EVENT_BOARD_ID (data_1) ((UINT32)((((UINT32)data_1)>>27)& 0x0000001f))
Gets the board id of this event.
Definition at line 1393 of file cvt_V1724.h.
#define CVT_V1724_GET_EVENT_COUNT (data_2) ((UINT32)(((UINT32)data_2)& 0x00ffffff))
Gets the counter of this event.
Definition at line 1395 of file cvt_V1724.h.
#define CVT_V1724_GET_EVENT_SIZE (data_0) ((UINT32)(((UINT32)data_0)& 0x0fffffff))
Gets the size of this event.
Definition at line 1390 of file cvt_V1724.h.
#define CVT_V1724_GET_EVENT_TAG (data_0) ((UINT32)((((UINT32)data_0)>>28)& 0x0000000f))
Gets the tag of this event.
Definition at line 1389 of file cvt_V1724.h.
#define CVT_V1724_GET_EVENT_TRIGGER_TIME_TAG (data_3) ((UINT32)(((UINT32)data_3)& 0xffffffff))
Gets the Trigger time tag of this event.
Definition at line 1397 of file cvt_V1724.h.
#define CVT_V1724_GET_FPIO_CTRL_DIR (reg) ((((UINT32)reg)& CVT_V1724_FPIO_CTRL_DIR_MSK)>> 2)
Extract the Front panel IO direction from UINT32 value.
Definition at line 1098 of file cvt_V1724.h.
#define CVT_V1724_GET_FPIO_CTRL_MODE (reg) ((((UINT32)reg)& CVT_V1724_FPIO_CTRL_MODE_MSK)>> 6)
Extract the Front panel IO mode from UINT32 value.
Definition at line 1101 of file cvt_V1724.h.
#define CVT_V1724_GET_FRONT_PANEL_IO (reg) (((UINT32)reg)& CVT_V1724_FPIO_MSK)
Extract front panel data from UINT32 value.
Definition at line 1082 of file cvt_V1724.h.
#define CVT_V1724_GET_INT_LEVEL (reg) (((UINT32)reg)& CVT_V1724_VME_CTRL_INT_LEVEL_MSK)
Extract the interrupt level from UINT32 value.
Definition at line 880 of file cvt_V1724.h.
#define CVT_V1724_GET_MCST_CBLT_ADD (reg) (((UINT32)reg)& CVT_V1724_MCST_CBLT_ADD_MSK)
Extract the Base Address of from UINT32 value.
Definition at line 1242 of file cvt_V1724.h.
#define CVT_V1724_GET_MCST_CBLT_CTRL (reg) ((((UINT32)reg)& CVT_V1724_MCST_CBLT_CTRL_MSK)>> 8)
Extract the MCST-CBLT Control from UINT32 value.
Definition at line 1245 of file cvt_V1724.h.
#define CVT_V1724_INT_EVENT_NUM_ADD 0xEF18
Interrupt event number register relative address.
Definition at line 107 of file cvt_V1724.h.
#define CVT_V1724_INT_EVENT_NUM_AM cvA32_S_DATA
Interrupt event number register address modifier.
Definition at line 498 of file cvt_V1724.h.
#define CVT_V1724_INT_EVENT_NUM_DATA_SIZE cvD32
Interrupt event number register data size.
Definition at line 297 of file cvt_V1724.h.
#define CVT_V1724_INT_STATUS_ID_ADD 0xEF14
Interrupt status id register relative address.
Definition at line 106 of file cvt_V1724.h.
#define CVT_V1724_INT_STATUS_ID_AM cvA32_S_DATA
Interrupt status id register address modifier.
Definition at line 497 of file cvt_V1724.h.
#define CVT_V1724_INT_STATUS_ID_DATA_SIZE cvD32
Interrupt status id register data size.
Definition at line 296 of file cvt_V1724.h.
#define CVT_V1724_IS_HEADER_TAG (data_0) ((data_0& 0xF0000000)== V1724_HEADER_TAG_MSK)
Checks if type is header tag.
Definition at line 1387 of file cvt_V1724.h.
#define CVT_V1724_MAX_BLT_EVENT_NUM 4
The maximum number of blt_event per readout cycle.
Definition at line 1413 of file cvt_V1724.h.
#define CVT_V1724_MAX_CHANNEL 8
The number of channels.
Definition at line 865 of file cvt_V1724.h.
Referenced by V1740Board::GetBoardMemory(), V1740Board::LoadConfig(), V1740BoardChannel::WriteChannelTrigger(), V1740BoardChannel::WriteDACOffset(), and V1740Board::WriteSampleBufferSize().
#define CVT_V1724_MCST_CBLT_ADD_CTRL_ADD 0xEF0C
MCST/CBLT Address and control register relative address.
Definition at line 104 of file cvt_V1724.h.
#define CVT_V1724_MCST_CBLT_ADD_CTRL_AM cvA32_S_DATA
MCST/CBLT Address and control register address modifier.
Definition at line 495 of file cvt_V1724.h.
#define CVT_V1724_MCST_CBLT_ADD_CTRL_DATA_SIZE cvD32
MCST/CBLT Address and control register data size.
Definition at line 294 of file cvt_V1724.h.
#define CVT_V1724_MIN_FIRMARE_REV 0x0002
Minimum firmware revision supported by this tool version
Definition at line 1378 of file cvt_V1724.h.
Referenced by V17XXBoard::Init().
#define CVT_V1724_MON_MODE_ADD 0x8144
Monitor output mode register relative address.
Definition at line 98 of file cvt_V1724.h.
#define CVT_V1724_MON_MODE_AM cvA32_S_DATA
Monitor output mode register address modifier.
Definition at line 489 of file cvt_V1724.h.
#define CVT_V1724_MON_MODE_DATA_SIZE cvD32
Monitor output mode register data size.
Definition at line 288 of file cvt_V1724.h.
#define CVT_V1724_MON_SET_ADD 0x8138
Monitor output set register relative address.
Definition at line 95 of file cvt_V1724.h.
#define CVT_V1724_MON_SET_AM cvA32_S_DATA
Monitor output set register address modifier.
Definition at line 486 of file cvt_V1724.h.
#define CVT_V1724_MON_SET_DATA_SIZE cvD32
Monitor output set register data size.
Definition at line 285 of file cvt_V1724.h.
#define CVT_V1724_OUT_BUFFER_ADD 0x0000
Output buffer relative address.
Definition at line 68 of file cvt_V1724.h.
#define CVT_V1724_OUT_BUFFER_AM cvA32_S_MBLT
Output buffer data buffer address modifier.
Definition at line 457 of file cvt_V1724.h.
#define CVT_V1724_OUT_BUFFER_DATA_SIZE cvD64
Output buffer data buffer.
Definition at line 258 of file cvt_V1724.h.
#define CVT_V1724_POST_TRIG_ADD 0x8114
Post trigger register relative address.
Definition at line 88 of file cvt_V1724.h.
#define CVT_V1724_POST_TRIG_AM cvA32_S_DATA
Post trigger register address modifier.
Definition at line 479 of file cvt_V1724.h.
#define CVT_V1724_POST_TRIG_DATA_SIZE cvD32
Post trigger register data size.
Definition at line 278 of file cvt_V1724.h.
#define CVT_V1724_RELOAD_CONFIG_ADD 0xEF34
Configuration Reload relative address.
Definition at line 114 of file cvt_V1724.h.
#define CVT_V1724_RELOAD_CONFIG_AM cvA32_S_DATA
Configuration Reload address modifier.
Definition at line 505 of file cvt_V1724.h.
#define CVT_V1724_RELOAD_CONFIG_DATA_SIZE cvD32
Configuration Reload data size.
Definition at line 304 of file cvt_V1724.h.
#define CVT_V1724_RELOCATION_ADDRESS_ADD 0xEF10
Relocation address register relative address.
Definition at line 105 of file cvt_V1724.h.
#define CVT_V1724_RELOCATION_ADDRESS_AM cvA32_S_DATA
Relocation address register address modifier.
Definition at line 496 of file cvt_V1724.h.
#define CVT_V1724_RELOCATION_ADDRESS_DATA_SIZE cvD32
Relocation address register data size.
Definition at line 295 of file cvt_V1724.h.
#define CVT_V1724_ROM_BOARD_ID_0_ADD 0xF03C
Configuration ROM Board identifier (LSB) relative address.
Definition at line 131 of file cvt_V1724.h.
Referenced by V17XXBoard::GetBoardId().
#define CVT_V1724_ROM_BOARD_ID_0_AM cvA32_S_DATA
Configuration ROM Board identifier (LSB) address modifier.
Definition at line 522 of file cvt_V1724.h.
Referenced by V17XXBoard::GetBoardId().
#define CVT_V1724_ROM_BOARD_ID_0_DATA_SIZE cvD32
Configuration ROM Board identifier (LSB) data size.
Definition at line 321 of file cvt_V1724.h.
Referenced by V17XXBoard::GetBoardId().
#define CVT_V1724_ROM_BOARD_ID_1_ADD 0xF038
Configuration ROM Board identifier relative address.
Definition at line 130 of file cvt_V1724.h.
Referenced by V17XXBoard::GetBoardId().
#define CVT_V1724_ROM_BOARD_ID_1_AM cvA32_S_DATA
Configuration ROM Board identifier address modifier.
Definition at line 521 of file cvt_V1724.h.
Referenced by V17XXBoard::GetBoardId().
#define CVT_V1724_ROM_BOARD_ID_1_DATA_SIZE cvD32
Configuration ROM Board identifier data size.
Definition at line 320 of file cvt_V1724.h.
Referenced by V17XXBoard::GetBoardId().
#define CVT_V1724_ROM_BOARD_ID_2_ADD 0xF034
Configuration ROM Board identifier (MSB) relative address.
Definition at line 129 of file cvt_V1724.h.
Referenced by V17XXBoard::GetBoardId().
#define CVT_V1724_ROM_BOARD_ID_2_AM cvA32_S_DATA
Configuration ROM Board identifier (MSB) address modifier.
Definition at line 520 of file cvt_V1724.h.
Referenced by V17XXBoard::GetBoardId().
#define CVT_V1724_ROM_BOARD_ID_2_DATA_SIZE cvD32
Configuration ROM Board identifier (MSB) data size.
Definition at line 319 of file cvt_V1724.h.
Referenced by V17XXBoard::GetBoardId().
#define CVT_V1724_ROM_C_CODE_ADD 0xF01C
Configuration ROM c_code relative address.
Definition at line 123 of file cvt_V1724.h.
#define CVT_V1724_ROM_C_CODE_AM cvA32_S_DATA
Configuration ROM c_code address modifier.
Definition at line 514 of file cvt_V1724.h.
#define CVT_V1724_ROM_C_CODE_DATA_SIZE cvD32
Configuration ROM c_code data size.
Definition at line 313 of file cvt_V1724.h.
#define CVT_V1724_ROM_CHKSUM_ADD 0xF000
Configuration ROM checksum relative address.
Definition at line 116 of file cvt_V1724.h.
#define CVT_V1724_ROM_CHKSUM_AM cvA32_S_DATA
Configuration ROM checksum address modifier.
Definition at line 507 of file cvt_V1724.h.
#define CVT_V1724_ROM_CHKSUM_DATA_SIZE cvD32
Configuration ROM checksum data size.
Definition at line 306 of file cvt_V1724.h.
#define CVT_V1724_ROM_CHKSUM_LEN_0_ADD 0xF00C
Configuration ROM checksum length (LSB) relative address.
Definition at line 119 of file cvt_V1724.h.
#define CVT_V1724_ROM_CHKSUM_LEN_0_AM cvA32_S_DATA
Configuration ROM checksum length (LSB) address modifier.
Definition at line 510 of file cvt_V1724.h.
#define CVT_V1724_ROM_CHKSUM_LEN_0_DATA_SIZE cvD32
Configuration ROM checksum length (LSB) data size.
Definition at line 309 of file cvt_V1724.h.
#define CVT_V1724_ROM_CHKSUM_LEN_1_ADD 0xF008
Configuration ROM checksum length relative address.
Definition at line 118 of file cvt_V1724.h.
#define CVT_V1724_ROM_CHKSUM_LEN_1_AM cvA32_S_DATA
Configuration ROM checksum length address modifier.
Definition at line 509 of file cvt_V1724.h.
#define CVT_V1724_ROM_CHKSUM_LEN_1_DATA_SIZE cvD32
Configuration ROM checksum length data size.
Definition at line 308 of file cvt_V1724.h.
#define CVT_V1724_ROM_CHKSUM_LEN_2_ADD 0xF004
Configuration ROM checksum length (MSB) relative address.
Definition at line 117 of file cvt_V1724.h.
#define CVT_V1724_ROM_CHKSUM_LEN_2_AM cvA32_S_DATA
Configuration ROM checksum length (MSB) address modifier.
Definition at line 508 of file cvt_V1724.h.
#define CVT_V1724_ROM_CHKSUM_LEN_2_DATA_SIZE cvD32
Configuration ROM checksum length (MSB) data size.
Definition at line 307 of file cvt_V1724.h.
#define CVT_V1724_ROM_CONST_0_ADD 0xF018
Configuration ROM constant (LSB) relative address.
Definition at line 122 of file cvt_V1724.h.
#define CVT_V1724_ROM_CONST_0_AM cvA32_S_DATA
Configuration ROM constant (LSB) address modifier.
Definition at line 513 of file cvt_V1724.h.
#define CVT_V1724_ROM_CONST_0_DATA_SIZE cvD32
Configuration ROM constant (LSB) data size.
Definition at line 312 of file cvt_V1724.h.
#define CVT_V1724_ROM_CONST_1_ADD 0xF014
Configuration ROM constant relative address.
Definition at line 121 of file cvt_V1724.h.
#define CVT_V1724_ROM_CONST_1_AM cvA32_S_DATA
Configuration ROM constant address modifier.
Definition at line 512 of file cvt_V1724.h.
#define CVT_V1724_ROM_CONST_1_DATA_SIZE cvD32
Configuration ROM constant data size.
Definition at line 311 of file cvt_V1724.h.
#define CVT_V1724_ROM_CONST_2_ADD 0xF010
Configuration ROM constant (MSB) relative address.
Definition at line 120 of file cvt_V1724.h.
#define CVT_V1724_ROM_CONST_2_AM cvA32_S_DATA
Configuration ROM constant (MSB) address modifier.
Definition at line 511 of file cvt_V1724.h.
#define CVT_V1724_ROM_CONST_2_DATA_SIZE cvD32
Configuration ROM constant (MSB) data size.
Definition at line 310 of file cvt_V1724.h.
#define CVT_V1724_ROM_OUI_0_ADD 0xF02C
Configuration ROM Manufacturer identifier (IEEE OUI) (LSB) relative address.
Definition at line 127 of file cvt_V1724.h.
#define CVT_V1724_ROM_OUI_0_AM cvA32_S_DATA
Configuration ROM Manufacturer identifier (IEEE OUI) (LSB) address modifier.
Definition at line 518 of file cvt_V1724.h.
#define CVT_V1724_ROM_OUI_0_DATA_SIZE cvD32
Configuration ROM Manufacturer identifier (IEEE OUI) (LSB) data size.
Definition at line 317 of file cvt_V1724.h.
#define CVT_V1724_ROM_OUI_1_ADD 0xF028
Configuration ROM Manufacturer identifier (IEEE OUI) relative address.
Definition at line 126 of file cvt_V1724.h.
#define CVT_V1724_ROM_OUI_1_AM cvA32_S_DATA
Configuration ROM Manufacturer identifier (IEEE OUI) address modifier.
Definition at line 517 of file cvt_V1724.h.
#define CVT_V1724_ROM_OUI_1_DATA_SIZE cvD32
Configuration ROM Manufacturer identifier (IEEE OUI) data size.
Definition at line 316 of file cvt_V1724.h.
#define CVT_V1724_ROM_OUI_2_ADD 0xF024
Configuration ROM Manufacturer identifier (IEEE OUI) (MSB) relative address.
Definition at line 125 of file cvt_V1724.h.
#define CVT_V1724_ROM_OUI_2_AM cvA32_S_DATA
Configuration ROM Manufacturer identifier (IEEE OUI) (MSB) address modifier.
Definition at line 516 of file cvt_V1724.h.
#define CVT_V1724_ROM_OUI_2_DATA_SIZE cvD32
Configuration ROM Manufacturer identifier (IEEE OUI) (MSB) data size.
Definition at line 315 of file cvt_V1724.h.
#define CVT_V1724_ROM_R_CODE_ADD 0xF020
Configuration ROM r_code relative address.
Definition at line 124 of file cvt_V1724.h.
#define CVT_V1724_ROM_R_CODE_AM cvA32_S_DATA
Configuration ROM r_code address modifier.
Definition at line 515 of file cvt_V1724.h.
#define CVT_V1724_ROM_R_CODE_DATA_SIZE cvD32
Configuration ROM r_code data size.
Definition at line 314 of file cvt_V1724.h.
#define CVT_V1724_ROM_REVISION_0_ADD 0xF04C
Configuration ROM Hardware revision identifier relative address.
Definition at line 135 of file cvt_V1724.h.
#define CVT_V1724_ROM_REVISION_0_AM cvA32_S_DATA
Configuration ROM Hardware revision identifier address modifier.
Definition at line 526 of file cvt_V1724.h.
#define CVT_V1724_ROM_REVISION_0_DATA_SIZE cvD32
Configuration ROM Hardware revision identifier data size.
Definition at line 325 of file cvt_V1724.h.
#define CVT_V1724_ROM_REVISION_1_ADD 0xF048
Configuration ROM Hardware revision identifier relative address.
Definition at line 134 of file cvt_V1724.h.
#define CVT_V1724_ROM_REVISION_1_AM cvA32_S_DATA
Configuration ROM Hardware revision identifier address modifier.
Definition at line 525 of file cvt_V1724.h.
#define CVT_V1724_ROM_REVISION_1_DATA_SIZE cvD32
Configuration ROM Hardware revision identifier data size.
Definition at line 324 of file cvt_V1724.h.
#define CVT_V1724_ROM_REVISION_2_ADD 0xF044
Configuration ROM Hardware revision identifier relative address.
Definition at line 133 of file cvt_V1724.h.
#define CVT_V1724_ROM_REVISION_2_AM cvA32_S_DATA
Configuration ROM Hardware revision identifier address modifier.
Definition at line 524 of file cvt_V1724.h.
#define CVT_V1724_ROM_REVISION_2_DATA_SIZE cvD32
Configuration ROM Hardware revision identifier data size.
Definition at line 323 of file cvt_V1724.h.
#define CVT_V1724_ROM_REVISION_3_ADD 0xF040
Configuration ROM Hardware revision identifier relative address.
Definition at line 132 of file cvt_V1724.h.
#define CVT_V1724_ROM_REVISION_3_AM cvA32_S_DATA
Configuration ROM Hardware revision identifier address modifier.
Definition at line 523 of file cvt_V1724.h.
#define CVT_V1724_ROM_REVISION_3_DATA_SIZE cvD32
Configuration ROM Hardware revision identifier data size.
Definition at line 322 of file cvt_V1724.h.
#define CVT_V1724_ROM_SERIAL_0_ADD 0xF084
Configuration ROM Serial number (LSB) relative address.
Definition at line 137 of file cvt_V1724.h.
#define CVT_V1724_ROM_SERIAL_0_AM cvA32_S_DATA
Configuration ROM Serial number (LSB) address modifier.
Definition at line 528 of file cvt_V1724.h.
#define CVT_V1724_ROM_SERIAL_0_DATA_SIZE cvD32
Configuration ROM Serial number (LSB) data size.
Definition at line 327 of file cvt_V1724.h.
#define CVT_V1724_ROM_SERIAL_1_ADD 0xF080
Configuration ROM Serial number (MSB) relative address.
Definition at line 136 of file cvt_V1724.h.
#define CVT_V1724_ROM_SERIAL_1_AM cvA32_S_DATA
Configuration ROM Serial number (MSB) address modifier.
Definition at line 527 of file cvt_V1724.h.
#define CVT_V1724_ROM_SERIAL_1_DATA_SIZE cvD32
Configuration ROM Serial number (MSB) data size.
Definition at line 326 of file cvt_V1724.h.
#define CVT_V1724_ROM_VCXO_TYPE_ADD 0xF088
Configuration ROM VCXO type relative address.
Definition at line 138 of file cvt_V1724.h.
#define CVT_V1724_ROM_VCXO_TYPE_AM cvA32_S_DATA
Configuration ROM VCXO type address modifier.
Definition at line 529 of file cvt_V1724.h.
#define CVT_V1724_ROM_VCXO_TYPE_DATA_SIZE cvD32
Configuration ROM VCXO type data size.
Definition at line 328 of file cvt_V1724.h.
#define CVT_V1724_ROM_VERSION_ADD 0xF030
Configuration ROM Purchased version of the Mod.V1724 relative address.
Definition at line 128 of file cvt_V1724.h.
#define CVT_V1724_ROM_VERSION_AM cvA32_S_DATA
Configuration ROM Purchased version of the Mod.V1724 address modifier.
Definition at line 519 of file cvt_V1724.h.
#define CVT_V1724_ROM_VERSION_DATA_SIZE cvD32
Configuration ROM Purchased version of the Mod.V1724 data size.
Definition at line 318 of file cvt_V1724.h.
#define CVT_V1724_SCRATCH_ADD 0xEF20
Scratch register relative address.
Definition at line 109 of file cvt_V1724.h.
#define CVT_V1724_SCRATCH_AM cvA32_S_DATA
Scratch register address modifier.
Definition at line 500 of file cvt_V1724.h.
#define CVT_V1724_SCRATCH_DATA_SIZE cvD32
Scratch register data size.
Definition at line 299 of file cvt_V1724.h.
#define CVT_V1724_SET_ACQCTRL_ACQ_MODE (reg, value) reg= (((UINT32)reg)& ~CVT_V1724_ACQCTRL_ACQ_MODE_MSK)| ((UINT32)value& CVT_V1724_ACQCTRL_ACQ_MODE_MSK)
Sets the acquisition mode value into UINT32 value.
Definition at line 1000 of file cvt_V1724.h.
#define CVT_V1724_SET_CH_DAC_CONF (reg, value) reg= (((UINT32)reg)& ~CVT_V1724_CHDAC_DATA_MSK)| ((UINT32)value& CVT_V1724_CHDAC_DATA_MSK)
Sets DAC's data into UINT32 value.
Definition at line 1130 of file cvt_V1724.h.
#define CVT_V1724_SET_CH_RND_ACC_BLOCK_ADD (reg, value) reg= (((UINT32)reg)& ~CVT_V1724_BROAD_CHRNDACC_BLOCK_ADD_MSK)| ((UINT32)value& CVT_V1724_BROAD_CHRNDACC_BLOCK_ADD_MSK)
Sets the Address of Block to be read into UINT32 value.
Definition at line 963 of file cvt_V1724.h.
#define CVT_V1724_SET_CH_RND_ACC_OFFSET (reg, value) reg= (((UINT32)reg)& ~CVT_V1724_BROAD_CHRNDACC_OFFSET_MSK)| ((((UINT32)value)<< 22)& CVT_V1724_BROAD_CHRNDACC_OFFSET_MSK)
Sets the Offset of Address Data into UINT32 value.
Definition at line 969 of file cvt_V1724.h.
#define CVT_V1724_SET_CH_RND_ACC_SAMPLE_NUM (reg, value) reg= (((UINT32)reg)& ~CVT_V1724_BROAD_CHRNDACC_SAMPLE_NUM_MSK)| ((((UINT32)value)<< 10)& CVT_V1724_BROAD_CHRNDACC_SAMPLE_NUM_MSK)
Sets the Number of samples to be read into UINT32 value.
Definition at line 966 of file cvt_V1724.h.
#define CVT_V1724_SET_FPIO_CTRL_DIR (reg, value) reg= (((UINT32)reg)& ~CVT_V1724_FPIO_CTRL_DIR_MSK)| ((((UINT32)value)<< 2)& CVT_V1724_FPIO_CTRL_DIR_MSK)
Sets the Front panel IO direction into UINT32 value.
Definition at line 1099 of file cvt_V1724.h.
#define CVT_V1724_SET_FPIO_CTRL_MODE (reg, value) reg= (((UINT32)reg)& ~CVT_V1724_FPIO_CTRL_MODE_MSK)| ((((UINT32)value)<< 6)& CVT_V1724_FPIO_CTRL_MODE_MSK)
Sets the Front panel IO mode into UINT32 value.
Definition at line 1102 of file cvt_V1724.h.
#define CVT_V1724_SET_FRONT_PANEL_IO (reg, value) reg= (((UINT32)reg)& ~CVT_V1724_FPIO_MSK)| ((UINT32)value& CVT_V1724_FPIO_MSK)
Sets front panel data into UINT32 value.
Definition at line 1083 of file cvt_V1724.h.
#define CVT_V1724_SET_INT_LEVEL (reg, value) reg= (((UINT32)reg)& ~CVT_V1724_VME_CTRL_INT_LEVEL_MSK)| ((UINT32)value& CVT_V1724_VME_CTRL_INT_LEVEL_MSK)
Sets the interrupt level value into UINT32 value.
Definition at line 881 of file cvt_V1724.h.
#define CVT_V1724_SET_MCST_CBLT_ADD (reg, value) reg= (((UINT32)reg)& ~CVT_V1724_MCST_CBLT_ADD_MSK)| ((UINT32)value& CVT_V1724_MCST_CBLT_ADD_MSK)
Sets the Base Address into UINT32 value.
Definition at line 1243 of file cvt_V1724.h.
#define CVT_V1724_SET_MCST_CBLT_CTRL (reg, value) reg= (((UINT32)reg)& ~CVT_V1724_MCST_CBLT_CTRL_MSK)| ((((UINT32)value)<< 8)& CVT_V1724_MCST_CBLT_CTRL_MSK)
Sets MCST-CBLT Control into UINT32 value.
Definition at line 1246 of file cvt_V1724.h.
#define CVT_V1724_SW_CLEAR_ADD 0xEF28
Software clear register relative address.
Definition at line 111 of file cvt_V1724.h.
#define CVT_V1724_SW_CLEAR_AM cvA32_S_DATA
Software clear register address modifier.
Definition at line 502 of file cvt_V1724.h.
#define CVT_V1724_SW_CLEAR_DATA_SIZE cvD32
Software clear register data size.
Definition at line 301 of file cvt_V1724.h.
#define CVT_V1724_SW_RESET_ADD 0xEF24
Software reset register relative address.
Definition at line 110 of file cvt_V1724.h.
#define CVT_V1724_SW_RESET_AM cvA32_S_DATA
Software reset register address modifier.
Definition at line 501 of file cvt_V1724.h.
#define CVT_V1724_SW_RESET_DATA_SIZE cvD32
Software reset register data size.
Definition at line 300 of file cvt_V1724.h.
#define CVT_V1724_SW_SYNC_ADD 0x813C
Sw sync register relative address.
Definition at line 96 of file cvt_V1724.h.
#define CVT_V1724_SW_SYNC_AM cvA32_S_DATA
Sw sync register address modifier.
Definition at line 487 of file cvt_V1724.h.
#define CVT_V1724_SW_SYNC_DATA_SIZE cvD32
Sw sync register data size.
Definition at line 286 of file cvt_V1724.h.
#define CVT_V1724_SW_TRIGGER_ADD 0x8108
Software trigger register relative address.
Definition at line 85 of file cvt_V1724.h.
#define CVT_V1724_SW_TRIGGER_AM cvA32_S_DATA
Software trigger register address modifier.
Definition at line 476 of file cvt_V1724.h.
#define CVT_V1724_SW_TRIGGER_DATA_SIZE cvD32
Software trigger register data size.
Definition at line 275 of file cvt_V1724.h.
#define CVT_V1724_TEST_IO_ADD 0x8168
I/O Test register relative address.
Definition at line 99 of file cvt_V1724.h.
#define CVT_V1724_TEST_IO_AM cvA32_S_DATA
I/O Test register address modifier.
Definition at line 490 of file cvt_V1724.h.
#define CVT_V1724_TEST_IO_DATA_SIZE cvD32
I/O Test register data size.
Definition at line 289 of file cvt_V1724.h.
#define CVT_V1724_THRESHOLD_NUM 8
Number of threshold registers.
Definition at line 23 of file cvt_V1724.h.
#define CVT_V1724_TRIGGER_SRC_ENABLE_ADD 0x810C
Trigger source enable register relative address.
Definition at line 86 of file cvt_V1724.h.
#define CVT_V1724_TRIGGER_SRC_ENABLE_AM cvA32_S_DATA
Trigger source enable register address modifier.
Definition at line 477 of file cvt_V1724.h.
#define CVT_V1724_TRIGGER_SRC_ENABLE_DATA_SIZE cvD32
Trigger source enable register data size.
Definition at line 276 of file cvt_V1724.h.
#define CVT_V1724_VME_CONTROL_ADD 0xEF00
VME Control register relative address.
Definition at line 101 of file cvt_V1724.h.
#define CVT_V1724_VME_CONTROL_AM cvA32_S_DATA
VME Control register address modifier.
Definition at line 492 of file cvt_V1724.h.
#define CVT_V1724_VME_CONTROL_DATA_SIZE cvD32
VME Control register data size.
Definition at line 291 of file cvt_V1724.h.
#define CVT_V1724_VME_STATUS_ADD 0xEF04
VME Status register relative address.
Definition at line 102 of file cvt_V1724.h.
#define CVT_V1724_VME_STATUS_AM cvA32_S_DATA
VME Status register address modifier.
Definition at line 493 of file cvt_V1724.h.
#define CVT_V1724_VME_STATUS_DATA_SIZE cvD32
VME Status register data size.
Definition at line 292 of file cvt_V1724.h.
#define PACKED_1
Definition at line 1404 of file cvt_V1724.h.
#define V1724_FLASH_PAGE_SIZE 264
V1724 Flash programming V1724 flash page size
Definition at line 1267 of file cvt_V1724.h.
#define V1724_HEADER_TAG_MSK 0xA0000000
The V1724 Header tag msk.
Definition at line 1385 of file cvt_V1724.h.
Typedef Documentation
typedef union PACKED_1 CVT_V1724_HEADER
Enumeration Type Documentation
enum CVT_V1724_ACQ_CONTROL_ACQ_MODES
CVT_V1724_ACQ_CONTROL_MSK acquisition modes.
Enumerator:
CVT_V1724_ACQCTRL_ACQ_MODE_REGISTER_CTRL
Register controlled acquisition mode
CVT_V1724_ACQCTRL_ACQ_MODE_S_IN_CTRL
S-IN controlled acquisition mode
CVT_V1724_ACQCTRL_ACQ_MODE_S_IN_GATE
S-IN gate acquisition mode
CVT_V1724_ACQCTRL_ACQ_MODE_MULTIBOARD_SYNC
Multiboard sync acquisition mode
Definition at line 1007 of file cvt_V1724.h.
enum CVT_V1724_ACQ_CONTROL_MSK
CVT_V1724_ACQ_CONTROL register bitmasks.
Enumerator:
CVT_V1724_ACQCTRL_ACQ_MODE_MSK
Acqisition mode msk
CVT_V1724_ACQCTRL_START_MSK
0--> Stop acquisition 1--> Start acquisition
CVT_V1724_ACQCTRL_EVENT_COUNTER_ALL_MSK
0--> Event counter counts only generated and accepted triggers 1--> Event counter counts all generated triggers
CVT_V1724_ACQCTRL_DOWNSAMPLE_MSK
Downsample enable bit
Definition at line 991 of file cvt_V1724.h.
enum CVT_V1724_ACQ_STATUS_MSK
CVT_V1724_ACQ_STATUS register bitmasks.
Enumerator:
CVT_V1724_ACQSTS_MEB_NOT_EMPTY_MSK
MEB not empty bit
CVT_V1724_ACQSTS_MEB_FULL_MSK
MEB full bit
CVT_V1724_ACQSTS_RUN_MSK
Run status bit
CVT_V1724_ACQSTS_EVENT_RDY_MSK
Event ready bit
CVT_V1724_ACQSTS_EVENT_FULL_MSK
Event full bit
CVT_V1724_ACQSTS_CLKEXT_MSK
External clock bit
CVT_V1724_ACQSTS_PLL_BYPASS_MSK
PLL Bypass bit
CVT_V1724_ACQSTS_PLL_STATUS_MSK
PLL Status bit
CVT_V1724_ACQSTS_S_IN_MSK
S-IN status bit
Definition at line 1020 of file cvt_V1724.h.
enum CVT_V1724_BOARD_INFO_MSK
CVT_V1724_BOARD_INFO register bitmasks.
Enumerator:
CVT_V1724_BRDINF_ID_MSK
Board info ID bits CVT_V17XX_TYPES
CVT_V1724_BRDINF_CH_BLOCK_SIZE_MUL_MSK
Channel block size multiplier bits (as multiple of 256K WORD 32)
Definition at line 976 of file cvt_V1724.h.
enum CVT_V1724_BROAD_CH_CONTROL_MSK
CVT_V1724_BROAD_CH_CTRL: Control register bitmasks.
Enumerator:
CVT_V1724_BROAD_CHCTRL_GATE_MODE_MSK
Gate mode bit (0 --> Window mode, 1 --> Single mode)
CVT_V1724_BROAD_CHCTRL_TRG_OVERLAP_MSK
Trigger Overlapping enable bit
CVT_V1724_BROAD_CHCTRL_MEM_TEST_ENABLE_MSK
Memory test enabled bit
CVT_V1724_BROAD_CHCTRL_MEM_ACC_MODE_MSK
Memory Access mode bit (0 --> random access mode, 1--> sequential access mode)
CVT_V1724_BROAD_CHCTRL_TRG_OUT_THR_MSK
Trigger Output Threshold mode bit (0 --> Over, 1 --> Under)
CVT_V1724_BROAD_CHCTRL_DES_MODE_MSK
Switch to des mode (4 channel mode) (0 --> Normal mode , 1 --> Des mode) (V1731 only)
Definition at line 940 of file cvt_V1724.h.
enum CVT_V1724_BROAD_CH_RND_ACC_MSK
CVT_V1724_BROAD_CH_RND_ACC register bitmasks.
Enumerator:
CVT_V1724_BROAD_CHRNDACC_BLOCK_ADD_MSK
Address of Block to be read bits
CVT_V1724_BROAD_CHRNDACC_SAMPLE_NUM_MSK
Number of samples to be read bits
CVT_V1724_BROAD_CHRNDACC_OFFSET_MSK
Offset of Address Data to be read bits
Definition at line 955 of file cvt_V1724.h.
enum CVT_V1724_CH_ADC_CONF_MSK
ADC CH Configuration register bitmasks for V1724/V1720 only.
Enumerator:
CVT_V1724_CHADCCONF_DITHER_MSK
CH ADC Dither bit
CVT_V1724_CHADCCONF_CLK_DUTY_STAB_MSK
CH ADC Clock Duty cycle stabilizer bit
CVT_V1724_CHADCCONF_RND_MSK
CH ADC Output Randomize bit
Definition at line 1055 of file cvt_V1724.h.
enum CVT_V1724_CH_ADC_CONF_MSK_2
ADC CH Configuration register bitmasks for V1731/V1721 only.
Enumerator:
CVT_V1724_CHADCCONF_CAL_MSK_2
CH ADC calibration bit
Definition at line 1067 of file cvt_V1724.h.
enum CVT_V1724_CH_ENABLE_MSK
CVT_V1724_CH_ENABLE register bitmasks.
Enumerator:
CVT_V1724_CHEN_CH0_MSK
Enable CH 0 bit
CVT_V1724_CHEN_CH1_MSK
Enable CH 1 bit
CVT_V1724_CHEN_CH2_MSK
Enable CH 2 bit
CVT_V1724_CHEN_CH3_MSK
Enable CH 3 bit
CVT_V1724_CHEN_CH4_MSK
Enable CH 4 bit
CVT_V1724_CHEN_CH5_MSK
Enable CH 5 bit
CVT_V1724_CHEN_CH6_MSK
Enable CH 6 bit
CVT_V1724_CHEN_CH7_MSK
Enable CH 7 bit
Definition at line 1038 of file cvt_V1724.h.
enum CVT_V1724_CH_STATUS_MSK
CH status register bitmasks.
Enumerator:
CVT_V1724_CHSTS_FIFO_FULL_MSK
CH Descriptor FIFO full Status bit
CVT_V1724_CHSTS_FIFO_EMPTY_MSK
CH Descriptor FIFO empty Status bit
CVT_V1724_CHSTS_DAC_BUSY_MSK
CH DAC Busy Status bit
CVT_V1724_CHSTS_BIST_END_MSK
CH BIST end Status bit
CVT_V1724_CHSTS_BIST_OK_MSK
CH BIST result bit
CVT_V1724_CHSTS_BLOCK_REM_OK_MSK
CH Block Remove result bit
CVT_V1724_CHSTS_CAL_RUN_MSK
CH calibration run bit (1 = calibration completed) (V1731/V1721 only)
Definition at line 1137 of file cvt_V1724.h.
enum CVT_V1724_DAC_CONF_MSK
CH DAC data configuration register bitmasks.
Todo:
Bits to define
Enumerator:
CVT_V1724_CHDAC_DATA_MSK
DAC data bits
CVT_V1724_CHDAC_SET_A_MSK
Set data for DAC A
CVT_V1724_CHDAC_SET_B_MSK
Set data for DAC B
Definition at line 1122 of file cvt_V1724.h.
enum CVT_V1724_EXTCLOCK
External clock allowed values.
Enumerator:
CVT_V1724_EXTCLK_10000KHz
10 MHz
CVT_V1724_EXTCLK_40000KHz
40 MHz
CVT_V1724_EXTCLK_50000KHz
50 MHz
CVT_V1724_EXTCLK_62500KHz
62.5 MHz
Definition at line 1173 of file cvt_V1724.h.
enum CVT_V1724_FLASH_BANK
V1724 Flash banks.
Enumerator:
CVT_V1724_ROM_FLASH_PAGE
V1724 ROM flash bank
CVT_V1724_PLL_FLASH_PAGE
V1724 PLL flash bank
CVT_V1724_FB_STANDARD
V1724 firmware standard flash bank
CVT_V1724_FB_BACKUP
V1724 firmware backup flash bank
Definition at line 1288 of file cvt_V1724.h.
enum CVT_V1724_FLASH_EN_MSK
Flash enable register bitmasks.
Enumerator:
CVT_V1724_FLEN_EN_MSK
Flash enable bit
Definition at line 1301 of file cvt_V1724.h.
enum CVT_V1724_FLASH_OPCODES
V1724 Flash register opcodes.
Enumerator:
CVT_V1724_FOP_PAGE_ERASE
V1724 flash page erase
CVT_V1724_FOP_PAGE_PROG_TH_BUF1
V1724 flash page write
CVT_V1724_FOP_PAGE_READ
V1724 flash page read
Definition at line 1275 of file cvt_V1724.h.
enum CVT_V1724_FP_TRIGGER_OUT_ENABLE_MSK
Front Panel Trigger Out enable bitmasks.
Enumerator:
CVT_V1724_FPTRGEN_CH0_MSK
Enable CH 0 trigger bit
CVT_V1724_FPTRGEN_CH1_MSK
Enable CH 1 trigger bit
CVT_V1724_FPTRGEN_CH2_MSK
Enable CH 2 trigger bit
CVT_V1724_FPTRGEN_CH3_MSK
Enable CH 3 trigger bit
CVT_V1724_FPTRGEN_CH4_MSK
Enable CH 4 trigger bit
CVT_V1724_FPTRGEN_CH5_MSK
Enable CH 5 trigger bit
CVT_V1724_FPTRGEN_CH6_MSK
Enable CH 6 trigger bit
CVT_V1724_FPTRGEN_CH7_MSK
Enable CH 7 trigger bit
CVT_V1724_FPTRGEN_EXT_MSK
External trigger enable bit
CVT_V1724_FPTRGEN_SW_MSK
Software trigger enable bit
Definition at line 921 of file cvt_V1724.h.
enum CVT_V1724_FRONT_PANEL_IO_CTRL_MSK
Front Panel IO control register bitmasks.
Enumerator:
CVT_V1724_FPIO_CTRL_TTL_MSK
TTL/NIM external signal bit
CVT_V1724_FPIO_CTRL_OUT_DIS_MSK
Output disable bit
CVT_V1724_FPIO_CTRL_DIR_MSK
Direction msk
CVT_V1724_FPIO_CTRL_MODE_MSK
Mode msk (bit 0x00000100 is don't care)
Definition at line 1090 of file cvt_V1724.h.
enum CVT_V1724_FRONT_PANEL_IO_MODES
Front Panel IO modes.
Enumerator:
CVT_V1724_FPIO_MODES_GPIO
General purpose IO
CVT_V1724_FPIO_MODES_PROGIO
Programmed IO
CVT_V1724_FPIO_MODES_PATTERN
Pattern mode
Definition at line 1109 of file cvt_V1724.h.
enum CVT_V1724_FRONT_PANEL_IO_MSK
Front Panel IO data register bitmasks.
Enumerator:
CVT_V1724_FPIO_MSK
IO data value
Definition at line 1077 of file cvt_V1724.h.
enum CVT_V1724_MCST_CBLT_ADD_CTRL_MSK
V1724 MCST-CBLT Address/Control register bit masks.
Enumerator:
CVT_V1724_MCST_CBLT_ADD_MSK
Address bits mask
CVT_V1724_MCST_CBLT_CTRL_MSK
Control bits mask
Definition at line 1236 of file cvt_V1724.h.
enum CVT_V1724_MCST_CBLT_CTRL_BOARDS
V1724 MCST-CBLT control boards.
Enumerator:
CVT_V1724_MCST_CBLT_CTRL_DISABLED_BOARD
Disabled Board
CVT_V1724_MCST_CBLT_CTRL_LAST_BOARD
Last Board
CVT_V1724_MCST_CBLT_CTRL_FIRST_BOARD
First Board
CVT_V1724_MCST_CBLT_CTRL_MID_BOARD
Middle Board
Definition at line 1254 of file cvt_V1724.h.
enum CVT_V1724_MON_MODES
V1724 Output monitor mode.
Enumerator:
CVT_V1724_MONMODE_TRIGGER_MAJ
V1724 channel trigger majority mode
CVT_V1724_MONMODE_TEST
V1724 channel test mode
CVT_V1724_MONMODE_MONITOR
V1724 channel ADC monitor mode
CVT_V1724_MONMODE_OCCUPANCY
V1724 channel buffer occupancy mode
CVT_V1724_MONMODE_SW_CTRL
V1724 channel direct software monitor control mode
Definition at line 1312 of file cvt_V1724.h.
enum CVT_V1724_NUM_BLOCKS
The number for blocks.
Enumerator:
CVT_V1724_NBLK_1
1 block
CVT_V1724_NBLK_2
2 blocks
CVT_V1724_NBLK_4
4 blocks
CVT_V1724_NBLK_8
8 blocks
CVT_V1724_NBLK_16
16 blocks
CVT_V1724_NBLK_32
32 blocks
CVT_V1724_NBLK_64
64 blocks
CVT_V1724_NBLK_128
128 blocks
CVT_V1724_NBLK_256
256 blocks
CVT_V1724_NBLK_512
512 blocks
CVT_V1724_NBLK_1024
1024 blocks
Definition at line 1153 of file cvt_V1724.h.
enum CVT_V1724_REG_INDEX
The registers indexes.
Provides an entry for each register: This is the index into the CVT_V1724_REG_TABLE board table
Enumerator:
CVT_V1724_OUT_BUFFER_INDEX
Output buffer data buffer index.
CVT_V1724_BROAD_CH_CTRL_INDEX
Control channel broadcast register index.
CVT_V1724_BROAD_CH_SET_CTRL_INDEX
Set control channel broadcast register index.
CVT_V1724_BROAD_CH_CLEAR_CTRL_INDEX
Clear control channel broadcast register index.
CVT_V1724_BROAD_NUM_BLOCK_INDEX
Number of blocks broadcast register index.
CVT_V1724_BROAD_CH_BUFF_FLUSH_INDEX
Number of buffers to be removed channel broadcast register index.
CVT_V1724_BROAD_CH_RND_ACC_INDEX
Parameters to Random access channel broadcast register index.
CVT_V1724_BROAD_CH_CUSSIZE_INDEX
Custom Size threshold channel broadcast register index.
CVT_V1724_BROAD_CH_ZSTH_INDEX
Zero suppression threshold channel broadcast register index.
CVT_V1724_BROAD_ADC_CONF_INDEX
ADC configuration broadcast register register index (Write only).
CVT_V1724_ACQ_CONTROL_INDEX
Acquisiton Control register index.
CVT_V1724_ACQ_STATUS_INDEX
Acquisiton Status register index.
CVT_V1724_SW_TRIGGER_INDEX
Software trigger register index.
CVT_V1724_TRIGGER_SRC_ENABLE_INDEX
Trigger source enable register index.
CVT_V1724_FP_TRIGGER_OUT_ENABLE_INDEX
Front panel trigger out enable mask register index.
CVT_V1724_POST_TRIG_INDEX
Post trigger register index.
CVT_V1724_FRONT_PANEL_IO_INDEX
Front panel IO register index.
CVT_V1724_FRONT_PANEL_IO_CTRL_INDEX
Front panel IO Control register index.
CVT_V1724_CH_ENABLE_INDEX
Channel enable mask register index.
CVT_V1724_FW_REV_INDEX
Firmware Revision register index.
CVT_V1724_DOWNSAMPLE_FACT_INDEX
DownSample factor register index.
CVT_V1724_EVENT_STORED_INDEX
Event stored register index.
CVT_V1724_MON_SET_INDEX
Monitor output set register index.
CVT_V1724_SW_SYNC_INDEX
Sw sync register index.
CVT_V1724_BOARD_INFO_INDEX
Board's information register index.
CVT_V1724_MON_MODE_INDEX
Monitor output mode register index.
CVT_V1724_TEST_IO_INDEX
Test Register for IO verification index.
CVT_V1724_VME_CONTROL_INDEX
VME Control register index.
CVT_V1724_VME_STATUS_INDEX
VME Status register index.
CVT_V1724_BOARD_ID_INDEX
Geo Address register index.
CVT_V1724_MCST_CBLT_ADD_CTRL_INDEX
MCST/CBLT Address and control register index.
CVT_V1724_RELOCATION_ADDRESS_INDEX
Relocation address register index.
CVT_V1724_INT_STATUS_ID_INDEX
Interrupt status id register index.
CVT_V1724_INT_EVENT_NUM_INDEX
Interrupt event number register index.
CVT_V1724_BLT_EVENT_NUM_INDEX
BLT event number register index.
CVT_V1724_SCRATCH_INDEX
Scratch register index.
CVT_V1724_SW_RESET_INDEX
Software reset register index.
CVT_V1724_SW_CLEAR_INDEX
Software clear register index.
CVT_V1724_FLASH_EN_INDEX
Flash enable index.
CVT_V1724_FLASH_DATA_INDEX
Flash data index.
CVT_V1724_RELOAD_CONFIG_INDEX
Configuration Reload index.
CVT_V1724_BASE_ADDRESS_INDEX
Base Address index.
CVT_V1724_ROM_CHKSUM_INDEX
Configuration ROM checksum index.
CVT_V1724_ROM_CHKSUM_LEN_2_INDEX
Configuration ROM checksum length (MSB) index.
CVT_V1724_ROM_CHKSUM_LEN_1_INDEX
Configuration ROM checksum length index.
CVT_V1724_ROM_CHKSUM_LEN_0_INDEX
Configuration ROM checksum length (LSB) index.
CVT_V1724_ROM_CONST_2_INDEX
Configuration ROM constant (MSB) index.
CVT_V1724_ROM_CONST_1_INDEX
Configuration ROM constant index.
CVT_V1724_ROM_CONST_0_INDEX
Configuration ROM constant (LSB) index.
CVT_V1724_ROM_C_CODE_INDEX
Configuration ROM c_code index.
CVT_V1724_ROM_R_CODE_INDEX
Configuration ROM r_code index.
CVT_V1724_ROM_OUI_2_INDEX
Configuration ROM Manufacturer identifier (IEEE OUI) (MSB) index.
CVT_V1724_ROM_OUI_1_INDEX
Configuration ROM Manufacturer identifier (IEEE OUI) index.
CVT_V1724_ROM_OUI_0_INDEX
Configuration ROM Manufacturer identifier (IEEE OUI) (LSB) index.
CVT_V1724_ROM_VERSION_INDEX
Configuration ROM Purchased version of the Mod.V1724 index.
CVT_V1724_ROM_BOARD_ID_2_INDEX
Configuration ROM Board identifier (MSB) index.
CVT_V1724_ROM_BOARD_ID_1_INDEX
Configuration ROM Board identifier index.
CVT_V1724_ROM_BOARD_ID_0_INDEX
Configuration ROM Board identifier (LSB) index.
CVT_V1724_ROM_REVISION_3_INDEX
Configuration ROM Hardware revision identifier index.
CVT_V1724_ROM_REVISION_2_INDEX
Configuration ROM Hardware revision identifier index.
CVT_V1724_ROM_REVISION_1_INDEX
Configuration ROM Hardware revision identifier index.
CVT_V1724_ROM_REVISION_0_INDEX
Configuration ROM Hardware revision identifier index.
CVT_V1724_ROM_SERIAL_1_INDEX
Configuration ROM Serial number (MSB) index.
CVT_V1724_ROM_SERIAL_0_INDEX
Configuration ROM Serial number (LSB) index.
CVT_V1724_ROM_VCXO_TYPE_INDEX
Configuration ROM VCXO type index.
CVT_V1724_CH0_RESERVED_RND_ACC_INDEX
CH 0 Read Block channel broadcast reserved register index.
CVT_V1724_CH0_ZSTH_INDEX
CH 0 Zero suppression threshold channel broadcast register index.
CVT_V1724_CH0_THRESHOLD_INDEX
CH 0 Threshold register index.
CVT_V1724_CH0_TIME_OVER_UNDER_THR_INDEX
CH 0 Over/Under Threshold Samples register index.
CVT_V1724_CH0_STATUS_INDEX
CH 0 status register index.
CVT_V1724_CH0_FW_REV_INDEX
CH 0 firmware revision register index.
CVT_V1724_CH0_BUFF_OCCUPANCY_INDEX
CH 0 Number of Buffers Filled register index.
CVT_V1724_CH0_DAC_CONF_INDEX
CH 0 DAC Data Configuration register index.
CVT_V1724_CH0_ADC_CONF_INDEX
CH 0 Configuration register index.
CVT_V1724_CH0_RESERVED_ADC_DEBUG_INDEX
CH 0 ADC Debug Reserved register index.
CVT_V1724_CH0_RESERVED_MEM_DATA_INDEX
CH 0 Memory test data Reserved register index.
CVT_V1724_CH0_RESERVED_MEM_ADDRESS_INDEX
CH 0 Memory test address Reserved register index.
CVT_V1724_CH1_RESERVED_RND_ACC_INDEX
CH 1 Read Block channel broadcast reserved register index.
CVT_V1724_CH1_ZSTH_INDEX
CH 1 Zero suppression threshold channel broadcast register index.
CVT_V1724_CH1_THRESHOLD_INDEX
CH 1 Threshold register index.
CVT_V1724_CH1_TIME_OVER_UNDER_THR_INDEX
CH 1 Over/Under Threshold Samples register index.
CVT_V1724_CH1_STATUS_INDEX
CH 1 status register index.
CVT_V1724_CH1_FW_REV_INDEX
CH 1 firmware revision register index.
CVT_V1724_CH1_BUFF_OCCUPANCY_INDEX
CH 1 Number of Buffers Filled register index.
CVT_V1724_CH1_DAC_CONF_INDEX
CH 1 DAC Data Configuration register index.
CVT_V1724_CH1_ADC_CONF_INDEX
CH 1 Configuration register index.
CVT_V1724_CH1_RESERVED_ADC_DEBUG_INDEX
CH 1 ADC Debug Reserved register index.
CVT_V1724_CH1_RESERVED_MEM_DATA_INDEX
CH 1 Memory test data Reserved register index.
CVT_V1724_CH1_RESERVED_MEM_ADDRESS_INDEX
CH 1 Memory test address Reserved register index.
CVT_V1724_CH2_RESERVED_RND_ACC_INDEX
CH 2 Read Block channel broadcast reserved register index.
CVT_V1724_CH2_ZSTH_INDEX
CH 2 Zero suppression threshold channel broadcast register index.
CVT_V1724_CH2_THRESHOLD_INDEX
CH 2 Threshold register index.
CVT_V1724_CH2_TIME_OVER_UNDER_THR_INDEX
CH 2 Over/Under Threshold Samples register index.
CVT_V1724_CH2_STATUS_INDEX
CH 2 status register index.
CVT_V1724_CH2_FW_REV_INDEX
CH 2 firmware revision register index.
CVT_V1724_CH2_BUFF_OCCUPANCY_INDEX
CH 2 Number of Buffers Filled register index.
CVT_V1724_CH2_DAC_CONF_INDEX
CH 2 DAC Data Configuration register index.
CVT_V1724_CH2_ADC_CONF_INDEX
CH 2 Configuration register index.
CVT_V1724_CH2_RESERVED_ADC_DEBUG_INDEX
CH 2 ADC Debug Reserved register index.
CVT_V1724_CH2_RESERVED_MEM_DATA_INDEX
CH 2 Memory test data Reserved register index.
CVT_V1724_CH2_RESERVED_MEM_ADDRESS_INDEX
CH 2 Memory test address Reserved register index.
CVT_V1724_CH3_RESERVED_RND_ACC_INDEX
CH 3 Read Block channel broadcast reserved register index.
CVT_V1724_CH3_ZSTH_INDEX
CH 3 Zero suppression threshold channel broadcast register index.
CVT_V1724_CH3_THRESHOLD_INDEX
CH 3 Threshold register index.
CVT_V1724_CH3_TIME_OVER_UNDER_THR_INDEX
CH 3 Over/Under Threshold Samples register index.
CVT_V1724_CH3_STATUS_INDEX
CH 3 status register index.
CVT_V1724_CH3_FW_REV_INDEX
CH 3 firmware revision register index.
CVT_V1724_CH3_BUFF_OCCUPANCY_INDEX
CH 3 Number of Buffers Filled register index.
CVT_V1724_CH3_DAC_CONF_INDEX
CH 3 DAC Data Configuration register index.
CVT_V1724_CH3_ADC_CONF_INDEX
CH 3 Configuration register index.
CVT_V1724_CH3_RESERVED_ADC_DEBUG_INDEX
CH 3 ADC Debug Reserved register index.
CVT_V1724_CH3_RESERVED_MEM_DATA_INDEX
CH 3 Memory test data Reserved register index.
CVT_V1724_CH3_RESERVED_MEM_ADDRESS_INDEX
CH 3 Memory test address Reserved register index.
CVT_V1724_CH4_RESERVED_RND_ACC_INDEX
CH 4 Read Block channel broadcast reserved register index.
CVT_V1724_CH4_ZSTH_INDEX
CH 4 Zero suppression threshold channel broadcast register index.
CVT_V1724_CH4_THRESHOLD_INDEX
CH 4 Threshold register index.
CVT_V1724_CH4_TIME_OVER_UNDER_THR_INDEX
CH 4 Over/Under Threshold Samples register index.
CVT_V1724_CH4_STATUS_INDEX
CH 4 status register index.
CVT_V1724_CH4_FW_REV_INDEX
CH 4 firmware revision register index.
CVT_V1724_CH4_BUFF_OCCUPANCY_INDEX
CH 4 Number of Buffers Filled register index.
CVT_V1724_CH4_DAC_CONF_INDEX
CH 4 DAC Data Configuration register index.
CVT_V1724_CH4_ADC_CONF_INDEX
CH 4 Configuration register index.
CVT_V1724_CH4_RESERVED_ADC_DEBUG_INDEX
CH 4 ADC Debug Reserved register index.
CVT_V1724_CH4_RESERVED_MEM_DATA_INDEX
CH 4 Memory test data Reserved register index.
CVT_V1724_CH4_RESERVED_MEM_ADDRESS_INDEX
CH 4 Memory test address Reserved register index.
CVT_V1724_CH5_RESERVED_RND_ACC_INDEX
CH 5 Read Block channel broadcast reserved register index.
CVT_V1724_CH5_ZSTH_INDEX
CH 5 Zero suppression threshold channel broadcast register index.
CVT_V1724_CH5_THRESHOLD_INDEX
CH 5 Threshold register index.
CVT_V1724_CH5_TIME_OVER_UNDER_THR_INDEX
CH 5 Over/Under Threshold Samples register index.
CVT_V1724_CH5_STATUS_INDEX
CH 5 status register index.
CVT_V1724_CH5_FW_REV_INDEX
CH 5 firmware revision register index.
CVT_V1724_CH5_BUFF_OCCUPANCY_INDEX
CH 5 Number of Buffers Filled register index.
CVT_V1724_CH5_DAC_CONF_INDEX
CH 5 DAC Data Configuration register index.
CVT_V1724_CH5_ADC_CONF_INDEX
CH 5 Configuration register index.
CVT_V1724_CH5_RESERVED_ADC_DEBUG_INDEX
CH 5 ADC Debug Reserved register index.
CVT_V1724_CH5_RESERVED_MEM_DATA_INDEX
CH 5 Memory test data Reserved register index.
CVT_V1724_CH5_RESERVED_MEM_ADDRESS_INDEX
CH 5 Memory test address Reserved register index.
CVT_V1724_CH6_RESERVED_RND_ACC_INDEX
CH 6 Read Block channel broadcast reserved register index.
CVT_V1724_CH6_ZSTH_INDEX
CH 6 Zero suppression threshold channel broadcast register index.
CVT_V1724_CH6_THRESHOLD_INDEX
CH 6 Threshold register index.
CVT_V1724_CH6_TIME_OVER_UNDER_THR_INDEX
CH 6 Over/Under Threshold Samples register index.
CVT_V1724_CH6_STATUS_INDEX
CH 6 status register index.
CVT_V1724_CH6_FW_REV_INDEX
CH 6 firmware revision register index.
CVT_V1724_CH6_BUFF_OCCUPANCY_INDEX
CH 6 Number of Buffers Filled register index.
CVT_V1724_CH6_DAC_CONF_INDEX
CH 6 DAC Data Configuration register index.
CVT_V1724_CH6_ADC_CONF_INDEX
CH 6 Configuration register index.
CVT_V1724_CH6_RESERVED_ADC_DEBUG_INDEX
CH 6 ADC Debug Reserved register index.
CVT_V1724_CH6_RESERVED_MEM_DATA_INDEX
CH 6 Memory test data Reserved register index.
CVT_V1724_CH6_RESERVED_MEM_ADDRESS_INDEX
CH 6 Memory test address Reserved register index.
CVT_V1724_CH7_RESERVED_RND_ACC_INDEX
CH 7 Read Block channel broadcast reserved register index.
CVT_V1724_CH7_ZSTH_INDEX
CH 7 Zero suppression threshold channel broadcast register index.
CVT_V1724_CH7_THRESHOLD_INDEX
CH 7 Threshold register index.
CVT_V1724_CH7_TIME_OVER_UNDER_THR_INDEX
CH 7 Over/Under Threshold Samples register index.
CVT_V1724_CH7_STATUS_INDEX
CH 7 status register index.
CVT_V1724_CH7_FW_REV_INDEX
CH 7 firmware revision register index.
CVT_V1724_CH7_BUFF_OCCUPANCY_INDEX
CH 7 Number of Buffers Filled register index.
CVT_V1724_CH7_DAC_CONF_INDEX
CH 7 DAC Data Configuration register index.
CVT_V1724_CH7_ADC_CONF_INDEX
CH 7 Configuration register index.
CVT_V1724_CH7_RESERVED_ADC_DEBUG_INDEX
CH 7 ADC Debug Reserved register index.
CVT_V1724_CH7_RESERVED_MEM_DATA_INDEX
CH 7 Memory test data Reserved register index.
CVT_V1724_CH7_RESERVED_MEM_ADDRESS_INDEX
CH 7 Memory test address Reserved register index.
CVT_V1724_LAST_INDEX
Tag : just to get table index size.
Definition at line 663 of file cvt_V1724.h.
enum CVT_V1724_TRIGGER_SRC_ENABLE_MSK
Trigger enable bitmasks.
Enumerator:
CVT_V1724_TRGEN_CH0_MSK
Enable CH 0 trigger bit
CVT_V1724_TRGEN_CH1_MSK
Enable CH 1 trigger bit
CVT_V1724_TRGEN_CH2_MSK
Enable CH 2 trigger bit
CVT_V1724_TRGEN_CH3_MSK
Enable CH 3 trigger bit
CVT_V1724_TRGEN_CH4_MSK
Enable CH 4 trigger bit
CVT_V1724_TRGEN_CH5_MSK
Enable CH 5 trigger bit
CVT_V1724_TRGEN_CH6_MSK
Enable CH 6 trigger bit
CVT_V1724_TRGEN_CH7_MSK
Enable CH 7 trigger bit
CVT_V1724_TRGEN_EXT_MSK
External trigger enable bit
CVT_V1724_TRGEN_SW_MSK
Software trigger enable bit
Definition at line 902 of file cvt_V1724.h.
enum CVT_V1724_VME_CONTROL_MSK
Control register bitmasks.
Enumerator:
CVT_V1724_VME_CTRL_INT_LEVEL_MSK
Interrupt level bit masks
CVT_V1724_VME_CTRL_BERR_ENABLE_MSK
Bus error enable bit
CVT_V1724_VME_CTRL_ALIGN64_MSK
Align 64 enable bit
CVT_V1724_VME_CTRL_RELOC_MSK
Reloc bit
Definition at line 872 of file cvt_V1724.h.
enum CVT_V1724_VME_STATUS_MSK
Status register bitmasks.
Todo:
To be defined
Enumerator:
CVT_V1724_VME_STS_DATA_READY_MSK
Data ready bit
CVT_V1724_VME_STS_FULL_MSK
Full bit
CVT_V1724_VME_STS_BERR_FLAG_MSK
Berr flag bit
CVT_V1724_VME_STS_PURGED_MSK
Purged bit
Definition at line 889 of file cvt_V1724.h.
enum CVT_V17XX_BOARD_CLOCK_INDEX
Boards internal clock indexer for CVT_V17XX_BOARD_CLOCK_KHZ[].
See also:
CVT_V17XX_BOARD_CLOCK_KHZ[]
Enumerator:
CVT_V1724_BOARD_CLOCK_INDEX
V1724 : 100 MHz
CVT_V1721_BOARD_CLOCK_INDEX
V1721 : 500 MHz
CVT_V1731_BOARD_CLOCK_INDEX
V1731 : 500 MHz
CVT_V1731_DES_BOARD_CLOCK_INDEX
V1731 Des mode :1000 MHz
CVT_V1720_BOARD_CLOCK_INDEX
V1720 : 250 MHz
CVT_V1740_BOARD_CLOCK_INDEX
V1740 : 62.5 MHz
CVT_V1751_BOARD_CLOCK_INDEX
V1751 : 1000 MHz
CVT_V1751_DES_BOARD_CLOCK_INDEX
V1751 Des mode : 2000 MHz
Definition at line 1200 of file cvt_V1724.h.
enum CVT_V17XX_ROM_CFG_BOARD_ID
Configurazion ROM board IDs.
Enumerator:
CVT_V17XX_RCFG_BOARD_ID_V1724
CVT_V17XX_RCFG_BOARD_ID_VX1724
CVT_V17XX_RCFG_BOARD_ID_V1721
CVT_V17XX_RCFG_BOARD_ID_VX1721
CVT_V17XX_RCFG_BOARD_ID_V1731
CVT_V17XX_RCFG_BOARD_ID_VX1731
CVT_V17XX_RCFG_BOARD_ID_V1720
CVT_V17XX_RCFG_BOARD_ID_VX1720
CVT_V17XX_RCFG_BOARD_ID_V1740
CVT_V17XX_RCFG_BOARD_ID_VX1740
CVT_V17XX_RCFG_BOARD_ID_V1751
CVT_V17XX_RCFG_BOARD_ID_VX1751
Definition at line 1360 of file cvt_V1724.h.
enum CVT_V17XX_ROM_CFG_VCXO_TYPE
Configurazion ROM VCXO types.
Enumerator:
CVT_V17XX_RCFG_VCXO_500
CVT_V17XX_RCFG_VCXO_1000
Definition at line 1349 of file cvt_V1724.h.
enum CVT_V17XX_TYPES
The V17XX board type.
Provides an entry for each board type
Enumerator:
CVT_V1724
The board is V1724.
CVT_V1721
The board is V1721.
CVT_V1731
The board is V1731.
CVT_V1720
The board is V1720.
CVT_V1740
The board is V1740.
CVT_V1751
The board is V1751.
Definition at line 32 of file cvt_V1724.h.
Function Documentation
BOOL cvt_V1724_adc_calib (cvt_V1724_data * p_data, UINT8 ch_msk)
Performs the specified ADCs' channels calibration (V1731/V1721 only).
Parameters:
p_data Pointer to board data
ch_msk The channel mask to calibrate
Returns:
TRUE: Procedure successfully executed
Referenced by V1751Board::Init(), V1731Board::Init(), and V1721Board::Init().
BOOL cvt_V1724_adc_temp (cvt_V1724_data * p_data, UINT8 ch_msk, UINT32 * tempadc)
Reads the specified ADCs' channels temperature (V1751 only).
Parameters:
p_data Pointer to board data
ch_msk The channel mask read temperature from
tampadc The caller allocated storage to hold channels' temperatures: it must be a CVT_V1724_MAX_CHANNEL UINT32 data array
Returns:
TRUE: Procedure successfully executed
BOOL cvt_V1724_close (cvt_V1724_data * p_data)
V1724 VME boards closing and resource free.
Provides specific handling for V1724 boards closing.
Parameters:
p_data Pointer to board data
Returns:
TRUE: board successfully closed
Note:
Must be called when done with any other board specific API.
Referenced by V17XXBoard::~V17XXBoard().
BOOL cvt_V1724_data_clear (cvt_V1724_data * p_data)
Performs a data clear.
Writes a dummy value into SW_CLEAR_REGISTER register.
Parameters:
p_data Pointer to board data
Returns:
TRUE: Procedure successfully executed
Referenced by V17XXBoard::SetFrontPanelIO(), V17XXBoard::WriteSampleBufferSize(), V1740Board::WriteSampleBufferSize(), and V17XXBoard::WriteTriggerMode().
BOOL cvt_V1724_erase_flash_page (cvt_V1724_data * p_data, UINT32 page_index)
Erases a board's flash page.
Parameters:
p_data Pointer to board data.
page_index The page index (0 based index) to be erased
Returns:
TRUE: Procedure successfully executed
BOOL cvt_V1724_fw_upgrade (cvt_V1724_data * p_data, const UINT8 * data_buff, UINT32 data_size, CVT_V1724_FLASH_BANK flash_bank, BOOL(*)(UINT32 written_bytes) call_back)
Performs a full flash upgrade onto specific bank (standard or backup).
Parameters:
p_data Pointer to board data.
data_buff The source data buffer
data_size The data_buff size (bytes)
flash_bank The flash bank to upgrade: must be a CVT_V1724_FLASH_BANK valid one
call_back End user call back function, called for each new page transferred: may be NULL: you can return FALSE to abort procedure
Returns:
TRUE: Procedure successfully executed
BOOL cvt_V1724_get_acquisition_mode (cvt_V1724_data * p_data, BOOL * p_sample_enable, CVT_V1724_NUM_BLOCKS * p_block_size)
Gets the acquisition mode parameters.
Retrives the relevant parameters settings for the acquisition mode.
Parameters:
p_data Pointer to board data
p_sample_enable Sample acquisition mode: if disabled the acquisition mode is windowed
p_block_size Samples' number per block size foreach channel: it must be a valid CVT_V1724_NUM_BLOCKS identifier.
Returns:
TRUE: Procedure successfully executed
See also:
CVT_V1724_NUM_BLOCKS
BOOL cvt_V1724_get_acquisition_status (cvt_V1724_data * p_data, BOOL * p_is_MEB_not_empty, BOOL * p_is_MEB_full, BOOL * p_is_running, BOOL * p_some_event_ready, BOOL * p_event_full, BOOL * p_s_in)
Gets the acquisition status parameters.
Retrives the relevant parameters for the acquisition status.
Parameters:
p_data Pointer to board data
p_is_MEB_not_empty This flag is set if MEB is not empty
p_is_MEB_full This flag is set if MEB is full
p_is_running This flag is set if acquisition is running
p_some_event_ready This flag is set if some event is ready
p_event_full This flag is set if event memory is full
p_s_in This flag shows the front panel' S-IN signal logical state
Returns:
TRUE: Procedure successfully executed
BOOL cvt_V1724_get_adc_conf (cvt_V1724_data * p_data, UINT8 ch_index, BOOL * p_dither_value, BOOL * p_clk_duty_stab_value, BOOL * p_randomize_value)
Gets the specified channel' adc configuration (V1724/V1720 only).
Gets the dither, clock duty cycle stabilizer and output randomize features status for the specified channel.
Parameters:
p_data Pointer to board data
ch_index The channel index
p_dither_value If TRUE the dither feature is enabled, disable otherwise
p_clk_duty_stab_value If TRUE the clock duty cycle stabilizer feature is enabled, disable otherwise
p_randomize_value If TRUE the output randomized feature is enabled, disable otherwise
Returns:
TRUE: Procedure successfully executed
BOOL cvt_V1724_get_buffer_cache (cvt_V1724_data * p_data, UINT16 event_index, UINT8 ch_index, UINT16 * p_buff, UINT32 * p_buff_size, UINT8 * p_board_id, UINT32 * p_trigger_time_tag, UINT32 * p_event_counter)
Reads data cache from previous cvt_V1724_read_data data call.
Call cvt_FIFO_BLT_read for Multiple Event Buffer and stores data into user buffer. If the returned data is just a V1724 not valid datum, this is discarded.
Parameters:
p_data Pointer to board data
event_index The event index from which retrive data
ch_index The channel index
p_buff The target buffer: caller allocated
p_buff_size The buffer size (16 bit word). On exit will holds the number of words really read.
p_board_id The board id stored into event
p_trigger_time_tag The trigger time tag stored into event
p_event_counter The counter stored into event
Returns:
TRUE: Procedure successfully executed, FALSE elsewhere (e.g. event or channel index not found)
See also:
cvt_V1724_read_data
Referenced by V17XXBoardChannel::ReadSamplesCache(), and V1740BoardChannel::ReadSamplesCache().
BOOL cvt_V1724_get_buffer_samples (cvt_V1724_data * p_data, UINT16 * p_num_k_samples, CVT_V1724_NUM_BLOCKS * p_num_block_read)
Returns the maximum number of samples per events for each channel.
Parameters:
p_data Pointer to board data
p_num_k_samples The number of samples (as K blocks) per channel or per group in case of CVT_V1740
p_num_block_read The num block register value read (CVT_V1724_NUM_BLOCKS)
Returns:
TRUE: Procedure successfully executed
Referenced by V17XXBoard::WriteSampleBufferSize(), and V1740Board::WriteSampleBufferSize().
BOOL cvt_V1724_get_channel_info (cvt_V1724_data * p_data, UINT8 ch_index, UINT16 * p_firmware_rev)
Gets board's system information.
Reads the firmware revision register and the serial number.
Parameters:
p_data Pointer to board data
ch_index The index of the channel to test.
p_firmware_rev The channel's firmare release (MSB major release, LSB minor release).
Returns:
TRUE: Procedure successfully executed
BOOL cvt_V1724_get_channel_offset (cvt_V1724_data * p_data, UINT8 ch_index, UINT16 * p_offset_value)
Sets specified channel' offset.
Retrives the offset value for the specified channel.
Parameters:
p_data Pointer to board data
ch_index The channel index
p_offset_value The channel' offset value.
Returns:
TRUE: Procedure successfully executed
BOOL cvt_V1724_get_channel_status (cvt_V1724_data * p_data, UINT8 ch_index, BOOL * p_is_dac_busy, BOOL * p_is_fifo_full, BOOL * p_is_fifo_empty, BOOL * p_is_block_remove_ok)
Gets information about board status.
Parameters:
p_data Pointer to board data.
ch_index The index of the channel to test.
p_is_dac_busy Returns the channel's DAC_BUSY flag status.
p_is_fifo_full Returns the channel's FIFO_FULL flag status.
p_is_fifo_empty Returns the channel's FIFO_EMPTY flag status.
p_is_block_remove_ok Returns the channel's BLOCK_REM_OK flag status.
Returns:
TRUE: Procedure successfully executed.
BOOL cvt_V1724_get_channel_trigger (cvt_V1724_data * p_data, UINT8 ch_index, UINT32 * p_trigger_threshold, UINT32 * p_threshold_samples)
Gets the specified channel' trigger parameters.
Retrives the relevant trigger parameters for the specified channel.
Parameters:
p_data Pointer to board data
ch_index The channel index
p_trigger_threshold The value of the trigger threshold
p_threshold_samples The hysteresis on threshold comparison
Returns:
TRUE: Procedure successfully executed
BOOL cvt_V1724_get_dither_enable (cvt_V1724_data * p_data, UINT8 ch_index, BOOL * p_dither_value)
Gets the specified channel' dithering feature status (V1724/V1720 only).
Gets the dither feature status for the specified channel.
Parameters:
p_data Pointer to board data
ch_index The channel index
p_dither_value If TRUE the dither feature is enabled, disable otherwise
Returns:
TRUE: Procedure successfully executed
Deprecated:
Use cvt_V1724_get_adc_conf
BOOL cvt_V1724_get_fp_trigger_out (cvt_V1724_data * p_data, BOOL * p_ext_trigger_enable, BOOL * p_sw_trigger_enable, UINT8 * p_ch_trigger_enable_msk)
Gets the front panel trigger output settings.
Retrives the relevant parameters setting for the front panel triggering mode.
Parameters:
p_data Pointer to board data
p_ext_trigger_enable External trigger status output enable.
p_sw_trigger_enable Software trigger status output enable.
p_ch_trigger_enable_msk Trigger output from channels thresholds comparison status.
Returns:
TRUE: Procedure successfully executed
BOOL cvt_V1724_get_front_panel_IO (cvt_V1724_data * p_data, BOOL * p_use_TTL, BOOL * p_is_out_en, UINT8 * p_dir_msk, CVT_V1724_FRONT_PANEL_IO_MODES * p_mode)
Gets front panel's IO.
Retrives the relevant parameters for the front panel's IO.
Parameters:
p_data Pointer to board data
p_use_TTL True if the external signals standard is TTL type
p_is_out_en True if the trigger output is enabled
p_dir_msk Gets the direction mask
p_mode Gets the operational mode
Returns:
TRUE: Procedure successfully executed
See also:
CVT_V1724_FRONT_PANEL_IO_MODES
BOOL cvt_V1724_get_interrupt (cvt_V1724_data * p_data, UINT8 * p_level, UINT32 * p_status_id, UINT16 * p_event_number)
Gets interrupt parameters.
Retrives the relevant parameters settings for interrupt usage.
Parameters:
p_data Pointer to board data
p_level The interrupt level.
p_status_id The interrupt stayus id (interupt vector).
p_event_number The number of events to get an interrupt (if 0 interrupt feature is disabled).
Returns:
TRUE: Procedure successfully executed
BOOL cvt_V1724_get_MCST_CBLT (cvt_V1724_data * p_data, UINT8 * p_address, MCST_CBLT_board_pos * p_pos)
Gets MCST/CBLT parameters from board.
Retrives the relevant parameters for MCST/CBLT usage.
Parameters:
p_data Pointer to board data.
p_address The MCST/CBLT address.
p_pos The board position into the MCST / CBLT chain: it must be a MCST_CBLT_board_pos identifier
Returns:
TRUE: Procedure successfully executed
See also:
MCST_CBLT_board_pos
BOOL cvt_V1724_get_readout_mode (cvt_V1724_data * p_data, BOOL * p_enable_bus_error, UINT32 * p_BLT_event_number)
Gets data readout mode parameters.
Retrives the relevant parameters settings for data readout.
Parameters:
p_data Pointer to board data
*p_enable_bus_error Bus error status: if TRUE the module is enabled to generate a Bus error to finish a block transfer.
*p_BLT_event_number The number of events to readout foreach BLT cycle.
Returns:
TRUE: Procedure successfully executed
BOOL cvt_V1724_get_system_info (cvt_V1724_data * p_data, UINT16 * p_firmware_rev, CVT_V1724_ROM_CONFIG * p_rom_config, BOOL * p_is_board_type_correct, BOOL * p_is_firmware_rev_correct)
Gets board's system information.
Reads the firmware revision register and the serial number.
Parameters:
p_data Pointer to board data
p_firmware_rev The firmare release (MSB major release, LSB minor release).
p_rom_config The ROM configuration.
p_is_board_type_correct Return TRUE if the cvt_V1724_data::m_type matches the CVT_V1724_ROM_CONFIG::m_board_id type
p_is_firmware_rev_correct Return TRUE if the CVT_V1724_FW_REV register value is greater or equal then minimum requested level for this tool's version CVT_V1724_MIN_FIRMARE_REV
Returns:
TRUE: Procedure successfully executed
See also:
CVT_V1724_MIN_FIRMARE_REV
Referenced by V17XXBoard::v1724_get_system_info_wrapper().
BOOL cvt_V1724_get_trigger_mode (cvt_V1724_data * p_data, BOOL * p_falling_edge_enable, BOOL * p_ext_trigger_enable, BOOL * p_sw_trigger_enable, UINT8 * p_ch_trigger_enable_msk, BOOL * p_trigger_overlap_enable, UINT32 * p_post_trigger)
Gets the trigger out settings.
Retrives the relevant parameters setting for the triggering mode.
Parameters:
p_data Pointer to board data
p_falling_edge_enable Triggering on falling edge status
p_ext_trigger_enable External trigger status.
p_sw_trigger_enable Software trigger status.
p_ch_trigger_enable_msk Trigger from channels thresholds comparison status. If bit i of the mask is setted, the channel i feature is setted.
p_trigger_overlap_enable Trigger overlap feature status.
p_post_trigger Amount of post trigger samples status
Returns:
TRUE: Procedure successfully executed
BOOL cvt_V1724_open (cvt_V1724_data * p_data, UINT16 base_address, long vme_handle, CVT_V17XX_TYPES type)
V1724 VME boards data initialization.
Provides specific handling for V1724 boards opening.
Parameters:
p_data Pointer to board data
base_address The board base address (MSW)
vme_handle The VME handle
type The board type : it must be a CVT_V17XX_TYPES value
Returns:
TRUE: board successfully opened
Note:
Must be called before any other board specific API.
See also:
CVT_V17XX_TYPES
Referenced by V17XXBoard::Init().
BOOL cvt_V1724_pll_upgrade (cvt_V1724_data * p_data, const char * filename)
Loads PLL from file and stores into flash.
Parameters:
p_data Pointer to board data.
filename The source file
Returns:
TRUE: Procedure successfully executed
cvt_V1724_read_data (cvt_V1724_data * p_data, UINT32 * p_ch_max_samples, UINT32 * p_num_events)
Reads data from the board's channels and stores to user buffer.
Calling cvt_V1724_read_data will cache the channels' data into internal buffer Then call cvt_V1724_get_buffer_cache to get cached data
Parameters:
p_data Pointer to board data
p_ch_max_samples returns the maximum number of samples per channel read for each event
p_num_events returns the number of events read
Returns:
TRUE: Procedure successfully executed
See also:
cvt_V1724_get_buffer_cache
Referenced by V17XXBoard::ReadBoardData().
BOOL cvt_V1724_read_flash_page (cvt_V1724_data * p_data, UINT8 * page_buff, UINT32 page_index)
Reads a page from board's flash.
Parameters:
p_data Pointer to board data.
page_buff The target page buffer: page_buff size must be V1724_FLASH_PAGE_SIZE and allocated by the caller
page_index The page index (0 based index) to be read
Returns:
TRUE: Procedure successfully executed
BOOL cvt_V1724_set_acquisition_mode (cvt_V1724_data * p_data, BOOL sample_enable, CVT_V1724_NUM_BLOCKS block_size, CVT_V1724_ACQ_CONTROL_ACQ_MODES acquisition_mode, BOOL count_all_trigger, UINT32 downsample_factor)
Setups the acquisition mode parameters.
Setups the relevant parameters for the acquisition mode.
Parameters:
p_data Pointer to board data
sample_enable Enable/Disable the sample acquisition mode: if disabled the acquisition mode is windowed
block_size Setup the samples' number per block size foreach channel: it must be a valid CVT_V1724_NUM_BLOCKS identifier.
acquisition_mode Setups the acquisition mode
count_all_trigger Set to TRUE if you want to count all triggers (accepted and not)
downsample_factor If != 0 the download factor will be setted and enabled , disabled otherwise
Returns:
TRUE: Procedure successfully executed
See also:
CVT_V1724_NUM_BLOCKS
Referenced by V17XXBoard::WriteSampleBufferSize(), and V1740Board::WriteSampleBufferSize().
BOOL cvt_V1724_set_adc_conf (cvt_V1724_data * p_data, UINT8 ch_msk, BOOL dither_value, BOOL clk_duty_stab_value, BOOL randomize_value)
Setups the channels' adc configuration (V1724/V1720 only).
Enables/Disables the dither, clock duty cycle stabilizer and output randomize features for each channel specified with ch_msk.
Parameters:
p_data Pointer to board data
ch_msk The channel mask
dither_value Set to TRUE to enable the dither channels in the mask, FALSE to disable
clk_duty_stab_value Set to TRUE to enable the clock duty cycle stabilizer feature, FALSE to disable
randomize_value Set to TRUE to enable the output randomized feature, FALSE to disable
Returns:
TRUE: Procedure successfully executed
BOOL cvt_V1724_set_buffer_samples (cvt_V1724_data * p_data, UINT16 num_k_samples, CVT_V1724_NUM_BLOCKS * p_num_block_written)
Sets the maximum number of samples per events for each channel.
Parameters:
p_data Pointer to board data
num_k_samples The number of samples (as K blocks: valid values are power of 2 multiples) per channel or per group in case of CVT_V1740
p_num_block_written The num block register value written (CVT_V1724_NUM_BLOCKS)
Returns:
TRUE: Procedure successfully executed
Referenced by V17XXBoard::WriteSampleBufferSize(), and V1740Board::WriteSampleBufferSize().
BOOL cvt_V1724_set_channel_offset (cvt_V1724_data * p_data, UINT8 ch_msk, UINT16 offset_value)
Sets channels' offset.
Sets the offset value for each channel specified with ch_msk.
Parameters:
p_data Pointer to board data
ch_msk The channel mask
offset_value The offset value to be applied to specified channels.
Returns:
TRUE: Procedure successfully executed
Referenced by V17XXBoardChannel::WriteDACOffset(), and V1740BoardChannel::WriteDACOffset().
BOOL cvt_V1724_set_channel_trigger (cvt_V1724_data * p_data, UINT8 ch_msk, UINT32 trigger_threshold, UINT32 threshold_samples)
Sets channels' trigger parameters.
Sets the relevant trigger parameters for each channel specified with ch_msk.
Parameters:
p_data Pointer to board data
ch_msk The channel mask
trigger_threshold The value of the trigger threshold
threshold_samples The hysteresis on threshold comparison
Returns:
TRUE: Procedure successfully executed
Referenced by V17XXBoardChannel::WriteChannelTrigger(), and V1740BoardChannel::WriteChannelTrigger().
BOOL cvt_V1724_set_des_mode (cvt_V1724_data * p_data, BOOL is_des_mode)
Switchs to DES mode or normal mode (V1731 only).
Performs the correct procedure to switch to DES mode (4 channels) or normal (8 channels) mode
Parameters:
p_data Pointer to board data
is_des_mode If TRUE the des mode is setted
Returns:
TRUE: Procedure successfully executed
Remarks:
!!! WARNING !!! Odd channel's input signal must be disconnected and acquisition setting will be modified
Referenced by V1751Board::Init(), and V1731Board::Init().
BOOL cvt_V1724_set_dither_enable (cvt_V1724_data * p_data, UINT8 ch_msk, BOOL dither_value)
Setups the channels' dithering feature (V1724/V1720 only).
Enables/Disables the dither feature for each channel specified with ch_msk.
Parameters:
p_data Pointer to board data
ch_msk The channel mask
dither_value Set to TRUE to enable the dither channels in the mask, FALSE to disable
Returns:
TRUE: Procedure successfully executed
Deprecated:
Use cvt_V1724_set_adc_conf
BOOL cvt_V1724_set_fp_trigger_out (cvt_V1724_data * p_data, BOOL ext_trigger_enable, BOOL sw_trigger_enable, UINT8 ch_trigger_enable_msk)
Setups the front panel triggering output parameters.
Setups the relevant parameters for the front panel triggering mode.
Parameters:
p_data Pointer to board data
ext_trigger_enable Enable/Disable the external trigger output.
sw_trigger_enable Enable/Disable the software trigger output.
ch_trigger_enable_msk Enable/Disable trigger output from channels thresholds comparison
Returns:
TRUE: Procedure successfully executed
BOOL cvt_V1724_set_front_panel_IO (cvt_V1724_data * p_data, BOOL use_TTL, BOOL out_en, UINT8 dir_msk, CVT_V1724_FRONT_PANEL_IO_MODES mode)
Sets front panel's IO.
Sets the relevant parameters for the front panel's IO.
Parameters:
p_data Pointer to board data
use_TTL If set, the external signals standard is TTL type, elsewhere NIM type is assumed
out_en If setted enables the trigger output
dir_msk Set direction mask
mode Set the operational mode
Returns:
TRUE: Procedure successfully executed
See also:
CVT_V1724_FRONT_PANEL_IO_MODES
Referenced by V17XXBoard::SetFrontPanelIO().
BOOL cvt_V1724_set_interrupt (cvt_V1724_data * p_data, UINT8 level, UINT32 status_id, UINT16 event_number)
Setups interrupt parameters.
Setups the relevant parameters for interrupt usage.
Parameters:
p_data Pointer to board data
level The interrupt level.
status_id The interrupt status id (interrupt vector).
event_number The number of events to get an interrupt (setting 0 interrupt feature is disabled).
Returns:
TRUE: Procedure successfully executed
BOOL cvt_V1724_set_MCST_CBLT (cvt_V1724_data * p_data, UINT8 address, MCST_CBLT_board_pos pos)
Setups MCST/CBLT parameters for this board.
Setups the relevant parameters for MCST/CBLT usage.
Parameters:
p_data Pointer to board data.
address The MCST/CBLT address.
pos The board position into the MCST / CBLT chain: it must be a MCST_CBLT_board_pos identifier
Returns:
TRUE: Procedure successfully executed
See also:
MCST_CBLT_board_pos
BOOL cvt_V1724_set_readout_mode (cvt_V1724_data * p_data, BOOL enable_bus_error, UINT32 BLT_event_number)
Setups data readout mode parameters.
Setups the relevant parameters for data readout.
Parameters:
p_data Pointer to board data
enable_bus_error Enable bus error: the module is enabled to generate a Bus error to finish a block transfer.
BLT_event_number The number of events to readout foreach BLT cycle.
Returns:
TRUE: Procedure successfully executed
Referenced by V17XXBoard::DoStartAcquisition(), and V1740Board::DoStartAcquisition().
BOOL cvt_V1724_set_trigger_mode (cvt_V1724_data * p_data, BOOL falling_edge_enable, BOOL ext_trigger_enable, BOOL sw_trigger_enable, UINT8 ch_trigger_enable_msk, BOOL trigger_overlap_enable, UINT32 post_trigger)
Setups the triggering parameters.
Setups the relevant parameters for the triggering mode.
Parameters:
p_data Pointer to board data
falling_edge_enable Enable/Disable triggering on falling edge
ext_trigger_enable Enable/Disable the external trigger.
sw_trigger_enable Enable/Disable the software trigger.
ch_trigger_enable_msk Enable/Disable trigger from channels thresholds comparison. If bit i of the mask is setted, the channel i feature is setted.
trigger_overlap_enable Enable/Disable the trigger overlap feature.
post_trigger The amount of post trigger samples
Returns:
TRUE: Procedure successfully executed
Referenced by V17XXBoard::WriteTriggerMode().
BOOL cvt_V1724_software_reset (cvt_V1724_data * p_data)
Performs a software reset.
Writes a dummy value into SW_RESET_REGISTER register.
Parameters:
p_data Pointer to board data
Returns:
TRUE: Procedure successfully executed
Referenced by V1751Board::Init(), V1731Board::Init(), and V1721Board::Init().
BOOL cvt_V1724_software_trigger (cvt_V1724_data * p_data)
Performs a software trigger.
Sends a software trigger. Software triggers must be enabled
Parameters:
p_data Pointer to board data
Returns:
TRUE: Procedure successfully executed
See also:
cvt_V1724_set_trigger_mode
Referenced by V17XXBoard::WriteSoftwareTrigger().
BOOL cvt_V1724_start_acquisition (cvt_V1724_data * p_data, UINT8 ch_msk)
Starts the acquisition for the spcified channel mask.
Parameters:
p_data Pointer to board data
ch_msk The mask of enabled channels
Returns:
TRUE: Procedure successfully executed
Referenced by V17XXBoard::DoStartAcquisition(), and V1740Board::DoStartAcquisition().
BOOL cvt_V1724_stop_acquisition (cvt_V1724_data * p_data)
Stops the acquisition.
Parameters:
p_data Pointer to board data
Returns:
TRUE: Procedure successfully executed
Referenced by V17XXBoard::DoStopAcquisition().
const char * cvt_V1724_SW_rev (void)
Returns the SDK software release.
Returns:
const char*: The SDK revision string
Referenced by InfoDialog::CreateControls().
BOOL cvt_V1724_write_flash_page (cvt_V1724_data * p_data, const UINT8 * page_buff, UINT32 page_index)
Writes a page into board's flash.
Parameters:
p_data Pointer to board data.
page_buff The source page buffer: page_buff size must be V1724_FLASH_PAGE_SIZE bytes
page_index The page index (0 based index) to be written
Returns:
TRUE: Procedure successfully executed
Variable Documentation
const UINT32 CVT_V1724_EXTCLOCK_KHZ[] [static]
Initial value:
{
        10000,
        40000,
        50000,
        62500,
}
External clock allowed values (KHz).
CVT_V1724_EXTCLOCK_KHZ
Definition at line 1186 of file cvt_V1724.h.
const UINT32 CVT_V17XX_BOARD_CLOCK_KHZ[] [static]
Initial value:
{
        100000,
        500000,
        500000,
        1000000,
        250000,
         62500,
        1000000,
        2000000,
}
Boards internal clock values (KHz): use CVT_V17XX_BOARD_CLOCK_INDEX enumeration as indexer.
CVT_V17XX_BOARD_CLOCK_KHZ
See also:
CVT_V17XX_BOARD_CLOCK_INDEX
Definition at line 1218 of file cvt_V1724.h.
Referenced by V1751Board::GetClockMHz(), V1740Board::GetClockMHz(), V1731Board::GetClockMHz(), V1724Board::GetClockMHz(), V1721Board::GetClockMHz(), and V1720Board::GetClockMHz().