#!/bin/sh
#=============================================================================
#
#             --- CAEN SpA - Computing Systems Division ---
#
#  Library installation script.
#
#
#  March  2004 :   Created.
#
#=============================================================================

install libCAENVME.so.2.11 /usr/lib
ln -sf /usr/lib/libCAENVME.so.2.11 /usr/lib/libCAENVME.so
/sbin/ldconfig
cp ../include/* /usr/include/
