/////////////////////////////////////////////////////////////////////////////
// Name:        infodialog.cpp
// Purpose:     
// Author:      NDA
// Modified by: 
// Created:     11/10/2006 12:54:22
// RCS-ID:      $Id: infodialog.cpp,v 1.1 2009/02/18 08:25:36 Colombini Exp $
// Copyright:   CAEN S.p.A All rights reserved.
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 11/10/2006 12:54:22

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma implementation "infodialog.h"
#endif

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif
////@begin includes
////@end includes

#include "appsettings.h"

#include "infodialog.h"
#include "hyperlinkctrl.h"
extern "C" 
{
	#include "cvt_board_commons.h"
}

////@begin XPM images
////@end XPM images

/*!
 * InfoDialog type definition
 */

IMPLEMENT_DYNAMIC_CLASS( InfoDialog, wxDialog )

/*!
 * InfoDialog event table definition
 */

BEGIN_EVENT_TABLE( InfoDialog, wxDialog )

////@begin InfoDialog event table entries
    EVT_BUTTON( ID_OK_BUTTON, InfoDialog::OnOkButtonClick )

////@end InfoDialog event table entries

    //EVT_LINK( ID_HYPERLINK, InfoDialog::OnHyperlink )
END_EVENT_TABLE()

/*!
 * InfoDialog constructors
 */

InfoDialog::InfoDialog( )
{
}

InfoDialog::InfoDialog( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Create(parent, id, caption, pos, size, style);
}

/*!
 * InfoDialog creator
 */

bool InfoDialog::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin InfoDialog member initialisation
    m_left_panel = NULL;
    m_left_sizer = NULL;
////@end InfoDialog member initialisation

////@begin InfoDialog creation
    SetExtraStyle(GetExtraStyle()|wxWS_EX_BLOCK_EVENTS);
    wxDialog::Create( parent, id, caption, pos, size, style );

    CreateControls();
    SetIcon(GetIconResource(AppSettings::get_default_img_path()+wxT("app_icon.ico")));
    if (GetSizer())
    {
        GetSizer()->SetSizeHints(this);
    }
////@end InfoDialog creation
    return true;
}

/*!
 * Control creation for InfoDialog
 */

void InfoDialog::CreateControls()
{    
////@begin InfoDialog content construction
    // Generated by DialogBlocks, 02/10/2007 16:48:06 (unregistered)

    InfoDialog* itemDialog1 = this;

    wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxHORIZONTAL);
    itemDialog1->SetSizer(itemBoxSizer2);

    m_left_panel = new wxPanel( itemDialog1, ID_PANEL2, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL );
    m_left_panel->SetBackgroundColour(wxColour(255, 255, 255));
    itemBoxSizer2->Add(m_left_panel, 1, wxGROW|wxALL, 5);

    wxBoxSizer* itemBoxSizer4 = new wxBoxSizer(wxHORIZONTAL);
    m_left_panel->SetSizer(itemBoxSizer4);

    m_left_sizer = new wxBoxSizer(wxVERTICAL);
    itemBoxSizer4->Add(m_left_sizer, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxBitmap itemStaticBitmap6Bitmap(itemDialog1->GetBitmapResource(AppSettings::get_default_img_path()+wxT("caen.png")));
    wxStaticBitmap* itemStaticBitmap6 = new wxStaticBitmap( m_left_panel, wxID_STATIC, itemStaticBitmap6Bitmap, wxDefaultPosition, wxSize(195, 62), 0 );
    m_left_sizer->Add(itemStaticBitmap6, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);

    wxBoxSizer* itemBoxSizer7 = new wxBoxSizer(wxVERTICAL);
    itemBoxSizer4->Add(itemBoxSizer7, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxStaticText* itemStaticText8 = new wxStaticText( m_left_panel, wxID_STATIC, _("CAENPLLConfig"), wxDefaultPosition, wxSize(150, -1), 0 );
    itemStaticText8->SetForegroundColour(wxColour(0, 0, 160));
    itemStaticText8->SetFont(wxFont(12, wxSWISS, wxITALIC, wxBOLD, false, _T("Tahoma")));
    itemBoxSizer7->Add(itemStaticText8, 1, wxALIGN_LEFT|wxALL|wxADJUST_MINSIZE, 5);

    wxStaticText* itemStaticText9 = new wxStaticText( m_left_panel, wxID_STATIC, _("CAEN ADC PLL configuration tool"), wxDefaultPosition, wxDefaultSize, 0 );
    itemStaticText9->SetForegroundColour(wxColour(0, 0, 160));
    itemStaticText9->SetFont(wxFont(8, wxSWISS, wxNORMAL, wxBOLD, false, _T("Tahoma")));
    itemBoxSizer7->Add(itemStaticText9, 0, wxALIGN_LEFT|wxLEFT|wxRIGHT|wxBOTTOM|wxADJUST_MINSIZE, 5);

    wxStaticText* itemStaticText10 = new wxStaticText( m_left_panel, wxID_STATIC, _("CAENPLLConfig Rev. 2.0.0"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer7->Add(itemStaticText10, 0, wxALIGN_LEFT|wxALL|wxADJUST_MINSIZE, 2);

    wxPanel* itemPanel11 = new wxPanel( itemDialog1, ID_PANEL1, wxDefaultPosition, wxDefaultSize, wxSIMPLE_BORDER|wxTAB_TRAVERSAL );
    itemPanel11->SetBackgroundColour(wxColour(192, 192, 192));
    itemBoxSizer2->Add(itemPanel11, 0, wxGROW|wxALL, 5);

    wxBoxSizer* itemBoxSizer12 = new wxBoxSizer(wxVERTICAL);
    itemPanel11->SetSizer(itemBoxSizer12);

    wxButton* itemButton13 = new wxButton( itemPanel11, ID_OK_BUTTON, _("Ok"), wxDefaultPosition, wxDefaultSize, 0 );
    itemButton13->SetDefault();
    itemButton13->SetHelpText(_("Close this windows"));
    if (ShowToolTips())
        itemButton13->SetToolTip(_("Close this windows"));
    itemButton13->SetFont(wxFont(8, wxSWISS, wxNORMAL, wxBOLD, false, _T("Tahoma")));
    itemBoxSizer12->Add(itemButton13, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);

////@end InfoDialog content construction
	wxHyperlinkCtrl *hyper_link= new wxHyperlinkCtrl( m_left_panel, ID_HYPERLINK, _("www.caen.it"));
	hyper_link->SetBackgroundColour(wxColour(255, 255, 255));
	hyper_link->SetLinkCursor();
	hyper_link->SetURL( _("http://www.caen.it"));
	hyper_link->SetToolTip( wxT("Goto caen web site") );
	hyper_link->AutoBrowse( true);
	hyper_link->UpdateLink();
	this->m_left_sizer->Add( hyper_link, 1, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);

}

/*!
 * Should we show tooltips?
 */

bool InfoDialog::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap InfoDialog::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin InfoDialog bitmap retrieval
    wxUnusedVar(name);
    if (name == _T("caen.png"))
    {
      wxBitmap bitmap(AppSettings::get_default_img_path()+_T("caen.png"), wxBITMAP_TYPE_PNG);
        return bitmap;
    }
    return wxNullBitmap;
////@end InfoDialog bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon InfoDialog::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin InfoDialog icon retrieval
    wxUnusedVar(name);
    if (name == _T("app_icon.ico"))
    {
      wxIcon icon(AppSettings::get_default_img_path()+_T("app_icon.ico"), wxBITMAP_TYPE_ICO);
        return icon;
    }
    return wxNullIcon;
////@end InfoDialog icon retrieval
}
/*!
 * wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_OK_BUTTON
 */

void InfoDialog::OnOkButtonClick( wxCommandEvent& /* event*/ )
{
	this->EndModal( wxID_OK);
}
//void InfoDialog::OnHyperlink(wxCommandEvent & /* event*/)
//{
//	wxHyperlinkCtrl::GotoURL(wxT("http://www.caen.it"), "", false, false);
//}
